### ISSUE TITLE
How to scroll

### ISSUE THREAD

**Issue by Vuqar05** [PojavLauncherTeam/PojavLauncher_iOS#103]
I’d like to change game language in settings but i cant scroll. My brother who’s playing on android can do it. Is there any way i can scroll in settings and inventory?

**Comment by Carter1190** [comment]
hold down in the scroll bar and it should when you move your finger down scroll down

**Comment by Carter1190** [comment]
ive noticed that most of your issues you hring up are stated on the page so read https://github.com/PojavLauncherTeam/PojavLauncher_iOS/ and the releases page https://github.com/PojavLauncherTeam/PojavLauncher_iOS/releases
