### ISSUE TITLE
[Information] Read before you make a Issue

### ISSUE THREAD

**Issue by Carter1190** [PojavLauncherTeam/PojavLauncher_iOS#105]
Here is a list of things already known by the devs and some possible fixs (not guaranteed to work) on your end you can try.
format= issue:fix
1. app crashs when opening:uninstall pojavlauncher and java,reinstall them then rejailbreak
2. App crashs when launching forge version:make sure you have enough ram for the mods and make sure its minecraft 1.13+ (below doesnt work at all) some versions of forge just may not work
3.issues installing forge/optifine/fabric/etc:Make sure you set the paths correctly and make sure you rename the part of the command "forge-installer.jar" to the name of the actual forge jar file (different for every version but for example for 1.16.5 latest it would be forge-1.16.5-36.0.48-installer.jar 
4.App crashs when loading vanilla version:Make sure it is above minecraft 1.6.1 (below isnt tested) and currently we know certain versions dont work (like 1.8.9)
5. make sure to read all existing issues that may involve your issue and make sure to follow the format for submitting issues.

**Comment by Carter1190** [comment]
Also make sure to fully read all of https://github.com/PojavLauncherTeam/PojavLauncher_iOS and https://github.com/PojavLauncherTeam/PojavLauncher_iOS/releases before making an issue as its likely your issue is already stated there

**Comment by Doregon** [comment]
Could I possibly work on a better wiki for Pojav? I have some ideas in my head for a more organized and robust wiki, if you want to hear.
