### ISSUE TITLE
Cant find me.xfl03

### ISSUE THREAD

**Issue by StomryRiley1** [PojavLauncherTeam/PojavLauncher_iOS#108]
![IMG_0056](https://user-images.githubusercontent.com/79979192/111350383-f684df80-8679-11eb-8b61-17c59580c7c0.jpeg)

**Comment by Carter1190** [comment]
we need the full image not just that snippet

**Comment by StomryRiley1** [comment]
![IMG_0057](https://user-images.githubusercontent.com/79979192/111352424-10272680-867c-11eb-8d2b-1ef76aafd0ae.png)

**Comment by Carter1190** [comment]
make sure to run the chmod command first and make sure you downloaded the headless installer

**Comment by StomryRiley1** [comment]
I have and it still didn’t work

**Comment by Carter1190** [comment]
can i see your files you downloaded?

**Comment by Carter1190** [comment]
also you are missing the paths to the files

**Comment by StomryRiley1** [comment]
Ok it thought it might not need them because it doesn’t show the things the optifine one shows and the fabric where do i need to put them
![IMG_FF59C11DCD95-1](https://user-images.githubusercontent.com/79979192/111364338-00faa580-8689-11eb-86ab-562ece47cccd.jpeg)

**Comment by Carter1190** [comment]
put /var/mobile/Documents/ before both the forge-installer and the forge headless installer .jar files

**Comment by StomryRiley1** [comment]
Ok

**Comment by StomryRiley1** [comment]
It gave me this error now
![IMG_545A8F6FA7BC-1](https://user-images.githubusercontent.com/79979192/111365090-f7be0880-8689-11eb-9c22-b51a3ac1b412.jpeg)

**Comment by StomryRiley1** [comment]
Don’t matter

**Comment by StomryRiley1** [comment]
I got it

**Comment by StomryRiley1** [comment]
Thanks for the help
