### ISSUE TITLE
[Bug Report]

### ISSUE THREAD

**Issue by lilkeve** [PojavLauncherTeam/PojavLauncher_iOS#111]
I’m on IOS 14.3 iPhone X

I don’t know if this I a known bug but when I install forge for 1.12.2 and load it up in pojav it crashes my game no matter what I do.

**Comment by Carter1190** [comment]
its a known bug, please read the releases page and the home page before making a issue report, only forge 1.13+ works with some versions still not working.

**Comment by lilkeve** [comment]
Ok thanks do you know if 1.12+ will ever be supported?

**Comment by Carter1190** [comment]
yeah i think it will be fully supported like the android version eventually no estimated time for when though

**Comment by lilkeve** [comment]
Ok thanks
