### ISSUE TITLE
[Info] Building PojavLauncher on Linux

### ISSUE THREAD

**Issue by Doregon** [PojavLauncherTeam/PojavLauncher_iOS#113]
**Take note** that this isn't meant for anyone to follow just yet. This is simply me opening up a brainstorm platform as I experiment, and then report on my findings. 

I'm starting to work with Darling on my Manjaro Linux PC to see if I can build PojavLauncher without needing anything other than this computer. This would be a step forward for people without Macs to be able to add their own contributions and not have to commit their changes to GitHub every time they want to build. Here's what I hope to accomplish:

- [x] Get Darling working
   * Kind of obvious. I've learned that the kernel module **will not build on Linux kernels >5.10**, so Darling doesn't work with those ones.
- [x] Install Xcode and use it with `xcode-select --select /Applications/Xcode.app`
   * The command line tools by itself *might* be enough, although I'm not sure.
- [x] Install the iOS SDKs we need
   * We'll use the iOS-SDKs repository for this.
- [ ] Install dependencies
   * The attempts to install Homebrew failed with segfaults. Sad.
- [ ] Clone and run a build
   * Test to make sure all of the builds go right and everything works the way it should.

**Comment by Doregon** [comment]
After a bit of weirdness with my first installation of Darling (I had to reset due to user error), I've got Darling working and am installing the command line tools for Xcode now. Let's hope that we won't need to install the full application for everything to work.

![Screenshot_20210324_181041](https://user-images.githubusercontent.com/55281754/112390246-5c9de200-8ccc-11eb-8842-ec2da09616d7.png)

**Comment by Doregon** [comment]
I noticed something about this though: Installing the SDKs. Darling, by default, installs MacOSX.sdk and MacOSX1013.sdk--so only the High Sierra and Catalina SDKs included with Darwin v19.6.0. We'll need to get the SDK from elsewhere, and a good place to start is at the [xybp888/iOS-SDKs]( https://github.com/xybp888/iOS-SDKs) repository.

**Comment by Doregon** [comment]
Xcode Command Line Tools installed.

**Comment by Doregon** [comment]
iPhoneOS13.4.sdk installed.

**Comment by Doregon** [comment]
Aaaand Homebrew won't install on Darling. Git keeps causing segmentation faults and then (potentially) corrupts your entire Darling prefix--not a good thing to have happen.

![image](https://user-images.githubusercontent.com/55281754/112393962-45fa8980-8cd2-11eb-8556-efb51fa0e815.png)

**Comment by Doregon** [comment]
Issues building cmake, I've been struggling with it for a while now.

**Comment by PerennialWheat** [comment]
I pretty much just used macosx in docker on arch Linux to build.
https://github.com/sickcodes/Docker-OSX

**Comment by Doregon** [comment]
That’s a good project and I’m glad that it works! I’m just looking for a way to do it without Docker or a cirtual machine, and was originally intending to use Darling. However, I’m going to begin working on cross-compilation instead.

**Comment by Doregon** [comment]
Closing this issue as neither route worked as easy as just setting up an OSX-KVM instance.
