### ISSUE TITLE
Keeps crashing on iOS when ever you open it right away

### ISSUE THREAD

**Issue by Eissy** [PojavLauncherTeam/PojavLauncher_iOS#115]
**First, let us know what you’re using.**
Tell us what iOS/iPadOS device and version you’re using, and the PojavLauncher version.
IPad Pro IOS 14.3
**Next, describe the issue.**
Make sure to be as descriptive as possible. 
So, I downloaded it, then I tried opening the app and it crashes righttt away.
**What’s supposed to happen?**
It supposed to open and not crash
What were you expecting?
It won’t crash 
**How does it happen?**
By clicking on the app
Let’s get a step by step on how to reproduce this issue.

**Any files you want to send?**
We could use a copy of latestlog.txt or a Cr4shed screenshot.

https://youtu.be/MFcjHVeHE1g here 

**Please verify that you have done the following:**

- [ ] Provided details on what you’re seeing vs what you wanted
- [ ] Provided a log file, if relevant
- [ ] Provided steps to reproduce this issue
- [ ] Tested on the latest version of PojavLauncher

**Comment by khanhduytran0** [comment]
> **Any files you want to send?**
> We could use a copy of latestlog.txt or a Cr4shed screenshot.

So, where are they? @Eissy

**Comment by Eissy** [comment]
> > **Any files you want to send?**
> > We could use a copy of latestlog.txt or a Cr4shed screenshot.
> 
> So, where are they? @Eissy 
 
 here some proof: https://youtu.be/MFcjHVeHE1g

**Comment by khanhduytran0** [comment]
🤦 "the crash animation" does not help us find the problem.

**Comment by khanhduytran0** [comment]
**Send latestlog.txt**!

**Comment by Eissy** [comment]
> **Send latestlog.txt**!

How do I? I’m not that good at this stuff, sorry!

**Comment by khanhduytran0** [comment]
- Copy latestlog.txt to "Files" app.
- Go to GitHub web, pick as below (it is also place to send text file).

![image](https://user-images.githubusercontent.com/40482367/112790562-dac20600-9089-11eb-90b5-a704caadc501.jpeg)

**Comment by Eissy** [comment]
> * Copy latestlog.txt to "Files" app.
> * Go to GitHub web, pick as below (it is also place to send text file).
> 
> ![image](https://user-images.githubusercontent.com/40482367/112790562-dac20600-9089-11eb-90b5-a704caadc501.jpeg)

Ok will try rn

**Comment by Eissy** [comment]
> * Copy latestlog.txt to "Files" app.
> * Go to GitHub web, pick as below (it is also place to send text file).
> 
> ![image](https://user-images.githubusercontent.com/40482367/112790562-dac20600-9089-11eb-90b5-a704caadc501.jpeg)

Where do I search it in files app?

**Comment by Eissy** [comment]
> * Copy latestlog.txt to "Files" app.
> * Go to GitHub web, pick as below (it is also place to send text file).
> 
> ![image](https://user-images.githubusercontent.com/40482367/112790562-dac20600-9089-11eb-90b5-a704caadc501.jpeg)

NEVER MIND FOUN DITTTT

-

**Comment by Eissy** [comment]
> **Send latestlog.txt**!

HERE 
[text.txt](https://github.com/PojavLauncherTeam/PojavLauncher_iOS/files/6219492/text.txt)

- ``

**Comment by Eissy** [comment]
> * Copy latestlog.txt to "Files" app.
> * Go to GitHub web, pick as below (it is also place to send text file).
> 
> ![image](https://user-images.githubusercontent.com/40482367/112790562-dac20600-9089-11eb-90b5-a704caadc501.jpeg)

Here u go
[text.txt](https://github.com/PojavLauncherTeam/PojavLauncher_iOS/files/6219495/text.txt)

**Comment by khanhduytran0** [comment]
wtfman do you expect PojavLauncher works without Java Runtime Environment?

**Comment by Eissy** [comment]
> wtfman do you expect PojavLauncher works without Java Runtime Environment?

How do I turn it on

**Comment by khanhduytran0** [comment]
Wait, but java is required to install **before** installing PojavLauncher.

**Comment by khanhduytran0** [comment]
(https://github.com/PojavLauncherTeam/PojavLauncher_iOS/releases/tag/v16-openjdk)

**Comment by Eissy** [comment]
> Wait, but java is required to install **before** installing PojavLauncher.

Thanks for ur help I did it

**Comment by Eissy** [comment]
> (https://github.com/PojavLauncherTeam/PojavLauncher_iOS/releases/tag/v16-openjdk)

Wait how do I bring my game pad bigger

**Comment by Eevvaann6** [comment]
I have the same issue. I have Java Runtime installed. It shows a grey overlay then goes back to the home screen

**Comment by Doregon** [comment]
latestlog.txt and/or Cr4shed log?

**Comment by Eevvaann6** [comment]
> 
> 
> latestlog.txt and/or Cr4shed log?
Crashes too early on to produce it. it crashes on the zoom in app opening animation but with the app background being transparent.

**Comment by Doregon** [comment]
So then check Cr4shed. It’ll be in one or the other, always.

**Comment by liamvmorar** [comment]
I have something similar

**Comment by Eevvaann6** [comment]
Here is my log from Cr4shed.
[log.txt](https://github.com/PojavLauncherTeam/PojavLauncher_iOS/files/6354255/log.txt)

**Comment by Doregon** [comment]
I can't remember what exactly caused this issue for me, but I remember I was able to fix it. Try checking to see can run: `sudo chmod +x /usr/lib/jvm/java-16-openjdk/bin/java`

**Comment by Doregon** [comment]
I remember now: 

`sudo chown -Rv mobile:mobile /var/mobile/Documents`
`sudo chmod -Rv 0775 /var/mobile/Documents`

**Comment by Eevvaann6** [comment]
> I remember now:
> 
> `sudo chown -Rv mobile:mobile /var/mobile/Documents`
> `sudo chmod -Rv 0775 /var/mobile/Documents`

Well, The commands ran but they did not fix the issue. I found a fixed issue that had using your repo as the solution when I am using your repo so that did not work.

**Comment by khanhduytran0** [comment]
Send latestlog.txt

**Comment by Eevvaann6** [comment]
> Send latestlog.txt

I already said it crashes before latestlog is made

**Comment by khanhduytran0** [comment]
So, manually check `minecraft` folder owner/group

**Comment by Eevvaann6** [comment]
> 
> 
> So, manually check `minecraft` folder owner/group

I fixed that. Now it works.

**Comment by Doregon** [comment]
Closing this issue. Folder permissions were fixed in a recent commit.
