### ISSUE TITLE
How do I make my game pad bigger? (iOS ipad)

### ISSUE THREAD

**Issue by Eissy** [PojavLauncherTeam/PojavLauncher_iOS#117]
**Ask your question here!**
Be descriptive in your question so that we can provide an equally descriptive answer. Make sure you’ve checked out the subreddit or the README before asking—your question might already have an answer.
Hello, I was just wondering that how do I make my game pad bigger? I’m on an ipad. So it’s pretty small, and basically barley playable

**Comment by ThatsNiceGuy** [comment]
Resizing UI controls is not possible at the moment.

**Comment by Eissy** [comment]
> Resizing UI controls is not possible at the moment.

That suck s, my ipad is 12.9 inches and then the game pad is soo small

**Comment by khanhduytran0** [comment]
There’s an option in launcher preferences now.
