### ISSUE TITLE
Crashing on launch

### ISSUE THREAD

**Issue by SewSulle123** [PojavLauncherTeam/PojavLauncher_iOS#119]
I’ve installed the open jdk 16 deb and the PojavLauncher deb. When I open PojavLauncher app, my screen gets darker and crashes, also my dock rotates like in landscape mode. I’ll attach a video and my “latestlog” file. I’ve done some research and I can’t figure out what’s wrong. I’m using an iPhone 7 Plus, iOS 14.4, Cheackra1n jailbreak.

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher_iOS/files/6252883/latestlog.txt)

https://user-images.githubusercontent.com/78162557/113483081-ad9d9b00-946f-11eb-9055-db0a50b595e8.MP4

**Comment by Doregon** [comment]
Are you using the latest build from the GitHub Actions tab?

**Comment by Doregon** [comment]
Also, run `/usr/lib/jvm/java-16-openjdk/bin/java` in a terminal. Tell us what it reads back.

**Comment by SewSulle123** [comment]
Yes, I’m using the latest build, when I run that command, it says permission denied, I tried running at root with the same result.

**Comment by SewSulle123** [comment]
I changed the permissions on the file to “read, write , execute” (it was originally just read and write.) Now when I run it in terminal it says what I think is a usage error. (I’ll attach a screenshot) I just put “ /usr/lib/jvm/java-16-openjdk/bin/java” in terminal. If I was supposed to enter something different to run it please send exactly what to enter. (I’m not very familiar with a terminal)

**Comment by Doregon** [comment]
I just wanted to see if it said "Killed: 9". I had that issue a couple of times before and runnind `ldid` fixed it, but this doesn't apply to you. Do you have Cr4shed installed? If not, install it and try to run PojavLauncher again. Cr4shed should be able to get an error.

**Comment by SewSulle123** [comment]
I did not have Cr4shed installed. When I installed it, cydia said "Reboot Device" instead of just a respring. After rebooting, I rejailbroke and was put in safe mode. When I open pojavlauncher in safe mode, cr4shed says nothing (Because it's in safe mode) I uninstalled cr4shed and got back to normal mode. I'll attach my tweak list if it helps.

[text.txt](https://github.com/PojavLauncherTeam/PojavLauncher_iOS/files/6254493/text.txt)

**Comment by SewSulle123** [comment]
I got it installed but when I open PojavLauncher, it doesn't say it crashed. It doesn't give me a notification or say in the list inside the app.

**Comment by Doregon** [comment]
I just looked over your logs again and saw that it's looking for a library that hasn't even been made for the iOS version of PojavLauncher. Here, use the copy from my repository and tell me how it does for you (if you were wondering, I'm allowed to do this since I now provide PojavLauncher for non-Procursus users)

https://doregon.github.io/cydia

**Comment by SewSulle123** [comment]
Thank you so much! It's working! The only issue is that to click anywhere you have to "long click" kinda. Also I can't change my hot bar slot. Is that a know issue and is there a fix?

**Comment by Doregon** [comment]
(Psst! Close this issue!)
