### ISSUE TITLE
Fabric Loader freezes on load

### ISSUE THREAD

**Issue by Mentalgen** [PojavLauncherTeam/PojavLauncher_iOS#120]
**First, let us know what you’re using.**
I am using an iPhone XS Max on PojavLauncher v1.1

**Next, describe the issue.**
After successfully installing fabric, running then said profile freezes the app, requiring a force close. Running “fabric-loader-0.11.3-1.16.4“

**What’s supposed to happen?**
Successfully launching into the main menu.

**How does it happen?**
I had just installed fabric just as the wiki said, and then I typed in the name of the profile into the Minecraft version line. 

**Any files you want to send?**
Said log is included here: https://paste.ee/p/LQnpg

**Please verify that you have done the following:**

- [X] Provided details on what you’re seeing vs what you wanted
- [X] Provided a log file, if relevant
- [X] Provided steps to reproduce this issue
- [X] Tested on the latest version of PojavLauncher

**Comment by Doregon** [comment]
Issues with Fabric finding the .jar for itself. Did you run the installer for Fabric as root?

If so, open Filza, navigate to /var/mobile/Documents, tap the (i) next to minecraft and change the permissions like so (watch closely!):

https://user-images.githubusercontent.com/55281754/113661949-14d86c80-9675-11eb-98be-cb1e766d8958.MP4

**Comment by Mentalgen** [comment]
I did install fabric as root, was having trouble with the command “chmod -R +x /usr/lib/jvm/java-16-openjdk/bin” giving me errors, don’t exactly remember what. Running as root did solve that issue. Not so very proficient in Terminal stuff so I apologize ^^, It did fix the issue.

**Comment by Doregon** [comment]
No problem, as long as it's working! Make sure you mark this issue as closed, it helps everyone that answers questions to figure out who still needs help.

**Comment by Doregon** [comment]
(Psst! Close the issue!)
