### ISSUE TITLE
Latest Zink build causes game to crash on startup

### ISSUE THREAD

**Issue by Ryorama** [PojavLauncherTeam/PojavLauncher_iOS#122]
**First, let us know what you’re using.**

iPhone XR

**Next, describe the issue.**

When I launch the game, it crashes because it can’t find a library named libOSMesaOverride.dylib.

**How does it happen?**
Install the latest version from the backend-zink branch, launch your game and it should crash.

**Any files you want to send?**
Yes, they will be attached to this issue.

[crash-2021-04-06_10.56.14-client.txt](https://github.com/PojavLauncherTeam/PojavLauncher_iOS/files/6264199/crash-2021-04-06_10.56.14-client.txt)

**Comment by Doregon** [comment]
Fixed

**Comment by Ryorama** [comment]
Yeah, it is.
