### ISSUE TITLE
[Bug Report]

### ISSUE THREAD

**Issue by calex112** [PojavLauncherTeam/PojavLauncher_iOS#123]
**First, let us know what you’re using.**
Tell us what iOS/iPadOS device and version you’re using, and the PojavLauncher version.

**Next, describe the issue.**
Make sure to be as descriptive as possible. 

**What’s supposed to happen?**
What were you expecting?

**How does it happen?**
Let’s get a step by step on how to reproduce this issue.

**Any files you want to send?**
We could use a copy of latestlog.txt or a Cr4shed screenshot.

**Please verify that you have done the following:**

- [ ] Provided details on what you’re seeing vs what you wanted
- [ ] Provided a log file, if relevant
- [ ] Provided steps to reproduce this issue
- [ ] Tested on the latest version of PojavLauncher

**Comment by khanhduytran0** [comment]
@calex112 bruh empty issue
