### ISSUE TITLE
Infinite loading 

### ISSUE THREAD

**Issue by calex112** [PojavLauncherTeam/PojavLauncher_iOS#124]
When i load forge it has an infinite loading screen after selecting play. I use version 1.0 of pojavlauncher because when i use the latest it crashes. I’m following the tutorial made by LAZZA MCPE I can do every other version except for forge please help me

Specs

iphone: Iphone SE (2020)

IOS: Ios 14.3

I use unc0ver jailbreak

**Comment by OwzygZawg** [comment]
Why did you make two reports and one does not show your problem provided?

**Comment by calex112** [comment]
sorry
![B53938F3-AEE1-4190-8CA9-67C2580D5B25](https://user-images.githubusercontent.com/82012174/113786350-f58a1f80-9706-11eb-8260-4e898c3a9fae.png)
 here is a picture it loads for a long time then just turns white

**Comment by OwzygZawg** [comment]
No problem! more are you in the recent version? or a forge?

**Comment by OwzygZawg** [comment]
Maybe upgrade to the latest version!

**Comment by calex112** [comment]
when i play on version 1.1 it crashes

**Comment by OwzygZawg** [comment]
so I recommend staying at 1.0! more what's your problem with the versions on 1.0?

**Comment by OwzygZawg** [comment]
Did you enter the correct version number you want to play?

**Comment by calex112** [comment]
yes i did and i still get white screen and infinite loading

**Comment by OwzygZawg** [comment]
Can you send Lastelog.txt?

**Comment by OwzygZawg** [comment]
And a photo to check if the number is correct, please!

**Comment by khanhduytran0** [comment]
~~Maybe switch to Taurine?~~
Also send latestlog.txt

**Comment by OwzygZawg** [comment]
@calex112 you did not send lastestlog.txt

**Comment by ednellbasilio** [comment]
Yeah but the Minecraft still loading with mods
