### ISSUE TITLE
How Do I Change The Amount Of Ram On iOS?

### ISSUE THREAD

**Issue by thezombieplays** [PojavLauncherTeam/PojavLauncher_iOS#125]
I know for a fact android can change the amount of ram but can iOS change the amount of ram. I have tried the method that was 24 days ago but keeps saying operation denied. Is there a way to add Rama on iOS using a different method or is that feature coming to iOS soon. I need more ram for mods as my device recommends 400MB even though it has 2GB.

**Comment by Doregon** [comment]
1. Are you running the script as root?
2. If so, run `chmod +x /usr/bin/jetsamctl`

Another option is to make a custom arguments file, although I don’t have as much experience with this route.

**Comment by thezombieplays** [comment]
After I did the script on NewTerm it says operation denied

**Comment by Doregon** [comment]
That doesn’t really help me...

**Comment by rhizomacomp10** [comment]
Make the file overrideargs.txt in /var/mobile/Documents/minecraft and add this -Xmx1G in the file and change 1 to how much gigs you want and if you want to use more then 3 gigs use jetsamctl like this: sudo jetsamctl -l 4096 PojavLauncher

**Comment by Doregon** [comment]
Question has been answered, closing.
