### ISSUE TITLE
1.12.2 optifine crashes

### ISSUE THREAD

**Issue by littlefish12345** [PojavLauncherTeam/PojavLauncher_iOS#131]
I installed 1.12.2 which is run perfectly and it have a lot performance increase than 1.16.5.
Then I tried to install optifine to load some shader packs and it have installed correctly.As soon as I tried to start the game than it crashes.
I don’t know how to fix it so I want to ask here is anyone have the same problem and how to fix it

**Comment by ENDERMANYK** [comment]
Do you use the zink build or the GL4ES build?

**Comment by littlefish12345** [comment]
I use the latest build in the release

**Comment by littlefish12345** [comment]
And now I have tried to use the latest build in actions and it also crushes

**Comment by ENDERMANYK** [comment]
iOS version doesn't like the android version, you can't run the normal PC shader on it, as i remember, the zink build lack triangle fan and really lag when the GL4ES build run faster but lack a lot of OpenGL API

**Comment by ENDERMANYK** [comment]
Wait i think i type something wrong, Optifine doesn't support below 1.13

**Comment by littlefish12345** [comment]
emmmmm okay
