### ISSUE TITLE
[Bug Report] Unable to load MetalANGLE 

### ISSUE THREAD

**Issue by Doregon** [PojavLauncherTeam/PojavLauncher_iOS#132]
**First, let us know what you’re using.**
iPhone 5s, 12.5.1, unc0ver
iPhone Se, 14.4, Odysseyra1n
iPad Air 4th, 14.3, unc0ver

**Next, describe the issue.**
Attempting to run PojavLauncher fails with an error loading MetalANGLE.

**What’s supposed to happen?**
I was expecting it to work.

**How does it happen?**
1. Run PojavLauncher using the latest build (PR from external-mouse branch).

**Any files you want to send?**
Not exactly, the important bits where that it couldn't load @rpath/MetalANGLE.framework/MetalANGLE.

**Please verify that you have done the following:**

- [x] Provided details on what you’re seeing vs what you wanted
- [x] Provided a log file, if relevant
- [x] Provided steps to reproduce this issue
- [x] Tested on the latest version of PojavLauncher

I found a workaround, which is to copy the MetalANGLE binary from an older build.

**Comment by Doregon** [comment]
And it looks like copying MetalANGLE worked, but now libopenal is malformed, just like MetalANGLE used to be.

**Comment by khanhduytran0** [comment]
That’s strange but both libs are untouched on merge branch.

**Comment by Doregon** [comment]
Looks like the newest build fixed this issue. I'll remove the update block on my repo and close this issue.
