### ISSUE TITLE
Could not find or load main class me.xf103. HeadlessInstaller

### ISSUE THREAD

**Issue by 44jost** [PojavLauncherTeam/PojavLauncher_iOS#134]
Hi, i followed the guide on how to install forge but i get this issue:

Joshs-iPhone:/var/mobile root# /usr/lib/jvm/java-16-openjdk/bin/j ava -cp forge-installerheadless-1.0.1.jar:forge-installe r. jar me.xf103.HeadlessInstaller -progress -installint /var/mobile/Documents/minecraft 

Error: Could not find or load main class me.xf103. HeadlessInstaller Caused by: java.1ang. ClassNoFoundException: me.xf103. Hea dlessInstaller 

i’m jailbroken on ios 14.3 and using NewTerm2

**Comment by Carter1190** [comment]
you didnt put the paths to the jar files and there are multiple mistakes in the command itself like a space in java (j ava),forge-installer.jar (installe r. jar)and a miss spell in -InstallClient

**Comment by 44jost** [comment]
okay, i’ve got this working now due to the paths you mentioned. thank you 👏🏻
