### ISSUE TITLE
[F-Req] Hide the HomeBar in game

### ISSUE THREAD

**Issue by 44jost** [PojavLauncherTeam/PojavLauncher_iOS#135]
**Is your feature request related to a problem? Please describe.**
the homebar covers the content of the hotbar at the bottom of the screen, when in landscape mode.

**Describe the solution you'd like**
for the homebar to be hidden, like in pocket edition. or auto minimising.

**Comment by Arsenij08** [comment]
Install hidebarx in cydia https://sparkdev.me/

**Comment by Doregon** [comment]
@44jost I have just implemented this in commit `c650b72`. Closing issue.
