### ISSUE TITLE
[Bug Report]

### ISSUE THREAD

**Issue by LilBr0b3ar** [PojavLauncherTeam/PojavLauncher_iOS#136]
**First, let us know what you’re using.**
Tell us what iOS/iPadOS device and version you’re using, and the PojavLauncher version.

**Next, describe the issue.**
Make sure to be as descriptive as possible. 

**What’s supposed to happen?**
What were you expecting?
 
**How does it happen?**
Let’s get a step by step on how to reproduce this issue.

**Any files you want to send?**
We could use a copy of latestlog.txt or a Cr4shed screenshot.

**Please verify that you have done the following:**

- [x] Provided details on what you’re seeing vs what you wanted
- [ ] Provided a log file, if relevant
- [ ] Provided steps to reproduce this issue
- [x] Tested on the latest version of PojavLauncher

how do I launch it in files? is that possible with jailbreak?

**Comment by LilBr0b3ar** [comment]
i dont know

**Comment by Doregon** [comment]
You have to have a jailbreak. The file manager we talk about is called Filza, it's an app you can only get when you're jailbroken and have access to the root system.
