### ISSUE TITLE
[Bug Report] Mouse support is broken

### ISSUE THREAD

**Issue by ThatsNiceGuy** [PojavLauncherTeam/PojavLauncher_iOS#139]
**First, let us know what you’re using.**
Tell us what iOS/iPadOS device and version you’re using, and the PojavLauncher version.

iPad Pro 2020 256GB WiFi on iPadOS 13.4 jailbroken with Taurine 1.0.4. PojavLauncher version is the latest one on Procursus (1.1+git20210417.f9198b4). Using Logitech G502 HERO with USB-C to USB-A adapter.

**Next, describe the issue.**
Make sure to be as descriptive as possible. 

When using a mouse, the game will freak out and eventually crash.

Video here: https://youtu.be/RsY0qQj8B_g

**What’s supposed to happen?**
Proper mouse functionality

**How does it happen?**
Let’s get a step by step on how to reproduce this issue.

1. Connect a mouse via USB-C or Bluetooth
2. Open PojavLauncher
3. Start game
4. Load a world
5. Move the mouse or click a button on it repeatedly and the game will crash

**Any files you want to send?**
We could use a copy of latestlog.txt or a Cr4shed screenshot.

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher_iOS/files/6344154/text.txt)\
the crash report from Settings>Privacy>Analytics & Improvements>Analytics Data doesn’t look useful (mainly just says `abort() called`) so I didn’t upload it here

**Please verify that you have done the following:**

- [x] Provided details on what you’re seeing vs what you wanted
- [x] Provided a log file, if relevant
- [x] Provided steps to reproduce this issue
- [x] Tested on the latest version of PojavLauncher

**Comment by ThatsNiceGuy** [comment]
> **First, let us know what you’re using.**
> Tell us what iOS/iPadOS device and version you’re using, and the PojavLauncher version.
> 
> iPad Pro 2020 256GB WiFi on iPadOS 13.4 jailbroken with Taurine 1.0.4. PojavLauncher version is the latest one on Procursus (1.1+git20210417.f9198b4) Using Logitech G502 HERO mouse over USB-C to USB-A adapter.
> 
> **Next, describe the issue.**
> Make sure to be as descriptive as possible.
> 
> When using a mouse, the game will freak out and eventually crash.
> 
> Video here: https://youtu.be/RsY0qQj8B_g
> 
> **What’s supposed to happen?**
> Proper mouse functionality
> 
> **How does it happen?**
> Let’s get a step by step on how to reproduce this issue.
> 
> 1. Connect a mouse via USB-C or Bluetooth
> 2. Open PojavLauncher
> 3. Start game
> 4. Load a world
> 5. Move the mouse or click a button on it repeatedly and the game will crash
> 
> **Any files you want to send?**
> We could use a copy of latestlog.txt or a Cr4shed screenshot.
> 
> [latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher_iOS/files/6344154/text.txt)
> 
> **Please verify that you have done the following:**
> 
> * [x]  Provided details on what you’re seeing vs what you wanted
> * [x]  Provided a log file, if relevant
> * [x]  Provided steps to reproduce this issue
> * [x]  Tested on the latest version of PojavLauncher

**Comment by Doregon** [comment]
It's still a work in progress atm

**Comment by ThatsNiceGuy** [comment]
ik, i can help test builds and stuff though

**Comment by Doregon** [comment]
Tracked on #184.
