### ISSUE TITLE
Can’t scroll down on settings, server lists and World lists

### ISSUE THREAD

**Issue by owenthehugger** [PojavLauncherTeam/PojavLauncher_iOS#140]
iPad Air 4th Gen
IOS 14.3
PojavLauncher Version 1.1 
Minecraft version 1.16.5

Video of the problem: https://streamable.com/xoy9cm

**Comment by khanhduytran0** [comment]
nah. Minecraft Java wasn't designed for touch devices. Hold the scrollbar and swipe.

**Comment by khanhduytran0** [comment]
Also you rip the issue tenmplate.

**Comment by Doregon** [comment]
@owenthehugger you have to hold down the scroll bar for about 1.5 seconds and then you can go ahead and scroll. Also to what @khanhduytran0 said:

I made the templates for a reason. Please try to keep in line with what the template contains rather than deleting everything and going rogue.

**Comment by Doregon** [comment]
Closing this issue as an answer has been provided. Reopen if you still need help with it.
