### ISSUE TITLE
[Bug Report] can’t install forge 

### ISSUE THREAD

**Issue by owenthehugger** [PojavLauncherTeam/PojavLauncher_iOS#142]
I keep getting this error while trying to install Minecraft Forge 1.16.5 and yea both the installer and headless (1.0.1) are in the correct paths 

Forge Version: forge-1.16.5-36.1.4-installer

IPad Air 4th gen iOS 14.3

screenshot: 
https://i.ibb.co/nkrLb9K/15821831-5-FB3-46-A7-8690-E3-B9-FF98724-E.jpg

**Comment by Doregon** [comment]
Don't try installing Forge as root.

**Comment by owenthehugger** [comment]
> Don't try installing Forge as root.

I’ve been using sudo, and if I don’t use that I get an “operation not permitted” error

**Comment by Doregon** [comment]
Try chmodding the java executable directly. PojavLauncher won't work if you try installing as root/sudo because applications run as the `mobile` user and it won't be able to access those files.

**Comment by creyes200** [comment]
> Try chmodding the java executable directly. PojavLauncher won't work if you try installing as root/sudo because applications run as the `mobile` user and it won't be able to access those files.

How do i do that i have the same problem

**Comment by Doregon** [comment]
@creyes200 

```
su                                               # The default password is alpine
chmod -R +x /usr/bin/jvm/java-16-openjdk/bin/*
```
