### ISSUE TITLE
[Question] does it have any virus?

### ISSUE THREAD

**Issue by jammmy2** [PojavLauncherTeam/PojavLauncher_iOS#144]
Does it have any virus? Do you have any proofs that it doesn’t have any virus?
I’m scared if it has virus 
Because my friend said that if I download this I’ll get a virus because it’s not a legit version of Minecraft java 

**Ask your question here!**
Be descriptive in your question so that we can provide an equally descriptive answer. Make sure you’ve checked out the subreddit or the README before asking—your question might already have an answer.

**Comment by CriticalRange** [comment]
You can check the source code on github anytime if you want to be sure it's not a virus, i use android version all the time, these guys are doing it!

**Comment by CriticalRange** [comment]
Also you can use virustotal aswell if ur manually installing it :+1:

**Comment by Doregon** [comment]
PojavLauncher has no viruses, it's basically just like having another launcher, like CurseForge. There's nothing to be afraid of here, you can check all the code from the following repositories with VirusTotal (like @CriticalRange said) if you want to be sure:

* this repository
* [PojavLauncherTeam/PojavLauncher](https://github.com/PojavLauncherTeam/PojavLauncher)
* [Doregon/cydia](https://github.com/Doregon/cydia) (the hosted version on my repo)
* [ProcursusTeam/Procursus](https://github.com/ProcursusTeam/Procursus) (the hosted version on Procursus)
