### ISSUE TITLE
[F-Req]

### ISSUE THREAD

**Issue by Aliriser** [PojavLauncherTeam/PojavLauncher_iOS#149]
To use this template:
* CHECK OTHER ISSUES and see if anyone else has requested the same functionality. We will close any duplicate requests.
* Don't delete any of the words between asterisks. 
* Add something descriptive to the title (ex. [F-Req] Controller Support)
* Follow all of the steps. If you do not provide an answer to each section in this template, the issue will be closed.

// Delete this line and the above text before submitting.

**Is your feature request related to a problem? Please describe.**
Give us some details into the problem, and how this affects it.

**Describe the solution you'd like**
What do you want to see changed, added, or removed? Make sure to be specific.

**Describe alternatives you've considered**
Is there anythingg else you’ve thought of but crossed off? If so, tell us why.

**Additional context**
Have a mock-up? Perhaps a template or set of files. Share them here!

**Make sure you’ve dine the following:**
- [ ] Provided a clear description into what the feature request is
- [ ] (If applicable) provided an issue that this request would fix
- [ ] (If applicable) presented potential possibilities into adding this request
- [ ] (If applicable) Provided evidence such as a drawing, log file, file, etc. of what you wish to see reflected

**Comment by Doregon** [comment]
You did not fill out the issue template.
