### ISSUE TITLE
[Bug Report] unable to launch game after installing optifine

### ISSUE THREAD

**Issue by owenthehugger** [PojavLauncherTeam/PojavLauncher_iOS#151]
Unable to launch game after attempting to launch the game for the second time with optifine, anybody know what causing this?

https://i.ibb.co/h1qLmWN/2-C18-A016-7347-4-CA0-95-E5-71235-C5-E1-BF4.png

**Comment by Doregon** [comment]
Swipe left on the user to delete it and then login in again.
