### ISSUE TITLE
[Bug Report] Icon not appearing on the Home Screen after installing .deb

### ISSUE THREAD

**Issue by ExeRhythm** [PojavLauncherTeam/PojavLauncher_iOS#152]
**First, let us know what you’re using.**
Tell us what iOS/iPadOS device and version you’re using, and the PojavLauncher version.

iPadOS 14.3, latest commit .deb

**Next, describe the issue.**
Make sure to be as descriptive as possible. 

I cannot find the icon on the Home Screen and in “find” iOS feature.

**What’s supposed to happen?**
What were you expecting?

**How does it happen?**
Let’s get a step by step on how to reproduce this issue.

Install the latest .deb from GitHub Actions

**Any files you want to send?**
We could use a copy of latestlog.txt or a Cr4shed screenshot.

**Please verify that you have done the following:**

- [x] Provided details on what you’re seeing vs what you wanted
- [ ] Provided a log file, if relevant
- [x] Provided steps to reproduce this issue
- [x] Tested on the latest version of PojavLauncher

**Comment by ExeRhythm** [comment]
I also tried respringing and soft rebooting.

**Comment by khanhduytran0** [comment]
But you haven’t run `uicache`?

**Comment by ExeRhythm** [comment]
I tried, still doesn't work (also, Sileo does that automatically)

**Comment by ExeRhythm** [comment]
Restarting my iPad fixed this issue. I don't know what was the cause. Thanks!
