### ISSUE TITLE
[Bug Report] Login window disappears right after I click "Microsoft login"

### ISSUE THREAD

**Issue by ExeRhythm** [PojavLauncherTeam/PojavLauncher_iOS#153]
**First, let us know what you’re using.**
iPadOS 14.3 Air 3, latest GitHub Actions commit .deb

**Next, describe the issue.**
When I try to press Microsoft Login, it shows login alert, but it closes about 0.1 seconds later.

**What’s supposed to happen?**
A login window should've opened

**How does it happen?**
Click on "Microsoft login" button

**Any files you want to send?**
(I am talking about this window, it closes instantly)
![IMG_0174](https://user-images.githubusercontent.com/52459150/115993964-c10ad480-a5dd-11eb-8ca9-cb8359210245.PNG)

**Please verify that you have done the following:**

- [x] Provided details on what you’re seeing vs what you wanted
- [x] Provided a log file, if relevant
- [x] Provided steps to reproduce this issue
- [x] Tested on the latest version of PojavLauncher

**Comment by ExeRhythm** [comment]
(I cannot click "Continue" when it is open)

**Comment by Doregon** [comment]
Known issue, we are working on a fix.

**Comment by Doregon** [comment]
@ExeRhythm check out the latest GitHub Actions build.

**Comment by ExeRhythm** [comment]
It works!! Thanks!
