### ISSUE TITLE
[Bug Report] Mouse pointer offset in Minecraft main menu, settings, etc. and sometimes not clicking buttons

### ISSUE THREAD

**Issue by slavicweebofficial** [PojavLauncherTeam/PojavLauncher_iOS#155]
**First, let us know what you’re using.**
Tell us what iOS/iPadOS device and version you’re using, and the PojavLauncher version.

iPad Mini 5 64GB Wifi on iPadOS 14.3 RC 1 with unc0ver jailbreak, pojavlauncher latest version (1.2) with a cheap 13$ bluetooth mouse (mouse has no problem)

**Next, describe the issue.**

When hovering on buttons the pointer in Minecraft there is a big offset upwards from the iPad's pointer. And sometimes mouse click don't respond so I have to relaunch pojavlauncher every time it happens.

**What’s supposed to happen?**
Pointer in Minecraft should be at the same location as the iPad's pointer, without offset.
All mouse clicks should respond

**How does it happen?**
1- Launch Minecraft in pojavlauncher
2- Move mouse anywhere in main menu, settings, etc.

1- Launch Minecraft in pojavlauncher
2- Interact with UI or change some settings
3- Then Minecraft randomly starts refusing mouse clicks

**Any files you want to send?**
We could use a copy of latestlog.txt or a Cr4shed screenshot.

**Please verify that you have done the following:**

- [x] Provided details on what you’re seeing vs what you wanted
- [ ] Provided a log file, if relevant
- [x] Provided steps to reproduce this issue
- [x] Tested on the latest version of PojavLauncher

**Comment by IvanKulagin** [comment]
Go into the video settings and enable fullscreen mode

**Comment by slavicweebofficial** [comment]
> Go into the video settings and enable fullscreen mode
Didn't work
