### ISSUE TITLE
[F-Req] IPA Version

### ISSUE THREAD

**Issue by ayunami2000** [PojavLauncherTeam/PojavLauncher_iOS#157]
**Is your feature request related to a problem? Please describe.**
Give us some details into the problem, and how this affects it.
N/A
**Describe the solution you'd like**
What do you want to see changed, added, or removed? Make sure to be specific.
Allow app to be installed on non-jailbroken IOS devices by exporting it as an IPA file instead of a DEB file. (users can sign it themselves)
**Describe alternatives you've considered**
Is there anythingg else you’ve thought of but crossed off? If so, tell us why.
I tried following a DEB to IPA tutorial but it did not sign correctly for me. There's a chance that it failed because of the app so it would be cool if you made an official build of an IPA.
**Additional context**
Have a mock-up? Perhaps a template or set of files. Share them here!

**Make sure you’ve dine the following:**
- [ ] Provided a clear description into what the feature request is
- [ ] (If applicable) provided an issue that this request would fix
- [ ] (If applicable) presented potential possibilities into adding this request
- [ ] (If applicable) Provided evidence such as a drawing, log file, file, etc. of what you wish to see reflected

**Comment by Carter1190** [comment]
ofc a deb to ipa converter didnt work and even if signed correctly it would still require java to be inside of the ipa (not something done) making it pointless

**Comment by Doregon** [comment]
Not possible, due to the JDK being unavailable when jailed (among the plethora of other issues that would come attached).

**Comment by ayunami2000** [comment]
https://holzschu.github.io/a-Shell_iOS/ Is it possible to use the JDK with a system similar to this? I was able to get a minecraft launcher to run on it, but wasn't able to get into the game. Maybe it's still possible?

**Comment by Doregon** [comment]
While yes, it is possible to run the JDK on a-Shell or iSH, running the actual game requires libraries and frameworks that just wouldn’t be available to apps like these, because they are sandboxed and are emulators.

**Comment by ayunami2000** [comment]
Oh I meant to link iSh lol, but yeah good point.
