### ISSUE TITLE
[Bug Report] Multiplayer is not functional on the latest version of the app

### ISSUE THREAD

**Issue by pinballmanfan** [PojavLauncherTeam/PojavLauncher_iOS#159]
**First, let us know what you’re using.**
iPhone XR running iOS 14, PojavLauncher version 1.2

**Next, describe the issue.**
Attempting to join a server using a premium account results in the error "io.netty.channel.ConnectTimeoutException: connection timed out". The server I attempt to connect to is accessible from the desktop game. The version of the game is 1.16.5 with no mods or add-ons.

**What’s supposed to happen?**
A connection to the server should be established and I should be able to join the game.

**How does it happen?**
I open the latest version of the app, sign in with my Mojang account details, launch the game, attempt to connect to a valid IP, then I get a connection timeout error.

**Any files you want to send?**
A copy of the log file as well as a screenshot of the error is attached.

**Please verify that you have done the following:**

- [X] Provided details on what you’re seeing vs what you wanted
- [X] Provided a log file, if relevant
- [X] Provided steps to reproduce this issue
- [X] Tested on the latest version of PojavLauncher
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher_iOS/files/6407311/latestlog.txt)
![Error Message](https://user-images.githubusercontent.com/45546294/116738820-ef632800-a9c0-11eb-89f1-f7755b04abff.png)

**Comment by khanhduytran0** [comment]
You can try create `/etc/resolv.conf` with content:
```
nameserver 8.8.8.8
nameserver 8.8.4.4
```
Then, try again :eyes:

**Comment by pinballmanfan** [comment]
Creating resolv.conf with those nameservers worked, thanks.
