### ISSUE TITLE
App crashing + iPad support.

### ISSUE THREAD

**Issue by ExeRhythm** [PojavLauncherTeam/PojavLauncher_iOS#16]
Hi, just tested it on my iPad, but was a bit disappointed when I saw that the app does not support iPads. When I hit “play”, the screen appears, but it is not in full screen. Maybe you can change .presentationMode to .fullscreen? I thought that I had old version, so I installed the latest one, but it is crashing for me. I tried reinstalling, but no luck. Thanks!

**Comment by khanhduytran0** [comment]
> Maybe you can change .presentationMode to .fullscreen?

Done. Try the latest build.

> but it is crashing for me

Try the latest build.

**Comment by ExeRhythm** [comment]
Nope, still crashes :(

**Comment by khanhduytran0** [comment]
Can you send /var/mobile/Documents/minecraft/latestlog.txt?

**Comment by ExeRhythm** [comment]
```

2021-02-01 12:22:02.338 PojavLauncher[6604:349508] Found JLI lib
2021-02-01 12:22:02.338 PojavLauncher[6604:349508] Calling JLI_Launch
[0.033s][warning][os,thread] Attempt to protect stack guard pages failed (0x000000016d968000-0x000000016d974000).
[0.033s][warning][os,thread] Attempt to deallocate stack guard pages failed.
We are on java now! Starting UI...
2021-02-01 12:22:02.589 PojavLauncher[6604:349505] libpojavexec loaded from vm=0x102b59e50

```

**Comment by khanhduytran0** [comment]
How you ran the app?

**Comment by ExeRhythm** [comment]
I just launched it from the home screen. No command line

**Comment by khanhduytran0** [comment]
What's your iOS version?

**Comment by ExeRhythm** [comment]
iPadOS 13.6

**Comment by ExeRhythm** [comment]
Tho the previous versions are working

**Comment by khanhduytran0** [comment]
Which build works?

**Comment by ExeRhythm** [comment]
The one from 19 hours ago

**Comment by CrafterPika** [comment]
> Which build works?
build [#363](https://github.com/PojavLauncherTeam/PojavLauncher_iOS/actions/runs/524944305) works on my iPad

**Comment by khanhduytran0** [comment]
Hmm I wondering why adding SceneDelegate causes crashes? I gonna disable it

**Comment by khanhduytran0** [comment]
Also... where it crashes?

**Comment by khanhduytran0** [comment]
(When open the launcher or when press play?)

**Comment by CrafterPika** [comment]
For me, the launcher crashes upon opening

**Comment by ExeRhythm** [comment]
Me too, at app open

**Comment by ExeRhythm** [comment]
Also, it seems that the build failed. Could you look into this? Thanks

**Comment by khanhduytran0** [comment]
Try [this latest build](https://github.com/PojavLauncherTeam/PojavLauncher_iOS/actions/runs/527382115)

**Comment by CrafterPika** [comment]
Still crashes :(

latest log:
``
2021-02-01 12:05:13.545 PojavLauncher[16790:1142042] Found JLI lib
2021-02-01 12:05:13.546 PojavLauncher[16790:1142042] Calling JLI_Launch
[0.006s][warning][os,thread] Attempt to protect stack guard pages failed (0x000000016cedc000-0x000000016cee8000).
[0.006s][warning][os,thread] Attempt to deallocate stack guard pages failed.
We are on java now! Starting UI...
2021-02-01 12:05:13.631 PojavLauncher[16790:1142039] libpojavexec loaded from vm=0x103b59e50``

**Comment by khanhduytran0** [comment]
Hmmm the only remaining way is to obtain crash report. Go to Settings -> Privacy -> Analytics & improvements -> Analysts data -> find for the last item starting with PojavLauncher and send it

**Comment by CrafterPika** [comment]
i searched all the Analytics data and didn't found anything, even apps like CrashReporter from sparkdev don't show anything :(

**Comment by khanhduytran0** [comment]
I was able to reproduce the problem by removing minecraft folder but... it generates a crash report..

**Comment by khanhduytran0** [comment]
Did you create config_ver.txt?

**Comment by ExeRhythm** [comment]
> Did you create config_ver.txt?

No, should I manually do so?

**Comment by ExeRhythm** [comment]
[PojavLauncher-2021-02-01-154111.txt](https://github.com/PojavLauncherTeam/PojavLauncher_iOS/files/5903988/PojavLauncher-2021-02-01-154111.txt)
Here is Crash Log

**Comment by CrafterPika** [comment]
> Did you create config_ver.txt?

oh actually not. I thought that would've been created by default.

**Comment by CrafterPika** [comment]
yes after creating "/var/Mobile/Documents/config_ver.txt".
The Launcher should be default generate the file honestly, because you can easily forget to do that.

**Comment by khanhduytran0** [comment]
The deb file already have folder `/var/mobile/Documents/minecraft` but seems only when first time install. I gonna add safety create file

**Comment by ExeRhythm** [comment]
Actually, the file needs to be in `"/var/Mobile/Documents/minecraft/config_ver.txt" `

**Comment by khanhduytran0** [comment]
You're welcome! Also, does buttons looks small on iPad?

**Comment by CrafterPika** [comment]
> You're welcome! Also, does buttons looks small on iPad?

I think their decent 
![11C06330-0DEC-4AE3-BC98-8885A2D33143](https://user-images.githubusercontent.com/48294025/106464894-92c3a000-6499-11eb-89f2-664f13717007.png)
![C1395547-8373-4641-BB12-11AEFE6C47CB](https://user-images.githubusercontent.com/48294025/106464762-6019a780-6499-11eb-8c36-3776417abc4e.png)

Also one small suggestion that the file does not get overwritten every time. Because I wanna play with OptiFine (yes OptiFine does launch on It)

**Comment by CrafterPika** [comment]
thanks
