### ISSUE TITLE
Trying to launch PojavLauncher results in white screen with error in the log file

### ISSUE THREAD

**Issue by jawshoeadan** [PojavLauncherTeam/PojavLauncher_iOS#17]
Steps to reproduce:
1. Install openjdk Deb from this repo
2. Install PojavLauncher Deb from GitHub actions
3. Uicache
4. Launch PojavLauncher, get 1 of 3 possible outcomes: 1. iPad sheet pops up with white screen with controls, 2. iPad sheet pops up with a white screen and no controls, 3. iPad sheet pops up with controls but the output at top is stuck at downloading version jar at 0% (the version is already downloaded as I can see in filza)
5. Latest log attached

This is done on an iPad mini 4 13.7 checkra1n.

`2021-02-01 10:41:35.768 PojavLauncher[14744:3101222] Found JLI lib
2021-02-01 10:41:35.768 PojavLauncher[14744:3101222] Calling JLI_Launch
[0.045s][warning][os,thread] Attempt to protect stack guard pages failed (0x000000016db34000-0x000000016db40000).
[0.045s][warning][os,thread] Attempt to deallocate stack guard pages failed.
We are on java now! Starting UI...
2021-02-01 10:41:36.328 PojavLauncher[14744:3101220] libpojavexec loaded from vm=0x1024bde50
Finding a version
config_ver.txt not found, defaulting to Minecraft 1.16.5
Selected Minecraft version: 1.16.5
Downloading version list
Finding a version
config_ver.txt not found, defaulting to Minecraft 1.16.5
Selected Minecraft version: 1.16.5
Downloading version list
Ignored net.java.jinput:jinput:2.0.5
Ignored org.lwjgl:lwjgl:3.2.1
Ignored org.lwjgl:lwjgl:3.2.2
Ignored org.lwjgl:lwjgl-jemalloc:3.2.1
Ignored org.lwjgl:lwjgl-jemalloc:3.2.2
Ignored org.lwjgl:lwjgl-openal:3.2.1
Ignored org.lwjgl:lwjgl-openal:3.2.2
Ignored org.lwjgl:lwjgl-opengl:3.2.1
Ignored org.lwjgl:lwjgl-opengl:3.2.2
Ignored org.lwjgl:lwjgl-glfw:3.2.1
Ignored org.lwjgl:lwjgl-glfw:3.2.2
Ignored org.lwjgl:lwjgl-stb:3.2.1
Ignored org.lwjgl:lwjgl-stb:3.2.2
Ignored org.lwjgl:lwjgl-tinyfd:3.2.1
Ignored org.lwjgl:lwjgl-tinyfd:3.2.2
Ignored org.lwjgl:lwjgl:3.2.1
Ignored org.lwjgl:lwjgl:3.2.2
Ignored org.lwjgl:lwjgl-jemalloc:3.2.1
Ignored org.lwjgl:lwjgl-jemalloc:3.2.2
Ignored org.lwjgl:lwjgl-openal:3.2.1
Ignored org.lwjgl:lwjgl-openal:3.2.2
Ignored org.lwjgl:lwjgl-opengl:3.2.1
Ignored org.lwjgl:lwjgl-opengl:3.2.2
Ignored org.lwjgl:lwjgl-glfw:3.2.1
Ignored org.lwjgl:lwjgl-glfw:3.2.2
Ignored org.lwjgl:lwjgl-stb:3.2.1
Ignored org.lwjgl:lwjgl-tinyfd:3.2.2
Ignored org.lwjgl:lwjgl-tinyfd:3.2.1
Ignored org.lwjgl:lwjgl-stb:3.2.2
2021-02-01 10:41:40.861 PojavLauncher[14744:3101220] CoreText: *** Unmapped "\uFFE6" <CTFont: 0x100450e60>{name = .SFUI-Regular, size = 17.000000, matrix = 0x0, descriptor = <CTFontDescriptor: 0x282b38cc0>{attributes = {
    NSFontNameAttribute = ".SFUI-Regular";
}>}}
Downloading 1.16.5.jar
2021-02-01 10:41:40.906 PojavLauncher[14744:3101220] MGLKViewController viewDidLoad
2021-02-01 10:41:40.921 PojavLauncher[14744:3101220] Received SurfaceViewController callback, width=2048, height=1536
[LWJGL] Failed to load a library. Possible solutions:
	a) Add the directory that contains the shared library to -Djava.library.path or -Dorg.lwjgl.librarypath.
	b) Add the JAR that contains the shared library to the classpath.
[LWJGL] Enable debug mode with -Dorg.lwjgl.util.Debug=true for better diagnostics.
[LWJGL] Enable the SharedLibraryLoader debug mode with -Dorg.lwjgl.util.DebugLoader=true for better diagnostics.
Saving GLES context
Launching Minecraft 1.16.5
Ignored non-exists file: /var/mobile/Documents/minecraft/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
Ignored non-exists file: /var/mobile/Documents/minecraft/libraries/org/lwjgl/lwjgl/3.2.1/lwjgl-3.2.1.jar
Ignored non-exists file: /var/mobile/Documents/minecraft/libraries/org/lwjgl/lwjgl-jemalloc/3.2.1/lwjgl-jemalloc-3.2.1.jar
Ignored non-exists file: /var/mobile/Documents/minecraft/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2.jar
Ignored non-exists file: /var/mobile/Documents/minecraft/libraries/org/lwjgl/lwjgl-openal/3.2.1/lwjgl-openal-3.2.1.jar
Ignored non-exists file: /var/mobile/Documents/minecraft/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2.jar
Ignored non-exists file: /var/mobile/Documents/minecraft/libraries/org/lwjgl/lwjgl-opengl/3.2.1/lwjgl-opengl-3.2.1.jar
Ignored non-exists file: /var/mobile/Documents/minecraft/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2.jar
Ignored non-exists file: /var/mobile/Documents/minecraft/libraries/org/lwjgl/lwjgl-glfw/3.2.1/lwjgl-glfw-3.2.1.jar
Ignored non-exists file: /var/mobile/Documents/minecraft/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2.jar
Ignored non-exists file: /var/mobile/Documents/minecraft/libraries/org/lwjgl/lwjgl-stb/3.2.1/lwjgl-stb-3.2.1.jar
Ignored non-exists file: /var/mobile/Documents/minecraft/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2.jar
Ignored non-exists file: /var/mobile/Documents/minecraft/libraries/org/lwjgl/lwjgl-tinyfd/3.2.1/lwjgl-tinyfd-3.2.1.jar
Ignored non-exists file: /var/mobile/Documents/minecraft/libraries/org/lwjgl/lwjgl-tinyfd/3.2.2/lwjgl-tinyfd-3.2.2.jar
Ignored non-exists file: /var/mobile/Documents/minecraft/libraries/org/lwjgl/lwjgl/3.2.1/lwjgl-3.2.1.jar
Ignored non-exists file: /var/mobile/Documents/minecraft/libraries/org/lwjgl/lwjgl-jemalloc/3.2.1/lwjgl-jemalloc-3.2.1.jar
Ignored non-exists file: /var/mobile/Documents/minecraft/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2.jar
Ignored non-exists file: /var/mobile/Documents/minecraft/libraries/org/lwjgl/lwjgl-openal/3.2.1/lwjgl-openal-3.2.1.jar
Ignored non-exists file: /var/mobile/Documents/minecraft/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2.jar
Ignored non-exists file: /var/mobile/Documents/minecraft/libraries/org/lwjgl/lwjgl-opengl/3.2.1/lwjgl-opengl-3.2.1.jar
Ignored non-exists file: /var/mobile/Documents/minecraft/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2.jar
Ignored non-exists file: /var/mobile/Documents/minecraft/libraries/org/lwjgl/lwjgl-glfw/3.2.1/lwjgl-glfw-3.2.1.jar
Ignored non-exists file: /var/mobile/Documents/minecraft/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2.jar
Ignored non-exists file: /var/mobile/Documents/minecraft/libraries/org/lwjgl/lwjgl-stb/3.2.1/lwjgl-stb-3.2.1.jar
Ignored non-exists file: /var/mobile/Documents/minecraft/libraries/org/lwjgl/lwjgl-tinyfd/3.2.2/lwjgl-tinyfd-3.2.2.jar
Ignored non-exists file: /var/mobile/Documents/minecraft/libraries/org/lwjgl/lwjgl-tinyfd/3.2.1/lwjgl-tinyfd-3.2.1.jar
Ignored non-exists file: /var/mobile/Documents/minecraft/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2.jar
2021-02-01 10:41:41.225 PojavLauncher[14744:3101220] MGLKViewController pause
Ignored net.java.jinput:jinput:2.0.5
Ignored org.lwjgl:lwjgl:3.2.1
Ignored org.lwjgl:lwjgl:3.2.2
Ignored org.lwjgl:lwjgl-jemalloc:3.2.1
Ignored org.lwjgl:lwjgl-jemalloc:3.2.2
Ignored org.lwjgl:lwjgl-openal:3.2.1
Ignored org.lwjgl:lwjgl-openal:3.2.2
Ignored org.lwjgl:lwjgl-opengl:3.2.1
Ignored org.lwjgl:lwjgl-opengl:3.2.2
Ignored org.lwjgl:lwjgl-glfw:3.2.1
Ignored org.lwjgl:lwjgl-glfw:3.2.2
Ignored org.lwjgl:lwjgl-stb:3.2.1
Ignored org.lwjgl:lwjgl-stb:3.2.2
Ignored org.lwjgl:lwjgl-tinyfd:3.2.1
Ignored org.lwjgl:lwjgl-tinyfd:3.2.2
Ignored org.lwjgl:lwjgl:3.2.1
Ignored org.lwjgl:lwjgl:3.2.2
Ignored org.lwjgl:lwjgl-jemalloc:3.2.1
Ignored org.lwjgl:lwjgl-jemalloc:3.2.2
Ignored org.lwjgl:lwjgl-openal:3.2.1
Ignored org.lwjgl:lwjgl-openal:3.2.2
Ignored org.lwjgl:lwjgl-opengl:3.2.1
Ignored org.lwjgl:lwjgl-opengl:3.2.2
Ignored org.lwjgl:lwjgl-glfw:3.2.1
Ignored org.lwjgl:lwjgl-glfw:3.2.2
Ignored org.lwjgl:lwjgl-stb:3.2.1
Ignored org.lwjgl:lwjgl-tinyfd:3.2.2
Ignored org.lwjgl:lwjgl-tinyfd:3.2.1
Ignored org.lwjgl:lwjgl-stb:3.2.2
Downloading 1.16.5.jar
2021-02-01 10:41:41.730 PojavLauncher[14744:3101220] MGLKViewController viewDidAppear
2021-02-01 10:41:41.731 PojavLauncher[14744:3101220] MGLKViewController pause
2021-02-01 10:41:41.731 PojavLauncher[14744:3101220] MGLKViewController resume
2021-02-01 10:41:41.732 PojavLauncher[14744:3101220] Warning: Attempt to present <SurfaceViewController: 0x10046b0f0>  on <LauncherViewController: 0x100734b50> which is already presenting <SurfaceViewController: 0x100453130>
2021-02-01 10:41:41.748 PojavLauncher[14744:3101220] MGLKViewController pause
2021-02-01 10:41:43.272 PojavLauncher[14744:3101220] MGLKViewController viewDidDisappear
2021-02-01 10:41:43.272 PojavLauncher[14744:3101220] MGLKViewController pause`
![936072A1-7C4D-44FD-A963-A764BA828B70](https://user-images.githubusercontent.com/62785552/106503330-559be580-647a-11eb-91c5-3296755f9ad4.png)
![0C3D042F-B7FF-4144-9630-A39812B9935C](https://user-images.githubusercontent.com/62785552/106503334-56cd1280-647a-11eb-8805-fdab9358bb32.png)
#

**Comment by khanhduytran0** [comment]
You are on old build, which the launch screen was not fullscreen on iPad. Try latest build.

**Comment by jawshoeadan** [comment]
Now, the app is stuck on the controls with no game popping up. Here is what it looks like and here is my new log.
`2021-02-01 23:15:27.309 PojavLauncher[17837:3250995] Found JLI lib
2021-02-01 23:15:27.309 PojavLauncher[17837:3250995] Calling JLI_Launch
[0.111s][warning][os,thread] Attempt to protect stack guard pages failed (0x000000016d778000-0x000000016d784000).
[0.111s][warning][os,thread] Attempt to deallocate stack guard pages failed.
We are on java now! Starting UI...
2021-02-01 23:15:28.056 PojavLauncher[17837:3250982] libpojavexec loaded from vm=0x102b59e50
Finding a version
Selected Minecraft version: rd-132211
Downloading version list
Downloading rd-132211.json assets info
Ignored net.java.jinput:jinput:2.0.5
Ignored org.lwjgl.lwjgl:lwjgl:2.9.0
Ignored org.lwjgl.lwjgl:lwjgl_util:2.9.0
Ignored org.lwjgl.lwjgl:lwjgl-platform:2.9.0
Ignored org.lwjgl.lwjgl:lwjgl:2.9.1-nightly-20130708-debug3
Ignored org.lwjgl.lwjgl:lwjgl_util:2.9.1-nightly-20130708-debug3
Ignored org.lwjgl.lwjgl:lwjgl-platform:2.9.1-nightly-20130708-debug3
Ignored net.java.jinput:jinput-platform:2.0.5
Ignored net.java.jinput:jinput-platform:2.0.5
Downloading rd-132211.jar
2021-02-01 23:15:34.847 PojavLauncher[17837:3250982] MGLKViewController viewDidLoad
2021-02-01 23:15:34.859 PojavLauncher[17837:3250982] Received SurfaceViewController callback, width=2048, height=1536
Saving GLES context
Launching Minecraft rd-132211
Ignored non-exists file: /var/mobile/Documents/minecraft/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
Ignored non-exists file: /var/mobile/Documents/minecraft/libraries/org/lwjgl/lwjgl/lwjgl/2.9.0/lwjgl-2.9.0.jar
Ignored non-exists file: /var/mobile/Documents/minecraft/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.0/lwjgl_util-2.9.0.jar
Ignored non-exists file: /var/mobile/Documents/minecraft/libraries/org/lwjgl/lwjgl/lwjgl-platform/2.9.0/lwjgl-platform-2.9.0.jar
Ignored non-exists file: /var/mobile/Documents/minecraft/libraries/org/lwjgl/lwjgl/lwjgl/2.9.1-nightly-20130708-debug3/lwjgl-2.9.1-nightly-20130708-debug3.jar
Ignored non-exists file: /var/mobile/Documents/minecraft/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.1-nightly-20130708-debug3/lwjgl_util-2.9.1-nightly-20130708-debug3.jar
Ignored non-exists file: /var/mobile/Documents/minecraft/libraries/org/lwjgl/lwjgl/lwjgl-platform/2.9.1-nightly-20130708-debug3/lwjgl-platform-2.9.1-nightly-20130708-debug3.jar
Ignored non-exists file: /var/mobile/Documents/minecraft/libraries/net/java/jinput/jinput-platform/2.0.5/jinput-platform-2.0.5.jar
Ignored non-exists file: /var/mobile/Documents/minecraft/libraries/net/java/jinput/jinput-platform/2.0.5/jinput-platform-2.0.5.jar
2021-02-01 23:15:35.050 PojavLauncher[17837:3250982] Keyboard cannot present view controllers (attempted to present <SurfaceViewController: 0x100868c50>)
2021-02-01 23:15:35.625 PojavLauncher[17837:3250982] MGLKViewController viewDidAppear
2021-02-01 23:15:35.625 PojavLauncher[17837:3250982] MGLKViewController pause
2021-02-01 23:15:35.625 PojavLauncher[17837:3250982] MGLKViewController resume
2021-02-01 23:15:35.629 PojavLauncher[17837:3250982] MGLKViewController pause
2021-02-01 23:15:55.759 PojavLauncher[17837:3250982] MGLKViewController appWillPause:
2021-02-01 23:15:55.760 PojavLauncher[17837:3250982] MGLKViewController pause
2021-02-01 23:15:56.775 PojavLauncher[17837:3250982] MGLKViewController pause
2021-02-01 23:15:56.967 PojavLauncher[17837:3250982] MGLKViewController pause
`
![F64EFF30-83E9-4394-BAF8-ADEBAFB70E9F](https://user-images.githubusercontent.com/62785552/106565605-ece95300-64e3-11eb-95cf-5ac7adb7b716.png)

I left it for around 20 mins

**Comment by ExeRhythm** [comment]
Maybe changing version to 1.16.5 will help?

**Comment by khanhduytran0** [comment]
Legacy version will not work on new builds.

**Comment by khanhduytran0** [comment]
Only 1.14+ will work at the moment.

**Comment by jawshoeadan** [comment]
Yeah I keep trying on 1.16.5 but after downloading everything, I still get a blank screen with the controls over it like the screenshot above. I think there's an issue with the launcher on iPads only.

**Comment by khanhduytran0** [comment]
I see that @ExeRhythm'a iPad works. But I wondering something wrong with your iPad...

**Comment by khanhduytran0** [comment]
@jawshoeadan get latest action build.

**Comment by jawshoeadan** [comment]
@khanhduytran0 Thank you so much for your help! This latest build works. Great work on PojavLauncher!
