### ISSUE TITLE
JSONMappingException when trying to log into Mojang account on iPadOS 14.3 (Taurine Jailbreak)

### ISSUE THREAD

**Issue by PCITechie** [PojavLauncherTeam/PojavLauncher_iOS#171]
Nothing looks wrong in latestlog.txt, error message is below. This happens after trying to log into my Mojang account. I use a long password and a password manager if that information helps at all.

> **JsonMappingException**
> 
> Unrecognized character escape
> 'k' (code 107)
> at [Source: (org.eclipse.jetty.server-
> -HttpInputOverHTTP); line: 1, column:
> 109] (through reference chain:
> com.mojang.yggdrasil.auth.dataac-
> cess.memcached.throttling.captcha.-
> CaptchaCredentials["password"]) `

**Comment by Doregon** [comment]
Try without the password manager.

**Comment by Doregon** [comment]
Closing stale issue.
