### ISSUE TITLE
Pojavoptimize or Optifine?

### ISSUE THREAD

**Issue by creyes200** [PojavLauncherTeam/PojavLauncher_iOS#174]
Hello i just have a one question: i have an iphone 7 and i wouldlike to know what is more recomendable to use on PojavLauncher, Optifine or Pojavoptimize (the one included in the repo)

to make the experience less laggy

**Comment by Doregon** [comment]
Here's my take (gonna be impartial as I switch between both OptiFine and PojavOptimize on my SE):

It depends on if there's *any* other factors. Here's a table:

|   | PojavOptimize | OptiFine |
| ------------- | ------------- | ------------ |
| A9 Performance  | ~34-42 FPS  | ~28-35 FPS |
| Fabric?  | Yes, included | Yes, with OptiFabric |
| Forge? | No, uses Fabric to work | Yes, but may not work |
| Works with mods? | Most Fabric mods | Yes, most Fabric and Forge mods |
| Works with shaders | No | GL4ES shaders only |
| Disk space required | ~100 MB | ~10-30 MB |

PojavOptimize performs better but is a bigger package and doesn't support Forge, some performance-improving Fabric mods, and shaders. OptiFine performs worse by a couple FPS, but can work in Forge or Fabric with many more mods, as well as certain shaders, in a slimmer package.

**Comment by creyes200** [comment]
Thanks 😊
