### ISSUE TITLE
[Bug Report] Forge 1.12.2 not loading.

### ISSUE THREAD

**Issue by creyes200** [PojavLauncherTeam/PojavLauncher_iOS#175]
**First, let us know what you’re using.**

Iphone 7 ios 14.4.2 checkra1n jailbreak
**Next, describe the issue.**
Make sure to be as descriptive as possible. 

when i try to run forge 1.12.2 it gets stuck on the loading screen or crashes.
**What’s supposed to happen?**
What were you expecting?

i was expecting to see minectaft load with forge 1.12.2
**How does it happen?**

idk it just doesnt load mc

**Please verify that you have done the following:**

- [ ] Provided details on what you’re seeing vs what you wanted
- [ ] Provided a log file, if relevant
- [ ] Provided steps to reproduce this issue
- [ ] Tested on the latest version of PojavLauncher

**Comment by Doregon** [comment]
Forge versions older than 1.16.x don't work with PojavLauncher at the moment, this is due to the usage of OpenJDK 16.

**Comment by creyes200** [comment]
Thanks
