### ISSUE TITLE
[Bug Report] No background in older versions

### ISSUE THREAD

**Issue by creyes200** [PojavLauncherTeam/PojavLauncher_iOS#176]
When i load any version other than 1.16 the classic backround in the title scrren is missing (there’s  more of a grey sky backround) 

is this something i need to worry about?

just checking if there’s a fix

**Comment by Doregon** [comment]
Check to see if 1.16 still has a background. If 1.16 has the grey background, delete the `/var/mobile/Documents/minecraft/assets` folder and try again.

**Comment by creyes200** [comment]
Ok ill try but my phone rebooted and i dont have my computer to rejailbreak so ill have to wait😂
