### ISSUE TITLE
[Question]how to update PojavLauncher 

### ISSUE THREAD

**Issue by creyes200** [PojavLauncherTeam/PojavLauncher_iOS#180]
How do i know if i have the latest version of PojavLauncher.¿does it update automatically from the cydia repo? Or is there something i have to do?

checkra1n jailbreak ios 14.4.2

**Comment by Doregon** [comment]
Where did you get it?

**Comment by creyes200** [comment]
From doregons repo on cydia

**Comment by Doregon** [comment]
It will automatically update.

**Comment by creyes200** [comment]
Thanks 🙏
