### ISSUE TITLE
[F-Req] File integrity check

### ISSUE THREAD

**Issue by NotAHero04** [PojavLauncherTeam/PojavLauncher_iOS#182]
When the launcher downloads music files for Minecraft, it usually misses something.

A part of my latestlog.txt says:

[04:02:01] [Worker-Main-1/WARN]: File minecraft:sounds/music/game/creative/creative5.ogg does not exist, cannot add it to event minecraft:music.creative

I need a check after downloading (or can be triggered anytime) to ensure every file has been downloaded.

**Comment by khanhduytran0** [comment]
As the mentioned commit above is still a workaround, probably I need to rewrite the entire downloader to objc before adding more checks.

**Comment by khanhduytran0** [comment]
The downloader is fully written to Objective-C and included SHA1 check now.
