### ISSUE TITLE
[Bug Report]

### ISSUE THREAD

**Issue by Rice-Krispy** [PojavLauncherTeam/PojavLauncher_iOS#187]
Sorry for opening another issue today but just to be sure, Multiplayer for PojavLauncher on iOS is currently not working or is bugged.

**Comment by Doregon** [comment]
We need more information. This is also the second time you have not followed the issue templates, which are there for important reasons. Following the issue template is not an option, and any issue not following the template after this warning will be closed without comments.

**Comment by Carter1190** [comment]
it does seem that multiplayer is indeed bugged,should i make a new issue and put everything in there (the issue template, all my info,etc) or just keep it in here?

**Comment by Doregon** [comment]
@Carter1190 make a new issue that follows the template. I’ll close and link this one to it.

**Comment by khanhduytran0** [comment]
@Rice-Krispy it has been months and you still haven't filled the details.
- LAN multiplayer requires the clients to be logged in with an online (or usually called "premium") account.
- Most servers have online mode enabled, which requires an online account.
- Realms may not work.
