### ISSUE TITLE
how do a change selected slot in hotbar

### ISSUE THREAD

**Issue by ProBlueCougar** [PojavLauncherTeam/PojavLauncher_iOS#189]
I can't change my selected hotbar slot 
IOS 14
iphone 7

**Comment by Doregon** [comment]
Delete `/var/mobile/Documents/minecraft/options.txt` and try again

**Comment by ProBlueCougar** [comment]
still can't change selected slot
(I've just been trying to tap the hotbar do I do it a different way?)

**Comment by ProBlueCougar** [comment]
never mind I figered it out
