### ISSUE TITLE
[Bug Report] Blank after entering "Setting"

### ISSUE THREAD

**Issue by Eric120110** [PojavLauncherTeam/PojavLauncher_iOS#190]
**First, let us know what you’re using.**
Tell us what iOS/iPadOS device and version you’re using, and the PojavLauncher version.
IOS 12.4, iPhone 6s, Unc0ver Cydia, PojavLauncher 1.2
**Next, describe the issue.**
Make sure to be as descriptive as possible. 
It is blank after entering the "Settings" option.
**What’s supposed to happen?**
What were you expecting?
There are some setting options, and java parameters.
**How does it happen?**
Let’s get a step by step on how to reproduce this issue.

**Any files you want to send?**
We could use a copy of latestlog.txt or a Cr4shed screenshot.

**Please verify that you have done the following:**

- [x] Provided details on what you’re seeing vs what you wanted
- [ ] Provided a log file, if relevant
- [x] Provided steps to reproduce this issue
- [x] Tested on the latest version of PojavLauncher

**Comment by Ryorama** [comment]
I pretty sure the settings menu isn’t fully implemented yet.

**Comment by Doregon** [comment]
@Eric120110 There’s nothing in the Settings menu yet
