### ISSUE TITLE
[Bug Report] banners and sheep are white even if dyed

### ISSUE THREAD

**Issue by creyes200** [PojavLauncherTeam/PojavLauncher_iOS#193]
**First, let us know what you’re using.**
iPhone 7 ios 14.4.2 checkra1n jailbreak

**Next, describe the issue. 
banners, sheep and spawn eggs are always white even if u dye them
**What’s supposed to happen?**
What were you expecting?

To see colors on them

**How does it happen?*

the banners are simply white

- [ ] Provided a log file, if relevant
- [ ] Provided steps to reproduce this issue
- [x] Tested on the latest version of PojavLauncher

**Comment by creyes200** [comment]
![550589D8-6A58-48A0-963E-24E287D62FD1](https://user-images.githubusercontent.com/84339275/120089260-8b6a7700-c0c6-11eb-904f-6369e45e00c6.jpeg)
![CF50BAD9-3E46-42AD-A7C6-FC8CCC528BB1](https://user-images.githubusercontent.com/84339275/120089263-8efdfe00-c0c6-11eb-9aa4-d2c307dbe046.jpeg)
![Uploading 6979B529-4DAC-4BDF-AA29-F3DC6F1D2718.jpeg…]()

**Comment by creyes200** [comment]
![FEFAC5F0-E787-413B-899A-BC4B1BA89E30](https://user-images.githubusercontent.com/84339275/120089267-91605800-c0c6-11eb-85f8-7a1e84b154ec.png)

**Comment by creyes200** [comment]
I know ive issued this before.
I just want to know if theres a fix for ios

**Comment by ENDERMANYK** [comment]
this a bug exists above the 1.16 version, you will need GL4ES 1.1.5 for this to fix, but GL4ES 1.1.5 seem doesn't works on IOS version..

**Comment by creyes200** [comment]
How do i get GL4ES??

**Comment by creyes200** [comment]
Could i fix it installing a default vanilla texture pack?

**Comment by ENDERMANYK** [comment]
hmm, you already got GL4ES built-in your device.. but it is 1.1.4 version instead of 1.1.5 version

**Comment by creyes200** [comment]
Will it be updated??

**Comment by ENDERMANYK** [comment]
maybe it caused by MetalANGEL translate layer, I am not very sure about this

**Comment by creyes200** [comment]
Ok thanks 

just checking if there was a fix

**Comment by khanhduytran0** [comment]
In v2.0, you can switch to gl4es 1.1.5 in the preferences.
