### ISSUE TITLE
[QUESTION] NOT ABLE TO RUN GAME

### ISSUE THREAD

**Issue by Vedansh-21** [PojavLauncherTeam/PojavLauncher_iOS#194]
I am not able to run minecraft on my iphone 6a
As soon as i start it, it loads for around 2 minutes and then it crashes plz help!

**Comment by khanhduytran0** [comment]
@Vedansh-21 now fill the template

**Comment by khanhduytran0** [comment]
@Vedansh-21 we don’t know anything other than “you can’t run game on your iPhone 6(s?)” that’s all. no log

**Comment by khanhduytran0** [comment]
https://github.com/PojavLauncherTeam/PojavLauncher_iOS/blob/main/.github/ISSUE_TEMPLATE/bug-report.md

**Comment by khanhduytran0** [comment]
Didn’t respond. Closing.
