### ISSUE TITLE
[Bug Report] hotbar slot, crashing and ram allocation 

### ISSUE THREAD

**Issue by bstar16** [PojavLauncherTeam/PojavLauncher_iOS#196]
**First, let us know what you’re using.**
iphone 6s plus ios 13.5

**Next, describe the issue.**
can’t use hot bar and game crashes sometimes after like 1-2 mins, i’d also like to know how to allocate more raw

**What’s supposed to happen?**
game should run fine usually and not crash after 1 min and i should be able to use hotbar

**How does it happen?**
nothing really makes it crash but i’m usually just walking around and that when it crashes, this is on forge and vanilla 1.16.5
**Any files you want to send?**
add me on discord or ping me in the pojav server if you want them bstar#1600
**Please verify that you have done the following:**
i have

**Comment by Doregon** [comment]
Hotbar issue should be fixed in development builds. Jetsam crashing can be overcome as described on the pinned issue.
