### ISSUE TITLE
[Bug Report] Microsoft Login Problem

### ISSUE THREAD

**Issue by Plasmapea987** [PojavLauncherTeam/PojavLauncher_iOS#197]
# To Reproduce:
Indicate steps to reproduce the buggy behavior: open PojavLauncher and select account then select Microsoft account 

# Expected behavior:
I expected to see the gui and the mojang logo

# Screenshots or videos:
*Upload here screenshots or videos of the buggy behavior, if possible.*

# Platform:
 - Platform ios
 - Uncover 6.1.1
 - Device Model iPhone 7+
 -iOS Version 14.3
 - PojavLauncher Version Latest Release 1.2
 - Minecraft 1.16.5

**Comment by Doregon** [comment]
wdym expected to see gui and mojang logo

**Comment by sasak2** [comment]
When i login with microsoft account, it doesn’t login
Ios 14.6
Iphone x
Jailbreaked with checkra1n

**Comment by khanhduytran0** [comment]
Update to latest build (pojavlauncher-dev)
- if you get "can't login with a demo account", check if you have bought Minecraft **Java*
- if you get "AddChildToFamily", add your account to your parent account.
