### ISSUE TITLE
[Bug Report] Hotbar switching doesn't work

### ISSUE THREAD

**Issue by 404oops** [PojavLauncherTeam/PojavLauncher_iOS#198]
**First, let us know what you’re using.**
Tell us what iOS/iPadOS device and version you’re using, and the PojavLauncher version.
14.7 Public Beta, Latest PojavLauncher 
**Next, describe the issue.**
Make sure to be as descriptive as possible. 
I can't switch to items on my hotbar
**What’s supposed to happen?**
What were you expecting?
To have tap controls to switch
**How does it happen?**
Let’s get a step by step on how to reproduce this issue.
Tapping on items (even opening the keyboard to press the buttons) doesn't work 
**Any files you want to send?**
We could use a copy of latestlog.txt or a Cr4shed screenshot.
No logs needed
**Please verify that you have done the following:**

- [x] Provided details on what you’re seeing vs what you wanted
- [x] Provided a log file, if relevant
- [x] Provided steps to reproduce this issue
- [x] Tested on the latest version of PojavLauncher

**Comment by khanhduytran0** [comment]
What is current Minecraft version?

**Comment by 404oops** [comment]
1.16.5

**Comment by Doregon** [comment]
Not reproducible with the latest release or builds.
