### ISSUE TITLE
[Bug Report]Fabric crashes on latest version

### ISSUE THREAD

**Issue by creyes200** [PojavLauncherTeam/PojavLauncher_iOS#201]
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher_iOS/files/6594339/latestlog.txt)

**First, let us know what you’re using.**
Iphone 7 ios 14.4.2
**Next, describe the issue.**
Make sure to be as descriptive as possible. 

fabric never loads (it gets stuck after pressing play) on latest version of PojavLauncher , i had to downgrade to make it work
**What’s supposed to happen?**
What were you expecting?
Fabric to load
**How does it happen?**
I noticed fabric wasnt working so i removed pojavfabric, but then i realized that i coudnt reinstall it because  it was no longer in the repo so when i installed it manually with the commands it wont load, i fixed the issue by downgrading PojavLauncher , but i dont want to stay stuck in an older version.

**Any files you want to send? 

**Please verify that you have done the following:**

- [ ] Provided details on what you’re seeing vs what you wanted
- [x] Provided a log file, if relevant
- [x] Provided steps to reproduce this issue
- [x] Tested on the latest version of PojavLauncher

**Comment by Doregon** [comment]
We can't help if there's no logs.

**Comment by creyes200** [comment]
I updated to the latest version and the same thing i am describing happened  and i sent latestlog txt

**Comment by creyes200** [comment]
Btw o wrote something wrong but i fixed it
( the game didn’t crash it jist didn’t load)

**Comment by Doregon** [comment]
I could only reproduce this when installing as root, which means you did not follow the website's installation instructions correctly. It is very clearly marked:

> Open a terminal or SSH client and **make sure you don't `su` and become root with the next command!**

To fix this, you need to run the following as root.

```
sudo chown -R mobile:mobile /var/mobile/Documents
```

And please, **read the website's instructions carefully.** We will not be providing support for not following directions correctly.

**Comment by creyes200** [comment]
Srry its just that it said operation not permitted when i did it without root

**Comment by Doregon** [comment]
```
sudo chown -R +x /usr/lib/jvm/java-16-openjdk/bin/*
```

This is also marked on the website.

**Comment by creyes200** [comment]
It worked!!!Well thank you you clearly know what your doing and PojavLauncher is awesome so thank you for being part of it
