### ISSUE TITLE
[Bug Report]the create mod crashes

### ISSUE THREAD

**Issue by creyes200** [PojavLauncherTeam/PojavLauncher_iOS#203]
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher_iOS/files/6599052/latestlog.txt)

**First, let us know what you’re using.**
Iphone 7 ios 14.4.2 on lates version of pojav launcher
**Next, describe the issue.**
Make sure to be as descriptive as possible. 
When i load forge with the create mod its start up but when the white bar almost finishes loading it crshes
**What’s supposed to happen?**
What were you expecting

For it to load MC with the mod running

**How does it happen?**
Let’s get a step by step on how to reproduce this issue.

i pasted the create mod .jar file into the mods folder and copy and pasted the forge version name into configversiontxt and when i started MC it was about to finish loading and crashed. Normally i would ignore this but the create mod runs fairly well on low end devices so i want to know if i did something wrong
**Any files you want to send?**
We could use a copy of latestlog.txt or a Cr4shed screenshot.

**Please verify that you have done the following:**

- [x] Provided details on what you’re seeing vs what you wanted
- [x] Provided a log file, if relevant
- [x] Provided steps to reproduce this issue
- [x] Tested on the latest version of PojavLauncher

**Comment by creyes200** [comment]
I sent latestlog.txt

**Comment by Doregon** [comment]
The Create mod doesn't seem to be supported at the moment. Your logs are similar to mine and they both point to issues rendering shaders, which means that the OpenGL version we're using doesn't have the features required.

**Comment by creyes200** [comment]
Ok thanks
