### ISSUE TITLE
[Question]is forge 1.12.2 supported??

### ISSUE THREAD

**Issue by creyes200** [PojavLauncherTeam/PojavLauncher_iOS#207]
Can forge 1.12.2 run on PojavLauncher??

**Comment by Carter1190** [comment]
currently no wait till java 8 release

**Comment by creyes200** [comment]
Ok

**Comment by kareemnew2019** [comment]
It is supported

**Comment by kareemnew2019** [comment]
3.1.1 latest

**Comment by kareemnew2019** [comment]
Version of pojavlauncher
And latest of forge

**Comment by Doregon** [comment]
@kareemnew2019 No it is not. iOS is different from Android, please make sure you know what you are talking about before posting comments.
