### ISSUE TITLE
[Question]how to run modpacks

### ISSUE THREAD

**Issue by creyes200** [PojavLauncherTeam/PojavLauncher_iOS#208]
If i paste a mod pack into the version folder will it run the modpack?? If not how could i run a modpack

**Comment by kareemnew2019** [comment]
https://youtube.com/c/FrostBTW
NOT ALL MODPACKS WORK THIS CHANNEL
TELL YOU HOW TO INSTALL SUPPORTED MODPACKS

**Comment by creyes200** [comment]
Thats for android not ios
