### ISSUE TITLE
[Bug Report] libgl4es_115 crashes the launcher

### ISSUE THREAD

**Issue by NotAHero04** [PojavLauncherTeam/PojavLauncher_iOS#209]
**First, let us know what you’re using.**
Tell us what iOS/iPadOS device and version you’re using, and the PojavLauncher version.
iPhone 6, iOS 12.5.2
Newest PojavLauncher (dev) version.
**Next, describe the issue.**
Make sure to be as descriptive as possible. 
I tried using libgl4es_115.dylib by using this argument:
-Dorg.lwjgl.opengl.libname=libgl4es_115.dylib
(changing the extension to .so makes lwjgl unable to use that library)
The launcher can’t go to the loading screen, instead, it crashed and Cr4shed threw a crash report.
**What’s supposed to happen?**
What were you expecting?
There would be a loading screen, or worse, a Minecraft crash report.
**How does it happen?**
Let’s get a step by step on how to reproduce this issue.
1: Have this in overrideargs.txt:
-Dorg.lwjgl.opengl.libname=libgl4es_115.dylib
2: Open the launcher. Choose any version from 1.16 to 1.17 (I have tested 1.16.5 Fabric and 1.17 vanilla), I don’t know if other versions could be used.
3: Simply press Play.
**Any files you want to send?**
We could use a copy of latestlog.txt or a Cr4shed screenshot.
This is my Cr4shed log: 

Date: 6/9/21, 1:16 AM
Process: PojavLauncher
Bundle id: net.kdt.pojavlauncher
Device: iPhone 6, iOS 12.5.2
Bundle version: 1.2

Exception type: EXC_BAD_ACCESS (SIGSEGV)
Exception subtype: KERN_INVALID_ADDRESS: 0x1828
Exception codes: 0x0000000000000001, 0x0000000000001828
Culprit: Unknown
VM Protection: 0x1828 is not in any region.

Triggered by thread: 36
Thread name: 
Call stack:
0   libsystem_kernel.dylib        	0x000000018159f124 0x18157c000 + 143652     	// __pthread_sigmask
1   libsystem_pthread.dylib       	0x0000000181622dc8 0x181616000 + 52680      	// pthread_sigmask
2   libjvm.dylib                  	0x00000001017ceaac 0x100f2c000 + 9054892    	// PosixSignals::chained_handler(int, __siginfo*, void*)
3   libjvm.dylib                  	0x00000001017cebf8 0x100f2c000 + 9055224    	// JVM_handle_bsd_signal
4   libsystem_platform.dylib      	0x00000001816129fc 0x18160b000 + 31228      	// _sigtramp
5   libgl4es_115.dylib            	0x0000000122db16e0 0x122cf4000 + 775904     	// gl4es_glGetError
6   ???                           	0x0000000147bb6070 0 + 5498429552
7   ???                           	0x0000000147bb1e68 0 + 5498412648
8   ???                           	0x0000000147bb1d80 0 + 5498412416
9   ???                           	0x0000000147bb1d80 0 + 5498412416
10  ???                           	0x0000000147bb1fc8 0 + 5498413000
11  ???                           	0x0000000147bb1d80 0 + 5498412416
12  ???                           	0x0000000147bb1fc8 0 + 5498413000
13  ???                           	0x0000000147bac144 0 + 5498388804
14  libjvm.dylib                  	0x000000010137bcd8 0x100f2c000 + 4521176    	// JavaCalls::call_helper(JavaValue*, methodHandle const&, JavaCallArguments*, Thread*)
15  libjvm.dylib                  	0x00000001017278e8 0x100f2c000 + 8370408    	// invoke(InstanceKlass*, methodHandle const&, Handle, bool, objArrayHandle, BasicType, objArrayHandle, bool, Thread*)
16  libjvm.dylib                  	0x0000000101726f5c 0x100f2c000 + 8367964    	// Reflection::invoke_method(oopDesc*, Handle, objArrayHandle, Thread*)
17  libjvm.dylib                  	0x000000010142df18 0x100f2c000 + 5250840    	// JVM_InvokeMethod
18  ???                           	0x0000000147bb6070 0 + 5498429552
19  ???                           	0x0000000147bb1d80 0 + 5498412416
20  ???                           	0x0000000148532078 0 + 5508374648
21  ???                           	0x0000000147bb1d80 0 + 5498412416
22  ???                           	0x0000000147bb2508 0 + 5498414344
23  ???                           	0x0000000147bb1fc8 0 + 5498413000
24  ???                           	0x0000000147bac144 0 + 5498388804
25  libjvm.dylib                  	0x000000010137bcd8 0x100f2c000 + 4521176    	// JavaCalls::call_helper(JavaValue*, methodHandle const&, JavaCallArguments*, Thread*)
26  libjvm.dylib                  	0x00000001017278e8 0x100f2c000 + 8370408    	// invoke(InstanceKlass*, methodHandle const&, Handle, bool, objArrayHandle, BasicType, objArrayHandle, bool, Thread*)
27  libjvm.dylib                  	0x0000000101726f5c 0x100f2c000 + 8367964    	// Reflection::invoke_method(oopDesc*, Handle, objArrayHandle, Thread*)
28  libjvm.dylib                  	0x000000010142df18 0x100f2c000 + 5250840    	// JVM_InvokeMethod
29  ???                           	0x0000000147bb6070 0 + 5498429552
30  ???                           	0x0000000147bb1d80 0 + 5498412416
31  ???                           	0x0000000147bb1d80 0 + 5498412416
32  ???                           	0x0000000147bb22c0 0 + 5498413760
33  ???                           	0x0000000147bb1d80 0 + 5498412416
34  ???                           	0x0000000147bb1fc8 0 + 5498413000
35  ???                           	0x0000000147bb2508 0 + 5498414344
36  ???                           	0x0000000147bac144 0 + 5498388804
37  libjvm.dylib                  	0x000000010137bcd8 0x100f2c000 + 4521176    	// JavaCalls::call_helper(JavaValue*, methodHandle const&, JavaCallArguments*, Thread*)
38  libjvm.dylib                  	0x000000010137ad74 0x100f2c000 + 4517236    	// JavaCalls::call_virtual(JavaValue*, Klass*, Symbol*, Symbol*, JavaCallArguments*, Thread*)
39  libjvm.dylib                  	0x000000010137ae40 0x100f2c000 + 4517440    	// JavaCalls::call_virtual(JavaValue*, Handle, Klass*, Symbol*, Symbol*, Thread*)
40  libjvm.dylib                  	0x0000000101429a70 0x100f2c000 + 5233264    	// thread_entry(JavaThread*, Thread*)
41  libjvm.dylib                  	0x000000010187c278 0x100f2c000 + 9765496    	// JavaThread::thread_main_inner()
42  libjvm.dylib                  	0x0000000101879eb4 0x100f2c000 + 9756340    	// Thread::call_run()
43  libjvm.dylib                  	0x00000001016b7018 0x100f2c000 + 7909400    	// thread_native_entry(Thread*)
44  libsystem_pthread.dylib       	0x00000001816212c0 0x181616000 + 45760      	// _pthread_body
45  libsystem_pthread.dylib       	0x0000000181621220 0x181616000 + 45600      	// _pthread_start
46  libsystem_pthread.dylib       	0x0000000181624cdc 0x181616000 + 60636      	// thread_start

Register values:
PC: 0x0                 LR: 0x0                 CPSR: 0x0
x0: 0x0                 x1: 0x0                 x2: 0x0
x3: 0x0                 x4: 0x0                 x5: 0x0
x6: 0x0                 x7: 0x0                 x8: 0x0
x9: 0x0                 x10: 0x0                x11: 0x0
x12: 0x0                x13: 0x0                x14: 0x0
x15: 0x0                x16: 0x0                x17: 0x0
x18: 0x0                x19: 0x0                x20: 0x0
x21: 0x0                x22: 0x0                x23: 0x0
x24: 0x0                x25: 0x0                x26: 0x0
x27: 0x0                x28: 0x0

Loaded images:
0: /Applications/PojavLauncher.app/PojavLauncher
1: /usr/lib/pspawn_payload-stg2.dylib
2: /usr/lib/TweakInject.dylib
3: /usr/lib/dyld
4: /Library/TweakInject/   Choicy.dylib
5: /Library/Frameworks/CydiaSubstrate.framework/CydiaSubstrate
6: /usr/lib/libhooker.dylib
7: /usr/lib/libblackjack.dylib
8: /Library/TweakInject/0Cr4shed.dylib
9: /usr/lib/libmryipc.dylib
10: /usr/lib/jvm/java-16-openjdk/lib/libjli.dylib
11: /usr/lib/jvm/java-16-openjdk/lib/server/libjvm.dylib
12: /usr/lib/jvm/java-16-openjdk/lib/libjimage.dylib
13: /usr/lib/jvm/java-16-openjdk/lib/libjava.dylib
14: /usr/lib/jvm/java-16-openjdk/lib/libnio.dylib
15: /usr/lib/jvm/java-16-openjdk/lib/libnet.dylib
16: /usr/lib/jvm/java-16-openjdk/lib/libzip.dylib
17: /Applications/PojavLauncher.app/Frameworks/libpojavexec.dylib
18: /Applications/PojavLauncher.app/Frameworks/MetalANGLE.framework/MetalANGLE
19: /System/Library/AccessibilityBundles/GAXClient.bundle/GAXClient
20: /usr/lib/jvm/java-16-openjdk/lib/libextnet.dylib
21: /usr/lib/libobjc-trampolines.dylib
22: /Applications/PojavLauncher.app/Frameworks/liblwjgl.dylib
23: /usr/lib/jvm/java-16-openjdk/lib/libmanagement.dylib
24: /usr/lib/jvm/java-16-openjdk/lib/libmanagement_ext.dylib
25: /usr/lib/jvm/java-16-openjdk/lib/libverify.dylib
26: /Applications/PojavLauncher.app/Frameworks/liblwjgl_opengl.dylib
27: /Applications/PojavLauncher.app/Frameworks/libgl4es_114.dylib
28: /Applications/PojavLauncher.app/Frameworks/libgl4es_115.dylib
29: /usr/lib/libSystem.B.dylib
30: /usr/lib/libc++.1.dylib
31: /usr/lib/libc++abi.dylib
32: /usr/lib/libobjc.A.dylib
33: /usr/lib/system/libcache.dylib
34: /usr/lib/system/libcommonCrypto.dylib
35: /usr/lib/system/libcompiler_rt.dylib
36: /usr/lib/system/libcopyfile.dylib
37: /usr/lib/system/libcorecrypto.dylib
38: /usr/lib/system/libdispatch.dylib
39: /usr/lib/system/libdyld.dylib
40: /usr/lib/system/liblaunch.dylib
41: /usr/lib/system/libmacho.dylib
42: /usr/lib/system/libremovefile.dylib
43: /usr/lib/system/libsystem_asl.dylib
44: /usr/lib/system/libsystem_blocks.dylib
45: /usr/lib/system/libsystem_c.dylib
46: /usr/lib/system/libsystem_configuration.dylib
47: /usr/lib/system/libsystem_containermanager.dylib
48: /usr/lib/system/libsystem_coreservices.dylib
49: /usr/lib/system/libsystem_darwin.dylib
50: /usr/lib/system/libsystem_dnssd.dylib
51: /usr/lib/system/libsystem_info.dylib
52: /usr/lib/system/libsystem_kernel.dylib
53: /usr/lib/system/libsystem_m.dylib
54: /usr/lib/system/libsystem_malloc.dylib
55: /usr/lib/system/libsystem_networkextension.dylib
56: /usr/lib/system/libsystem_notify.dylib
57: /usr/lib/system/libsystem_platform.dylib
58: /usr/lib/system/libsystem_pthread.dylib
59: /usr/lib/system/libsystem_sandbox.dylib
60: /usr/lib/system/libsystem_symptoms.dylib
61: /usr/lib/system/libsystem_trace.dylib
62: /usr/lib/system/libunwind.dylib
63: /usr/lib/system/libxpc.dylib
64: /usr/lib/libicucore.A.dylib
65: /usr/lib/libz.1.dylib
66: /System/Library/Frameworks/CoreFoundation.framework/CoreFoundation
67: /usr/lib/libbsm.0.dylib
68: /usr/lib/libenergytrace.dylib
69: /System/Library/Frameworks/IOKit.framework/Versions/A/IOKit
70: /usr/lib/libxml2.2.dylib
71: /usr/lib/libbz2.1.0.dylib
72: /usr/lib/liblzma.5.dylib
73: /usr/lib/libsqlite3.dylib
74: /usr/lib/libMobileGestalt.dylib
75: /System/Library/Frameworks/CFNetwork.framework/CFNetwork
76: /System/Library/Frameworks/Foundation.framework/Foundation
77: /System/Library/Frameworks/Security.framework/Security
78: /System/Library/Frameworks/SystemConfiguration.framework/SystemConfiguration
79: /usr/lib/libCRFSuite.dylib
80: /usr/lib/libapple_nghttp2.dylib
81: /usr/lib/libarchive.2.dylib
82: /usr/lib/libcoretls.dylib
83: /usr/lib/libcoretls_cfhelpers.dylib
84: /usr/lib/liblangid.dylib
85: /usr/lib/libnetwork.dylib
86: /usr/lib/libpcap.A.dylib
87: /System/Library/Frameworks/IOSurface.framework/IOSurface
88: /System/Library/Frameworks/Accelerate.framework/Frameworks/vecLib.framework/libBLAS.dylib
89: /System/Library/Frameworks/Accelerate.framework/Frameworks/vecLib.framework/libLAPACK.dylib
90: /System/Library/Frameworks/Accelerate.framework/Frameworks/vImage.framework/vImage
91: /System/Library/Frameworks/Accelerate.framework/Frameworks/vecLib.framework/libSparseBLAS.dylib
92: /System/Library/Frameworks/Accelerate.framework/Frameworks/vecLib.framework/libvMisc.dylib
93: /System/Library/Frameworks/Accelerate.framework/Frameworks/vecLib.framework/libBNNS.dylib
94: /System/Library/Frameworks/Accelerate.framework/Frameworks/vecLib.framework/libLinearAlgebra.dylib
95: /System/Library/Frameworks/Accelerate.framework/Frameworks/vecLib.framework/libQuadrature.dylib
96: /System/Library/Frameworks/Accelerate.framework/Frameworks/vecLib.framework/libSparse.dylib
97: /System/Library/Frameworks/Accelerate.framework/Frameworks/vecLib.framework/libvDSP.dylib
98: /System/Library/Frameworks/Accelerate.framework/Frameworks/vecLib.framework/vecLib
99: /System/Library/Frameworks/Accelerate.framework/Accelerate
100: /usr/lib/libcompression.dylib
101: /System/Library/Frameworks/CoreGraphics.framework/CoreGraphics
102: /System/Library/PrivateFrameworks/IOAccelerator.framework/IOAccelerator
103: /System/Library/Frameworks/OpenGLES.framework/libCoreFSCache.dylib
104: /System/Library/Frameworks/Metal.framework/Metal
105: /System/Library/PrivateFrameworks/GraphicsServices.framework/GraphicsServices
106: /System/Library/Frameworks/MobileCoreServices.framework/MobileCoreServices
107: /System/Library/PrivateFrameworks/IOSurfaceAccelerator.framework/IOSurfaceAccelerator
108: /System/Library/PrivateFrameworks/AppleJPEG.framework/AppleJPEG
109: /System/Library/Frameworks/ImageIO.framework/ImageIO
110: /System/Library/PrivateFrameworks/BaseBoard.framework/BaseBoard
111: /System/Library/PrivateFrameworks/AssertionServices.framework/AssertionServices
112: /System/Library/PrivateFrameworks/CorePhoneNumbers.framework/CorePhoneNumbers
113: /System/Library/PrivateFrameworks/AppSupport.framework/AppSupport
114: /System/Library/PrivateFrameworks/CrashReporterSupport.framework/CrashReporterSupport
115: /System/Library/PrivateFrameworks/AggregateDictionary.framework/AggregateDictionary
116: /usr/lib/libTelephonyUtilDynamic.dylib
117: /System/Library/PrivateFrameworks/ProtocolBuffer.framework/ProtocolBuffer
118: /System/Library/PrivateFrameworks/MobileKeyBag.framework/MobileKeyBag
119: /System/Library/PrivateFrameworks/BackBoardServices.framework/BackBoardServices
120: /System/Library/PrivateFrameworks/FrontBoardServices.framework/FrontBoardServices
121: /System/Library/PrivateFrameworks/SpringBoardServices.framework/SpringBoardServices
122: /System/Library/PrivateFrameworks/PowerLog.framework/PowerLog
123: /System/Library/PrivateFrameworks/CommonUtilities.framework/CommonUtilities
124: /usr/lib/liblockdown.dylib
125: /System/Library/Frameworks/CoreData.framework/CoreData
126: /System/Library/PrivateFrameworks/TCC.framework/TCC
127: /usr/lib/libcupolicy.dylib
128: /System/Library/Frameworks/CoreTelephony.framework/CoreTelephony
129: /System/Library/Frameworks/Accounts.framework/Accounts
130: /System/Library/PrivateFrameworks/AppleSauce.framework/AppleSauce
131: /System/Library/PrivateFrameworks/DataMigration.framework/DataMigration
132: /System/Library/PrivateFrameworks/Netrb.framework/Netrb
133: /System/Library/PrivateFrameworks/PersistentConnection.framework/PersistentConnection
134: /usr/lib/libmis.dylib
135: /System/Library/PrivateFrameworks/ManagedConfiguration.framework/ManagedConfiguration
136: /usr/lib/libReverseProxyDevice.dylib
137: /usr/lib/libamsupport.dylib
138: /System/Library/Frameworks/OpenGLES.framework/libCoreVMClient.dylib
139: /System/Library/Frameworks/OpenGLES.framework/libCVMSPluginSupport.dylib
140: /usr/lib/libutil.dylib
141: /System/Library/Frameworks/OpenGLES.framework/libGLImage.dylib
142: /System/Library/PrivateFrameworks/APFS.framework/APFS
143: /System/Library/PrivateFrameworks/MediaKit.framework/MediaKit
144: /usr/lib/updaters/libSERestoreInfo.dylib
145: /System/Library/PrivateFrameworks/DiskImages.framework/DiskImages
146: /System/Library/Frameworks/OpenGLES.framework/libGFXShared.dylib
147: /usr/lib/libauthinstall.dylib
148: /System/Library/PrivateFrameworks/IOMobileFramebuffer.framework/IOMobileFramebuffer
149: /System/Library/Frameworks/OpenGLES.framework/OpenGLES
150: /System/Library/PrivateFrameworks/ColorSync.framework/ColorSync
151: /System/Library/Frameworks/CoreVideo.framework/CoreVideo
152: /usr/lib/libCTGreenTeaLogger.dylib
153: /System/Library/Frameworks/CoreAudio.framework/CoreAudio
154: /System/Library/PrivateFrameworks/CoreAnalytics.framework/CoreAnalytics
155: /System/Library/PrivateFrameworks/UserFS.framework/UserFS
156: /System/Library/Frameworks/CoreMedia.framework/CoreMedia
157: /usr/lib/libprotobuf-lite.dylib
158: /usr/lib/libprotobuf.dylib
159: /usr/lib/libAWDSupportFramework.dylib
160: /System/Library/PrivateFrameworks/WirelessDiagnostics.framework/WirelessDiagnostics
161: /System/Library/Frameworks/VideoToolbox.framework/VideoToolbox
162: /System/Library/PrivateFrameworks/FontServices.framework/libFontParser.dylib
163: /System/Library/PrivateFrameworks/FontServices.framework/FontServices
164: /System/Library/Frameworks/CoreText.framework/CoreText
165: /System/Library/PrivateFrameworks/IntlPreferences.framework/IntlPreferences
166: /System/Library/PrivateFrameworks/RTCReporting.framework/RTCReporting
167: /System/Library/PrivateFrameworks/CoreBrightness.framework/CoreBrightness
168: /usr/lib/libAudioStatistics.dylib
169: /System/Library/Frameworks/AudioToolbox.framework/AudioToolbox
170: /System/Library/Frameworks/QuartzCore.framework/QuartzCore
171: /System/Library/Frameworks/MediaAccessibility.framework/MediaAccessibility
172: /usr/lib/libiconv.2.dylib
173: /System/Library/PrivateFrameworks/NetworkStatistics.framework/NetworkStatistics
174: /System/Library/Frameworks/MetalPerformanceShaders.framework/Frameworks/MPSCore.framework/MPSCore
175: /System/Library/Frameworks/MetalPerformanceShaders.framework/Frameworks/MPSImage.framework/MPSImage
176: /System/Library/Frameworks/MetalPerformanceShaders.framework/Frameworks/MPSMatrix.framework/MPSMatrix
177: /System/Library/PrivateFrameworks/CoreAUC.framework/CoreAUC
178: /System/Library/Frameworks/MediaToolbox.framework/MediaToolbox
179: /System/Library/Frameworks/MetalPerformanceShaders.framework/Frameworks/MPSNeuralNetwork.framework/MPSNeuralNetwork
180: /System/Library/Frameworks/MetalPerformanceShaders.framework/MetalPerformanceShaders
181: /System/Library/PrivateFrameworks/FaceCore.framework/FaceCore
182: /System/Library/PrivateFrameworks/GraphVisualizer.framework/GraphVisualizer
183: /usr/lib/libFosl_dynamic.dylib
184: /System/Library/Frameworks/CoreImage.framework/CoreImage
185: /System/Library/Frameworks/CoreMotion.framework/CoreMotion
186: /System/Library/Frameworks/CoreBluetooth.framework/CoreBluetooth
187: /System/Library/PrivateFrameworks/PlugInKit.framework/PlugInKit
188: /System/Library/PrivateFrameworks/Celestial.framework/Celestial
189: /System/Library/PrivateFrameworks/Quagga.framework/Quagga
190: /System/Library/Frameworks/AVFoundation.framework/Frameworks/AVFAudio.framework/AVFAudio
191: /System/Library/Frameworks/AVFoundation.framework/AVFoundation
192: /System/Library/PrivateFrameworks/CacheDelete.framework/CacheDelete
193: /System/Library/PrivateFrameworks/StreamingZip.framework/StreamingZip
194: /System/Library/PrivateFrameworks/CoreEmoji.framework/CoreEmoji
195: /System/Library/PrivateFrameworks/CoreLocationProtobuf.framework/CoreLocationProtobuf
196: /System/Library/PrivateFrameworks/SymptomDiagnosticReporter.framework/SymptomDiagnosticReporter
197: /System/Library/PrivateFrameworks/GeoServices.framework/GeoServices
198: /System/Library/PrivateFrameworks/MobileAsset.framework/MobileAsset
199: /System/Library/PrivateFrameworks/Lexicon.framework/Lexicon
200: /usr/lib/libcmph.dylib
201: /System/Library/PrivateFrameworks/LanguageModeling.framework/LanguageModeling
202: /System/Library/Frameworks/CoreLocation.framework/CoreLocation
203: /System/Library/PrivateFrameworks/PhoneNumbers.framework/PhoneNumbers
204: /usr/lib/libChineseTokenizer.dylib
205: /usr/lib/libmecab_em.dylib
206: /usr/lib/libThaiTokenizer.dylib
207: /usr/lib/libgermantok.dylib
208: /System/Library/PrivateFrameworks/CoreNLP.framework/CoreNLP
209: /System/Library/Frameworks/JavaScriptCore.framework/JavaScriptCore
210: /usr/lib/libheimdal-asn1.dylib
211: /usr/lib/libate.dylib
212: /System/Library/PrivateFrameworks/TextureIO.framework/TextureIO
213: /System/Library/PrivateFrameworks/CoreUI.framework/CoreUI
214: /System/Library/PrivateFrameworks/MobileIcons.framework/MobileIcons
215: /System/Library/PrivateFrameworks/TextInput.framework/TextInput
216: /System/Library/Frameworks/FileProvider.framework/FileProvider
217: /System/Library/PrivateFrameworks/ProofReader.framework/ProofReader
218: /usr/lib/libAccessibility.dylib
219: /System/Library/PrivateFrameworks/WebCore.framework/Frameworks/libwebrtc.dylib
220: /System/Library/PrivateFrameworks/WebCore.framework/WebCore
221: /System/Library/PrivateFrameworks/WebKitLegacy.framework/WebKitLegacy
222: /System/Library/PrivateFrameworks/ProtectedCloudStorage.framework/ProtectedCloudStorage
223: /System/Library/Frameworks/UserNotifications.framework/UserNotifications
224: /System/Library/PrivateFrameworks/AppleIDAuthSupport.framework/AppleIDAuthSupport
225: /System/Library/PrivateFrameworks/AuthKit.framework/AuthKit
226: /System/Library/Frameworks/UIKit.framework/UIKit
227: /System/Library/PrivateFrameworks/DocumentManagerCore.framework/DocumentManagerCore
228: /System/Library/PrivateFrameworks/HangTracer.framework/HangTracer
229: /System/Library/PrivateFrameworks/PhysicsKit.framework/PhysicsKit
230: /System/Library/PrivateFrameworks/StudyLog.framework/StudyLog
231: /System/Library/PrivateFrameworks/UIFoundation.framework/UIFoundation
232: /System/Library/Frameworks/CloudKit.framework/CloudKit
233: /System/Library/PrivateFrameworks/IntentsFoundation.framework/IntentsFoundation
234: /System/Library/Frameworks/Intents.framework/Intents
235: /usr/lib/libresolv.9.dylib
236: /System/Library/PrivateFrameworks/CoreDuetDebugLogging.framework/CoreDuetDebugLogging
237: /usr/lib/libtidy.A.dylib
238: /System/Library/PrivateFrameworks/CoreDuet.framework/CoreDuet
239: /System/Library/PrivateFrameworks/CoreDuetContext.framework/CoreDuetContext
240: /System/Library/PrivateFrameworks/CoreDuetDaemonProtocol.framework/CoreDuetDaemonProtocol
241: /System/Library/PrivateFrameworks/IMFoundation.framework/IMFoundation
242: /System/Library/PrivateFrameworks/DiagnosticLogCollection.framework/DiagnosticLogCollection
243: /System/Library/PrivateFrameworks/Marco.framework/Marco
244: /System/Library/PrivateFrameworks/MessageProtection.framework/MessageProtection
245: /System/Library/PrivateFrameworks/StoreServices.framework/StoreServices
246: /System/Library/PrivateFrameworks/Engram.framework/Engram
247: /System/Library/PrivateFrameworks/IDSFoundation.framework/IDSFoundation
248: /System/Library/PrivateFrameworks/CaptiveNetwork.framework/CaptiveNetwork
249: /System/Library/PrivateFrameworks/EAP8021X.framework/EAP8021X
250: /System/Library/PrivateFrameworks/MobileWiFi.framework/MobileWiFi
251: /System/Library/PrivateFrameworks/OAuth.framework/OAuth
252: /System/Library/PrivateFrameworks/CommonAuth.framework/CommonAuth
253: /System/Library/PrivateFrameworks/Heimdal.framework/Heimdal
254: /System/Library/Frameworks/GSS.framework/GSS
255: /System/Library/PrivateFrameworks/ApplePushService.framework/ApplePushService
256: /System/Library/PrivateFrameworks/AccountsDaemon.framework/AccountsDaemon
257: /System/Library/PrivateFrameworks/AppleIDSSOAuthentication.framework/AppleIDSSOAuthentication
258: /System/Library/PrivateFrameworks/AppleAccount.framework/AppleAccount
259: /System/Library/PrivateFrameworks/CoreUtils.framework/CoreUtils
260: /System/Library/PrivateFrameworks/IDS.framework/IDS
261: /System/Library/PrivateFrameworks/MediaServices.framework/MediaServices
262: /System/Library/PrivateFrameworks/MediaRemote.framework/MediaRemote
263: /System/Library/PrivateFrameworks/UserManagement.framework/UserManagement
264: /System/Library/PrivateFrameworks/MobileBluetooth.framework/MobileBluetooth
265: /System/Library/PrivateFrameworks/Bom.framework/Bom
266: /System/Library/PrivateFrameworks/FTAWD.framework/FTAWD
267: /System/Library/PrivateFrameworks/FTServices.framework/FTServices
268: /System/Library/PrivateFrameworks/SiriTTS.framework/SiriTTS
269: /System/Library/PrivateFrameworks/SAObjects.framework/SAObjects
270: /System/Library/PrivateFrameworks/VoiceServices.framework/VoiceServices
271: /System/Library/PrivateFrameworks/AssistantServices.framework/AssistantServices
272: /System/Library/PrivateFrameworks/BluetoothManager.framework/BluetoothManager
273: /System/Library/PrivateFrameworks/PrototypeTools.framework/PrototypeTools
274: /System/Library/PrivateFrameworks/CoreSymbolication.framework/CoreSymbolication
275: /usr/lib/libtzupdate.dylib
276: /System/Library/PrivateFrameworks/Preferences.framework/Preferences
277: /System/Library/PrivateFrameworks/CoreTime.framework/CoreTime
278: /System/Library/PrivateFrameworks/DifferentialPrivacy.framework/DifferentialPrivacy
279: /System/Library/PrivateFrameworks/MobileSystemServices.framework/MobileSystemServices
280: /System/Library/PrivateFrameworks/SafariCore.framework/SafariCore
281: /System/Library/PrivateFrameworks/Futhark.framework/Futhark
282: /System/Library/PrivateFrameworks/NanoRegistry.framework/NanoRegistry
283: /System/Library/PrivateFrameworks/BaseBoardUI.framework/BaseBoardUI
284: /System/Library/PrivateFrameworks/ConstantClasses.framework/ConstantClasses
285: /System/Library/PrivateFrameworks/AXRuntime.framework/AXRuntime
286: /System/Library/PrivateFrameworks/ScreenReaderCore.framework/ScreenReaderCore
287: /System/Library/PrivateFrameworks/TextToSpeech.framework/TextToSpeech
288: /System/Library/Frameworks/CoreMIDI.framework/CoreMIDI
289: /usr/lib/libAXSafeCategoryBundle.dylib
290: /usr/lib/libAXSpeechManager.dylib
291: /System/Library/PrivateFrameworks/AccessibilityUtilities.framework/AccessibilityUtilities
292: /System/Library/PrivateFrameworks/MobileInstallation.framework/MobileInstallation
293: /System/Library/PrivateFrameworks/Accessibility.framework/Frameworks/AccessibilityUIUtilities.framework/AccessibilityUIUtilities
294: /System/Library/PrivateFrameworks/AXMediaUtilities.framework/AXMediaUtilities
295: /System/Library/PrivateFrameworks/CoreFollowUp.framework/CoreFollowUp
296: /System/Library/PrivateFrameworks/SharedWebCredentials.framework/SharedWebCredentials
297: /System/Library/PrivateFrameworks/SafariFoundation.framework/SafariFoundation
298: /System/Library/PrivateFrameworks/SetupAssistantSupport.framework/SetupAssistantSupport
299: /System/Library/PrivateFrameworks/SetupAssistant.framework/SetupAssistant
300: /System/Library/PrivateFrameworks/LinguisticData.framework/LinguisticData
301: /System/Library/Frameworks/MetalKit.framework/MetalKit
302: /System/Library/PrivateFrameworks/MobileDeviceLink.framework/MobileDeviceLink
303: /System/Library/PrivateFrameworks/MobileBackup.framework/MobileBackup
304: /System/Library/PrivateFrameworks/Accessibility.framework/Frameworks/AccessibilityUIShared.framework/AccessibilityUIShared
305: /System/Library/PrivateFrameworks/Accessibility.framework/Frameworks/AccessibilityUI.framework/AccessibilityUI
306: /System/Library/PrivateFrameworks/LoggingSupport.framework/LoggingSupport
307: /System/Library/PrivateFrameworks/kperf.framework/kperf
308: /System/Library/PrivateFrameworks/kperfdata.framework/kperfdata
309: /usr/lib/libdscsym.dylib
310: /System/Library/PrivateFrameworks/ktrace.framework/ktrace
311: /System/Library/PrivateFrameworks/Accessibility.framework/Frameworks/SpeakTypingServices.framework/SpeakTypingServices
312: /System/Library/PrivateFrameworks/Accessibility.framework/Frameworks/ZoomServices.framework/ZoomServices
313: /System/Library/PrivateFrameworks/BiometricKit.framework/BiometricKit
314: /System/Library/PrivateFrameworks/DeviceIdentity.framework/DeviceIdentity
315: /System/Library/PrivateFrameworks/Rapport.framework/Rapport
316: /System/Library/PrivateFrameworks/SignpostSupport.framework/SignpostSupport
317: /usr/lib/libtailspin.dylib
318: /System/Library/AccessibilityBundles/AccessibilitySettingsLoader.bundle/AccessibilitySettingsLoader
319: /System/Library/Extensions/AGXMetalA8.bundle/AGXMetalA8
320: /System/Library/Frameworks/Accelerate.framework/Frameworks/vImage.framework/Libraries/libCGInterfaces.dylib
321: /System/Library/PrivateFrameworks/FontServices.framework/libGSFontCache.dylib
322: /System/Library/PrivateFrameworks/FontServices.framework/libTrueTypeScaler.dylib
323: /System/Library/PrivateFrameworks/InternationalSupport.framework/InternationalSupport
324: /System/Library/PrivateFrameworks/SignpostCollection.framework/SignpostCollection
325: /System/Library/PrivateFrameworks/XCTTargetBootstrap.framework/XCTTargetBootstrap
326: /System/Library/PrivateFrameworks/libEDR.framework/libEDR
327: /usr/lib/libcharset.1.dylib
328: /System/Library/Frameworks/AuthenticationServices.framework/AuthenticationServices
329: /System/Library/Frameworks/CoreServices.framework/CoreServices
330: /System/Library/Frameworks/MetalPerformanceShaders.framework/Frameworks/MPSRayIntersector.framework/MPSRayIntersector
331: /System/Library/Frameworks/Network.framework/Network
332: /System/Library/PrivateFrameworks/ASEProcessing.framework/ASEProcessing
333: /System/Library/PrivateFrameworks/AXCoreUtilities.framework/AXCoreUtilities
334: /System/Library/PrivateFrameworks/AppleMediaServices.framework/AppleMediaServices
335: /System/Library/PrivateFrameworks/DocumentManager.framework/DocumentManager
336: /System/Library/PrivateFrameworks/IdleTimerServices.framework/IdleTimerServices
337: /System/Library/PrivateFrameworks/OTSVG.framework/OTSVG
338: /System/Library/PrivateFrameworks/ROCKit.framework/ROCKit
339: /System/Library/PrivateFrameworks/RemoteTextInput.framework/RemoteTextInput
340: /System/Library/PrivateFrameworks/SampleAnalysis.framework/SampleAnalysis
341: /System/Library/PrivateFrameworks/SiriInstrumentation.framework/SiriInstrumentation
342: /System/Library/PrivateFrameworks/StatsKit.framework/StatsKit
343: /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore
344: /System/Library/PrivateFrameworks/UIKitServices.framework/UIKitServices
345: /System/Library/PrivateFrameworks/URLFormatting.framework/URLFormatting

{"ProcessBundleID":"net.kdt.pojavlauncher","ProcessName":"PojavLauncher","Culprit":"Unknown"}

**Please verify that you have done the following:**

- [x] Provided details on what you’re seeing vs what you wanted
- [x] Provided a log file, if relevant
- [x] Provided steps to reproduce this issue
- [x] Tested on the latest version of PojavLauncher

**Comment by khanhduytran0** [comment]
```
27: /Applications/PojavLauncher.app/Frameworks/libgl4es_114.dylib
28: /Applications/PojavLauncher.app/Frameworks/libgl4es_115.dylib
```
You've made it load both gl4es...

**Comment by NotAHero04** [comment]
What should i do to unload the gl4es_114 one?

**Comment by NotAHero04** [comment]
Thanks a lot, I just rename gl4es_115 to gl4es_114 and it worked! However, can you config the launcher that (if someone would ever need 1.1.4) when you load 1.1.5 it unloads 1.1.4?
