### ISSUE TITLE
Stuck on a white screen after assets downloading

### ISSUE THREAD

**Issue by Officeyutong** [PojavLauncherTeam/PojavLauncher_iOS#21]
iPad Pro 2020,11inch, iPadOS 13.5.1, using Odyssey Jailbreak
https://github.com/PojavLauncherTeam/PojavLauncher_iOS/actions/runs/532491057

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher_iOS/files/5916491/latestlog.txt)
The launcher stuck on the following screen after I clicked `Play` and finished assets downloading
![QQ图片20210203141937](https://user-images.githubusercontent.com/9004058/106706652-f7facb00-662a-11eb-87c1-f0007d0a5d21.png)

**Comment by khanhduytran0** [comment]
Try https://github.com/PojavLauncherTeam/PojavLauncher_iOS/actions/runs/533323365

**Comment by Officeyutong** [comment]
> Try https://github.com/PojavLauncherTeam/PojavLauncher_iOS/actions/runs/533323365

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher_iOS/files/5917261/latestlog.txt)

Still the same situation...

**Comment by khanhduytran0** [comment]
Maybe try a clean install?

**Comment by Officeyutong** [comment]
> Maybe try a clean install?

I removed `/var/mobile/Documents/minecraft` and pojavelauncher and reinstalled, But still got the same situation
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher_iOS/files/5917870/latestlog.txt)

**Comment by khanhduytran0** [comment]
How long you've waited for?

**Comment by Officeyutong** [comment]
> How long you've waited for?

At least five minutes

**Comment by Officeyutong** [comment]
I also tried https://github.com/PojavLauncherTeam/PojavLauncher_iOS/actions/runs/533869705 and waited for 5 minutes, still the same problem.
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher_iOS/files/5918569/latestlog.txt)

**Comment by jawshoeadan** [comment]
I'm having the same issue. Everything downloads and the controls show up but over the blank screen. Is it possible that it's an iPad only issue? I haven't seen it work on an iPad yet.
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher_iOS/files/5945476/latestlog.txt)

**Comment by timof121** [comment]
same

**Comment by Officeyutong** [comment]
I tried https://github.com/PojavLauncherTeam/PojavLauncher_iOS/releases/tag/v1.0 and the problem is solved
