### ISSUE TITLE
[Bug Report]1.17 crashes

### ISSUE THREAD

**Issue by creyes200** [PojavLauncherTeam/PojavLauncher_iOS#210]
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher_iOS/files/6619521/latestlog.txt)

**First, let us know what you’re using.**
Iphone 7 ios 14.4.2 checkra1n 
**Next, describe the issue.**
Make sure to be as descriptive as possible. 
1.17 update crashes
**What’s supposed to happen?**
What were you expecting?
For it to run
**How does it happen?**
I opened pojav launcher typed 1.17 and it started downloading stuff and then crashed

**Any files you want to send?**
We could use a copy of latestlog.txt or a Cr4shed screenshot.

**Please verify that you have done the following:**

- [ ] Provided details on what you’re seeing vs what you wanted
- [x] Provided a log file, if relevant
- [x] Provided steps to reproduce this issue
- [x] Tested on the latest version of PojavLauncher

**Comment by CriticalRange** [comment]
It's not supported atm, be patient

**Comment by creyes200** [comment]
Srry i just thought that since the snapshots were the update would be too
