### ISSUE TITLE
[Bug Report] A cursor appeared on the ‘Keyboard’ button when tapping

### ISSUE THREAD

**Issue by NotAHero04** [PojavLauncherTeam/PojavLauncher_iOS#211]
**First, let us know what you're using.**

iPhone 6, iOS 12.5.2
Latest PojavLauncher (dev) version.
**Next, describe the issue.**

After tapping ‘Keyboard’ button, a cursor will appear on that button. The text typed is also displayed on that button with black color.
**What's supposed to happen?**

There would be no cursors on ‘Keyboard’ button after tapping.
**How does it happen?**

**Any files you want to send?**

This is the screenshot containing this bug: 
(sorry, the ‘Attach an image’ button doesn’t work for me. I will send a link to the image later.)
**Please verify that you have done the following:**

- [x] Provided details on what you're seeing vs what you wanted
- [ ] Provided a log file, if relevant
- [x] Provided steps to reproduce this issue
- [x] Tested on the latest version of PojavLauncher

**Comment by NotAHero04** [comment]
This is the image:
https://share.icloud.com/photos/0xgCIrDxsSohMlEOOuO7PqdTA

**Comment by Doregon** [comment]
Does it render you unable to type into the text box?

**Comment by NotAHero04** [comment]
Text is displayed on both the ‘Keyboard’ and the text box.

**Comment by khanhduytran0** [comment]
As of the commit 82dc17cd9ce03db2be38cc600183c2478d9f814e, the input text box is now made hidden. The reason for visible text box in old version was due to improperly handled keyboard visibility toggle.
