### ISSUE TITLE
[Bug Report] keyboard not opening

### ISSUE THREAD

**Issue by TopBlade0** [PojavLauncherTeam/PojavLauncher_iOS#212]
**First, let us know what you're using.**

**Next, describe the issue.**

**What's supposed to happen?**

**How does it happen?**

**Any files you want to send?**

**Please verify that you have done the following:**

- [x] Provided details on what you're seeing vs what you wanted
- [x] Provided a log file, if relevant
- [x] Provided steps to reproduce this issue
- [x] Tested on the latest version of PojavLauncher

**Comment by khanhduytran0** [comment]
Finally, don't play around with checkboxes and fill the template.
