### ISSUE TITLE
[F-Req] .ipa file

### ISSUE THREAD

**Issue by beetrootpotatocarrot** [PojavLauncherTeam/PojavLauncher_iOS#215]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Make sure you’ve dine the following:**
- [ ] Provided a clear description into what the feature request is
- [ ] (If applicable) provided an issue that this request would fix
- [ ] (If applicable) presented potential possibilities into adding this request
- [ ] (If applicable) Provided evidence such as a drawing, log file, file, etc. of what you wish to see reflected

**Comment by Carter1190** [comment]
copy of #157  and many others.
