### ISSUE TITLE
[F-Req] bring back the old icon

### ISSUE THREAD

**Issue by creyes200** [PojavLauncherTeam/PojavLauncher_iOS#216]
![Captura de Pantalla 2021-06-14 a la(s) 15 15 36](https://user-images.githubusercontent.com/84339275/121947298-e4bbe280-cd23-11eb-999e-eeb0d5e3260e.png)
![Captura de Pantalla 2021-06-14 a la(s) 15 18 03](https://user-images.githubusercontent.com/84339275/121947336-f00f0e00-cd23-11eb-861f-17d03984e3df.png)

the old Black icon was way better looking and the Block in it was bigger (and it would look much better with dark mode)

the White one looks bad and the Block is zoomed out and that gives it more of a fake sort of feeling

maybe you could be able to choose what icon you want when installing the package
nothing very important but im pretty sure most people would agree with me
dont realy care just prefer

**Comment by creyes200** [comment]
sorry about the Picture sizes (i dont know how to Edit screenshots)

**Comment by Doregon** [comment]
This has been a change since the later development builds of 1.1 and no one has brought this to our attention. We also use the same icon on Android and have not received any complaints, so the icon will remain the same.

**Comment by creyes200** [comment]
Fair enough👌

**Comment by Carter1190** [comment]
if you want the i on bad enough you can manually change the icon using filza

**Comment by Carter1190** [comment]
icon*

**Comment by creyes200** [comment]
Realy

**Comment by creyes200** [comment]
Tell me where pls

**Comment by Carter1190** [comment]
yes as long as you have the icon you can go into the apps files and replace it

**Comment by creyes200** [comment]
Where wich files?

**Comment by creyes200** [comment]
Filza?

**Comment by creyes200** [comment]
Gimme the directroy

**Comment by Carter1190** [comment]
filza is a file manager

**Comment by creyes200** [comment]
Example: var/mobile/documents ...

**Comment by Carter1190** [comment]
/Applications/PojavLauncher.app

**Comment by creyes200** [comment]
> filza is a file manager

I know

**Comment by creyes200** [comment]
Thanks

**Comment by creyes200** [comment]
There are 2 icons one that says ipados and another do i replace both?

**Comment by Carter1190** [comment]
i would replace both

**Comment by creyes200** [comment]
Ok

**Comment by creyes200** [comment]
Didnt work☹️

**Comment by Doregon** [comment]
> yes as long as you have the icon you can go into the apps files and replace it

This is not possible, as the icons are drawn from Assets.car itself. These two files are made when compiling Assets.xcassets with the `--app-icon` flag which was required, and they seem to have no purpose.

**Comment by creyes200** [comment]
But is it possible to do it another way?

**Comment by Doregon** [comment]
If you download an older build of PojavLauncher that has the older icon, you can extract `Assets.car` from the .deb and place it in `/Applications/PojavLauncher.app`, but this will break the LaunchScreen and the front page images and things will look… odd.

The other option is to rebuild `Assets.xcassets` with the older icons, but this requires Xcode and a Mac.

**Comment by creyes200** [comment]
I rebuilt the asset.xcasset but how do i convert it to asset.car

**Comment by Doregon** [comment]
`make extras` will do the trick, then run `make package` and install the .deb that is produced.

**Comment by creyes200** [comment]
Im confused ¿where?

**Comment by creyes200** [comment]
In terminal?

**Comment by Doregon** [comment]
correct

**Comment by creyes200** [comment]
And where will the package be located

**Comment by Doregon** [comment]
the packages folder

**Comment by creyes200** [comment]
When i run the command it says no rule to make extras or package

**Comment by Doregon** [comment]
you have to change the directory to where you cloned pojavlauncher

**Comment by creyes200** [comment]
If its in my desktop what would be the command?

**Comment by Doregon** [comment]
```
cd Desktop/PojavLauncher_iOS
make
```

**Comment by creyes200** [comment]
Thanks ill try it

**Comment by creyes200** [comment]
it gives me this= 

starting build task - extraneous files
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>com.apple.actool.compilation-results</key>
	<dict>
		<key>output-files</key>
		<array>
			<string>/dev/null</string>
		</array>
	</dict>
	<key>com.apple.actool.errors</key>
	<array>
		<dict>
			<key>description</key>
			<string>None of the input catalogs contained a matching stickers icon set or app icon set named  "AppIcon".</string>
		</dict>
	</array>
</dict>
</plist>
make: *** [extras] Error 1

**Comment by creyes200** [comment]
i tried doing it again by renaming the images just as the ones that were original in the build but it didn't work

**Comment by creyes200** [comment]
please help

**Comment by Doregon** [comment]
@creyes200 I stated this above

> We will not provide support or tutorials for either of these options.

**Comment by creyes200** [comment]
fair enough

**Comment by creyes200** [comment]
after a los off messing around with files and images i got it to work here is the assets.car incase anyone wanted the old icon as much as i did its in .zip because i coudnt upload it in .car 
[Assets.car.zip](https://github.com/PojavLauncherTeam/PojavLauncher_iOS/files/6665590/Assets.car.zip)

**Comment by creyes200** [comment]
> If you download an older build of PojavLauncher that has the older icon, you can extract `Assets.car` from the .deb and place it in `/Applications/PojavLauncher.app`, but this will break the LaunchScreen and the front page images and things will look… odd.
> 
> The other option is to rebuild `Assets.xcassets` with the older icons, but this requires Xcode and a Mac.
> 
> We will not provide support or tutorials for either of these options.

thanks for pointing me in the right direction
