### ISSUE TITLE
[F-Req] The local mode note should not be displayed every time you tap the ‘Local’ button

### ISSUE THREAD

**Issue by NotAHero04** [PojavLauncherTeam/PojavLauncher_iOS#217]
**Is your feature request related to a problem? Please describe.**

The popup about local mode shows every time you tap the ‘Local’ button.
**Describe the solution you'd like**

The popup should be shown only once.
**Describe alternatives you've considered**

You should link the Discord announcement to the launcher in ‘FAQ’.
**Additional context**

**Make sure you’ve dine the following:**
- [x] Provided a clear description into what the feature request is
- [ ] (If applicable) provided an issue that this request would fix
- [x] (If applicable) presented potential possibilities into adding this request
- [ ] (If applicable) Provided evidence such as a drawing, log file, file, etc. of what you wish to see reflected

**Comment by Doregon** [comment]
This is known and I am currently working on it.
