### ISSUE TITLE
[Bug Report] The Discord link breaks the ‘About’ section

### ISSUE THREAD

**Issue by NotAHero04** [PojavLauncherTeam/PojavLauncher_iOS#218]
**First, let us know what you're using.**

iPhone 6, iOS 12.5.2
**Next, describe the issue.**

The Discords comes with some blank spaces that overwrite to the second column (which is the version changelog).
**What's supposed to happen?**

It would render normally
**How does it happen?**

**Any files you want to send?**

Link in the next comment.
**Please verify that you have done the following:**

- [x] Provided details on what you're seeing vs what you wanted
- [ ] Provided a log file, if relevant
- [x] Provided steps to reproduce this issue
- [x] Tested on the latest version of PojavLauncher

**Comment by NotAHero04** [comment]
Here is the image:
https://share.icloud.com/photos/05cVBdKILZfmGn6QBjZaYP3kQ

**Comment by Doregon** [comment]
This is known and I am currently working on it.
