### ISSUE TITLE
[Bug Report] The local login is broken

### ISSUE THREAD

**Issue by NotAHero04** [PojavLauncherTeam/PojavLauncher_iOS#219]
**First, let us know what you're using.**

iPhone 6, iOS 12.5.2
Latest PojavLauncher (dev) version.
**Next, describe the issue.**

When you login with new local accounts, it’s displayed on the account selection screen as a different name. I have tested these:
just a test -> process
a more test -> process (it just overrides the old one, ‘just a test’)
pojavlauncher -> a bunch of similar but strange letters.
**What's supposed to happen?**

It would displayed normally.
**How does it happen?**

Create a local account, then go back and finally tap ‘Account’ to see if the name is correct.
**Any files you want to send?**

Link in the next comment.
**Please verify that you have done the following:**

- [x] Provided details on what you're seeing vs what you wanted
- [ ] Provided a log file, if relevant
- [x] Provided steps to reproduce this issue
- [x] Tested on the latest version of PojavLauncher

**Comment by NotAHero04** [comment]
https://share.icloud.com/photos/0do9Co54i-6XM0FZ3RPdELmAQ
This video also introduce the problem that i have a request, #217.

**Comment by Doregon** [comment]
@NotAHero04 We can’t open this

**Comment by Doregon** [comment]
Either way, I cannot reproduce this with any of the builds I have been testing and using. I did have one incident with an offline account being renamed “RBSTarget”, but it only happened once so I believe that they are isolated incidents.

**Comment by NotAHero04** [comment]
> @NotAHero04 We can’t open this

Sorry, I am managing with the icloud link. I wil update the new link soon.

**Comment by NotAHero04** [comment]
I somehow have it worked. But I have a temporary fix for this: to modify the file in .pojavlauncher/accounts folder.
