### ISSUE TITLE
[Question] How to change OpenGL version using custom environment variables?

### ISSUE THREAD

**Issue by NotAHero04** [PojavLauncherTeam/PojavLauncher_iOS#220]
**Ask your question here!**

In Android version (Zink build I think) there is a custom environment variable used to force OpenGL version, such as:
`MESA_GL_VERSION_OVERRIDE=3.2`
Is there any similar thing to gl4es on iOS?

**Comment by Doregon** [comment]
Although technically yes, it is possible to do, the game would still not run as it still requires OpenGL 3 specific objects and shaders.
