### ISSUE TITLE
[Question]

### ISSUE THREAD

**Issue by creyes200** [PojavLauncherTeam/PojavLauncher_iOS#222]
Since pojav launcher is on the playstore do u think it'll aver be on the appStore
(Honestly if it does get on the appstore i wouldn't mind if it cost's money)

**Comment by CriticalRange** [comment]
It wouldn't get into appstore due to Apple's terms and it cannot be priced since it would be like selling it again so developers would definitely get sued for that

**Comment by creyes200** [comment]
Yeah that makes sense
