### ISSUE TITLE
[Bug Report] IMPORTANT: Local account is still able to download new Minecraft versions

### ISSUE THREAD

**Issue by NotAHero04** [PojavLauncherTeam/PojavLauncher_iOS#223]
**First, let us know what you're using.**

iPhone 6, iOS 12.5.2
Latest PojavLauncher (dev) version at the time, which is alpha25.
**Next, describe the issue.**

A local account that I made is still able to download new versions from Mojang.
**What's supposed to happen?**

Local accounts would not be able to download any new versions.
**How does it happen?**

1. Create a local account
2. Choose a version that you have not downloaded.
**Any files you want to send?**

A screen recording video is coming...
**Please verify that you have done the following:**

- [x] Provided details on what you're seeing vs what you wanted
- [ ] Provided a log file, if relevant
- [x] Provided steps to reproduce this issue
- [x] Tested on the latest version of PojavLauncher

**Comment by NotAHero04** [comment]
I don’t know but I can’t reproduce this issue again. I’m about to reinstall PojavLauncher in an attempt to reproduce it. Sorry for bothering you.

**Comment by NotAHero04** [comment]
I can reproduce this now. If you have no local accounts and have a offline accout that created before the local mode introduction, the local account will be able to download versions. Here is the video:
https://share.icloud.com/photos/0fBYC2LCJHVS56Sk1mxlq9uBw

**Comment by Doregon** [comment]
This is known. The local mode change has not yet been implemented.

**Comment by NotAHero04** [comment]
But if i create two local accounts, both two CANNOT choose versions. Can you explain this?

**Comment by Doregon** [comment]
I can’t reproduce this with my test local accounts. We have not changed anything about offline mode yet, so whatever is happening for you is an isolated incident unrelated to the local mode changes coming in the future.

**Comment by NotAHero04** [comment]
Yes, that’s what I called it a random issue.
