### ISSUE TITLE
[Question]

### ISSUE THREAD

**Issue by FunnyOrDummy** [PojavLauncherTeam/PojavLauncher_iOS#225]
I have tried to add forge into pojavlauncher but the terminal sent me this error:could not find or load main class.var.mobile.......! If anybody know how to fix this, pls reply me😭

**Comment by Doregon** [comment]
we need more than this to help you.

**Comment by FunnyOrDummy** [comment]
When i put this command:/usr/lib/jvm/java-16-openjdk/bin/java -cp /var/mobile/Documents/forge-installer-headless-1.0.1.jar: /var/mobile/Documents/forge-1.16.5-36.1.32-installer.jar me.xfl03.HeadlessInstaller -progress -installClient /var/mobile/Documents/minecraft  into NewTerm, it appear an error like: could not find or load main class .var.mobile.Documents.forge-1.16.5-36.1.32-installer.jar
Caused by: Java.lang.classnotfoundexception /var/mobile/Documents/forge...... 
(Sorry i don’t know why but I can’t send picture:(((()

**Comment by khanhduytran0** [comment]
```
...ents/forge-installer-headless-1.0.1.jar: /var/mobile/Documents/..
                                           ^
```
This space is invalid :eyes:

**Comment by FunnyOrDummy** [comment]
Oh see it! It’s a little bit mistake😅! Sorry about my fault!!!!
