### ISSUE TITLE
[Question] Can't install optofine, no information on the "new wiki"

### ISSUE THREAD

**Issue by mistororange** [PojavLauncherTeam/PojavLauncher_iOS#228]
**Ask your question here!**

I keep trying to follow tutorials on how to install optifine , but there is no optiinst.jar file there is no wiki period. it says its "moved" to the new site, and theres no page for the wiki.. how am I suppose to install???

**Comment by Doregon** [comment]
Yes there is, https://pojavlauncherteam.github.io/ios/wiki/going-further/non-vanilla/optifine
