### ISSUE TITLE
Mouse and keyboard support?

### ISSUE THREAD

**Issue by sourcelocation** [PojavLauncherTeam/PojavLauncher_iOS#23]
That would be really awesome.

**Comment by khanhduytran0** [comment]
Possibility, but I don't have external mouse and keyboard to test...

**Comment by Ecstxsy** [comment]
I think adding controller support for Xbox controllers would be a nice bonus too.

**Comment by Gymxo** [comment]
Mouse works fine for me. Still needs some keyboard support and then login support for me to be happy with this :). You still doing a great job though.

**Comment by Matthew92007** [comment]
Mouse and keyboard support would make this a dream. The touchscreen controls are really intuitive, but you just can't beat a mouse/keyboard for java edition.

**Comment by SmartBoy84** [comment]
+1 for controller support. It shouldn't that hard afaik it would just require for MFI controller input to be passed through and then mods like Controllable or LambdaControls can handle the mapping.

**Comment by Doregon** [comment]
> +1 for controller support. It shouldn't that hard afaik it would just require MFI controller input to be passed through and then mods like Controllable or LambdaControls can handle the mapping.

True, but for those who wish to play without modified versions wouldn't be able to use controllers.

**Comment by Doregon** [comment]
This issue is being tracked in #184. This is still an issue.
