### ISSUE TITLE
Cannot change hotbar item when  GUI Scale is not auto.

### ISSUE THREAD

**Issue by asdfugil** [PojavLauncherTeam/PojavLauncher_iOS#232]
**First, let us know what you're using.**
iPad Pro 9.7 WiFi iOS 14.3 
PojavLauncher 1.2

**Next, describe the issue.**
(title)

**What's supposed to happen?**
It works regardless of GUI scale.

**How does it happen?**
1. Launch minecraft
2. Change GUI Scale to 5
3. Close minecraft
4. Launch minecraft again 
5. Open a world
6. Try to change hotbar item

**Any files you want to send?**

**Please verify that you have done the following:**

- [x] Provided details on what you're seeing vs what you wanted
- [ ] Provided a log file, if relevant
- [x] Provided steps to reproduce this issue
- [x] Tested on the latest version of PojavLauncher

**Comment by asdfugil** [comment]
this is quite similar to #198, but this has an exact reason.

**Comment by NotAHero04** [comment]
This problem has a hard workaround: try to add number buttons.

**Comment by asdfugil** [comment]
Fixed

**Comment by SOSTHEGREAT** [comment]
I’m on iOS 14.1 and this didn’t work at all
