### ISSUE TITLE
[Bug Report]

### ISSUE THREAD

**Issue by admin-elvistrujanovic** [PojavLauncherTeam/PojavLauncher_iOS#233]
**First, let us know what you're using.**
iOS 14.5.1 (iPhone 7 GSM) -->

**Next, describe the issue.**
PojavLauncher Dev version is not opening after latest update

**What's supposed to happen?**
Opened App

**How does it happen?**
Crashed in opening app

**Any files you want to send?**
None
**Please verify that you have done the following:**

- [x] Provided details on what you're seeing vs what you wanted
- [ ] Provided a log file, if relevant
- [x] Provided steps to reproduce this issue
- [x] Tested on the latest version of PojavLauncher

**Comment by NotAHero04** [comment]
Yes, it’s an issue with the makefile as Doregon said on Discord.

**Comment by Doregon** [comment]
@admin-elvistrujanovic Downgrade to a previous version

**Comment by admin-elvistrujanovic** [comment]
Repaired with the latest version now after update in dev channel.
