### ISSUE TITLE
Minecraft 1.17 does not work

### ISSUE THREAD

**Issue by Rice-Krispy** [PojavLauncherTeam/PojavLauncher_iOS#240]
**First, let us know what you're using.**

**Next, describe the issue.**

**What's supposed to happen?**

**How does it happen?**

**Any files you want to send?**

**Please verify that you have done the following:**

- [ ] Provided details on what you're seeing vs what you wanted
- [ ] Provided a log file, if relevant
- [ ] Provided steps to reproduce this issue
- [x] Tested on the latest version of PojavLauncher

**Comment by Rice-Krispy** [comment]
When ever installing Minecraft 1.17 jar it crashes when launched

**Comment by Doregon** [comment]
You need to follow the instructions on our website to make it work.
