### ISSUE TITLE
[Question]openjdk 8

### ISSUE THREAD

**Issue by creyes200** [PojavLauncherTeam/PojavLauncher_iOS#242]
I noticed openjdk 8 on the cydia repo. Does this mean pojavlauncher will finally work with older modded versions?

**Comment by LegacyGamerHD** [comment]
It already does that as it uses jdk8 by default

**Comment by LegacyGamerHD** [comment]
Oops didn't read that this is iOS version

**Comment by Doregon** [comment]
@creyes200 Yes, but you need to use the latest dev builds to use it correctly. Instructions can be found in the Launcher FAQ (again, latest build).

**Comment by creyes200** [comment]
I cant find custom_env.txt and im on the latest dev version

**Comment by Doregon** [comment]
You have to create it.
