### ISSUE TITLE
[Bug Report]

### ISSUE THREAD

**Issue by admin-elvistrujanovic** [PojavLauncherTeam/PojavLauncher_iOS#243]
**First, let us know what you're using.**

iOS 14.5.1 iPhone 7 GSM Jailbroken (Odysseyra1n)
**Next, describe the issue.**

Minecraft 1.12.2 constantly crashes while creating and opening any world

**What's supposed to happen?**

Opened world

**How does it happen?**

Constantly closes the game

**Any files you want to send?**

[latestlog.txt - OneDrive](https://1drv.ms/t/s!AlXllPspfdqogivvLUhzr0QxbLtD)
**Please verify that you have done the following:**

- [x] Provided details on what you're seeing vs what you wanted
- [x] Provided a log file, if relevant
- [x] Provided steps to reproduce this issue
- [x] Tested on the latest version of PojavLauncher

**Comment by khanhduytran0** [comment]
Does Cr4shed logs something? If so please send it here.

**Comment by admin-elvistrujanovic** [comment]
> Does Cr4shed logs something about crashes? If so please send it here.

Date: 8/21/21, 10:06 AM
Process: PojavLauncher
Bundle id: net.kdt.pojavlauncher
Device: iPhone 7, iOS 14.5.1

Reason: The process was terminated for exceeding jetsam memory limits
Uptime: 389s
Virtual memory size: 0x620cf78000 bytes
Resident memory size: 0x26470000 bytes
CPU usage: 0%
Thread count: 32

Binary Images:
0x1dc326000 - 0x1dc336fff libsystem_pthread.dylib arm64  <32A07BA4-7865-3AD4-9BCF-AD54DA07CF54> /usr/lib/system/libsystem_pthread.dylib
0x193c06000 - 0x193c84fff libdispatch.dylib arm64  <16C9F613-7AE3-32CE-BA3A-B0DCF0464F0E> /usr/lib/system/libdispatch.dylib
0x1dc31a000 - 0x1dc324fff libsystem_platform.dylib arm64  <D5E47884-B93D-388E-B0BC-3DABCEA2F1EF> /usr/lib/system/libsystem_platform.dylib
0x1c3c08000 - 0x1c3d18fff libEmbeddedSystemAUs.dylib arm64  <53F9A2D4-CB84-3693-935B-FF6FDEB8340B> /System/Library/Frameworks/AudioToolbox.framework/libEmbeddedSystemAUs.dylib
0x12dbf0000 - 0x12dd4bfff libopenal.dylib arm64  <186F5ED2-0B8E-322C-97B3-FF829C1A334E> /Applications/PojavLauncher.app/Frameworks/libopenal.dylib
0x193f14000 - 0x1942bffff CoreFoundation arm64  <373EC2DD-3A29-3E74-B85D-BE4EE925167A> /System/Library/Frameworks/CoreFoundation.framework/CoreFoundation
0x195d96000 - 0x1970bdfff UIKitCore arm64  <7E4F912A-868A-3669-96D1-6D89F785509F> /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore
0x1aa654000 - 0x1aa65cfff GraphicsServices arm64  <069A6354-4A62-3DA8-A5CD-4D4168D3D417> /System/Library/PrivateFrameworks/GraphicsServices.framework/GraphicsServices
0x10852c000 - 0x108b37fff libjvm.dylib arm64  <859ADEC4-782F-312E-BC9E-D2E889564D3B> /usr/lib/jvm/java-8-openjdk/lib/server/libjvm.dylib
0x1bfc9d000 - 0x1bfccdfff libsystem_kernel.dylib arm64  <269E9333-8D3B-3CC5-8A93-AEB94FE3E32E> /usr/lib/system/libsystem_kernel.dylib
0x104628000 - 0x10465bfff libpojavexec.dylib arm64  <84DA3CC8-1D0E-38F1-9922-449F33DDFACC> /Applications/PojavLauncher.app/Frameworks/libpojavexec.dylib
0x1056ac000 - 0x1056d7fff libjava.dylib arm64  <14318FA7-FC20-3932-B9FD-AA4AAA713254> /usr/lib/jvm/java-8-openjdk/lib/libjava.dylib
0x104604000 - 0x10460bfff PojavLauncher arm64  <E52387B6-1E89-3963-B61A-618D18914A29> /Applications/PojavLauncher.app/PojavLauncher
0x10566c000 - 0x10567ffff libjli.dylib arm64  <E027EFD1-06DB-39D6-A864-2053452E3C53> /usr/lib/jvm/java-8-openjdk/lib/jli/libjli.dylib
0x1951ef000 - 0x195484fff Foundation arm64  <43EFCCFB-D4FE-3F57-8653-DDD0CB5F2BFF> /System/Library/Frameworks/Foundation.framework/Foundation
0x193c85000 - 0x193cbbfff libdyld.dylib arm64  <19E502BE-AFC1-3E00-AD3F-D28C0AE1287E> /usr/lib/system/libdyld.dylib

{"ProcessBundleID":"net.kdt.pojavlauncher","NSExceptionReason":"The process was terminated for exceeding jetsam memory limits","ProcessName":"PojavLauncher"}

**Comment by khanhduytran0** [comment]
It literally said the reason
> Reason: The process was terminated for exceeding jetsam memory limits

**Comment by admin-elvistrujanovic** [comment]
> It literally said the reason
> 
> > Reason: The process was terminated for exceeding jetsam memory limits

Yes, but why is that reason for me for almost all system processes the same (also for safari, app store, SpringBoard, Sileo, Settings and etc…)

**Comment by admin-elvistrujanovic** [comment]
Could it be that iOS 14.5.1 has some bugs (maybe this bug also) that Apple has fixed in newer versions

**Comment by admin-elvistrujanovic** [comment]
> Could it be that iOS 14.5.1 has some bugs (maybe this bug also) that Apple has fixed in newer versions

If so, I will definitely not update because I need a jailbreak without a computer and for that I need to be on the oldest possible iOS version

**Comment by khanhduytran0** [comment]
Closing as we have nothing to do with a system bug.
