### ISSUE TITLE
[Bug] Game crashes when opening inventory in 1.12

### ISSUE THREAD

**Issue by bstar16** [PojavLauncherTeam/PojavLauncher_iOS#245]
### Describe the bug

game crashes when opening inventory in 1.12

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher_iOS/files/6873727/latestlog.txt)

### Steps To Reproduce

```markdown
open inventory in 1.12
```

### Expected Behavior

inventory opens like normal and doesn’t crash game

### Platform

```markdown
- Device model: 6s Plus
- iOS version: 13.5
- PojavLauncher version: Latest dev build
```

**Comment by khanhduytran0** [comment]
You have an outdated JRE8 build.

**Comment by khanhduytran0** [comment]
No response from the author (@bstar16), closing.
