### ISSUE TITLE
[Bug] Versions below 1.13 show the screen in a very small corner of the screen

### ISSUE THREAD

**Issue by tschanadam** [PojavLauncherTeam/PojavLauncher_iOS#246]
### Describe the bug

When you launch a version below 1.13, the game window shows in a very small corner of the screen. The same issue also occurred with Alpha 1.1.2, which I never expected to work. The Alpha version will actually load, but the 1.12.2 will crash. I am using Forge and I installed Openjdk 8 from the repo and specified that directory as my java home. 

### The log file and images/videos

![F93410BB-4E18-4FB7-9EAA-83AD5B673127](https://user-images.githubusercontent.com/63157695/127983134-a69056b8-a846-4708-8c14-040d7cadbc48.png)
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher_iOS/files/6922475/latestlog.txt)
iPadOS 14.7 with Odysseyra1n, latest dev build from Doregon’s repo.

### Steps To Reproduce

```markdown
1. Start PojavLauncher
2. Select 1.12 forge or Alpha 1.1.2(example)
3. Start the game
4. Window will display as shown above
```

### Expected Behavior

I expect the game to use the whole screen.

### Platform

```markdown
- Device model: iPad 7th gen wifi 
- iOS version: 14.7
- PojavLauncher version: Dev build from Doregon’s repo
```

### Anything else?

1.12 crashes idk if that’s related

**Comment by admin-elvistrujanovic** [comment]
I can't make any new issues (Templates not found)

**Comment by khanhduytran0** [comment]
> Versions below 1.13 show the screen in a very small corner of the screen 

~~Why did you turned off fullscreen mode? That’s  why the window is small.~~ Also, **Forge** 1.12.2 crashes is a known issue. Workaround:
Download the [stub text2speech-1.10.3.jar](https://cdn.discordapp.com/attachments/816675053671284736/868057567404916746/text2speech-1.10.3.jar). Overwrite file in `/var/mobile/Documents/minecraft/libraries/com/mojang/text2speech/1.10.3` folder. This is the modified library that contains only stubs for fixing Forge 1.12.2 crashes.

> The same issue also occurred with Alpha 1.1.2, which I never expected to work

Versions older than 1.6 are working as expected just before adding mod installer, as it depends on windowing stuff which we have just finished recently. Several classic versions may not handle fullscreen mode properly, so you may need to trigger F11 press manually.

**Comment by khanhduytran0** [comment]
> @Doregon can't make any new issues (Templates not found)

Now we use forms instead of templates, so you need to follow them :eyes:

**Comment by khanhduytran0** [comment]
> @Doregon can't make any new issues (Templates not found)

It’s likely that GitHub app doesn’t support form yet. You need to switch to web in order to make issue.

**Comment by admin-elvistrujanovic** [comment]
> instead

👍

**Comment by admin-elvistrujanovic** [comment]
> > @Doregon can't make any new issues (Templates not found)
> 
> 
> 
> Now we use forms instead of templates, so you need to follow them :eyes:

👍
