### ISSUE TITLE
Switch hotbar item with a tap

### ISSUE THREAD

**Issue by ExeRhythm** [PojavLauncherTeam/PojavLauncher_iOS#25]
If you could somehow implement this, it would be as good as a PE edition!

**Comment by khanhduytran0** [comment]
It was already added.

**Comment by ExeRhythm** [comment]
Alright, thanks

**Comment by ShroomKing** [comment]
sorry for commenting on a closed issue but it doesn’t work.

when i touch the hotbar nothing is happening, i think it might have something to do with my screen size(using an iphone6s)

**Comment by khanhduytran0** [comment]
Are you on latest build?

**Comment by ShroomKing** [comment]
yes, i assume i had some leftover config files because i had installed it before it was implemented.
i cleared the minecraft directory and now it works
