### ISSUE TITLE
[Bug] GUI jar apps not working very well

### ISSUE THREAD

**Issue by admin-elvistrujanovic** [PojavLauncherTeam/PojavLauncher_iOS#251]
### Describe the bug

Option "Launch a mod installer" not working with any Minecraft java unofficial launchers downloaded and runned from jar file in that GUI mode (same for any other java game in GUI mode - jar file)

### The log file and images/videos

![F57A6F50-CA2D-4F7A-A684-5D646847395C](https://user-images.githubusercontent.com/45666011/128596215-c5ae0d3b-569a-4536-9af2-c776271035e5.png)
![AE88AFDB-E0CD-4805-8929-E4443FA4841E](https://user-images.githubusercontent.com/45666011/128596338-19bc72ac-06e2-4553-8a17-fdb713b7aaac.png)
![196642D1-2D32-4934-9E78-DD4EEEDE09B0](https://user-images.githubusercontent.com/45666011/128596339-e56c6507-740d-4903-be82-bd9a16dea062.png)

### Steps To Reproduce

```markdown
1. Start PojavLauncher
2. Click on logged user
3. Click on options
4. Click on "Launch a mod installer"
5. Choose unofficial Minecraft Launcher from the TLauncher official website (TLauncher.jar)
6. Waiting to install and configure the launcher in setup
7. See the Two Errors: One error is when i simply run the jar file and another error is when i extract jvm manually (See images)
```

### Expected Behavior

I expect the launcher to run normally with little bugs because I'm using pre-release versions (dev channel) so this versions must be unstable.

### Platform

```markdown
- Device model: iPhone 7 (GSM)
- iOS version: 14.5.1
- PojavLauncher version: dev - latest release from the dev channel (1.3~alpha70)
```

### Anything else?
No

**Comment by artdeell** [comment]
Do you think the mod installer was intended to run launchers? TL won't start up because it uses JavaFX, and even if it would, you won't be able to run Minecraft with it.

**Comment by admin-elvistrujanovic** [comment]
> Do you think the mod installer was intended to run launchers? TL won't start up because it uses JavaFX, and even if it would, you won't be able to run Minecraft with it.

Ok. I thought I would try to open Java GUI applications like TLauncher at least through this way, but obviously it is intended exclusively for mod installers. I searched the internet to use Java GUI applications on iOS 14.5.1 but I didn't find the possibility that it is possible at all. It is possible here, but obviously not like on computers and emulators that can work much better and can be used on Linux, Windows, MacOS and Android. It would be very interesting to make a Java GUI on iOS devices as well so that we who are iOS users can use desktop applications but that will not happen due to the limit of iPhone and iPad.
