### ISSUE TITLE
[Bug] java 8 crash

### ISSUE THREAD

**Issue by creyes200** [PojavLauncherTeam/PojavLauncher_iOS#253]
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher_iOS/files/6949805/latestlog.txt)

### Describe the bug

Java 8 crashes just begore the mojang screens finishes loading.

### The log file and images/videos

>  @`
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher_iOS/files/6949798/latestlog.txt)
`

### Steps To Reproduce

```markdown
Start PojavLauncher with custom_env.txt with openjdk 8 and when the mojang bar almost finishes it crashes
```

### Expected Behavior

I expected  for the game to run

### Platform

```markdown
- Device model: iphone 8
- iOS version: 14.6 checkra1n jailbreak
- PojavLauncher version: latest dev
```

**Comment by khanhduytran0** [comment]
It should work now. Please check latest launcher build.

**Comment by creyes200** [comment]
Didn’t work i just updated it and tried

**Comment by creyes200** [comment]
I got the same result

**Comment by khanhduytran0** [comment]
Where did you update?

**Comment by creyes200** [comment]
In cydia

**Comment by creyes200** [comment]
From doregons repo

**Comment by creyes200** [comment]
I went to changes and upgraded PojavLauncher

**Comment by khanhduytran0** [comment]
That's nightly build, not immediate build. take a look at https://github.com/PojavLauncherTeam/PojavLauncher_iOS/actions for latest

**Comment by creyes200** [comment]
Ok

**Comment by creyes200** [comment]
How do i do it?

**Comment by creyes200** [comment]
I would just prefer to wait for the fix to be updated on cydia

**Comment by khanhduytran0** [comment]
The update is likely won't be updated to the repo soon due to https://github.com/oprypin/nightly.link/issues/26

**Comment by Doregon** [comment]
@khanhduytran0 I'm gonna switch to interacting with the API itself pretty soon

**Comment by creyes200** [comment]
Ok the. How do i install the inmediat build
?
