### ISSUE TITLE
[Question] <Short description> Openjdk 8 fps

### ISSUE THREAD

**Issue by creyes200** [PojavLauncherTeam/PojavLauncher_iOS#254]
### Ask the question here.

When using openjdk 8 i noticed a massive fps drop and i want to know if this is just because its still in development or is it as good as its gonna get? 

( btw i had 45-60 fps and dropped to 0-10)

**Comment by khanhduytran0** [comment]
We didn’t get enough information.

> and i want to know if this is just because its still in development 

We took the port from Mac M1’s complete port.

**Comment by Doregon** [comment]
Unable to help as you did not provide enough information for us to work.
