### ISSUE TITLE
[Bug] <Crash>

### ISSUE THREAD

**Issue by SailentWasTaken** [PojavLauncherTeam/PojavLauncher_iOS#257]
### Describe the bug

When you click the 3 dots and press “Launch A Mod Installer” nothing shows up and it crashes immediately.

### Steps To Reproduce

```markdown
1. Select Your Account On PojavLauncher.
2. Click The ... (3 dots).
3. Click “Launch A Mod Installer”
4. Watch it crash.
```

### Expected Behavior

I expect for the menu to open and choose my mod launcher.

### Platform

```markdown
- Device model: iPad 6th Generation 
- iOS version: 14.3
- PojavLauncher version: Latest (1.3)
```

**Comment by khanhduytran0** [comment]
If you update to latest build, you will see the answer. Mod installer only works with Java 8.

**Comment by khanhduytran0** [comment]
Also, you didn't attach the log file
