### ISSUE TITLE
Even if I did that the git hub says the Minecraft 1.17 still doesn't work

### ISSUE THREAD

**Issue by Glasslive** [PojavLauncherTeam/PojavLauncher_iOS#260]
### Describe the bug

Crashed when it was near and shows game exited with code 0

### Steps To Reproduce

```markdown
..
```

### Expected Behavior

.. 

### Platform

```markdown
- Device model: Mi 8
- PojavLauncher version: newest
```

**Comment by khanhduytran0** [comment]
The template isn't filled properly and wrong repo. This repo is for iOS platform, not Android.
