### ISSUE TITLE
[Question] mod launcher directory

### ISSUE THREAD

**Issue by creyes200** [PojavLauncherTeam/PojavLauncher_iOS#262]
![DA5AB7C3-48C7-43A1-A89E-5F1E4FA1198F](https://user-images.githubusercontent.com/84339275/129816539-e0d1147e-cd22-4409-a6be-c9a08d395456.png)
### Ask the question here.

What directory do i need to put when using a mod installer in the ui that apears

**Comment by SailentWasTaken** [comment]
Hmmmmm, try putting Documents then the minecraft folder

**Comment by khanhduytran0** [comment]
Update to latest build, then the `Library/Application Support/minecraft` directory will be symlinked to `Documents/minecraft` directory.
or, you can change to /var/mobile/Documents/minecraft
