### ISSUE TITLE
[Bug] Please Help

### ISSUE THREAD

**Issue by SailentWasTaken** [PojavLauncherTeam/PojavLauncher_iOS#263]
### Describe the bug

I’ve used the Mod Installer to install forge 1.8.9 and other mods such as LabyMod. The problem is the installed versions don’t work. I’ve tried to run LabyMod and it shows the prompt when a file is missing or something like that. Same with Forge 1.8.9. My only hope is to use the headless which can’t even install forge 1.8.9. Please make it so that there’s a jar in the Installed version so that it can work because the Universal way (aka Launch Mod Installer) doesn’t work properly unfortunately.

### Steps To Reproduce

```markdown
1. Open Launch Mod Installer
2. Select the forge 1.8.9 file.
3. Install it thru client and do the installation process.
4. Try to run the forge 1.8.9 version.
```

### Expected Behavior

I expected the Forge 1.8.9 to work.

### Platform

```markdown
- Device model: iPad 6th Generation
- iOS version: 14.3
- PojavLauncher version: 1.3
```

**Comment by khanhduytran0** [comment]
The log file is missing.

**Comment by khanhduytran0** [comment]
> the installed versions don’t work.

Make sure that you have installed the vanilla version. Local account won't download anything. Switch to your Mojang/Microsoft account which you used to buy Minecraft.

**Comment by khanhduytran0** [comment]
If you didn't buy the game, then I'm wondering about how you got an expensive Apple device but not a video game.

**Comment by SailentWasTaken** [comment]
I got this device for my bday lol

**Comment by SailentWasTaken** [comment]
Also where can I download the log?

**Comment by creyes200** [comment]
/var/mobile/documents/.pojavlauncher/latestlog.txt or do ot the easy way and get it from the app its self. By tapping the blue icon in the top right then tap send your logs.

**Comment by Doregon** [comment]
Closing stale issue.
