### ISSUE TITLE
[Bug] <1.12.2 forge crash)

### ISSUE THREAD

**Issue by creyes200** [PojavLauncherTeam/PojavLauncher_iOS#264]
### Describe the bug

When forge 1.12.2 almost finishes loading it crashes

### Steps To Reproduce

```markdown
Start pojavlauncher select forge 1.12.2 then play end when it almost finishes it crashes
```

### Expected Behavior

I expected see the minecraft home screen

### Platform

```markdown
- Device model: iphone 8
- iOS version: 14.6 checkra1n 
- PojavLauncher version: 
Latest dev version
```

**Comment by lanspring** [comment]
try this
turn on splash.properties file
modify enabled=true to enabled=false
the directory where it is /var/mobile/Documents/minecraft/config

**Comment by Doregon** [comment]
These options should fix the crashing:

1. Update to the latest build, and install Forge 1.12.2.
2. Replace `/var/mobile/Documents/.pojavlauncher/Library/Application Support/minecraft/libraries/com/mojang/text2speech/1.10.3/text2speech-1.10.3.jar` with [this stub file](https://cdn.discordapp.com/attachments/816675053671284736/868057567404916746/text2speech-1.10.3.jar).
3. If you do not have a config directory in the `minecraft` folder, attempt to open Forge and let it crash.
4. Edit `config/splash.properties` and change `enabled=true` => `enabled=false`.

**Comment by YahyaYa10** [comment]
how do i open splash.properties
