### ISSUE TITLE
[Bug] <1.8.9 crashes after a minute or 2

### ISSUE THREAD

**Issue by creyes200** [PojavLauncherTeam/PojavLauncher_iOS#265]
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher_iOS/files/7025669/latestlog.txt)
### Describe the bug

When i use 1.8.9 it works for a short time before crashing.

### The log file and images/videos

> ``

### Steps To Reproduce

```markdown
Start pojavlauncher select 1.8.9 and then after a while it crashes.
```

### Expected Behavior

I expected to be able to play wighout problem

### Platform

```markdown
- Device model: iPhone 8
- iOS version: 14.6 checkra1n jailbreak
- PojavLauncher version: latest dev
```

**Comment by Doregon** [comment]
Reproduce the issue and provide a new log.

**Comment by creyes200** [comment]
[latestlog.old.txt](https://github.com/PojavLauncherTeam/PojavLauncher_iOS/files/7230082/latestlog.old.txt)

**Comment by creyes200** [comment]
sorry for the late response I forgot my GitHub password and it took me a while to change it

**Comment by khanhduytran0** [comment]
You need to enable VBO in the video settings.
