### ISSUE TITLE
[Bug] labymod doesnt work at all

### ISSUE THREAD

**Issue by ibrahim0534** [PojavLauncherTeam/PojavLauncher_iOS#269]
### Describe the bug

labymod simply doesnt work on any version
1.8.9 loads the game but the client itself doesnt load
1.12.2 crashes on loading screen
1.16.5 crashes as soon as the controls appear on the screen

### The log file and images/videos

ive sent them more than 10 times on #general-ios tried a lot of solutions and none worked

### Steps To Reproduce

```markdown
install any version of labymod through the mod installer and launch the game with labymod
```

### Expected Behavior

i expect a loading screen and then the main menu of labymod like i get on my pc or my friends get on pojavlauncher for android 

### Platform

```markdown
- Device model: iPhone X
- iOS version: 14.6
- PojavLauncher version: Latest Release
```

### Anything else?

an android developer told me to get a dll file once and said maybe thats why it doesnt work on ios but i didnt understand him and where do i put the dll file if i get it

**Comment by ibrahim0534** [comment]
idk if its a dll or not but i searched it up and people say its a dll file related to a java JNA or smt like that the dev said 
“I think on iOS it's because of missing jnidispatch”

**Comment by khanhduytran0** [comment]
Have you tried newer builds? Labymod should work again. However, LabyMod 1.8.9 only works on iOS 14+ due to the current JNA library.

**Comment by crystall1nedev** [comment]
Closing issue as Labymod works.
