### ISSUE TITLE
Control issue

### ISSUE THREAD

**Issue by HongyiMC** [PojavLauncherTeam/PojavLauncher_iOS#27]
The D-pad will hold down a key when fingers move to a different key
For example when press forward key and them move my finger to a nearby key, my character will still keep walking forward.

**Comment by khanhduytran0** [comment]
What’s your using build?

**Comment by HongyiMC** [comment]
430

**Comment by khanhduytran0** [comment]
Can you try latest build? :eyes:

**Comment by Doregon** [comment]
Closing stale issue.
