### ISSUE TITLE
[Bug] 1.17.1 won’t work

### ISSUE THREAD

**Issue by JellyfishJ** [PojavLauncherTeam/PojavLauncher_iOS#271]
### Describe the bug

1.17.1 crashes before opening

### Steps To Reproduce

```markdown
I start pojav launcher, login to my account, type 1.17.1, and the app crashes
```

### Expected Behavior

The game opens up

### Platform

```markdown
- Device model: Iphone 6s
- iOS version: 1.14.3 taurine
- PojavLauncher version: 1.2
```

### Anything else?

I downloaded PojavLauncher on an iphone 6s and i downloaded openjdk 17 jre from cydia but 1.17.1 still won’t work, the app just crashes

**Comment by Doregon** [comment]
You need to be on the development builds of PojavLauncher to use 1.17.1. Once you have a developer build installed, step into the preferences window and switch the renderer to tinygl4angle.

**Comment by JellyfishJ** [comment]
Where can i find the dev build?

**Comment by admin-elvistrujanovic** [comment]
> Where can i find the dev build?

Here:
[https://repo.doregon.gq](https://repo.doregon.gq)(Doregon repo)
Search for PojavLauncher (Dev) and install it
