### ISSUE TITLE
[Bug] 21w10a+ not working

### ISSUE THREAD

**Issue by admin-elvistrujanovic** [PojavLauncherTeam/PojavLauncher_iOS#272]
### Describe the bug

I can't run any Minecraft version from 21w10a and up after new update.

### The log file and images/videos

[latestlog.txt](https://www.icloud.com/iclouddrive/0zORMrvvLpl8XJVFZa_Nxkv-Q#latestlog)

### Steps To Reproduce

```markdown
1. Start PojavLauncher
2. Login
3. Select Minecraft version
4. Select options
5. Select Java 17
6. Select 1.17+ render (tinygl4angle)
7. Close PojavLauncher
8. Start PojavLauncher
9. Again, select same options
10. Start the game
11. Mojang message is loading
12. Crash
```

### Expected Behavior

I expect the game to run this version

### Platform

```markdown
- Device model: iPhone 7
- iOS version: 14.5.1
- PojavLauncher version: Latest Release (Dev channel)
```

### Anything else?

No

**Comment by admin-elvistrujanovic** [comment]
@khanhduytran0 Can you reopen this issue because I tested new dev update but it's not fixed for me

**Comment by khanhduytran0** [comment]
Where did you update?

**Comment by admin-elvistrujanovic** [comment]
> Where did you update?

I downloaded deb file from latest action on GitHub

**Comment by khanhduytran0** [comment]
Did you change the render again?
