### ISSUE TITLE
[Bug] Launcher crashes after downloading all the game files.

### ISSUE THREAD

**Issue by sourcelocation** [PojavLauncherTeam/PojavLauncher_iOS#274]
### Describe the bug

The launcher crashes after downloading all the game files.

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher_iOS/files/7160252/latestlog.txt)

### Steps To Reproduce

```markdown
1. Sign in (I use Microsoft account, but local does not work either)
2. Launch the game (1.7.10 does not work and 1.17.1 too)
```

### Expected Behavior

I expected the game to launch

### Platform

```markdown
- Device model: iPad Air 3
- iOS version: 14.3
- PojavLauncher version: 1.3~alpha95
```

**Comment by Doregon** [comment]
This seems to be a common issue with Taurine + 14.3 + A12+. Pinning this issue as we continue to track down the source of the issue (we do not currently have any A12+ devices available to test).

**Comment by Doregon** [comment]
@ExeRhythm Can you try this build? I'm starting to rerun older commits from around the time where it stopped working to pinpoint the issue.

https://github.com/PojavLauncherTeam/PojavLauncher_iOS/suites/3779721945/artifacts/93102149

**Comment by ExeRhythm** [comment]
Crashes with JDK 16 and 17 when 1.17.1 is selected

**Comment by Doregon** [comment]
Can you send logs please

**Comment by ExeRhythm** [comment]
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher_iOS/files/7176407/latestlog.txt)
Sorry, couldn’t respond, because I was asleep

**Comment by ExeRhythm** [comment]
@Doregon Is there any update on this issue?

**Comment by Doregon** [comment]
SO it seems to be that the launcher is deallocating the preferences loader before we call it. We just need to find out why now.

**Comment by khanhduytran0** [comment]
Try using v2.0 release or the latest build.

**Comment by crystall1nedev** [comment]
Closing stale issue.
