### ISSUE TITLE
[Bug] Minecraft versions not working

### ISSUE THREAD

**Issue by admin-elvistrujanovic** [PojavLauncherTeam/PojavLauncher_iOS#275]
### Describe the bug

Black screen

### The log file and images/videos
[latestlog.txt - iCloud source](https://www.icloud.com/iclouddrive/0ibf8XI3OHFh0uZiAOKPl4cbg#latestlog)
[latestlog.txt - GitHub source](https://github.com/PojavLauncherTeam/PojavLauncher_iOS/files/7206140/latestlog.txt)

### Steps To Reproduce

```markdown
1. Start PojavLauncher
2. Login
3. Select Minecraft version (in this case, version is 1.17.1)
4. Select options
5. Select new render (Zink Mesa 21.0 - Exports OpenGL 4.1)
6. Select Java 17
7. Click Play
8. Crash
```

### Expected Behavior

Opened game

### Platform

```markdown
- Device model: iPhone 7
- iOS version: 14.5.1
- PojavLauncher version: Latest Pre-Release (Dev)
```

### Anything else?

/

**Comment by khanhduytran0** [comment]
latestlog.txt is required.

**Comment by admin-elvistrujanovic** [comment]
>  latestlog.txt is required.

The link was deleted from my post but has now been restored

**Comment by khanhduytran0** [comment]
*why did you always upload to iCloud while GitHub has option to do that* (web version)

**Comment by khanhduytran0** [comment]
Btw the link you sent does nothing when open, is permission set correctly?

**Comment by crystall1nedev** [comment]
Closing stale issue, reopen it you have anythibg to add.
