### ISSUE TITLE
[Bug] Invalid Address Kernel Crash 

### ISSUE THREAD

**Issue by lbertitoyt** [PojavLauncherTeam/PojavLauncher_iOS#276]
### Describe the bug

Basically when i go into any >1.12.2 version after 1 minute or 2 it inevitably crashes. Here is the bug report of Cr4shed.

### The log file and images/videos

Also, latestlog.txt doesn’t capture absolutely anything related to this error, but im still going to upload it. I provided here the Cr4shed report.
[latestlog.old.txt](https://github.com/PojavLauncherTeam/PojavLauncher_iOS/files/7198130/latestlog.old.txt)
![185BC1E2-50D5-4A30-BE50-2FD3D3C0AC56](https://user-images.githubusercontent.com/49609909/134060381-473aa879-f121-4b74-8724-694754de882e.png)

### Steps To Reproduce

```markdown
1. Start PojavLauncher and log in
2. Using Java 8, run Minecraft Vanilla >1.12.2
3. Create a world and move around for a bit
4. Profit
```

### Expected Behavior

I was expecting for it to let me play and not crash

### Platform

```markdown
- Device model: iPad 6th gen
- iOS version: 13.7
- PojavLauncher version: 1.3
```

**Comment by khanhduytran0** [comment]
Basically when i go into any >1.12.2 version after 1 minute or 2 it inevitably crashes.

> Selected Minecraft version: 1.7.10
<:bruh:696116942259617802>
Did you mean ≤1.12.2?

**Comment by Py10lolz** [comment]
> > Basically when i go into any >1.12.2 version after 1 minute or 2 it inevitably crashes.
> 
> latestlog.txt:
> 
> > Selected Minecraft version: 1.7.10
> 
> <:bruh:696116942259617802>
> Did you mean ≤1.12.2?

Using discord emoji in github bhai 101% real.

**Comment by Py10lolz** [comment]
<:ULTIMATEROFEL:786306660141629441>

**Comment by ChinaTomMiao** [comment]
Hello?

**Comment by khanhduytran0** [comment]
No response moment. The VBO option needs to be enabled.
