### ISSUE TITLE
[Question] <Short description>

### ISSUE THREAD

**Issue by ChinaTomMiao** [PojavLauncherTeam/PojavLauncher_iOS#280]
### Ask the question here.

Hi, I’m Tom. 

I love playing Minecraft,  and I think it’s not convenient to play it on a computer, so I want to play it on my IPad. Then I found Projav Luancher, and I want to download it, but I don’t know where to download, so is there anybody who can tell me how to download Projav Launcher? Thanks a lot.

By the way, I’m not good at English, sorry.

**Comment by ENDERMANYK** [comment]
you need to jailbreak your iPad to use it, then add apt.doregon.gq in source, then download pojavlauncher-dev, openjdk-8, openjdk-16, then you can play it

**Comment by ChinaTomMiao** [comment]
Thanks for replying me. 
What’s jailbreak? And I don’t know where to download all the things above on IPad. Could you tell me the link?

**Comment by ChinaTomMiao** [comment]
By the way, I’m from China, where are you from? Nice to meet to, and I like your head portrait.

**Comment by ChinaTomMiao** [comment]
By the way, I’m from China, where are you from? Nice to meet you, and I like your head portrait.

**Comment by ENDERMANYK** [comment]
bruh,百度或谷歌下iOS越狱就行...,而且你这机翻..下载的东西全部在越狱之后的下载源

**Comment by asdfugil** [comment]
> bruh,百度或谷歌下iOS越狱就行...,而且你这机翻..下载的东西全部在越狱之后的下载源

這不太像機翻, 文法還可以。

**Comment by asdfugil** [comment]
https://jailbreaks.app

**Comment by crystall1nedev** [comment]
Closing issue as answer has been provided.
