### ISSUE TITLE
[F-Req] <Short description>

### ISSUE THREAD

**Issue by SailentWasTaken** [PojavLauncherTeam/PojavLauncher_iOS#281]
### Is this request related to a bug?

You should make the hotbar easier to go on to because for me when I tap on an item in the hotbar with auto gui, it usually goes onto the item on the right of it.

### Describe the request.

Better hotbar & a mouse cursor like pojav android?

**Comment by khanhduytran0** [comment]
> You should make the hotbar easier to go on to because for me when I tap on an item in the hotbar with auto gui, it usually goes onto the item on the right of it.

There's no way to handle them completely + correctly for all versions. Every version may calculates the UI scale different along with customizable resolution, it would be a pain to handle **all** of them. Alternative you can enable the "swipeable hotbar" option.

> a mouse cursor like pojav android?

Added in customctrl branch.
