### ISSUE TITLE
[Bug] <Short description>crash when trying to install forge 1.12.2

### ISSUE THREAD

**Issue by creyes200** [PojavLauncherTeam/PojavLauncher_iOS#282]
### Describe the bug

trying to install forge 1.12.2 results in crash

### The log file and images/videos

[latestlog.old.txt](https://github.com/PojavLauncherTeam/PojavLauncher_iOS/files/7230096/latestlog.old.txt)

### Steps To Reproduce

```markdown
start pojavlauncher choose your account select launch a mod installer select forge 1.12.2.jar file and then it crashes
```

### Expected Behavior

I expected for forge to install successfully 

### Platform

```markdown
- Device model: iPhone 8
- iOS version: 14.6 (checkra1n jailbreak)
- PojavLauncher version: latest dev (on cydia at least)
```

**Comment by creyes200** [comment]
Any help?

**Comment by NotAHero04** [comment]
Reinstall Forge :fr:

**Comment by khanhduytran0** [comment]
> ModInstaller: launching /private/var/mobile/Containers/Data/Application/A9CDF804-DA19-4CC8-88D0-01F7A6964CA8/tmp/net.kdt.pojavlauncher-Inbox/forge-1.12.2-14.23.5.2855-<ins>universal</ins>.jar

Why universal but not installer?
