### ISSUE TITLE
[Bug] <crash on old versions>

### ISSUE THREAD

**Issue by creyes200** [PojavLauncherTeam/PojavLauncher_iOS#287]
### Describe the bug

Loading into a world ends in crash after a few seconds (1.7.10 and 1.8 specifically) 

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher_iOS/files/7448997/latestlog.txt)
[hs_err_pid16144.log](https://github.com/PojavLauncherTeam/PojavLauncher_iOS/files/7449008/hs_err_pid16144.log)

### Steps To Reproduce

```markdown
Start pojavlauncher select 1.8.9 
Enter a world look around for a second and it crashes.
```

### Expected Behavior

I expected to be able to play without problem.

### Platform

```markdown
- Device model: iPhone 8
- iOS version: 14.6 checkra1n 
- PojavLauncher version: latest dev
```

**Comment by NotAHero04** [comment]
@khanhduytran0 from Discord server:
> 1.1.4 does not work (crashes while loading proper worlds)
>
There's a bug in gl4es 1.1.4's fixed pipeline emulator which can be fixed by setting environment variable `LIBGL_USEVBO=0`

**Comment by LegacyGamerHD** [comment]
> @khanhduytran0 from Discord server:
> 
> > 1.1.4 does not work (crashes while loading proper worlds)
> 
> There's a bug in gl4es 1.1.4's fixed pipeline emulator which can be fixed by setting environment variable `LIBGL_USEVBO=0`

Yes and decreases performance heavely just set vbo on

**Comment by creyes200** [comment]
how exactly do i do that?

**Comment by creyes200** [comment]
help pease?

**Comment by Doregon** [comment]
Closing as @LegacyGamerHD provided the answer.
