### ISSUE TITLE
[F-Req] idea for pojav raspi

### ISSUE THREAD

**Issue by dolphin-cat** [PojavLauncherTeam/PojavLauncher_iOS#288]
you could slightly modify this to run on a raspberry pi 4 as rpi's are armhf devices that with some tweaking can support arm64 too, i think it will just run but the problem is the .minecraft location as there is no /device, i will try it out and tell you how it went in a reply/comment or whatever its called

**Comment by dolphin-cat** [comment]
to install java 8(-1.16.5) and java 16(+1.17) this wiki has instructions specifically for the raspberry pi https://adoptopenjdk.net/installation.html#linux-pkg

**Comment by khanhduytran0** [comment]
Bruh, Raspberry PI doesn’t run Darwin, their graphics library (X11) is also different with iOS (Cocoa). We are not going to make the launcher for arm/arm64 since there was some people doing that (see https://forums.raspberrypi.com/viewtopic.php?f=78&t=321888)
