### ISSUE TITLE
[Bug] iOS Repo Not Working

### ISSUE THREAD

**Issue by slavicweebofficial** [PojavLauncherTeam/PojavLauncher_iOS#289]
### Describe the bug

The repo "https://doregon.github.io/cydia" doesn't work, I tried pasting it on a browser it shows 404. Can you check what's the problem?

### The log file and images/videos

![IMG_0491](https://user-images.githubusercontent.com/63901383/140270668-f014dfe2-9c4b-499a-8a8b-f0e56f5e2b8f.png)
![IMG_0492](https://user-images.githubusercontent.com/63901383/140270686-c22c8ac1-150a-4f25-9da7-5e9d8d88c4c5.jpeg)

### Steps To Reproduce

```markdown
1- Copy the repo "https://doregon.github.io/cydia" from "https://pojavlauncherteam.github.io/ios/install-guide/doregon-repo.html"
2- Add the repo in a package manager
3- Error shows up
```

### Expected Behavior

Adding the repo successfully and able to install it's packages

### Platform

```markdown
- Device model: iPad Mini 5
- iOS version: iPadOS 14.3
- PojavLauncher version: None
```

**Comment by asdfugil** [comment]
a repo doesn't need to have anything in it's root to be a valid repo so the browser part is invalid.

**Comment by asdfugil** [comment]
Additionally, you should be using https://apt.doregon.gq

**Comment by slavicweebofficial** [comment]
oh so it uses a different repo thanks it works
