### ISSUE TITLE
[Question] How to symlink Java?

### ISSUE THREAD

**Issue by UInt2048** [PojavLauncherTeam/PojavLauncher_iOS#290]
The [wiki page for installing Forge](https://pojavlauncherteam.github.io/ios/wiki/going-further/non-vanilla/forge.html#installation) mentions having symlinked Java "as explained on the installing page" but I wasn't able to find this explanation.

Could this explanation be linked if it's present somewhere?

**Comment by khanhduytran0** [comment]
Why would you need to symlink anyways?
> Next, type this command to install Forge (<ins>if you symlinked</ins> Java as explained on the installing page, you can just type java):

Also, in newer builds, launch them in the mod installer instead.
