### ISSUE TITLE
[Bug] with 1.8-1.8.9

### ISSUE THREAD

**Issue by Omgitst** [PojavLauncherTeam/PojavLauncher_iOS#296]
### Describe the bug

1.8-1.8.9 crashes after entering a world and looking around

### Steps To Reproduce

```markdown
Start PojavLauncher select 1.8.9 and launch and join a world and look around and crash
```

### Expected Behavior

I expect the game not to crash

### Platform

```markdown
- Device model: iPhone 12
- iOS version: 14.3
- PojavLauncher version: 2.0~alpha8
Jailbroken
```

### Anything else?

I really want a fix please help!!!

**Comment by admin-elvistrujanovic** [comment]
> 
> ### The log file and images/videos
> 
> _No response_
> 
> 
> ### Anything else?
> 
> I really want a fix please help!!!

If you really want a fix, please, upload a log file for that game here

**Comment by Omgitst** [comment]
> 

Ok

**Comment by khanhduytran0** [comment]
> Ok

It’s been almost 2 weeks, still no log provided. I assume that VBO is not enabled. Head to Settings -> Video Settings -> VBO to enable it.
