### ISSUE TITLE
[Bug] fabric crashing 

### ISSUE THREAD

**Issue by Omgitst** [PojavLauncherTeam/PojavLauncher_iOS#298]
### Describe the bug

Fabric on all versions does not work

### The log file and images/videos

This is the crash log for 1.16.5 fabric

java.lang.ClassNotFoundException: net.fabricmc.loader.impl.launch.knot.KnotClient
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:419)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:352)
	at net.kdt.pojavlaunch.Tools.lambda$launchMinecraft$0(Tools.java:143)
	at java.lang.Thread.run(Thread.java:748)

### Steps To Reproduce

```markdown
Install fabric and launch and it will not work
```

### Expected Behavior

I expect the game to load

### Platform

```markdown
- Device model: iPhone 12
- iOS version: 14.3
- PojavLauncher version: 2.0 alpha 8
```

### Anything else?

I really want this to work so someone help me

all versions of Minecraft fabric and fabric loader do not work

**Comment by Omgitst** [comment]
Yo

**Comment by khanhduytran0** [comment]
Account type is not stated. Also lacks of latestlog.txt

**Comment by khanhduytran0** [comment]
I assume that you have logged in with a local account, which doesn’t allow downloading.
