### ISSUE TITLE
[Bug] microsoft not doing anything once tapped

### ISSUE THREAD

**Issue by kittiguns** [PojavLauncherTeam/PojavLauncher_iOS#302]
### Describe the bug

nothing happens when selecting microsoft account 

### The log file and images/videos

![1D56B174-6C9D-4C02-9F72-CA1740323754](https://user-images.githubusercontent.com/93688065/147312845-385ac772-02a3-4917-8716-b054ce840f3b.png)

https://user-images.githubusercontent.com/93688065/147312862-f47129f2-6306-465a-9a61-293a693e3de9.MP4

### Steps To Reproduce

```markdown
dk
```

### Expected Behavior

i expect it to pop up a login page of some sort

### Platform

```markdown
- Device model: iPhone 6
- iOS version: 12.5.5
- PojavLauncher version: latest release 1.3
```

**Comment by khanhduytran0** [comment]
1.3 is not the latest version. Please update to 2.0.
