### ISSUE TITLE
[Bug] Nothing happens when microsoft account is selected

### ISSUE THREAD

**Issue by kittiguns** [PojavLauncherTeam/PojavLauncher_iOS#303]
### Describe the bug

when clicking microsoft account nothing happens even after updating to version 2.0

### The log file and images/videos

![732B54D5-8516-4959-BE99-CF6613697F21](https://user-images.githubusercontent.com/93688065/147369758-31bbc067-12d6-426e-b3a8-b7d066e756d1.png)

https://user-images.githubusercontent.com/93688065/147369761-0bdc38f5-3d9c-4a65-894c-4c6b4a8c9871.MP4

### Steps To Reproduce

```markdown
start pojav launcher and clicked on microsoft
```

### Expected Behavior

expect it to load a page to login but nothing happens

### Platform

```markdown
- Device model: iphone 6
- iOS version: 12.5.5
- PojavLauncher version: 2.0
```

### Anything else?

ive restarted my phone and rejailbroke it and the problem still continues to happen

**Comment by khanhduytran0** [comment]
**Lacks of the log file**. Please send latestlog.txt after many tries of login.

**Comment by kittiguns** [comment]
> **Lacks of the log file**. Please send latestlog.txt after many tries of login.

how do you find the log txt

**Comment by kittiguns** [comment]
[text.txt](https://github.com/PojavLauncherTeam/PojavLauncher_iOS/files/7775301/text.txt)

**Comment by Doregon** [comment]
You can access it by tapping "About" at the top right and then "Send your logs".
