### ISSUE TITLE
[BUG] PojavLauncher Crashing as soon as joining server

### ISSUE THREAD

**Issue by Sadek2002** [PojavLauncherTeam/PojavLauncher_iOS#307]
### Describe the bug

Whenever I try joining a minecraft server it crashes my game. I run 1.8.9 optifine and also without to see if optifine was the issue.

Hope to get help to resolve this issue. 😄

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/7875808/latestlog.txt)

### Steps To Reproduce

```markdown
1. Start PojavLauncher
2. Login (Used microsoft myself because I migrated)
3. Start any version
4. Join a server (Works fine on singleplayer)
5. Game crash
```

### Expected Behavior

I expect the launcher to work on servers.

### Platform

```markdown
- Device model: iPhone 12
- CPU architecture: Apple A14 not sure 
- Ios version: 14.4.2
- Jailbreak: Unc0ver
- PojavLauncher version: 2.1
```

**Comment by Sadek2002** [comment]
> Wrong repository moment

Wdym wrong repository?

**Comment by Sadek2002** [comment]
> 

why what....

**Comment by khanhduytran0** [comment]
> > Wrong repository moment
> 
> Wdym wrong repository?

The PojavLauncher one is for Android. This (I transferred to) is for iOS.

Try enabling VBO moment.

**Comment by Sadek2002** [comment]
> > > Wrong repository moment
> > 
> > 
> > Wdym wrong repository?
> 
> The PojavLauncher one is for Android. This (I transferred to) is for iOS.
> 
> Try enabling VBO moment.

Oh okay sorry where do I find VBO?

**Comment by khanhduytran0** [comment]
> Oh okay sorry where do I find VBO?

It's in the video settings of the game...

**Comment by Vishal2935** [comment]
[latest.log](https://github.com/PojavLauncherTeam/PojavLauncher_iOS/files/14069200/latest.log)
i am also unable to join server
please resolve this issue
