### ISSUE TITLE
When can it be installed with forge and mods

### ISSUE THREAD

**Issue by wyc66652** [PojavLauncherTeam/PojavLauncher_iOS#31]

**Comment by InfernoNova9999** [comment]
i tried fabric with sodium and it works but i cant get fabric api or fabric mod menu to work which means that other mods wont work

**Comment by khanhduytran0** [comment]
@wyc66652 Fabric API and Forge are working now, but Forge one has issue about mouse.

**Comment by khanhduytran0** [comment]
Forge is fully working now. Closing
