### ISSUE TITLE
[Question] <Is it possible to run this app without jailbreak when JIT is enabled.>

### ISSUE THREAD

**Issue by js-john** [PojavLauncherTeam/PojavLauncher_iOS#311]
### Ask the question here.

The iOS qemu-based virtual machine app UTM can successfully runs vms without jailbreak.
UTM has two version: UTM and UTM SE.
UTM uses JIT to generate code which is faster and UTM SE use TCI which is slower. There are many methods to enable JIT on iOS devices, such as Xcode tethered launch, AltJIT and Jitterbug.
I want to know if PojavLauncher relies on some jailbreak environment.

Here is the UTM repository:
https://github.com/utmapp/utm

Thanks for taking a look!

**Comment by js-john** [comment]
I got the answer from wiki.

**Comment by khanhduytran0** [comment]
> There are many methods to enable JIT on iOS devices, such as Xcode tethered launch, AltJIT and Jitterbug.

These above are all RW/RX JIT. Java relies on RWX JIT with RW/RX swapping is handled by `pthread_jit_write_protect_np` on macOS. Therefore, Java needs to be modified before it works with RW/RX JIT methods like above.
