### ISSUE TITLE
[Bug] Minecraft 1.18.1 not working on my device

### ISSUE THREAD

**Issue by admin-elvistrujanovic** [PojavLauncherTeam/PojavLauncher_iOS#312]
### Describe the bug

Game crash at startup

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher_iOS/files/7939895/latestlog.txt)

### Steps To Reproduce

```markdown
1. Start PojavLauncher
2. Select (Demo) account
3. Select game version 1.18.1
4. Click play
5. App crashed
```

### Expected Behavior

I expect the game to start

### Platform

```markdown
- Device model: iPhone 7 (GSM)
- iOS version: 14.3
- PojavLauncher version: Latest pre-release (downloaded deb file from github actions)
```

### Anything else?

This error is showing on all minecraft versions (include all renders). Only MC 1.16.5 working on Java 8 (not 16 or 17)

**Comment by khanhduytran0** [comment]
1.17+ require `tinygl4angle` selected, but the attached log was run with Zink.

**Comment by admin-elvistrujanovic** [comment]
> 1.17+ require `tinygl4angle` renderer selected, but the attached log was run with Zink.

When I change to any other openjdk version - I get this:
[cr4shed.txt](https://github.com/PojavLauncherTeam/PojavLauncher_iOS/files/8010910/cr4shed.txt)

**Comment by Doregon** [comment]
See #321.
