### ISSUE TITLE
[Bug] Microsoft login stuck at “logging in”

### ISSUE THREAD

**Issue by NoDa75** [PojavLauncherTeam/PojavLauncher_iOS#315]
### Describe the bug

When I select “Microsoft login” and click continue, the screen just has a loading wheel and says “logging in” I left it for 10 minutes and it still said “logging in.” This happens with the demo account as well

### The log file and images/videos

![0E9072A0-6529-4491-B4DD-B3C506287607](https://user-images.githubusercontent.com/84991444/152651967-3021b42e-eaf1-4749-a3a9-e043450c91c0.jpeg)
![1BE22DF7-2785-42EA-8A79-AA999A9F14AD](https://user-images.githubusercontent.com/84991444/152651969-5c0e07c1-0ee4-4a86-b099-286ca70d5d14.png)

### Steps To Reproduce

```markdown
1. Click “sign in”
2. Select “Microsoft account”
3. Click “continue” in the browser window
```

### Expected Behavior

I expect to click “continue” and to be promptly logged into my Microsoft account, and to be able to play the game.

### Platform

```markdown
- Device model: iPhone SE 2020
- iOS version: 14.2
- PojavLauncher version: dev 2.1~beta 1
```

**Comment by khanhduytran0** [comment]
The logging in progress is now moved to the title to prevent infinite loading. (The UIKit internal is a bit weird: it doesn’t allow dismissing a dialog while in transition)

**Comment by NoDa75** [comment]
So what does that mean for me?
