### ISSUE TITLE
[Bug] Crash when  load a world twice

### ISSUE THREAD

**Issue by M00nL355** [PojavLauncherTeam/PojavLauncher_iOS#317]
### Describe the bug

It can only run a new world(All version between 1.16.5 and 1.13)

### The log file and images/videos

https://user-images.githubusercontent.com/99098354/152828589-ed8bb910-6ea7-4e40-94c6-3d3c2db365f6.MOV

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher_iOS/files/8016913/latestlog.txt)
[crash-2022-02-07_16.07.30-server.txt](https://github.com/PojavLauncherTeam/PojavLauncher_iOS/files/8016915/crash-2022-02-07_16.07.30-server.txt)

### Steps To Reproduce

```markdown
1.Start PojavLauncher2.0
2.Select Account
3.Click Play
4.Loading a world already created
5.Crash
```

### Expected Behavior

Just fix it

### Platform

```markdown
- Device model: iPad Pro2018
- iOS version: 14.3
- PojavLauncher version: 2.0
```

**Comment by M00nL355** [comment]
Maybe unsupport Java8🤭

**Comment by khanhduytran0** [comment]
Try with Java 16/17 or try updating to v2.1 (dev). Also, check the installed JRE8 path.

**Comment by M00nL355** [comment]
> 

thank you,i switched to Java17 and it works well
