### ISSUE TITLE
[F-Req] Expect for better touch control

### ISSUE THREAD

**Issue by M00nL355** [PojavLauncherTeam/PojavLauncher_iOS#318]
### Describe the request.

Dear Developer:

Everyone who using touch control expect a highly customized touch control,That we can use 3,4 even more fingers.

I expect the customize page like PUBGM or CODM,hold and move to customize a button

Please improve custom control!
(and add the WA&WD button)

**Comment by khanhduytran0** [comment]
> That we can use 3,4 even more fingers.

Using multiple fingers while playing is possible.

> I expect the customize page like PUBGM or CODM,hold and move to customize a button

That’s why Custom Controls exists. Simply update to the latest v2.1 dev build, go to Custom Controls then stuff is here.
- Wanna make Bedrock-like swipeable direction? The `Swipeable` toggle is here.
- Wanna combine W+A or W+D? Multi-keys binding is already here.

![09176EBD-EFD5-4698-BD56-B85A6B2E5B35](https://user-images.githubusercontent.com/40482367/152975832-d6cb15d3-3bc7-412c-ab0c-893d663a6993.jpeg)
