### ISSUE TITLE
[Bug] Pojavlauncher2.1 Crash

### ISSUE THREAD

**Issue by M00nL355** [PojavLauncherTeam/PojavLauncher_iOS#320]
### Describe the bug

Start,then crash(beta2-beta5)

but Beta1 worked normally

### Steps To Reproduce

```markdown
1.Start Pojav
2.Crash
```

### Expected Behavior

i expect all version work

### Platform

```markdown
- Device model: iPadPro2018
- iOS version: 14.3
- PojavLauncher version: 2.1beta5
```

**Comment by Doregon** [comment]
If you are using unc0ver, this is a known issue. You say you're on 14.3 so I'd suggest switching to Taurine.

**Comment by M00nL355** [comment]
im using taurine1.1.1

**Comment by Doregon** [comment]
Send us crash logs. latestlog.txt if that's generated or go into Settings > Privacy > Analytics and Ads > Analytics Data > look for PojavLauncher-<time near when the crash happened>.ips

**Comment by M00nL355** [comment]
Nothing be generated

https://user-images.githubusercontent.com/99098354/153323479-8a4f11dd-07a9-4e30-a9eb-c2ded4e79925.MP4

**Comment by NoDa75** [comment]
I am also having this issue
Unc0ver iOS 14.2
iPhone SE 2020
