### ISSUE TITLE
[Bug] Crash when opening

### ISSUE THREAD

**Issue by critiqalfish** [PojavLauncherTeam/PojavLauncher_iOS#325]
### Describe the bug

When i open PojavLauncher it instantly crashes. Happens on versions 2.1 beta 2 - beta 6.
Works fine on beta 1. 

My device is Iphone X iOS 14.4 Taurine Jailbreak

There are no logs generated from PojavLauncher but i have the logs from cr4shed crash reporter. It seems to be an issue with the Alderis color picker library?

### The log file and images/videos

[Crash.txt](https://github.com/PojavLauncherTeam/PojavLauncher_iOS/files/8054441/Crash.txt)

### Steps To Reproduce

```markdown
Open pojavlauncher
```

### Expected Behavior

It should open normally without any crashes

### Platform

```markdown
- Device model: Iphone X
- iOS version: 14.4
- PojavLauncher version: 2.1 beta 2 to beta 6
```

**Comment by khanhduytran0** [comment]
This is now fixed on the latest build (Alderis is now only loaded when necessary)

**Comment by khanhduytran0** [comment]
It might not available in the repo yet, so download it [here](https://github.com/PojavLauncherTeam/PojavLauncher_iOS/actions).

**Comment by critiqalfish** [comment]
Ok thank you very much
