### ISSUE TITLE
[Bug] Custom Control be strange 

### ISSUE THREAD

**Issue by M00nL355** [PojavLauncherTeam/PojavLauncher_iOS#326]
### Describe the bug

by the title

### The log file and images/videos

![0EA19D94-A711-4478-8F9D-5E50AF6D7A38](https://user-images.githubusercontent.com/99098354/153739789-6bd92a24-7cb3-4d29-af9c-81113281eb74.jpeg)

### Steps To Reproduce

```markdown
1.Try to edit a btn
```

### Expected Behavior

i expect it return normal

### Platform

```markdown
- Device model: iPadPro2018
- iOS version: 14.3
- PojavLauncher version: dev2.1(beta7)
```

### Anything else?

and,please add a setting to disable gesture(hold or tap to mapping L/R mouse btn)🥺

**Comment by khanhduytran0** [comment]
@M00nL355 please check again in the latest dev build/

**Comment by M00nL355** [comment]
not fix yet(beta15)
