### ISSUE TITLE
[Bug] mouse broken on latest version

### ISSUE THREAD

**Issue by InfernoNova9999** [PojavLauncherTeam/PojavLauncher_iOS#329]
### Describe the bug

Mouse doesnt work on 1.18.1 (restart before launching is off and the virtual mouse option is on)

### The log file and images/videos

https://user-images.githubusercontent.com/70199277/155118922-fe28d439-433a-4b4e-a3bb-8e33c6cd7fd4.mov

### Steps To Reproduce

```markdown
Start 1.18.1
Mouse not working
```

### Expected Behavior

The mouse worked on the old versions now it broke

### Platform

```markdown
- Device model: iphone xr
- iOS version: 14.3
- PojavLauncher version: Version: https://github.com/PojavLauncherTeam/PojavLauncher_iOS/actions/runs/1879847708
```

**Comment by khanhduytran0** [comment]
As of commit 9ee414a4b0d07940f4ade9e6a2c801d23730612d, this should be fixed.
