### ISSUE TITLE
[Bug] Unable to login with Microsoft

### ISSUE THREAD

**Issue by McgahGuhmer** [PojavLauncherTeam/PojavLauncher_iOS#333]
### Describe the bug

When attempting to login with Microsoft it does nothing for a small amount of time then gives the following pop-up/error:
<PRE>
java.lang.RuntimeException: MSA Error: 504: Gateway Time-out, error stream:
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<HTML><HEAD><META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=iso-8859-1">
<TITLE>ERROR: The request could not be satisfied</TITLE>
</HEAD><BODY>
<H1>504 ERROR</H1>
<H2>The request could not be satisfied.</H2>
<HR noshade size="1px">
CloudFront attempted to establish a connection with the origin, but either the attempt failed or the origin closed the connection.
We can't connect to the server for this app or website at this time. There might be too much traffic or a configuration error. Try again later, or contact the app or website owner.
<BR clear="all">
If you provide content to customers through CloudFront, you can find steps to troubleshoot and help prevent this error by reviewing the CloudFront documentation.
<BR clear="all">
<HR noshade size="1px">
<PRE>
Generated by cloudfront (CloudFront)
Request ID: djOcUEZ3Q_rB7sN5vqqHk1lAil6wIuBiaKasFvYS7x__9VBq7osY0Q==
</PRE>
<ADDRESS>
</ADDRESS>
</BODY></HTML>
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.throwResponseError(Msa.java:304)
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.acquireMinecraftToken(Msa.java:212)
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.acquireXsts(Msa.java:175)
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.acquireXBLToken(Msa.java:130)
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.acquireAccessToken(Msa.java:83)
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.<init>(Msa.java:44)
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftAuthTask.run(MicrosoftAuthTask.java:39)
	at net.kdt.pojavlaunch.uikit.AccountJNI.loginAccount(AccountJNI.java:44)
</PRE>

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher_iOS/files/8263274/latestlog.txt)

### Steps To Reproduce

```markdown
1. Start PojavLauncher
2. Login with Microsoft
3. Wait
```

### Expected Behavior

I expect the game to log me in.

### Platform

```markdown
- Device model: iPad (6th Generation)
- iOS version: 14.6
- PojavLauncher version: 2.0
```

**Comment by NotAHero04** [comment]
There's currently an issue on Mojang authentication servers, wait for it to be fixed.

**Comment by khanhduytran0** [comment]
It is already fixed, closing.
