### ISSUE TITLE
[F-Req] <IPA Download>

### ISSUE THREAD

**Issue by TheBalkanDev** [PojavLauncherTeam/PojavLauncher_iOS#334]
### Is this request related to a bug?

No

### Describe the request.

Hi,

Please Release an IPA Version.
It would be helpful, because right now you need an Jailbroken iDevice to use this.
IPA Files are like APK Files. You can Install them through an Program called AltStore.

### Anything else?

No

**Comment by TheBalkanDev** [comment]
By jailbreaking you lose any warenty.

**Comment by Aerolome** [comment]
> By jailbreaking you lose any warenty.

Yes but you can recover to a non-jailbreaked state and then your warranty is recovered.

**Comment by DelofJ** [comment]
Hi, wanted to bring back the subject
You say that you can’t use AltStore because iOS does not support JIT
However AltStore will support AltJIT in the future releases, and it’s already available for beta users of AltStore
I think it would be a good idea to take an interest in AltStore, moreover PojavLauncher could have greater visibility knowing that the installation of applications via AltStore is much simpler

**Comment by artdeell** [comment]
> Hi, wanted to bring back the subject You say that you can’t use AltStore because iOS does not support JIT However AltStore will support AltJIT in the future releases, and it’s already available for beta users of AltStore I think it would be a good idea to take an interest in AltStore, moreover PojavLauncher could have greater visibility knowing that the installation of applications via AltStore is much simpler

@DelofJ The common thing is, about these "Jailbreak-less JIT" solutions, is that they allow a sort-of partial JIT - you can write instructions into a memory block and then switch it to be executable.
What Java requires is the ability to have memory pages be both writable and executable - which none of the Jailbreak-less JIT solutions seem to allow right now.

**Comment by DelofJ** [comment]
It’s sad, but it’s right that these alternatives are not complete than the jailbreak for JIT, I understand that for the moment PovajLauncher remains as a tweak for jailbroken devices, I hope there will be a full JIT  for iOS in the future
