### ISSUE TITLE
[F-Req] Can’t use openjdk in NewTerm or ssh.

### ISSUE THREAD

**Issue by Hi-hass** [PojavLauncherTeam/PojavLauncher_iOS#335]
### Describe the bug

Can’t use openjdk in NewTerm or ssh.

Error occurred during initialization of VM
Could not reserve enough space for code cache (245760K)

### The log file and images/videos

iPhone:~ root# /usr/lib/jvm/java-16-openjdk/bin/java
Error occurred during initialization of VM
Could not reserve enough space for code cache (245760K)

### Steps To Reproduce

```markdown
ldid -S /usr/lib/jvm/openjdk-xxx/bin/* (zsh:killed 9)

./java 

Error occurred during initialization of VM
Could not reserve enough space for code cache (245760K)
```

### Expected Behavior

No.

### Platform

```markdown
- Device model: iPhone5s
- iOS version: 12.5.5
- PojavLauncher version: 2.0
```

### Anything else?

How can i use openjdk to start spigot1.18.1 on iOS 12.5.5?

**Comment by khanhduytran0** [comment]
This is not a PojavLauncher issue.

> ldid -S /usr/lib/jvm/openjdk-xxx/bin/* (zsh:killed 9)

By re-signing, you broke the JIT entitlement.
