### ISSUE TITLE
[Question] Debian Package?

### ISSUE THREAD

**Issue by AM7999** [PojavLauncherTeam/PojavLauncher_iOS#337]
### Ask the question here.

I just have a short question about this release, why is it packaged into a debian package?

**Comment by khanhduytran0** [comment]
Pojav is currently only target jailbroken devices. With Jailbreak, you get a package manager (Cydia, Sileo, Zebra, etc..). All of these use dpkg to manage, which is similar to what you found on Debian/Ubuntu.

**Comment by AM7999** [comment]
Ah alright
