### ISSUE TITLE
Tôi không thể vào ứng dụng

### ISSUE THREAD

**Issue by Dai2k9hihipro** [PojavLauncherTeam/PojavLauncher_iOS#339]
### Describe the bug

https://youtu.be/kYdOg61yor4
2 video 

### The log file and images/videos

.

### Steps To Reproduce

```markdown
.
```

### Expected Behavior

.

### Platform

```markdown
- Device model: 
- iOS version: 12.5.5
- PojavLauncher version: 2.0
```

### Anything else?

.

**Comment by Dai2k9hihipro** [comment]
Hepmme

**Comment by khanhduytran0** [comment]
The information you provided is incomplete (video isn’t enough). However, there’s a common bug around JRE8. Try [this one](https://github.com/crystall1nedev/ios-apt-sync/blob/bigbadserver-3.0/debs/openjdk-8-jre_1.8.0%7E292b10-build14_iphoneos-arm.deb).

**Comment by Dai2k9hihipro** [comment]
Nó đã hoạt động

**Comment by Dai2k9hihipro** [comment]
Cảm ơn
