### ISSUE TITLE
PojavLauncher Crashes when opening it in Jailbroken iOS 13.5.1.

### ISSUE THREAD

**Issue by cuj** [PojavLauncherTeam/PojavLauncher_iOS#34]
Hi, I would like to try PojavLauncher for iOS (Minecraft Java in iOS), But I ran into an issue, when I try to start PojavLauncher in iOS, it crashes, Here's a video showing it crashes:

https://user-images.githubusercontent.com/66434686/107396789-24bd4f80-6b0f-11eb-8637-de0f14af5ea1.MP4

### How I Installed PojavLauncher for iOS:
1. Download OpenJDK deb from [Releases](https://github.com/PojavLauncherTeam/PojavLauncher_iOS/releases/tag/v16-openjdk) and install deb via filza
2. Download latest PojavLauncher deb from the latest run in [Actions](https://github.com/PojavLauncherTeam/PojavLauncher_iOS/actions) and install deb via filza
3. Respring iOS via cydia by (re)installing any tweak that requires a respring
4. Click icon and app crashes.
---
### iDevice info:
- iOS 13.5.1
- Jailbroken with checkra1n
- iPhone 7 Plus A1784 (iPhone9,2)
(please let me know if you need more info about the iDevice specs)

So can someone please tell me a solution? it would be greatly appreciated, thanks.

**Comment by khanhduytran0** [comment]
Can you check if file `/var/mobile/Documents/minecraft/latestlog.txt` exists and send it?

**Comment by cuj** [comment]
![IMG_0019](https://user-images.githubusercontent.com/66434686/107470077-e316be00-6b7b-11eb-83b6-c88e9b0d6e00.PNG)

**Comment by khanhduytran0** [comment]
- Did you enable network?
- Check Minecraft folder?

**Comment by cuj** [comment]
> Did you enable network?

yes, but my phone has some network issues, now I tried starting the app again, but with network on, but it crashes.

> Check Minecraft folder?

Minecraft folder has config_ver.txt, and latestlog.txt

**Comment by khanhduytran0** [comment]
Is this really the "latest build" you installed? https://github.com/PojavLauncherTeam/PojavLauncher_iOS/actions/runs/551286872

**Comment by cuj** [comment]
I used the [latest build](https://github.com/PojavLauncherTeam/PojavLauncher_iOS/actions/runs/553730583) of PojavLauncher since you just released it, but app crashed, latestlog.txt has the same thing.

**Comment by khanhduytran0** [comment]
Also, you respring instead of run uicache, that's might not good.

**Comment by cuj** [comment]
Right now I am having something else to do, so later I'm jailbreaking with Odyssey right now, and I'm going to install PojavLauncher in Jailbroken iOS, and I will say if it works or not.

**Comment by SuperKael** [comment]
I also have this exact same problem, with the same latestlog and everything.

**Comment by khanhduytran0** [comment]
Check if minecraft/versions/1.16.5/1.16.5.json exists?

**Comment by SuperKael** [comment]
There is no versions folder.

**Comment by cuj** [comment]
oh, I almost forgot about this, anyways, I tried opening pojavlauncher in my iPhone X (iPhone10,6) and I managed to, but when I select "Offline login" and then click play, when mc starts, app crashes.

**Comment by SuperKael** [comment]
I just realized, this latestlog file is not actually due to the app crashing. That log file was produced when I tried running the script in PojavLauncher.app, before realizing I needed to run UICache to make the app appear.

**Comment by SuperKael** [comment]
With regards to the actual crash, CrashReporter produces this:
https://pastebin.com/EZGgYcnu

**Comment by khanhduytran0** [comment]
You can't run ios app from command line directly 
Try https://github.com/PojavLauncherTeam/PojavLauncher_iOS/actions/runs/565855529

**Comment by SuperKael** [comment]
That build did not fix it. Still crashes immediately when trying to open it, before it even writes to latestlog.txt

**Comment by khanhduytran0** [comment]
Stills run the app from command line?

**Comment by SuperKael** [comment]
No. It crashes immediately when I try to run it from the Home Screen. I do see the new message when running it from command line, which is nice, but the real issue is the fact that it fails to run from the Home Screen.

**Comment by khanhduytran0** [comment]
Maybe try
```
uicache -u /Application/PojavLauncher.app
uicache -p /Application/PojavLauncher.app
```
Then try launch again

**Comment by SuperKael** [comment]
The commands wouldn’t run with /Application/PojavLauncher.app. After changing it to /Applications/PojavLauncher.app, the commands ran, but it still crashes immediately.

**Comment by khanhduytran0** [comment]
Does java itself even run?
Try exec `/usr/lib/jvm/java-16-openjdk/bin/java`

**Comment by SuperKael** [comment]
Running that command caused my terminal to reset, and nothing else. However, navigating to that location and executing Java using Filza caused it to print out help information.

**Comment by khanhduytran0** [comment]
Does /var/mobile/Documents/minecraft exists? Also what's inside if exists?

**Comment by SuperKael** [comment]
That folder appeared from my previous running it from the terminal. However, if I delete the folder and try to run the app from the Home Screen, the folder does not reappear.

**Comment by khanhduytran0** [comment]
It was the source of crash! The Debian package pre-create it, but you deleted.

**Comment by SuperKael** [comment]
Huh? No, I only deleted it a couple minutes ago to see if it would reappear...

**Comment by SuperKael** [comment]
There, I just removed the folder from trash and put it back. Still doesn’t work.

**Comment by khanhduytran0** [comment]
Anything inside latestlog.txt or not ever reach to?

**Comment by SuperKael** [comment]
Never reached it.

**Comment by khanhduytran0** [comment]
Try a clean install.

**Comment by khanhduytran0** [comment]
So, possibility the minecraft folder was no longer accessible by PojavLauncher, crashes at `fileno(“latestlog.txt”)`.

**Comment by nergzd723** [comment]
This is **not** iOS 13.5.1 specific, works fine on iPad Air 2 iOS 13.5.1.

**Comment by SuperKael** [comment]
After performing a complete uninstall and reinstall of openjdk and PojavLauncher, it actually works now! To be specific, I removed the two packages, deleted the “minecraft” and “.pojavlauncher” folders in Documents, then reinstalled them both. In particular, after installing PojavLauncher again, I performed uicache and then resprung in that order. Oh, and btw, I’m on iOS 14.3, so seemingly unrelated to iOS version.

**Comment by khanhduytran0** [comment]
So what about crash of @cuj ?

**Comment by cuj** [comment]
> So what about crash of @cuj ?

When I start PojavLauncher in my iPhone X (iPhone10,6), it starts, and I click on offline login and input any name (**test** is the username) and when I click on play, it downloads the minecraft and then crashes

**Comment by khanhduytran0** [comment]
Send latestlog.txt

**Comment by khanhduytran0** [comment]
Also try https://github.com/PojavLauncherTeam/PojavLauncher_iOS/actions/runs/567549911

**Comment by cuj** [comment]
> Send latestlog.txt



> Also try https://github.com/PojavLauncherTeam/PojavLauncher_iOS/actions/runs/567549911

I will do these things once I get home, right now I'm working.

**Comment by khanhduytran0** [comment]
@cuj so?

**Comment by cuj** [comment]
@khanhduytran0 I restored rootfs in my iphone x and then I rejailbreaked with unc0ver 6.0.0, now PojavLauncher is all fine.
