### ISSUE TITLE
Need help

### ISSUE THREAD

**Issue by Confirm1234** [PojavLauncherTeam/PojavLauncher_iOS#343]
### Ask the question here.

I have questions how can i download it, because it seems not work on iOS 15.5+
Ps: send me e-mail soon when you have time. Have a nice day!

**Comment by Aerolome** [comment]
ofc it doesn't, because there is no jailbreak for that version of ios, maybe wait on that update for a year or more and you will get a jailbreak

**Comment by crystall1nedev** [comment]
PojavLauncher on iOS requires a jailbreak, which isn't available on iOS 15 or 16.

**Comment by Confirm1234** [comment]
Thank you very much
________________________________
Lähettäjä: Eilionoir Tunnicliff ***@***.***>
Lähetetty: lauantai 18. kesäkuuta 2022 21.50
Vastaanottaja: PojavLauncherTeam/PojavLauncher_iOS ***@***.***>
Kopio: Ville Immonen ***@***.***>; Author ***@***.***>
Aihe: Re: [PojavLauncherTeam/PojavLauncher_iOS] Need help (Issue #343)


Closed #343<https://github.com/PojavLauncherTeam/PojavLauncher_iOS/issues/343> as completed.
