### ISSUE TITLE
Error on launching 1.19

### ISSUE THREAD

**Issue by Lilyp3892** [PojavLauncherTeam/PojavLauncher_iOS#344]
### Describe the bug

Pressing play for 1.19 will crash the game

### The log file and images/videos

[here](https://cdn.discordapp.com/attachments/840287822707556352/991884222610542632/latest.log)

### Steps To Reproduce

```markdown
1. Start pojav iOS 2.0.1
2. Select online account
4. Select java 17
5. Select tinygl4angle render
5. Restart launcher
6. Select online account
7. Select 1.19
8. Press play
9. Crash
```

### Expected Behavior

I expected the game to load up

### Platform

```markdown
- Device model: iPhone XR
- iOS version: 14.3
- PojavLauncher version: 2.0.1
```

**Comment by khanhduytran0** [comment]
The log is incomplete. Please get the full file.
Also, since the Steps To Reproduce didn’t include `Select tinygl4angle renderer`, I can assume that you’re missing this step.

**Comment by Lilyp3892** [comment]
> The log is incomplete. Please get the full file.
> 
> Also, since the Steps To Reproduce didn’t include `Select tinygl4angle renderer`, I can assume that you’re missing this step.

That was the full log unfortunately, I have the same issue no matter what render I use but I used tinygl4angle render and it still crashed I linked the log file in the edited issue

**Comment by Lilyp3892** [comment]
Being worked on in discord

**Comment by crystall1nedev** [comment]
Known issue, going to move to #184.
