### ISSUE TITLE
[Bug] <Crashes on play 1.19>

### ISSUE THREAD

**Issue by complicatednena** [PojavLauncherTeam/PojavLauncher_iOS#348]
### Describe the bug

Clicking on „Play“ results in a crash after a few seconds.

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher_iOS/files/9112516/latestlog.txt)

### Steps To Reproduce

```markdown
1. Start Pojavlauncher
2. click on play
```

### Expected Behavior

I expect the game to start.

### Platform

```markdown
- Device model: iPhone 11 Pro Max
- iOS version: 14.5.1
- PojavLauncher version: Latest Release
```

**Comment by Aerolome** [comment]
`java.lang.UnsatisfiedLinkError: /private/var/mobile/Containers/Data/Application/3DBFDF27-C854-471F-B220-3AAB10036C82/tmp/libjcocoa10713192283021722936.dylib: dlopen`

Something didn't open correctly it looks like, but I'm not even a beginner with iOS, so take this with a grain of salt.

**Comment by khanhduytran0** [comment]
The latest release does not support 1.19. Support for it is only available on dev builds for now, However, you might get some other issues that I’m not able to reproduce, let us know in case of it.

**Comment by complicatednena** [comment]
Thanks, I'll try it! :>
