### ISSUE TITLE
[Bug] pojavlauncher crashes (jre problem) 

### ISSUE THREAD

**Issue by mohamad1GW** [PojavLauncherTeam/PojavLauncher_iOS#349]
### Describe the bug

So, when ever I run pojav launcher it immediately crashes and generate a log file, I think it's a have runtime issue because it couldn't load a file (java-8-openjdk/lib/**libjli.dylib**) inside the Java runtime files and unbe able to find a command or something like that. And if asked me if I have the Java jre installed, the answer is yes, I already have it. I have no idea why that is happening. 

### The log file and images/videos

latestlog.txt:
[(https://pastebin.com/gGQM0Sr5)] 

### Steps To Reproduce

```markdown
1. Power my phone on
2. Open pojavlauncher
3. Craches immediately and getting the log file
```

### Expected Behavior

I expect the game to run normally like everyone else.

### Platform

```markdown
- Device model: iPhone 6
- iOS version: 12.5.5
- PojavLauncher version: latest release
```

### Anything else?

I hope someone can help me as fast as possible 🙂🙄

**Comment by crystall1nedev** [comment]
This is a known issue with OpenJDK 8 on iOS 12. Until we can fix this, use this workaround to use the launcher.

1. Install `openjdk-16-jre` or `openjdk-17-jre` from my repo.
2. Open `/usr/share/pojavlauncher/launcher_preferences.plist` in Filza File Manager.
3. In the `env_vars` section, change `java_home` to `/usr/lib/jvm/java-16-openjdk` or `/usr/lib/jvm/java-17-openjdk`, respectively.

Please note that due to the lack of OpenJDK 8, you will not be able to use anything requiring it.

**Comment by mohamad1GW** [comment]
> This is a known issue with OpenJDK 8 on iOS 12. Until we can fix this, use this workaround to use the launcher.
> 
> 1. Install `openjdk-16-jre` or `openjdk-17-jre` from my repo.
> 2. Open `/usr/share/pojavlauncher/launcher_preferences.plist` in Filza File Manager.
> 3. In the `env_vars` section, change `java_home` to `/usr/lib/jvm/java-16-openjdk` or `/usr/lib/jvm/java-17-openjdk`, respectively.
> 
> Please note that due to the lack of OpenJDK 8, you will not be able to use anything requiring it.

Hello @crystall1nedev, 
thank you for your support, the game actually worked using the Java 16 but it crashes if I choose the 17, I don't really care about the 17 so it's ok. I can run the game (minecraft) normally but when I do, the back ground of minecraft is black and white (no image) and when I open a world it crashes, I tried to understand the crash file but I didn't understand anything at all. BTW I tried running 1.7.10, 1.13.2 and 1.19, 1.19 required Java 17

Minecraft crash file: https://pastebin.com/zfcnSgWq
![IMG-20220717-WA0000](https://user-images.githubusercontent.com/86711244/179391690-f2f66172-1a09-40d0-a4f5-93e448a8541a.jpg)
