### ISSUE TITLE
Download Pojav

### ISSUE THREAD

**Issue by CondHub** [PojavLauncherTeam/PojavLauncher_iOS#353]
### Add some background

I can’t understand how to get Pojav Launcher on IOS. Can you write back to me how to get it? Thanks!

### Time to document.

I can’t understand how to get Pojav Launcher on IOS. Can you write back to me how to get it? Thanks!

**Comment by mohamad1GW** [comment]
Do you know what a jailbreak is? 
If yes then jailbreak your phone and take a look at [README.md](https://github.com/PojavLauncherTeam/PojavLauncher_iOS#readme)
If no, then search at Google what is a jailbreak on ios

**Comment by Jeysonale** [comment]
Hola soy nuevo  anhelo descargar Pojavlauncher , ayúdenme porfavor  puede que tengan su recompensa por esto , no soy tan rico pero puedo darles una pequeña recompensa :3

**Comment by crystall1nedev** [comment]
Closing this issue as it can be solved by simply reading the README.
