### ISSUE TITLE
[F-Req/Question] AltStore support?

### ISSUE THREAD

**Issue by naturecodevoid** [PojavLauncherTeam/PojavLauncher_iOS#355]
### Is this request related to a bug?

No.

### Describe the request.

I’m wondering if there are any plans to support [AltStore](https://altstore.io/). It could allow for installing pojav on non-jailbroken devices. This could be achieved in multiple ways:

- Custom sources; someone (maybe me) can host a json file on a website that allows users to easily install it.
- Extracting the .deb and adding the .app manually? I don’t know if this will work, I will experiment when I have the time.

**Comment by naturecodevoid** [comment]
accidentally opened it 😅

**Comment by naturecodevoid** [comment]
After a little inspection I think it could work. The only problem is where Pojav stores it’s data. To work with AltStore it would need to store everything at the On My iPhone directory.

**Comment by naturecodevoid** [comment]
I was able to add the app to my home screen after packaging the .app as an .ipa, adding a CFBundleIdentifier to the frameworks without one and resigning all the .framework folders with my own identifier. Unsurprisingly it crashes upon launching.

**Comment by crystall1nedev** [comment]
Plans are already in place to do this, and we are aware of what we need to do in order to get PojavLauncher working unjailbroken.
