### ISSUE TITLE
Can’t use openjdk in NewTerm

### ISSUE THREAD

**Issue by timof121** [PojavLauncherTeam/PojavLauncher_iOS#36]
Hello. I tried installing optifine and fabric, but when i try tu use openjdk (java) it gives me a “permission denied” error. I tried running as su (root) but the same thing happens. I have iPad Mini 2 and jailbroken ios 12.4.8 with uncover jailbreak. Also i use NewTerm. Heres the error

`iPad:/var/mobile root# /usr/lib/jvm/java-16-openjdk/bin/java -jar
                                                                
sh: /usr/lib/jvm/java-16-openjdk/bin/java: Permission denied`

**Comment by khanhduytran0** [comment]
What about chmod first?

**Comment by timof121** [comment]
oh.

**Comment by timof121** [comment]
Well now it auto kills it

**Comment by khanhduytran0** [comment]
So what it does then?

**Comment by timof121** [comment]
nothing

**Comment by timof121** [comment]
When i try to run somethting with it, or even use -version it says “Killed: 9”

**Comment by timof121** [comment]
Sorry for this. It was probably a RAM issue bc my ipad 1gb RAM and now it started working properly.
