### ISSUE TITLE
[Question] <How do I get open-jdk 17 for the altsore?>

### ISSUE THREAD

**Issue by KozmikNano** [PojavLauncherTeam/PojavLauncher_iOS#361]
### Ask the question here.

I am using a iPhone 13 mini running iOS 16 so I can’t jailbreak my phone. Instead I use alt store. How do I install open jdk in it so then I can play 1.19?

**Comment by crystall1nedev** [comment]
OpenJDK 17 is not currently supported unjailbroken.
