### ISSUE TITLE
Minecraft won't start 

### ISSUE THREAD

**Issue by Chebyrek180808** [PojavLauncherTeam/PojavLauncher_iOS#362]
### Describe the bug

I see only black screen when i'm trying to start minecraft 

### Steps To Reproduce

```markdown
1.Start pojavlauncher
2.Click play
3. Choose version (I tried to run 1.16.5)
4. End
```

### Expected Behavior

I clicked play and see only black screen 

### Platform

```markdown
- Device model: Ipad 2021 256gb (iPad 9 gen)
- iOS version: 15.6
- PojavLauncher version: latest release
```

### Anything else?

I used altstore to run pojavlauncher

**Comment by Gamr13** [comment]
If you're trying to boot the game without a jailbreak you **MUST** use AltJIT via AltServer OR JIT Streamer. 

You'll also need to use Minecraft 1.16.5 or below for now (IIRC)

**Comment by Chebyrek180808** [comment]
I tried to run Minecraft 1.16.5, and I used altstore

**Comment by Gamr13** [comment]
Did you enable JIT via AltServer manually, or use JIT Streamer to launch the app?

**Comment by Chebyrek180808** [comment]
no, I'll try now

**Comment by Chebyrek180808** [comment]
no, I'll try now

**Comment by Gamr13** [comment]
Grand. You absolutely must do this every time you launch PojavLauncher, as without JIT you'll only see a black screen on non-jailbroken devices.

**Comment by Chebyrek180808** [comment]
yes it worked, thanks, minecraft loading screen appeared

**Comment by Chebyrek180808** [comment]
yes it worked, thanks, minecraft loading screen appeared

**Comment by Gamr13** [comment]
Great! Could you please close this issue?
