### ISSUE TITLE
A few updates:

### ISSUE THREAD

**Issue by msharitoktik** [PojavLauncherTeam/PojavLauncher_iOS#363]
A few updates:

- **Java W^X now working!** Enjoy Minecraft to the fullest with way better performance.
- **Reintroducing... RAM slider!** If you dare... you can now set your memory limit to 40%.
  - We're working on bringing even more memory to supported devices.

_Originally posted by @crystall1nedev in https://github.com/PojavLauncherTeam/PojavLauncher_iOS/issues/359#issuecomment-1212798640_

**Comment by c4scdev** [comment]
Please, learn on how to use GitHub :)
This platform is not suitable for children aged 13 and below-

**Comment by crystall1nedev** [comment]
Closing issue as it’s literally copied from mine.

**Comment by msharitoktik** [comment]
I passed the real king lite file net.kdt.pojavlauncher-INT.ipa do you have
a download link
