### ISSUE TITLE
[Question] <Short description>

### ISSUE THREAD

**Issue by haya4422** [PojavLauncherTeam/PojavLauncher_iOS#366]
### Ask the question here.

kouzaka.hayaki.1.16@icloud.com

**Comment by haya4422** [comment]
Create a report to help us sqaush bugs. If this doesn’t look right, [choose a different type.](https://github.com/PojavLauncherTeam/PojavLauncher_iOS/issues/new/choose)

**Comment by crystall1nedev** [comment]
mfw stop
