### ISSUE TITLE
Offline login requires username > 3 characters long 

### ISSUE THREAD

**Issue by asdfugil** [PojavLauncherTeam/PojavLauncher_iOS#37]
Minecraft usernames could be 1-2 characters long, it is just impossible to create these accounts anymore. I don't see why offline login need to have this length restriction.

**Comment by khanhduytran0** [comment]
I followed [Minecraft username requirements](https://help.minecraft.net/hc/en-us/articles/360034636712-Minecraft-Usernames), so you should set name in range of 3-16 characters, or joining server will gives error.
![32355B39-A691-44C2-B4A2-DC530AC1F910](https://user-images.githubusercontent.com/40482367/107768736-80831500-6d69-11eb-8a51-75726b5af141.png)
