### ISSUE TITLE
Website link leads to scams/ads

### ISSUE THREAD

**Issue by Heath123** [PojavLauncherTeam/PojavLauncher_iOS#371]
### Describe the bug

The https://pojav.ml/ link now leads to a redirect that will go to various scam sites, betting sites and 18+ sites.

### The log file and images/videos

![F1D5DBFF-BA72-422A-AB08-C1E55D737ED0](https://user-images.githubusercontent.com/13787163/186014712-4fb3eb3a-b3a2-458d-b3a1-951800752ab9.png)

It’s in Greek because I’m on holiday in Cyprus, but it looks like a betting site

### Steps To Reproduce

```markdown
1. Click the link in the README
2. See a sketchy site
```

### Expected Behavior

I expect to go to the actual site.

### Platform

```markdown
N/A
```

### Anything else?

This is a scam where the domain provider (Freenom) will give you a “free domain”, then when you get enough traffic they redirect it to one of these sites and try to get money from you to put it back. Please don’t use a free domain if possible.

**Comment by MrZomka** [comment]
If you want to get a domain for cheap. Just get an .xyz domain from Porkbun, it's a great domain registrar and I use it myself. Just make sure you use code `AWESOMENESS` 😎

**Comment by MrZomka** [comment]
_oh god it sounds like an ad lol_

**Comment by crystall1nedev** [comment]
*sigh* On it.

**Comment by oaddyk** [comment]
> _sigh_ On it.

Any updates?

**Comment by crystall1nedev** [comment]
Fixed
