### ISSUE TITLE
sodium is broken with 1.17+ in pojavlauncher

### ISSUE THREAD

**Issue by Juncer2021** [PojavLauncherTeam/PojavLauncher_iOS#372]
### Describe the bug

When I use sodium mod in 1.17.1,my game flashback as soon as I enter the game.Sodium needs OpenGl3.3 and higher,but pojavluancher now only support OpenGl3.2 to render the game,which leads to the crash.

### Steps To Reproduce

```markdown
1.start pojavlauncher
2.enter the game 
3.enter my save
4.the game flashback
```

### Expected Behavior

I hope pojavlauncher can use a higher version render(OpenGl3.3 or higher) or give a proper solution to load the sodium.Thanks!

### Platform

```markdown
- Device model:ipad9 
- iOS version:ipados 15.6.1
- PojavLauncher version: pojavlauncher-2.1beta
```

### Anything else?

nothing

**Comment by crystall1nedev** [comment]
Known issue, currently cannot fix.
