### ISSUE TITLE
[Bug] <Short description>

### ISSUE THREAD

**Issue by 03052019Sevgilin** [PojavLauncherTeam/PojavLauncher_iOS#374]
### Describe the bug

My device is not jailbroken and I downloaded pojavlauncher with altstore and selected 1.16.5 and pressed play, it crashes immediately after starting please help. By the way, I open the application with JitStreamer

### Steps To Reproduce

```markdown
1. Start Pojavlauncher with JitStreamer
2. Press play button 
3. Crash the game
```

### Expected Behavior

Please help me.

### Platform

```markdown
- Device model: İPad Air 3 (Wi-Fi)
- iOS version: 1.16
- PojavLauncher version: 2.1
```

**Comment by crystall1nedev** [comment]
You did not provide log files. Closing this issue until you do.
