### ISSUE TITLE
Game Crashes upon open

### ISSUE THREAD

**Issue by DatBoyMax** [PojavLauncherTeam/PojavLauncher_iOS#375]
### Describe the bug

Everytime minecraft starts, it will show the hud for a second, then crash

### The log file and images/videos

[latestlog.old.txt](https://github.com/PojavLauncherTeam/PojavLauncher_iOS/files/9440303/latestlog.old.txt)
[text.txt](https://github.com/PojavLauncherTeam/PojavLauncher_iOS/files/9440304/text.txt)

### Steps To Reproduce

```markdown
Start any version
```

### Expected Behavior

I expected the game to load

### Platform

```markdown
- Device model: iPhone 7
- iOS version: 15.5
- PojavLauncher version: Latest version
```

**Comment by crystall1nedev** [comment]
Update to the latest commit and try again.

**Comment by popoods** [comment]
it crashes for me as well i updated it to latest and it still crashes

**Comment by crystall1nedev** [comment]
Unable to reproduce, make sure you use the latest commits and enable JIT.
