### ISSUE TITLE
"Toggle" option dont work?

### ISSUE THREAD

**Issue by Geskawary234** [PojavLauncherTeam/PojavLauncher_iOS#378]
### Ask the question here.

"Toggle" option dont work? I tried to make a custom gui and when i edited "sneak" button i turned on "toggle" setting and it dont do anything.

**Comment by Aerolome** [comment]
> ### Ask the question here.
> 
> "Toggle" option dont work? I tried to make a custom gui and when i edited "sneak" button i turned on "toggle" setting and it dont do anything.

have you saved the controlmap and leaved the editor? also what does "doesnt do anything" mean?

**Comment by khanhduytran0** [comment]
This option is under construction, will be implemented soon.

**Comment by Geskawary234** [comment]
> > ### Ask the question here.
> > "Toggle" option dont work? I tried to make a custom gui and when i edited "sneak" button i turned on "toggle" setting and it dont do anything.
> 
> have you saved the controlmap and leaved the editor? also what does "doesnt do anything" mean?
Sorry i am not eng, i mean nothing changed. And yeah i saved the control scheme and set it as default
