### ISSUE TITLE
zh_cn translate

### ISSUE THREAD

**Issue by root-S7** [PojavLauncherTeam/PojavLauncher_iOS#379]
### Describe the request.

add zh_cn translate
[Localizable.zip](https://github.com/PojavLauncherTeam/PojavLauncher_iOS/files/9540392/Localizable.zip)

**Comment by khanhduytran0** [comment]
I have set up Crowdin integration that you can translate there.
Please go to https://crowdin.com/project/pojavlauncher. Thank you.
