### ISSUE TITLE
the controller is not working correctly

### ISSUE THREAD

**Issue by gysok1337** [PojavLauncherTeam/PojavLauncher_iOS#382]
### Describe the bug

I can't rotate the camera, open the settings, switch slots in the inventory and change the control settings of the controller

### The log file and images/videos

https://user-images.githubusercontent.com/88579750/189501955-fe9a06db-3f2c-4e62-8b57-d37edcc1afa0.mov 

### Steps To Reproduce

```markdown
when I turn the left stick, nothing happens. When I turn the right stick I walk
```

### Expected Behavior

should work fine

### Platform

```markdown
- Device model: iPhone11
- iOS version: 15.1
- PojavLauncher version: latest version
- Controller: DualShock 4
```

### Anything else?

to connect the controller, I use the MidnightControls mod

**Comment by khanhduytran0** [comment]
Controller input support is currently incomplete due to me not having one to work with.
For now, gamepad keys are mapped to keyboard keys, causing controller mods to not able to recognize controller keys at all. A switch might be added to toggle between those later.

**Comment by khanhduytran0** [comment]
Controller support is complete, it’s handled by launcher itself, so you don’t need to install controller mod.
