### ISSUE TITLE
[Bug] <Short description>

### ISSUE THREAD

**Issue by owenthehugger** [PojavLauncherTeam/PojavLauncher_iOS#383]
### Describe the bug

Black screen when launching the game. iPad Air 4, IOS 15.6.1 

### The log file and images/videos

![200AD44E-BF2D-40A3-B8F3-87146C6AAB88](https://user-images.githubusercontent.com/73128784/190026870-903fcc9b-b4e4-43ef-8dfc-a30a0805df92.png)

### Steps To Reproduce

```markdown
1. Start PojavLauncher 
2. Launch any version
```

### Expected Behavior

Black screen

### Platform

```markdown
- Device model: iPad Air 4
- iOS version: 15.6.1
- PojavLauncher version: 2.1
```

**Comment by Aerolome** [comment]
have you downloaded the latest ipa file? are you using trollstore or altstore? have you installed and enabled jitstreamer?

**Comment by crystall1nedev** [comment]
This looks like an issue of JIT not being enabled, and as such the game never starts or crashes immediately. Update to the latest build and try again.
