### ISSUE TITLE
[Bug] iOS Controller Mapping Issue

### ISSUE THREAD

**Issue by Blockbuster-MC** [PojavLauncherTeam/PojavLauncher_iOS#385]
### Describe the bug

I have everything installed on my iphone 12 pro max and am using a razer kishi with it.  Everything works on the kishi except the left thumbstick doesnt change where my view is, only touching and dragging on the screen itself will do that. 

Is that intentional?

literally every other button works, i can jump, punch, open my inventory, crouch, etc, i just cant use the left tumbstick to control where it is im looking in game.  Nonetheless i am severely impressed at how well it works without the controller, however, i hate playing on my iphone without a controller.

### Steps To Reproduce

```markdown
Start the game.
```

### Expected Behavior

for the left thumbstick of the Razer Kishi directly attached controller on my iPhone to move the view of the where the player is looking.

### Platform

```markdown
- Device model: iphone 12 pro max
- iOS version: 15.6.1
- PojavLauncher version: 2.1
```

**Comment by khanhduytran0** [comment]
Controller input is untested as I don’t have one to do so. Anyways, I have made some changes to map left thumbstick to camera/virtual mouse movement, however speed is unknown.

**Comment by Blockbuster-MC** [comment]
> 

ill take a look at this today, been super busy with work lol

**Comment by Blockbuster-MC** [comment]
I just installed build #526

Left thumbstick now "works" where as before, moving it did nothing. If there is any way i can be of more help diagnosing this with you as you dont have a controller to test please let me know and i can make myself available.

**Feedback Specific to Camera View:**

1. Speed, is very very very slow (unplayable) as you mentioned that speed would be unknown.  
2. Holding the thumbstick steady in one direction doesn't continually send the input, it will go that direction once but that is it, you have to "rock" the thumbstick slightly to get it to keep going in that direction if that makes sense. I guess another way for me to word it is if you were holding down W on a keyboard to go forward you would go forward 1 block and not continually forward while holding down W.
3. If you could allow for the Up / Down to be toggleable somehow so it can be not inverted that would be great.  Currently Up makes you look down and pushing down gets you to look up.

Request - I 99% of the time have played MC on keyboard and mouse since like beta 1.6 so i apologize for not really realizing this earlier.  I only recently used it for the "bedrock" version to play with my nieces and nephews in the beginning of the summer, but haven't touched it since then.  I just redownloaded the iOS version of MC and instantly realized that the mapping of the left and right thumbsticks are backwards which is probably why it felt weird when I first started to test the pojav launcher.

To clarify what I meant by opposite, on the iOS app version of MC and all Bedrock Versions that use a controller like Switch Xbox, etc, the Left Thumbstick makes your player move:
Up = Forward
Down = Backward
Left = Left Sidestep
Right = Right Sidestep

And the right thumbstick is the "camera or crosshair" where:
Right = Right
Left = Left
Up = Up
Down = Down

If it would be possible to flip flop them to match how Minecraft works on controller based devices that would be great.

**Feedback Specific To Movement:**
While testing out the above and then comparing it to the bedrock version, I noticed that the movement doesn't seem to take into consideration the "exact" location of the thumbstick direction.   What I mean by that is it appears to only take into consideration 1 of 8 directions and will default to whatever you are closest too.  Meaning if I push Up (North) it will move forward, if I move slightly to the left while pushing up it will still go up until I hit the North West threshold and then it will move on that exact diagonal.  If I keep rotating the stick to the left it will eventually go West once I've broken the NW threshold and am moving for West than NW.  I hope that makes sense/helps.

**Comment by khanhduytran0** [comment]
Current code is missing ticking, I will look at it

> the movement doesn't seem to take into consideration the "exact" location of the thumbstick direction. What I mean by that is it appears to only take into consideration 1 of 8 directions

Keep in mind that Minecraft Java doesn’t support controller natively. It takes WASD input instead of joystick angle and handle strength, so neither 360° movement nor custom walking speed (for example, walk slowly without sneaking or sprint without additional keys) are available.

**Comment by Blockbuster-MC** [comment]
You're completely right. I completely forgot that java, for some reason still doesn't natively support controller input.

The only reason I even want it is so I can more efficiently do things when putting my kids down for naps or while I'm sitting on the train for work.

If you could implement the ticking and I guess increase the speed a bit that would be more than sufficient enough to get the job done.

Oh and also if it's possible to flip the joystick mapping so left would be WASD and Right would be camera and make it so the camera wasn't inverted or an option to toggle that I would be internally grateful.

Thanks again for your quick response.

**Comment by Blockbuster-MC** [comment]
Has there been any updates to this that I can test?

**Comment by khanhduytran0** [comment]
Thumbstick is swapped and have ticking configured. However, speed is again unknown to fit (a bit too fast?). I tried it only with a virtual joystick.

**Comment by Blockbuster-MC** [comment]
I'll test it shortly and report back findings.

**Comment by Blockbuster-MC** [comment]
@khanhduytran0 Works great and is definitely playable. If there was a way to manually edit the sensitivity level on our own for the camera that would be great as it is still very fast.

The video is me holding right and left at 100%

https://user-images.githubusercontent.com/113774055/194461986-ea03e7d6-8c3f-43ff-8ad6-ec30498692f9.mov

**Comment by khanhduytran0** [comment]
The sensitivity slider in game control settings should be what you’re looking for.

**Comment by khanhduytran0** [comment]
Virtual mouse speed can be changed in launcher settings.
Camera movement speed can be changed in game `mouse sensitivity` settings.

If you have any other problems, please open a new issue.
