### ISSUE TITLE
[Question] Pojavlauncher keeps deleting all the game version I install at midnight everyday is this a bug? How do I stop it from deleting the versions

### ISSUE THREAD

**Issue by Zamperplayz** [PojavLauncherTeam/PojavLauncher_iOS#386]
### Ask the question here.

Pojav launcher is deleting the game versions everyday i don't know it this is a feature or a bug. How do I prevent this from happening

**Comment by CasVeux** [comment]
If you have just updated PojavLauncher now, we have made some changes (that i (me) forgot to put into the news page.)

- If your Android Operating System version is above 10 (10+, or 10, 11, 12, 13), **the new directory is `Android/data/net.kdt.pojavlaunch`.debug (if you installed an "Actions" build)`/files`.

Uninstalling PojavLauncher **before the change in launcher directory does not delete `/games/PojavLauncher`.**
Uninstalling PojavLauncher after this change **does delete it's directory**, but in some heavily modified AOSP, **there's an option to tick if you want to keep the data directory.**

**Comment by CasVeux** [comment]
Wait sorry. I thought this is the Android repository.

**Comment by LolekLiam** [comment]
close issue
