### ISSUE TITLE
[Bug] Why does the pojav launcher crash when I use jit to start it????

### ISSUE THREAD

**Issue by sunsetRL** [PojavLauncherTeam/PojavLauncher_iOS#388]
### Describe the bug

I crashed after starting pojavLauncher with jit
And the pojav version I downloaded is the latest submission
I have to use the previous version to start normally

### The log file and images/videos

https://user-images.githubusercontent.com/92244300/192781270-8d7d687b-861c-4a13-b294-4eb385b036fb.MOV

### Steps To Reproduce

```markdown
1.I started it with jit
2.Jumped to pojav（is Latest submission）
3.It broke down
```

### Expected Behavior

I hope I can use jit to play games normally

### Platform

```markdown
- Device model: ipad mini 5
- iOS version: 15.2
- PojavLauncher version: Latest Release
```

**Comment by Aerolome** [comment]
send latestlog.txt

**Comment by sunsetRL** [comment]
No,I use Jitterbug

**Comment by sunsetRL** [comment]
> > No,I use Jitterbug
> 
> although jitterbug should work, try using jitstreamer

ok…

**Comment by khanhduytran0** [comment]
@sunsetRL fixed Jitterbug compatibility issue. you may also use TrollStore, which is super easy [to install](https://github.com/opa334/TrollStore#installing-trollstore-no-jailbreak) and have PojavLauncher work with self-JIT enabled.

**Comment by sunsetRL** [comment]
> @sunsetRL fixed Jitterbug compatibility issue. you may also use TrollStore, which is super easy [to install](https://github.com/opa334/TrollStore#installing-trollstore-no-jailbreak) and have PojavLauncher work with self-JIT enabled.

Thanks for your reminder. Now it can run successfully
