### ISSUE TITLE
pojavlauncher crashes wen i lunch the version

### ISSUE THREAD

**Issue by Doh723** [PojavLauncherTeam/PojavLauncher_iOS#389]
### Describe the bug

,,

### Steps To Reproduce

```markdown
start pojavlauncher
open any Minecraft version
its open Hud for ascend and then crash
```

### Expected Behavior

,

### Platform

```markdown
- Device model: iPhone 6s plus
- iOS version: 15.4.1
- PojavLauncher version: 2.1
```

### Anything else?

,

**Comment by Aerolome** [comment]
2.1 is super old. Just use TrollStore and the latest IPA builds from GitHub Actions on this repo instead. Make sure to also download and install JITStreamer along with Pojav.

**Comment by khanhduytran0** [comment]
@Doh723 [TrollStore installation](https://github.com/opa334/TrollStore#installing-trollstore-no-jailbreak)
It’s super easy nowadays as you just install it from Safari.
