### ISSUE TITLE
[Bug] Minecraft crashes on startup

### ISSUE THREAD

**Issue by amytwe** [PojavLauncherTeam/PojavLauncher_iOS#391]
### Describe the bug

Launch minecraft crash

### The log file and images/videos

[latestlog.old.txt](https://github.com/PojavLauncherTeam/PojavLauncher_iOS/files/9691758/latestlog.old.txt)

### Steps To Reproduce

```markdown
1.Start Pojavlauncher
2.Start Minecraft
3.Game crashed.
```

### Expected Behavior

I want the game to start.

### Platform

```markdown
- Device model: IPhone 6s
- iOS version:14.2 （jaibroken） 
- PojavLauncher version: Latest Release
```

**Comment by khanhduytran0** [comment]
Deb package is going to be deprecated soon, please use [TrollStore](https://github.com/opa334/TrollStore) to install, then Minecraft should launch.
