### ISSUE TITLE
Pojavlauncher crashed when i started game

### ISSUE THREAD

**Issue by faiz36** [PojavLauncherTeam/PojavLauncher_iOS#392]
### Describe the bug

Pojavlauncher is crashed when i started the game

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher_iOS/files/9692535/latestlog.txt)

### Steps To Reproduce

```markdown
1. Start the game
2. Crashed
```

### Expected Behavior

idk ):

### Platform

```markdown
- Device model: iPhone 8
- iOS version: 16.0.2
- PojavLauncher version: 2.1
```

**Comment by Aerolome** [comment]
check Actions, not Releases.

**Comment by faiz36** [comment]
i used action XD

**Comment by faiz36** [comment]
i used this action
https://github.com/PojavLauncherTeam/PojavLauncher_iOS/actions/runs/3123945396

**Comment by Aerolome** [comment]
make sure to update and also, make sure you have jitstreamer installed and enabled before you start up pojav

**Comment by faiz36** [comment]
yup i enabled jit with altstore

**Comment by faiz36** [comment]
i will update now

**Comment by Aerolome** [comment]
your game did nothing and acted as if jit was not enabled, so you try stuff and see

**Comment by faiz36** [comment]
what stuff

**Comment by Aerolome** [comment]
> what stuff

like jitstreamer instead of altjit for example

**Comment by faiz36** [comment]
okay i will

**Comment by faiz36** [comment]
ohhhhhhh it worked thx!
