### ISSUE TITLE
[Bug] Black screen on launch

### ISSUE THREAD

**Issue by 4193883-eng** [PojavLauncherTeam/PojavLauncher_iOS#393]
### Describe the bug

Black screen on launch.

### The log file and images/videos

![IMG_3024](https://user-images.githubusercontent.com/83756034/194018092-3412242e-5078-42ee-8573-ee22a1059de6.png)

### Steps To Reproduce

```markdown
1. Install pojav launcher through altserver
2. Enable JIT via altserver
3. Install minecraft 1.19.2
4. Start it
```

### Expected Behavior

I expect it to launch

### Platform

```markdown
- Device model: iPad Air 4
- iOS version: 15.6
- PojavLauncher version: 2.1 debug
```

**Comment by root-S7** [comment]
长时间黑屏就是没jit权限，你肯定没获取成功

**Comment by Gaming32** [comment]
The same happens to me without JIT. I also used AltStore/AltServer.

**Comment by khanhduytran0** [comment]
Without log, we can’t know what’s happening.
Please try alternatives like JitStreamer.

**Comment by Gaming32** [comment]
How do I get logs?

**Comment by 4193883-eng** [comment]
It already works, thanks!

**Comment by Gaming32** [comment]
Wait, do you need JIT enabled to use Pojav?

**Comment by Beast9265** [comment]
yes?

**Comment by Gaming32** [comment]
Oh
