### ISSUE TITLE
Question(s)

### ISSUE THREAD

**Issue by Fireworkstars46** [PojavLauncherTeam/PojavLauncher_iOS#394]
Can I get it on iOS without jailbreak?

**Comment by Aerolome** [comment]
yep, trollstore or altstore with jitstreamer

**Comment by crystall1nedev** [comment]
Please read what is written on literally the first page you see when entering this repository.

**Comment by Fireworkstars46** [comment]
I have iPhone 8 Plus on iOS 16 and windows pc
