### ISSUE TITLE
[Bug] PojavLauncher crashes on unjailbroken device

### ISSUE THREAD

**Issue by maksg** [PojavLauncherTeam/PojavLauncher_iOS#395]
### Describe the bug

After update for TrollStore the app crashes when launching from Jitterbug. It doesn't crash when launching normally from home screen.

The commit which causes the crash is this: https://github.com/PojavLauncherTeam/PojavLauncher_iOS/commit/ccaa9416f182dad0bc26832cbec85b799ae47dad

It worked without issue in earlier versions.

### Steps To Reproduce

```markdown
1. Download ipa from Actions.
2. Sideload it to an unjailbroken device (using Sideloadly for example).
3. Launch Jitterbug and select PojavLauncher.
4. Instant crash.
```

### Expected Behavior

It should not crash.

### Platform

```markdown
- Device model: iPhone 14 Pro Max (also 13 Pro Max)
- iOS version: 16.1 (also 16.0)
- PojavLauncher version: Latest Release
```

**Comment by khanhduytran0** [comment]
As the commit you pointed says `self-JIT support`, did you notice it? :eyes: By that means PojavLauncher installed with TrollStore can enable JIT by itself, therefore JIT enabler isn't necessary. It's plug-and-play.

**Comment by khanhduytran0** [comment]
Alright I missed the point at iOS version. I'd recommend you to use JitStreamer.

**Comment by maksg** [comment]
Thanks for the recommendation but in my case Jitterbug also gives me the same VPN plug-and-play experience and is simpler to use.

Anyway your commit did fix the crash so thank you!

Also I think this is actually the same issue as in #388 so that should also be now fixed.
