### ISSUE TITLE
[Bug] I can't choose another slot from the controller

### ISSUE THREAD

**Issue by gysok1337** [PojavLauncherTeam/PojavLauncher_iOS#397]
### Describe the bug

The L1 and R1 buttons do not switch slots

### Steps To Reproduce

```markdown
I press the L1 or R1 button on the controller
```

### Expected Behavior

the L1 and R1 buttons should switch slots

### Platform

```markdown
- Device model: iPhone 11
- iOS version: 15.1
- PojavLauncher version: Latest
- Controller: DualShock 4
```

**Comment by khanhduytran0** [comment]
Could you check if those buttons scroll or do nothing?

**Comment by gysok1337** [comment]
they do the same thing as L2, R2 (pcm, lcm)

**Comment by BigBoiMan123** [comment]
Same behaviour on an Xbox One Controller.

**Comment by khanhduytran0** [comment]
Got it. A fix will be pushed shortly.
