### ISSUE TITLE
[Bug] Black Screen On Launch

### ISSUE THREAD

**Issue by HockeyGamr** [PojavLauncherTeam/PojavLauncher_iOS#398]
### Describe the bug

When I try to to click “play” on pojavlauncher I am greeted with a black screen that doesn’t go away. How to fix this?

### The log file and images/videos

[latestlog.old.txt](https://github.com/PojavLauncherTeam/PojavLauncher_iOS/files/9769120/latestlog.old.txt)

### Steps To Reproduce

```markdown
1. Start Pojavlauncher
2. Click play
3. Black screen appears
```

### Expected Behavior

I expect the game to load 

### Platform

```markdown
- Device model: IPhone 14
- iOS version: Ios 16.01
- PojavLauncher version: 2.1
```

**Comment by khanhduytran0** [comment]
JIT is required for Java to work, as you didn’t mention about it, [more info](https://github.com/PojavLauncherTeam/PojavLauncher_iOS#without-jailbreak-sideload-as-ipa).

**Comment by HockeyGamr** [comment]
I had not enabled.
