### ISSUE TITLE
[Bug] Crashes when using Sodium with Fabric Loader

### ISSUE THREAD

**Issue by korboybeats** [PojavLauncherTeam/PojavLauncher_iOS#399]
### Describe the bug

I've installed both the latest Fabric Loader and Sodium mod, but when I try to enter a world, the game crashes.

### Steps To Reproduce

```markdown
Load into world with Sodium mod in Fabric
```

### Expected Behavior

I expect to load in the game successfully with Sodium.

### Platform

```markdown
- Device model: M1 iPad Pro
- iOS version: 15.5b4
- PojavLauncher version: 2.1
```

**Comment by khanhduytran0** [comment]
Sodium is currently unsupported due to the lack of OpenGL 3/4. While M1 Mac has OpenGL 4.1, iPads don’t.
An alternative is VulkanMod ([patched fork](https://github.com/PojavLauncherTeam/VulkanMod/actions)), which makes use of Vulkan for game rendering.
