### ISSUE TITLE
Build instructions?

### ISSUE THREAD

**Issue by thecoder08** [PojavLauncherTeam/PojavLauncher_iOS#4]
The README has a link that says Building but it appears to be dead as there is to building section in the readme. can you add one?

**Comment by DwifteJB** [comment]
I don't think this project is at a stage to compile

**Comment by artdeell** [comment]
> I don't think this project is at a stage to compile

_if it's not, how do the action builds work?_

**Comment by khanhduytran0** [comment]
Build instruction added.
