### ISSUE TITLE
Microsoft login shows that Safari browser can't open the page because the URL is invalid. What should I do

### ISSUE THREAD

**Issue by wyc66652** [PojavLauncherTeam/PojavLauncher_iOS#40]

**Comment by khanhduytran0** [comment]
Copy the url to here

**Comment by Windoooors** [comment]
I have the same problem and there is no way to copy the url.
here is a screenshot
![IMG_4387](https://user-images.githubusercontent.com/54850483/109309295-0b8e0000-787e-11eb-9198-42ab56d895c5.PNG)

**Comment by Windoooors** [comment]
I reinstalled the application and now it is working, but I don't know why.

**Comment by khanhduytran0** [comment]
Ah, maybe before you are on an old build...
