### ISSUE TITLE
Minecraft cannot be started while jailbroken.

### ISSUE THREAD

**Issue by amytwe** [PojavLauncherTeam/PojavLauncher_iOS#403]
### Describe the bug

Pojavlauncher cannot detect JIT when jailbroken.

### Steps To Reproduce

```markdown
1.Start Pojavlauncher
2.Start Minecraft
3.Display whit JIT title.
```

### Expected Behavior

I hope Minecraft will continue to launch.

### Platform

```markdown
- Device model: Iphone 6s
- iOS version: 14.2 (Jailbroken)
- PojavLauncher version: Latest Release
```

**Comment by crystall1nedev** [comment]
It works with my test devices when jailbroken, can you send logs?

**Comment by amytwe** [comment]
[Uploading latestlog.txt…]()

**Comment by amytwe** [comment]
I using Taurine.

**Comment by amytwe** [comment]
When the Pojavlauncher is restored to a non Jailbreak state, it can be used normally

**Comment by khanhduytran0** [comment]
But does Minecraft launch while jailbroken? Ignore the JIT message.

**Comment by amytwe** [comment]
When jailbroken, Minecraft can launch normally.And I installed AppSync.

**Comment by crystall1nedev** [comment]
So... issue is fixed on its own?
