### ISSUE TITLE
[Bug] Cannot install dev build

### ISSUE THREAD

**Issue by LolekLiam** [PojavLauncherTeam/PojavLauncher_iOS#404]
### Describe the bug

I cannot install the dev build. I tried installing .deb and uninstalling, running iCleaner and respringing but nothing worked.

### The log file and images/videos

In Cydia:
Downloading PojavLauncher iOS (Development)
Done PojavLauncher iOS (Development)
Running Debian Packager
dpkg-deb —control subprocess returned error exit status 2
Sub-process /usr/libexec/cydia/cydo returned an error code (1)

In Filza(ipa):
Rejecting downgrade of system/internal app net.kdt.pojavlauncher: installed version is 2, proposed version is 2

### Steps To Reproduce

```markdown
1. Try to install with Cydia
2. Fail

1. Try to install .ipa
2. Fail
```

### Expected Behavior

Succesfully installed PojavLauncher dev build

### Platform

```markdown
- Device model: iPad Pro (9.7-inch)
- iOS version: 14.4.2
- PojavLauncher version: Lastest Dev build 2.1~beta46
```

**Comment by khanhduytran0** [comment]
Debian package method is deprecated and will be removed in future release.
As a result of previously-installed deb, the package is somehow registered as system app, so installing ipa through Filza might not work.
Please use TrollStore to install.
