### ISSUE TITLE
Install forge >crash< (no jailbreak)

### ISSUE THREAD

**Issue by lenotv** [PojavLauncherTeam/PojavLauncher_iOS#407]
### Ask the question here.

Pls I know and please tutorial

**Comment by nevfuxon** [comment]
```
Issue Title: log history
10/20/22 2:00 PM PHT > from " I know install forge (no jailbreak)" to...
```
wow

Anyways, invalid question.

**Comment by crystall1nedev** [comment]
You can install Forge by downloading the .jar file and:

For v2.0 and v2.0.1
- Sign in
- Tap "More" or the three ... at the top right
- Tap "Launch a mod installer"

For v2.1 and later
- Sign in
- Tap "Install .jar"
