### ISSUE TITLE
Help crash

### ISSUE THREAD

**Issue by Tatouu14** [PojavLauncherTeam/PojavLauncher_iOS#408]
### Describe the bug

hello, I have a problem which is every time I try to enter a world it does not load me, when I manage to enter and after a short time I save and I leave and I want to re-enter it does not enter, many times I try to remove the world from the game files and putting it and that sometimes worked, but it always ended in the same, another error also happens to me that when the chunks are loaded the game closes, that is, if I go out to explore after a few moments the game quits, I suppose that It's because of the chunk load, I tried to lower it to 6 or 7 and it still happens, I normally play with 9 or 10, when I play for more than 30 minutes it closes, I play in version 1.19, but in 1.16.5 it works for me to the worlds and I can exit normally, I don't know if it comes out when the chunks are loaded, I haven't tested very well, I hope you can help me, I play on an ios WITHOUT jailbreak, I'm sorry if there are spelling or order errors , I write this from a translator, I speak Spanish, happy day/night, I hope you can keep improving the game, it's a pretty well done job, I want to add that when I assign more ram the world does open, but the same thing happens with the problem that it closes when loading chunks, i have renderer auto,no matter what render it uses you pass that.

### The log file and images/videos
 

https://user-images.githubusercontent.com/114040777/197120126-8b601260-efea-402a-9841-1884fd7c827d.mp4

https://user-images.githubusercontent.com/114040777/197120062-7a9fc393-5293-4f79-9b2a-48bbeb658633.mp4

[latestlog.old.txt](https://github.com/PojavLauncherTeam/PojavLauncher_iOS/files/9835950/latestlog.old.txt)

### Steps To Reproduce

```markdown
first error
start pojavlauncher
enter version 1.19
create or enter some world
get out of the world saving
try to re-enter the world
second error
start pojavlauncher
enter version 1.19
create or enter some world
explore the world with or without elytras or flying
```

### Expected Behavior

play normally

### Platform

```markdown
- Device model: iphone 11 pro max
- iOS version: 16
- PojavLauncher version: 2.1
```

**Comment by khanhduytran0** [comment]
> when I assign more ram the world does open, but the same thing happens with the problem that it closes when loading chunks

Unless it has a sandbox exception (jailbreak, TrollStore), it is not allowed to allocate more RAM.
Also, as stated in README.md, playing with large render distance is not recommended, when you can’t allocate more RAM.

**Comment by Tatouu14** [comment]
Also playing with 7 chunks the game closes, is there a solution?

**Comment by Aerolome** [comment]
> Also playing with 7 chunks the game closes, is there a solution?

allocate less ram

**Comment by Tatouu14** [comment]
it won't let me enter the worlds, can't you do something?, any solution?, I would like to be able to play 1.19 without problems

**Comment by khanhduytran0** [comment]
Playing with vanilla has never been a good idea. It is recommend to install something like OptiFine.

**Comment by crystall1nedev** [comment]
Issue seems to have a resolution:

- use an optimized version of Minecraft
- lower video settings
- lower memory allocation
