### ISSUE TITLE
[Bug] Won't download on AltStore

### ISSUE THREAD

**Issue by iiab76** [PojavLauncherTeam/PojavLauncher_iOS#409]
### Describe the bug

I tried to download using AltStore but it says it isn't the correct type of file. I went to actions like the tutorial specified and still won't work

### Steps To Reproduce

```markdown
I don't know.
```

### Expected Behavior

I expected it to download.

### Platform

```markdown
- Device model: iPhone 8
- iOS version: 16
- PojavLauncher version: latest release
```

**Comment by Aerolome** [comment]
are you sure you extracted the zip and selected the ipa?

**Comment by iiab76** [comment]
It says that it is an inappropriate file format.

**Comment by BrandonPlays** [comment]
where would I find the IPA?

**Comment by crystall1nedev** [comment]
Closimg the issue as this is just someone having a skill issue, tbh.

1. Download from actions
2. Extract the .zip
3. Open .ipa in AltStore
4. Play Minecraft
