### ISSUE TITLE
Icon not showing up on installation even when running uicache

### ISSUE THREAD

**Issue by Hinkiii** [PojavLauncherTeam/PojavLauncher_iOS#41]
Even a respring doesn't show it

**Comment by Tsumiicode** [comment]
Same it dosnt show for me and I’ve installed using Filza and NewTerm dpkg

**Comment by khanhduytran0** [comment]
Are both on checkra1n?

**Comment by Tsumiicode** [comment]
Yeah I am and what I did is I deleted the app in Filza then ran ui cache in Filza and it worked but one thing how do I get fabric or optifine because opti installer is missing it’s a 404

**Comment by khanhduytran0** [comment]
Oh. I need to add launcher_profiles.json before mod can be installed

**Comment by khanhduytran0** [comment]
@Hinkiii try uicache manually, run as root
```
uicache -u /Applications/PojavLauncher.app
uicache -p /Applications/PojavLauncher.app
```

@Tsumiicode 
- Fabric + sodium: https://github.com/PojavLauncherTeam/PojavLauncher_iOS/wiki/Installing-Fabric-and-Sodium
- Optifine: https://github.com/PojavLauncherTeam/PojavLauncher_iOS/wiki/Installing-OptiFine

**Comment by khanhduytran0** [comment]
@Tsumiicode reply?

**Comment by Tsumiicode** [comment]
It's working. Thanks
