### ISSUE TITLE
Pojav ios stuck in control customization screen 

### ISSUE THREAD

**Issue by aspauldingcode** [PojavLauncherTeam/PojavLauncher_iOS#411]
### Describe the bug

Using Non-Jailbroken PojavLauncher for iOS, (iPhone 12 Pro Max, iOS 15.2)
I can’t close out of the screen for control customization menu.
This is rather odd. There is no way to close out, no way to edit a button (such as my keybind of escape) and then save it or click “done”. There is no button to return to the game, so I have to close PojavLauncher with the app switcher. 

### Steps To Reproduce

```markdown
1. Start PojavLauncher. 
2. Sign in, or select user. 
3. Customize controls…
Good luck saving your controls configuration, or playing after that.
```

### Expected Behavior

I should be able to save, or click a button that says “done” to close out of the control customization menu. 

### Platform

```markdown
- Device model: iPhone 12 Pro Max
- iOS version: 15.2
- PojavLauncher version: 2.01, Rootless Launcher
```

### Anything else?

Closing the launcher removes my settings for the controls customization, so I still can’t use it.

**Comment by aspauldingcode** [comment]
Not implemented yet, I guess.

**Comment by khanhduytran0** [comment]
All you need to do is a long-press, anywhere on screen, this seems like only the curious can find it out, so I’m gonna add a tiny guide.
![9AFFFD13-A8D6-4E68-B0C3-E86127B918FC](https://user-images.githubusercontent.com/40482367/199364557-0e5cb1c2-c4fc-4e88-b77b-ab7dafc4f64b.jpeg)
A note: Exit does not automatically save changes for now, you have to save before exit.

**Comment by SamZong233** [comment]
long press the screen
