### ISSUE TITLE
[Bug] pojavlauncher crashes after closing minecraft (IOS 16.1/Without jailbreak)

### ISSUE THREAD

**Issue by bsndmd** [PojavLauncherTeam/PojavLauncher_iOS#412]
### Describe the bug

pojavlauncher crashes after closing minecraft (IOS 16.1/Without jailbreak)

I press force close or close minecraft in the main menu, after that pojavlauncher crashes

### Steps To Reproduce

```markdown
1. i starting minecraft 1.16.5
2. after i click exit on the main menu.
3. pojavlauncher crashes
```

### Expected Behavior

launcher crashes

### Platform

```markdown
- Device model: Iphone XS
- iOS version: 16.1 Without jailbreak
- PojavLauncher version: 2.1
```

**Comment by khanhduytran0** [comment]
This is intended behavior. Since Java runs in launcher’s process, the only way to completely free memory as of now is force exit, which results in crash-like animation. Otherwise, if Force Close/Exit returns to launcher screen, memory leaks may occur when game launches for the second time.
