### ISSUE TITLE
[Question] Unjailbroken ipa file?

### ISSUE THREAD

**Issue by LolekLiam** [PojavLauncherTeam/PojavLauncher_iOS#414]
### Ask the question here.

Where is the .ipa file for sideloading on an unjailbroken device? It was here before and now there are just .deb files, which i cannot install via trollstore.

**Comment by SamZong233** [comment]
download it from actions tab,you may need to sign in to download the ipa artifact

**Comment by khanhduytran0** [comment]
See [README.md](https://github.com/PojavLauncherTeam/PojavLauncher_iOS#getting-started-with-pojavlauncher)
