### ISSUE TITLE
[Bug] Joystick loses key presses randomly

### ISSUE THREAD

**Issue by Blockbuster-MC** [PojavLauncherTeam/PojavLauncher_iOS#416]
### Describe the bug

I was using build 385 and movement was working fine, I updated to the latest build and now I have scrollable inventory using bumpers which I didn’t have before but movement is hit or miss.

it seems to “lose” the fact that you’re holding down W when the joystick is moved up. It will randomly just stop even though the joystick is at 100% and require you to rock the joystick to get it to redo the key press.

### Steps To Reproduce

```markdown
Use Razer kishi
```

### Expected Behavior

Player continues to move while joystick is pressed

### Platform

```markdown
- Device model: iPhone 12 Pro Max 
- iOS version: 16.0.2
- PojavLauncher version: latest
```

**Comment by khanhduytran0** [comment]
Controller was not available until build 396, so how did it work?

Anyways, try [build 538](https://github.com/PojavLauncherTeam/PojavLauncher_iOS/actions/runs/3255602958) and [build 542](https://github.com/PojavLauncherTeam/PojavLauncher_iOS/actions/runs/3261530010) to see if there’s any difference.

**Comment by Blockbuster-MC** [comment]
> Controller was not available until build 396, so how did it work?
> 
> 
> 
> Anyways, try [build 538](https://github.com/PojavLauncherTeam/PojavLauncher_iOS/actions/runs/3255602958) and [build 542](https://github.com/PojavLauncherTeam/PojavLauncher_iOS/actions/runs/3261530010) to see if there’s any difference.

I was going off the last bug report I submitted, I must've used the wrong number in that one then. I will take a look at those and report back.

**Comment by Blockbuster-MC** [comment]
Build 538

Not having the same moving forward issue as i was in the latest build, however, hot bar item switching using R1 L1 is opposite of what it should be (which i assume was updated in later builds since it was working properly in latest)

Build 542

Movement seems more "fluid" (not sure what was changed between 538 and 542) however it appears to randomly stop.
The best way i can get it to replicate is by moving the joystick very quickly and/or in opposite directions. It seems appears to me that it isnt picking up the new input direction but stopping the old input direction if that makes any sense to you. (again R1 and L1 seem to be opposite and scrolling quickly (more than one slot) not one at a time per key press)

**Comment by crystall1nedev** [comment]
I'll get to work on this when my iPhone 14 Pro Max arrives on Monday/Tuesday.

**Comment by Blockbuster-MC** [comment]
> 

Sounds good, let me know if i can be of any assistance.

**Comment by crystall1nedev** [comment]
Unable to reproduce this issue with my DualShock 4, wondering if this is a Kishi-only issue.

**Comment by Blockbuster-MC** [comment]
> 

what happened between build 538 and 542 ?

**Comment by khanhduytran0** [comment]
A change in handling direction, as a user reported getting random direction movements.

**Comment by crystall1nedev** [comment]
Closing issue as it's stale. If the issue still persists, reopen.

**Comment by guyman624** [comment]
Hello, I also have a kishi on iOS. My DS4 didn’t have this issue either. I don’t think its to do with controller updating. For now, I have bypassed this issue by pushing my stick slightly left or slightly right, and I can hold it no problem. If I hold it straight dead forward, I have issues. The controller works fine in all other games.
