### ISSUE TITLE
[F-Req] allow configuring JitStreamer custom servers

### ISSUE THREAD

**Issue by esgie** [PojavLauncherTeam/PojavLauncher_iOS#418]
### Is this request related to a bug?

JitStreamer support has been added to PojavLauncher for iOS recently, so users of this service should have JIT enabled seamlessly after starting the app. Unfortunately, currently there seems to be no way to configure target host address and port of the JitStreamer server instance. Thus, this feature is currently limited to default, public instance of JitStreamer.
Public instance has its advantages (like it’s trivial to configure, due to really simple tutorial and totally free), but it also comes with several limitations. First, security - it requires users to share their device’s pairing credentials with third-party, *possibly* giving the party access to execute debugger commands on device through network connection, without notice. Second, performance - it is slow and it went offline plenty of times already. Also, developers tend to „factory reset” the instance once per few months by clearing all the pairing information, requiring user to register and pair device again. JitStreamer is an open source software and can be easily built and run on any platform, allowing more skilled users to run their own private instances in their home networks, without flaws I have mentioned.

### Describe the request.

It would be desired to allow user to configure custom local address and port of his own JitStreamer server instance (other than default http://69.69.0.0:80)

**Comment by jkcoxson** [comment]
Um we’ve only had to reset once. And we’ve solved it so it won’t happen again.

**Comment by crystall1nedev** [comment]
@jkcoxson could this be useful for self-hosted servers? Not saying that the claims to "factory reset" are common - just wondering
