### ISSUE TITLE
[Bug] PojavLauncher broken with palera1n 

### ISSUE THREAD

**Issue by crystall1nedev** [PojavLauncherTeam/PojavLauncher_iOS#423]
### Describe the bug

With the recent developments by the palera1n team to release a working jailbreak for checkm8 devices on iOS 15, we've stumbled into another issue. JIT does not automatically enable itself, and AltKit has an issue mounting the DeveloperDiskImage (which also means Jitterbug is broken too.)

PojavLauncher installed with TrollStore on palera1n is unaffected.

### The log file and images/videos

<img width="1446" alt="Screenshot 2022-11-14 at 19 04 42" src="https://user-images.githubusercontent.com/55281754/201793988-f7ce0a1c-e465-4be2-be42-be21a4dd5baf.png">

### Steps To Reproduce

```markdown
1. Open PojavLauncher
2. JIT will not be enabled
```

### Expected Behavior

Expecting it to work after my fixes are completed, will most likely integrate before the final release of PojavLauncher 2.1.

### Platform

```markdown
- Device model: iPhone 7
- iOS version: 15.7.1
- PojavLauncher version: 2.1rc2
```

**Comment by crystall1nedev** [comment]
Currently unable to fix as there is no way to tell whether or not palera1n is being used.

**Comment by khanhduytran0** [comment]
Same issue while jailbroken with Taurine. Core issue: `CS_DEBUGGED` not set after calling `ptrace(PT_TRACE_ME)` in the child process.
Added skip option as workaround, might not work.

**Comment by crystall1nedev** [comment]
We should probably get a way to identify those jailbreaks without needing to skip and guess on whether or not it worked.

**Comment by crystall1nedev** [comment]
Although this is what the jailbreak detecting code was for? 

```obj-c
void init_checkForJailbreak() {
    bool jbDyld = false;
    bool jbFlag = true;
    bool jbProc = init_checkForsubstrated();
    
    int imageCount = _dyld_image_count();
    uint32_t flags = CS_PLATFORM_BINARY;
    
    for (int i=0; i < imageCount; i++) {
        if (strcmp(_dyld_get_image_name(i),"/usr/lib/pspawn_payload-stg2.dylib") == 0) {
            jbDyld = true;
        } else {
            jbDyld = false;
        }
    }
    if (csops(0, CS_OPS_STATUS, &flags, sizeof(flags)) != -1) {
        if ((flags & CS_PLATFORM_BINARY) == 0) {
            jbFlag = false;
        } else {
            jbFlag = true;
        }
    }
    
    if (jbDyld || jbFlag || jbProc) {
        setenv("POJAV_DETECTEDJB", "1", 1);
    }
}
```

Looking for `/usr/lib/pspawn_payload-stg2.dylib` is what should identify Taurine, at least that's how Nick Chan and I figured it would.

**Comment by crystall1nedev** [comment]
Going to cc @asdfugil on this one.

**Comment by speedyfriend67** [comment]
May Perhaps the path /var/jb/var/mobile/Library/Preferences should be used in the plugin configuration file.
Helpful for preventing jailbreak detection

**Comment by speedyfriend67** [comment]
I think it's necessary to remind other developers that you may need to change your Tweak path to var/jb directory, because the one is your main working directory.

**Comment by crystall1nedev** [comment]
> May Perhaps the path /var/jb/var/mobile/Library/Preferences should be used in the plugin configuration file.
> Helpful for preventing jailbreak detection

Cannot use this, as then it would misidentify unjailbroken devices that had run palera1n before.

**Comment by crystall1nedev** [comment]
> I think it's necessary to remind other developers that you may need to change your Tweak path to var/jb directory, because the one is your main working directory.

This is not the place for this message...
