### ISSUE TITLE
[Bug] External mouse isnt working

### ISSUE THREAD

**Issue by InfernoNova9999** [PojavLauncherTeam/PojavLauncher_iOS#424]
### Describe the bug

External mouse isnt working. The mouse moves the iOS cursor but not the pojavlauncher virtual mouse.

### The log file and images/videos

https://user-images.githubusercontent.com/70199277/201857303-dc197e2e-40e3-45a2-8856-47853160b493.MP4

### Steps To Reproduce

```markdown
1: move the mouse
```

### Expected Behavior

The mouse should work properly. 

### Platform

```markdown
- Device model: iPad Air 4
- iOS version: 15.5b4
- PojavLauncher version: Latest actions
```

**Comment by khanhduytran0** [comment]
Marked as resolved in your post (Discord).
