### ISSUE TITLE
How do I add new renderer

### ISSUE THREAD

**Issue by Coolpants515** [PojavLauncherTeam/PojavLauncher_iOS#427]
### Ask the question here.

I play on iPhone 12 unjailbroken PojavLauncher version 2.0.1 I think and wanted to know if it is possible to add a new renderer on it via files app?

**Comment by khanhduytran0** [comment]
Renderer isn’t a module component. It’s a bundle of hardcoded functions, takes different parameter, so every render requires a separate interface. You can’t "insert RTX to your iPhone and then import RTX (driver) renderer to play with ray tracing shaders".
