### ISSUE TITLE
[Bug] pre render error (why bug report closed I haven’t gotten reply)

### ISSUE THREAD

**Issue by SYZYGYGAMER** [PojavLauncherTeam/PojavLauncher_iOS#430]
### Describe the bug

When I launch pojavlauncher in ios and check log output it shows 
![7EB65A26-49AA-40BF-98B8-BD47C99D387E](https://user-images.githubusercontent.com/114241650/202448767-4b8743cd-140b-48b7-886e-8f7e271557f5.png)
And crashes or lags

### The log file and images/videos

Pls fix it I already reported it 2 times lags so high I can’t play the game anymore 

![A21F8951-A245-41AF-90DB-726A2C160ECA](https://user-images.githubusercontent.com/114241650/202449593-fb65b517-0a81-4485-9c01-1a3866f78a26.png)

### Steps To Reproduce

```markdown
1 start pojavlauncher
2 launch 1.8.9(in my case)
3 check log output
```

### Expected Behavior

I expect the game to be fixed and gets bug fix 
Proof of error 
![31BD0241-BCE7-4616-AC24-1270A63D8912](https://user-images.githubusercontent.com/114241650/202449139-1693c780-c375-4911-b6f3-fea5774c8b8e.png)

### Platform

```markdown
- Device model: iPhone 11
- iOS version: 1.16.1
- PojavLauncher version: latest from actions
```

### Anything else?

Pls fix it or give a reply before closing it
It happened after the new updates 
Also pojav launcher can now not be played if I don’t use vpn 
Normally I use it to open and disable it to save battery and ram 
Pls fix it

**Comment by SYZYGYGAMER** [comment]
It does not stop and crashes the game

**Comment by GaucovyAero** [comment]
what renderer, what ram allocation?

**Comment by SYZYGYGAMER** [comment]
> 

Check the picture I sent when I check log output it happens

**Comment by crystall1nedev** [comment]
You did not say what renderer or RAM allocation you have set.

**Comment by SYZYGYGAMER** [comment]
Auto render and auto ram I’ll do another bug report with more info soon
