### ISSUE TITLE
[Bug] <@pre render error> (more info)

### ISSUE THREAD

**Issue by SYZYGYGAMER** [PojavLauncherTeam/PojavLauncher_iOS#432]
### Describe the bug

When u launch 1.8.9 in pojav ios (latest version) in log output a message infinetly appear 
![Uploading 662FC364-0172-49D6-85B2-9973294C632A.png…]()

### The log file and images/videos

Proof of what’s happening (including my settings both in game and pojav launcher)
![DBBB7E13-7E7E-47B3-A7CD-0D12EB0530E6](https://user-images.githubusercontent.com/114241650/202594534-bdaa7876-23e4-473e-8523-0d7317c79495.png)

![0BE4BC73-0CDB-4794-9135-724F079B5429](https://user-images.githubusercontent.com/114241650/202594550-69b8abde-d59f-49df-8383-810eceec65e7.png)
 
![E0865B83-217B-455D-AA39-A8A85ACBD030](https://user-images.githubusercontent.com/114241650/202594693-1cee8e7e-44df-42c0-bb39-1d28cbf7ee22.png)
![75B3F73D-5D66-4630-9010-B9C7BEA279C4](https://user-images.githubusercontent.com/114241650/202594798-edb59c84-c998-420b-811c-1b08945e42a5.png)
![C162E792-85FB-441D-858E-AC55081A8DC2](https://user-images.githubusercontent.com/114241650/202594966-2012404d-93d4-4df2-b63a-d7d104d277ce.png)
![73400E77-D999-4374-92C4-760AC9F335B9](https://user-images.githubusercontent.com/114241650/202594983-6839ba12-fa60-45f5-a586-65d9e8b0cd36.png)
![E8A641C4-7BE0-47F3-854D-39FFCCBA6C04](https://user-images.githubusercontent.com/114241650/202594997-dadbc9fe-3ccd-4a1c-a19b-db15c671e8ee.png)
![D5DDB7F4-042E-4E2B-9FBB-58B6EEEE2D5D](https://user-images.githubusercontent.com/114241650/202595023-918a029d-933e-4c41-b3da-50342db6725f.png)

### Steps To Reproduce

```markdown
1 start poiav launcher 
2 launch 1.8.9 (includes options and forge)
3 check log output
```

### Expected Behavior

In log output it says pre render 
Pre render error as shown here 
![ECC1E883-EC47-4774-B95E-407E90B26542](https://user-images.githubusercontent.com/114241650/202594868-10e8f7ee-3038-4d2d-9a52-0dc515848179.png)

### Platform

```markdown
- Device model: I phone 11
- iOS version: 1.16.1
- PojavLauncher version: latest from action bar
```

### Anything else?

It does not happen with latest Minecraft 1.19.2
Currently only happens with 1.8.9 pls fix it if u need more info pls reply

**Comment by SYZYGYGAMER** [comment]
It’s not duplicate last one is closed btw

**Comment by SYZYGYGAMER** [comment]
Pls reply

**Comment by crystall1nedev** [comment]
I can't produce this issue.

![image](https://user-images.githubusercontent.com/55281754/202837215-9aa4b2ab-3e30-4101-a030-507a0726463f.png)

**Comment by SYZYGYGAMER** [comment]
How

**Comment by SYZYGYGAMER** [comment]
Did u do what I did

**Comment by SYZYGYGAMER** [comment]
Is the version and others same

**Comment by SYZYGYGAMER** [comment]
Can I make a video and sent it?

**Comment by SYZYGYGAMER** [comment]
Can I contact u on discord

**Comment by crystall1nedev** [comment]
> Is the version and others same

Yes.

**Comment by SYZYGYGAMER** [comment]
Can I send u a screen video or screen share on discord

**Comment by SYZYGYGAMER** [comment]
Or anything

**Comment by SYZYGYGAMER** [comment]
SYZYGY#0227 My discord Id

**Comment by crystall1nedev** [comment]
Resolved.
