### ISSUE TITLE
Black Screen

### ISSUE THREAD

**Issue by Sinu03** [PojavLauncherTeam/PojavLauncher_iOS#433]
### Describe the bug

Black Screen

### The log file and images/videos

![61383814-51FF-4A4A-B173-487CEBF29142](https://user-images.githubusercontent.com/118577631/202833532-48d5d17a-ecdb-4592-aa1f-5d5d1099000e.png)

### Steps To Reproduce

```markdown
.
```

### Expected Behavior

.

### Platform

```markdown
- Device model: iPad Pro 5
- iOS version: 16.1.1
- PojavLauncher version: last
```

### Anything else?

.

**Comment by crystall1nedev** [comment]
There isn't much we can do without any detail, closing until you can provide.
