### ISSUE TITLE
Crashes after joining server after the loading terrain gos away

### ISSUE THREAD

**Issue by Luke14jXX2nd** [PojavLauncherTeam/PojavLauncher_iOS#434]
### Describe the bug

Yeah so its crashing right after the loading terrain part gos away to join a server and i have jit enabled and optifine on.

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher_iOS/files/10086841/latestlog.txt)

### Steps To Reproduce

```markdown
I had opened my pojav and enabled jit before that then I went to install jar and i got optifine and tried to use a server but did not work.
```

### Expected Behavior

I expected it to join the server.

### Platform

```markdown
- Device model: iPad 8th Generation
- iOS version: 16.1.1
- PojavLauncher version: Latest Release
```

**Comment by GaucovyAero** [comment]
```
# There is insufficient memory for the Java Runtime Environment to continue.
# Native memory allocation (mmap) failed to map 8388608 bytes for Failed to reserve memory for metaspace
```
allocate more memory

**Comment by crystall1nedev** [comment]
Yeah, this is a memory issue. Allocate more or go for a little less - the default value should work fine. Reopen if this issue still exists, I can't reproduce on the servers I play on.
