### ISSUE TITLE
[Bug] Installing .jars with Java 8 causes a crash

### ISSUE THREAD

**Issue by TheCrazyInsanity** [PojavLauncherTeam/PojavLauncher_iOS#435]
### Describe the bug

Installing forge installer instantly causes a crash
Fabric is the same as well

### The log file and images/videos

[latestlog.old.txt](https://github.com/PojavLauncherTeam/PojavLauncher_iOS/files/10087969/latestlog.old.txt)

### Steps To Reproduce

```markdown
1. Start Pojav Launcher
2. Login to account
3. Press install .jar
4. Select valid forge / fabric installer jar file
5. Crash
```
```markdown
1. Start Pojav Launcher
2. Login to account
3. Select a version
4. Press play
5. Wait for it to open
6. Tap anywhere
7. Enjoy the crash
```

### Expected Behavior

The forge / fabric installer successfully launches
Tapping doesnt crash

### Platform

```markdown
- Device model: iPhone 7
- iOS version: 15.6
- PojavLauncher version: 2.1
```

### Anything else?

Tested using forge 1.12.2 and fabric 1.19

**Comment by crystall1nedev** [comment]
Cannot reproduce this, are you sure you are enabling JIT before launching?

**Comment by TheCrazyInsanity** [comment]
> Cannot reproduce this, are you sure you are enabling JIT before launching?

Its jailbroken jit is auto enabled, and it wouldnt let me open it in the first place without jit

**Comment by crystall1nedev** [comment]
> jailbroken jit is auto enabled
You're using palera1n, where automatic JIT is broken.

**Comment by TheCrazyInsanity** [comment]
> > jailbroken jit is auto enabled
> 
> You're using palera1n, where automatic JIT is broken.

Oh

**Comment by khanhduytran0** [comment]
> You're using palera1n, where automatic JIT is broken.

It was not
```
2022-11-24 19:01:36.445 PojavLauncher[5964:119892] [Pre-init] Sandbox is disabled, trying to enable JIT
2022-11-24 19:01:36.542 PojavLauncher[6863:145949] parent pid is not launchd, calling ptrace(PT_TRACE_ME)
2022-11-24 19:01:36.544 PojavLauncher[5964:119892] [Pre-init] JIT has heen enabled with PT_TRACE_ME
```

**Comment by khanhduytran0** [comment]
@TheCrazyInsanity if you enabled tweak injection, install Cr4shed and try to get Cr4shed to log it(?)
Otherwise, grab the latest PojavLauncher.ips report from Analytics Data.

**Comment by crystall1nedev** [comment]
> > You're using palera1n, where automatic JIT is broken.
> 
> It was not
> 
> ```
> 2022-11-24 19:01:36.445 PojavLauncher[5964:119892] [Pre-init] Sandbox is disabled, trying to enable JIT
> 2022-11-24 19:01:36.542 PojavLauncher[6863:145949] parent pid is not launchd, calling ptrace(PT_TRACE_ME)
> 2022-11-24 19:01:36.544 PojavLauncher[5964:119892] [Pre-init] JIT has heen enabled with PT_TRACE_ME
> ```

Ah, forgot to look at the log. Heard "jailbreak" and saw iP7 + 15.6 and assumed, my bad.

**Comment by TheCrazyInsanity** [comment]
> @TheCrazyInsanity if you enabled tweak injection, install Cr4shed and try to get Cr4shed to log it(?) Otherwise, grab the latest PojavLauncher.ips report from Analytics Data.

alright, im having issues with sileo right now once they are resolved i will upload the logs

**Comment by TheCrazyInsanity** [comment]
> @TheCrazyInsanity if you enabled tweak injection, install Cr4shed and try to get Cr4shed to log it(?) Otherwise, grab the latest PojavLauncher.ips report from Analytics Data.

cr4shed doesnt support ios 15, how do i do the other one

**Comment by crystall1nedev** [comment]
Settings > Privacy & Security > Analytics & Improvements > Analytics Data

**Comment by TheCrazyInsanity** [comment]
> Settings > Privacy & Security > Analytics & Improvements > Analytics Data

[ResetCounter-2022-11-25-101604.ips.zip](https://github.com/PojavLauncherTeam/PojavLauncher_iOS/files/10093981/ResetCounter-2022-11-25-101604.ips.zip) had to zip it because of github complaining

**Comment by crystall1nedev** [comment]
That's not the right file. Send the most recent one that has PojavLauncher in the name.

**Comment by TheCrazyInsanity** [comment]
> 
[PojavLauncher-2022-11-25-111240.ips.zip](https://github.com/PojavLauncherTeam/PojavLauncher_iOS/files/10094116/PojavLauncher-2022-11-25-111240.ips.zip)

**Comment by khanhduytran0** [comment]
> ```
> Exception Type:  EXC_GUARD (SIGKILL)
> Exception Subtype: GUARD_TYPE_VIRT_MEMORY
> Exception Message: offset=0x00000001692e0000, flavor=0x00000001 (DEALLOC_GAP)
> Description: Address size fault
> Thread: com.apple.main-thread
> Call stack:
> 0 __mmap
> 1 mmap
> 2 os::pd_uncommit_memory(char*, unsigned long, bool)
> 3 javathread::create_stack_guard_pages()
> ```

Well, it looks like any memory failure will crash rather than just returning warning as
```
Java HotSpot(TM) 64-Bit Server VM warning: Attempt to deallocate stack guard pages failed. 
```

Try adding these to jvm arguments:
```
-XX:+UnlockExperimentalVMOptions -XX:+DisablePrimordialThreadGuardPages
```
If it fixes the issue, I’ll add it to default arguments.

**Comment by TheCrazyInsanity** [comment]
Solved, enabling use Java 17 for Minecraft fixed it

**Comment by TheCrazyInsanity** [comment]
reopening because thats a bad solution, it causes forge to crash

**Comment by TheCrazyInsanity** [comment]
> > ```
> > Exception Type:  EXC_GUARD (SIGKILL)
> > Exception Subtype: GUARD_TYPE_VIRT_MEMORY
> > Exception Message: offset=0x00000001692e0000, flavor=0x00000001 (DEALLOC_GAP)
> > Description: Address size fault
> > Thread: com.apple.main-thread
> > Call stack:
> > 0 __mmap
> > 1 mmap
> > 2 os::pd_uncommit_memory(char*, unsigned long, bool)
> > 3 javathread::create_stack_guard_pages()
> > ```
> 
> Well, it looks like any memory failure will crash rather than just returning warning as
> 
> ```
> Java HotSpot(TM) 64-Bit Server VM warning: Attempt to deallocate stack guard pages failed. 
> ```
> 
> Try adding these to jvm arguments:
> 
> ```
> -XX:+UnlockExperimentalVMOptions -XX:+DisablePrimordialThreadGuardPages
> ```
> 
> If it fixes the issue, I’ll add it to default arguments.

doesnt work

**Comment by khanhduytran0** [comment]
> doesnt work

Send PojavLauncher.ips

**Comment by TheCrazyInsanity** [comment]
> > doesnt work
> 
> Send PojavLauncher.ips

doesnt generate one because its not a hard crash, pojav launcher catches it

logs pojav launcher generates
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher_iOS/files/10109090/latestlog.txt)

**Comment by khanhduytran0** [comment]
> doesnt generate one because its not a hard crash, pojav launcher catches it
> 
> logs pojav launcher generates [latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher_iOS/files/10109090/latestlog.txt)

I mean these two arguments when launch with java 8, not java 17.
```
-XX:+UnlockExperimentalVMOptions -XX:+DisablePrimordialThreadGuardPages
```

**Comment by TheCrazyInsanity** [comment]
> > doesnt generate one because its not a hard crash, pojav launcher catches it
> > logs pojav launcher generates [latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher_iOS/files/10109090/latestlog.txt)
> 
> I mean these two arguments when launch with java 8, not java 17.
> 
> ```
> -XX:+UnlockExperimentalVMOptions -XX:+DisablePrimordialThreadGuardPages
> ```

Still doesn’t work

**Comment by khanhduytran0** [comment]
> Still doesn’t work

Still contains no information for debugging.
I asked you to send PojavLauncher.ips, but you redirected it to Java 17. 🤷‍♂️

**Comment by TheCrazyInsanity** [comment]
> > Still doesn’t work
> 
> Still contains no information for debugging. I asked you to send PojavLauncher.ips, but you redirected it to Java 17. man_shrugging If Pojav catches the error, send latestlog.txt
[PojavLauncher-2022-11-29-164946.ips.zip](https://github.com/PojavLauncherTeam/PojavLauncher_iOS/files/10117673/PojavLauncher-2022-11-29-164946.ips.zip)

**Comment by khanhduytran0** [comment]
Try the latest dev build

**Comment by crystall1nedev** [comment]
Closing issue as we cannot reproduce with the latest nightlies and it is stale. Reopen if it still exists.
