### ISSUE TITLE
cannot play 1.19.2

### ISSUE THREAD

**Issue by redderder** [PojavLauncherTeam/PojavLauncher_iOS#436]
### Describe the bug

i tried to play it and it just immediately crashed

### The log file and images/videos

[latestlog 2.txt](https://githu
b.com/PojavLauncherTeam/PojavLauncher_iOS/files/10097480/latestlog.2.txt)

[latestlog 2.zip](https://github.com/PojavLauncherTeam/PojavLauncher_iOS/files/10097481/latestlog.2.zip)

### Steps To Reproduce

```markdown
1.start pojav
2.click play with 1.19.2
3.crash
```

### Expected Behavior

my 1.19.2 have problem at somewhere

### Platform

```markdown
- Device model: iPhone12pro
- iOS version: 14.3
- PojavLauncher version:# 2.1 "Sculk Catalyst"
```

**Comment by redderder** [comment]
and sorry my English isn't good so there are tons of grammar errors

**Comment by khanhduytran0** [comment]
Is your device jailbroken? If so, please install Cr4shed and see if any crash is caught there.
Otherwise, go to Analytics Data and grab the latest `PojavLauncher.ips`

**Comment by redderder** [comment]
no，mine used trollstore

**Comment by khanhduytran0** [comment]
> Otherwise, go to Analytics Data and grab the latest PojavLauncher.ips

**Comment by redderder** [comment]
ok

**Comment by redderder** [comment]
what is Pojavlauncher.ips btw

**Comment by redderder** [comment]
there aren't any “ips”in latest log

**Comment by redderder** [comment]
[Uploading PojavLauncher-2022-11-27-113414.zip…]()

**Comment by redderder** [comment]
[Uploading PojavLauncher-2022-11-27-113414.zip…]()

**Comment by redderder** [comment]
![image](https://user-images.githubusercontent.com/113320874/204125900-1f7f15ab-1351-4aa1-a95e-99ecce448f29.png)

it says bad access

**Comment by redderder** [comment]
Thread 3 crashed with ARM Thread State (64-bit):
    x0: 0x000000000000002c   x1: 0x0000000102c53160   x2: 0x0000000000000000   x3: 0x0000000000000000
    x4: 0x0000000000000000   x5: 0x0000000000000000   x6: 0x0000000102c17864   x7: 0x0000000102c17873
    x8: 0x0000000120736b10   x9: 0x0000000102c1787c  x10: 0x0000000102c17877  x11: 0x00000000000007fd
   x12: 0x0000000000000001  x13: 0x00000000afe2c8f4  x14: 0x00000000b002d000  x15: 0x000000000000005a
   x16: 0x000000000000002e  x17: 0x0000000030000000  x18: 0x0000000000000000  x19: 0x0000000102c55c10
   x20: 0x0000000102c52000  x21: 0x0000000102c53160  x22: 0x00000001034516c0  x23: 0x0000000280fd7fc0
   x24: 0x0000000280f7e8a0  x25: 0x0000000102c53160  x26: 0x0000000280f7e8a0  x27: 0x000000028210fc80
   x28: 0x00000002801eecd0   fp: 0x000000016d59aa40   lr: 0x0000000102bcc5d4
    sp: 0x000000016d5997d0   pc: 0x0000000120736b10 cpsr: 0x80001000
   esr: 0x82000007 (Instruction Abort) Translation fault



so the thread 3 had some problems

translation fault

**Comment by redderder** [comment]
this bug only appears on 1.19.2，because i can play 1.8.9 with mod

**Comment by redderder** [comment]
this bug only appears on 1.19.2，because i can play 1.8.9 with mod

i dunno if this helps or nah

**Comment by khanhduytran0** [comment]
> Uploading PojavLauncher-2022-11-27-113414.zip…

It says uploading. Didn’t complete upload but you pressed comment.

**Comment by redderder** [comment]
so i have to wait before clicking the play button？
i mean that is simple

**Comment by redderder** [comment]
[PojavLauncher-2022-11-27-113414.zip](https://github.com/PojavLauncherTeam/PojavLauncher_iOS/files/10097919/PojavLauncher-2022-11-27-113414.zip)

**Comment by khanhduytran0** [comment]
You sent a 9-byte zip file, contains:
```
Not Found
```

**Comment by redderder** [comment]
what？

**Comment by redderder** [comment]
[PojavLauncher-2022-11-27-113414 2.zip](https://github.com/PojavLauncherTeam/PojavLauncher_iOS/files/10097947/PojavLauncher-2022-11-27-113414.2.zip)

**Comment by khanhduytran0** [comment]
wrong memory protection
```
--->  __TEXT                   12909c000-1290ac000 [   64K] r--/rw- SM=COW  .../libjli.dylib
```
This is a known issue, no idea why as I don’t have an arm64e device with TrollStore. I’ll probably push a hack fix to see what’s next.

**Comment by redderder** [comment]
ok so what should i do

**Comment by khanhduytran0** [comment]
For now the known workaround is [downgrade TrollStore to older version](https://github.com/opa334/TrollStore/releases/download/1.3/TrollStore.tar). I’ll ask TS’s dev about this.

**Comment by redderder** [comment]
wait my trollstore version is 1.3.5 how about i upgrade to 1.4.4

**Comment by redderder** [comment]
well it doesn't work
should i reinstall pojavlauncher after i upgrade？

**Comment by khanhduytran0** [comment]
Should be fixed in the latest build.

**Comment by redderder** [comment]
you mean pojavlauncher's build or TrollStore's ?

**Comment by khanhduytran0** [comment]
There was an issue in dylib, you can now use latest TrollStore version to install without Java 17 issues. You’ll need PojavLauncher v2.1-rc2 or newer.
