### ISSUE TITLE
[Bug] Unable to turn camera with mouse on iPhone

### ISSUE THREAD

**Issue by NoviceXiaoren** [PojavLauncherTeam/PojavLauncher_iOS#437]
### Describe the bug

Can't use the mouse to turn the camera

### The log file and images/videos

I don't know why I can't upload videos

### Steps To Reproduce

```markdown
Try mouse manipulation
```

### Expected Behavior

It can fix the problem of mouse rotation angle

### Platform

```markdown
- Device model: iPhone se2
- iOS version: 15.0.1
- PojavLauncher version: 83a59948815e004820d5ffa3ae47def3b6ba5088
```

**Comment by khanhduytran0** [comment]
Does the cursor move when paused?

**Comment by NoviceXiaoren** [comment]
doesn't
> Does the cursor move when paused?

**Comment by khanhduytran0** [comment]
Try opening launcher settings and back to see if cursor moves

**Comment by NoviceXiaoren** [comment]
I tried before. But now I don't know, because I'm in the hospital.It may be my system problem, because I always don't know why the cursor has all kinds of strange problems.

> Try opening launcher settings and back to see if cursor moves

**Comment by GaucovyAero** [comment]
should be resolved
