### ISSUE TITLE
[Bug] <Short description>

### ISSUE THREAD

**Issue by LeonVN210** [PojavLauncherTeam/PojavLauncher_iOS#439]
### Describe the bug

when sprint pri is switch to sec and when aim to enemy or want to break block it switch back

### Steps To Reproduce

```markdown
1. hold W and crt
2.press pri
``

### Platform

```markdown
- Device model: iPhone 7
- iOS version: 15.7.1
- PojavLauncher version: pre-release 2 2.1
```

**Comment by khanhduytran0** [comment]
This is not Bedrock Edition. Bedrock touchscreen gestures don’t apply here. PojavLauncher maps touchscreen input to keyboard/mouse, so it has no idea on when you point the camera to entity, block or air unless mod installed or a screen reader.
