### ISSUE TITLE
PojavLauncher installs Minecraft but opens up the arrow controls without showing any UI

### ISSUE THREAD

**Issue by JforJason101** [PojavLauncherTeam/PojavLauncher_iOS#44]
As the title reads
![image](https://user-images.githubusercontent.com/32575402/107858712-e667af00-6df2-11eb-8016-d4fd658897fe.png)

**Comment by khanhduytran0** [comment]
Send latestlog.txt

**Comment by JforJason101** [comment]
> Send latestlog.txt

Nevermind, it works now. But anyways, how do you install optifine, or just make it run faster?

**Comment by khanhduytran0** [comment]
I will write tutorial then. But now you can install fabric first

**Comment by JforJason101** [comment]
> I will write tutorial then. But now you can install fabric first

How does that work? Like how do you install fabric?

**Comment by khanhduytran0** [comment]
Check https://github.com/PojavLauncherTeam/PojavLauncher_iOS/wiki/Installing-Fabric
I just also added instruction installing Sodium, a Fabric optimizer mod.

**Comment by JforJason101** [comment]
Ok thanks
