### ISSUE TITLE
m2 pad

### ISSUE THREAD

**Issue by Epicfb** [PojavLauncherTeam/PojavLauncher_iOS#441]
### Describe the bug

m2 ipad laggy on this
but m1 ipad is not
why

### Steps To Reproduce

```markdown
w
```

### Expected Behavior

w

### Platform

```markdown
- Device model: 
- iOS version: 
- PojavLauncher version:
```

### Anything else?

w

**Comment by khanhduytran0** [comment]
Not enough info
