### ISSUE TITLE
[Bug] forge launch crash

### ISSUE THREAD

**Issue by blueghost42** [PojavLauncherTeam/PojavLauncher_iOS#443]
### Describe the bug

Crash when launch forge 1.8.9

### Steps To Reproduce

```markdown
1. Start Povjav launcher
2. Download forge jar file
4. Install forge 1.8.9 in Pojav launcher
3. Run forge 1.8.9 version
4. Crash
```

### Expected Behavior

Expected to launch forge 

### Platform

```markdown
- Device model: iPhone 13
- iOS version: 16
- PojavLauncher version: 1.3
```

**Comment by khanhduytran0** [comment]
> The log file and images/videos
> No response

Also, make sure to check that you got `installer`, not `universal`. `universal` is only for server, which isn’t the case here.

**Comment by khanhduytran0** [comment]
version is invalid: you can’t install a version that required jailbreak (1.3), and also outdated.

**Comment by blueghost42** [comment]
Actually i dont really know what version i installed and yea i chose installer not server. Where can i check my game version?

**Comment by blueghost42** [comment]
https://user-images.githubusercontent.com/64053412/206896340-e0173f93-e674-42ff-9cb7-a959e2b68470.mp4

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher_iOS/files/10201813/latestlog.txt)

here is a video of me reproducing the bug and the crash log file

**Comment by khanhduytran0** [comment]
You’re using outdated build. Update to 2.1 and try again.

**Comment by crystall1nedev** [comment]
Closing due to outdated build. Reopen if issue is still present on the latest release/nightlies.
