### ISSUE TITLE
[Bug] Crashing right before game starts. iOS 13.41 

### ISSUE THREAD

**Issue by ChefPooH** [PojavLauncherTeam/PojavLauncher_iOS#444]
### Describe the bug

When I click play on any version, it loads all the way, but as soon as it finishes, a black screen pops up and I get this message saying “Game exited with code 1” ... (latestlog.txt). The only way out is to force close. I’m on a jail broken (uncOver) iPhone SE 2020 on iOS 13.4.1 and six have jit enabled. I’ve also allocated twice the ram to see if that was the problem but it wasn’t. 

### The log file and images/videos

![C759D323-8B39-481B-9708-6837176E9AB0](https://user-images.githubusercontent.com/81269120/206931269-f2277905-472f-4a67-b3ae-40437fd91af2.png)

### Steps To Reproduce

```markdown
Start PojavLauncher
Make sure you’re signed in
Go on any Minecraft version
Click play
See message
```

### Expected Behavior

I expected the game to start running after downloading a version

### Platform

```markdown
- iPhone SE 2020 
- iOS 13.4.1
- 2.1
```

**Comment by khanhduytran0** [comment]
latestlog.txt should have contained something else

**Comment by ChefPooH** [comment]
That's all it said when I copied it but before allocating more ram (738 - 1500), it said 
Error occurred during initialization... 
could not allocate metaspace: 107374

**Comment by GaucovyAero** [comment]
should be resolved i think
