### ISSUE TITLE
[Bug] Optifine 1.18.2

### ISSUE THREAD

**Issue by Titan87zs** [PojavLauncherTeam/PojavLauncher_iOS#445]
### Describe the bug

When I try to use optifine 1.18.2 to log in to the server or create a single-player world, he will exit the game with error code 6 after loading

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher_iOS/files/10207784/latestlog.txt)

### Steps To Reproduce

```markdown
1. Start PojavLauncher
2. Open Optifine 1.18.2_HD_U_H7
3. Create a world
4. Game exited with code 6
```

### Expected Behavior

successfully created the world

### Platform

```markdown
- Device model: iphone 7 plus
- iOS version: 15.1
- PojavLauncher version: Latest Release
```

**Comment by khanhduytran0** [comment]
You need to turn off `Render regions`, multidrawing is currently not supported.

**Comment by Titan87zs** [comment]
> 您需要關閉`Render regions`，目前不支持多圖。

in game video setting?
