### ISSUE TITLE
Black screen version 2.1

### ISSUE THREAD

**Issue by Totodabest** [PojavLauncherTeam/PojavLauncher_iOS#446]
### Describe the bug

When I open the app sometimes, it just appears as a black screen with only the play and select version buttons.

### The log file and images/videos

![360A3802-64F3-4767-9DD0-02D231209954](https://user-images.githubusercontent.com/113480149/207067990-bcc8efd6-085b-4fe4-b206-7af9b29a7581.png)

### Steps To Reproduce

```markdown
Open the app
```

### Expected Behavior

It is supposed to show the options

### Platform

```markdown
- Device model: iPhone SE 2nd gen
- iOS version: 15.2
- PojavLauncher version: 2.1
```

**Comment by Charles3541** [comment]
Having the same problem on an iPhone 6s using iOS 15.7

**Comment by khanhduytran0** [comment]
Known issue on compact-sized iPhone. However, there’s a workaround:
- Rotate to landscape
- Swipe from the left edge, this will make UI appear back
- Head to UI Debugging settings, then enable Unlock iPadOS UI.

**Comment by crystall1nedev** [comment]
Resolved.
