### ISSUE TITLE
Microsoft Login not working.

### ISSUE THREAD

**Issue by FatSandwich** [PojavLauncherTeam/PojavLauncher_iOS#45]
Every time I sign in with Microsoft it says something like "This is should be downloaded from the App Store. Click "Continue" if it is." Then when I click continue it takes me back to the launcher and the launcher freezes and nothing is clickable. Then when I restart the launcher it does the same thing and nothing shows up in "Select Accounts".

**Comment by khanhduytran0** [comment]
Can you send latestlog.txt?

**Comment by khanhduytran0** [comment]
@FatSandwich reply?

**Comment by Darthveder69420** [comment]
Does bedrock Microsoft account work on Java ?

**Comment by khanhduytran0** [comment]
> Does bedrock Microsoft account work on Java ?

Bedrock and Java are different product.

**Comment by Darthveder69420** [comment]
Do you need to pay for a Java account ?

**Comment by khanhduytran0** [comment]
Yes, otherwise use "Offline account" where most servers such as Hypixel could not be join.

**Comment by Darthveder69420** [comment]
Ok thanks!

**Comment by recklessking** [comment]
Happens to me too. Anyone know a fix?how Do I get lastetlog.txt

**Comment by khanhduytran0** [comment]
Haven’t you bought Minecraft?
@FatSandwich reply?

**Comment by elvistrujanovic51** [comment]
> Does bedrock Microsoft account work on Java ?

Yes - check with your original Minecraft PC Launcher if you buy Minecraft (Java Edition) with Microsoft account but I bought an account for minecraft (Java edition), but they won't sign me in via Mojang or Microsoft with this PojavLauncher (Only working on pc)

**Comment by elvistrujanovic51** [comment]
> Does bedrock Microsoft account work on Java ?

Yes - check with your original Minecraft PC Launcher if you buy Minecraft (Java Edition) with Microsoft account but I paid an account for minecraft (Java edition), but they won't sign me in via Mojang or Microsoft with this PojavLauncher (Only working on pc)

**Comment by FatSandwich** [comment]
> Haven’t you bought Minecraft?
> @FatSandwich reply?

I haven't bought it!

**Comment by khanhduytran0** [comment]
Mojang moving to Microsoft account does not make Minecraft become free.

**Comment by admin-elvistrujanovic** [comment]
> Mojang moving to Microsoft account does not make Minecraft become free.

No

**Comment by admin-elvistrujanovic** [comment]
> Mojang moving to Microsoft account does not make Minecraft become free.

Free trial (limited) only
