### ISSUE TITLE
[Bug] <Short description>

### ISSUE THREAD

**Issue by Maycolabr** [PojavLauncherTeam/PojavLauncher_iOS#461]
### Describe the bug

DARK SCREEN BUG IN IOS 16 ON IPHONE 12

### The log file and images/videos

No

### Steps To Reproduce

```markdown
…
```

### Expected Behavior

…

### Platform

```markdown
- Device model: Iphone 12
- iOS version: 16
- PojavLauncher version: 2.1.1
```

### Anything else?

..

**Comment by khanhduytran0** [comment]
Incomplete info. No logs and screenshots sent.
