### ISSUE TITLE
[Bug] PojavLauncher still thinks I did not install fabric when I install fabric

### ISSUE THREAD

**Issue by Jadon67** [PojavLauncherTeam/PojavLauncher_iOS#462]
### Describe the bug

I Installed fabric on PojavLauncher on a Local account because I can’t use safari for no reason and when I click I play, PojavLauncher thinks it’s not installed. Please fix this bug.

iPadOS Version: 15.3.1
Method installed: TrollStore

### Steps To Reproduce

```markdown
1.Start PojavLauncher 
2. Install fabric 
3. click on play
```

### Expected Behavior

I expect the game to play.

### Platform

```markdown
- Device model: iPad Pro (11-inch) (3rd generation)
- iOS version: 15.3.1 
- PojavLauncher version:2.1.1
```

**Comment by khanhduytran0** [comment]
Do you think that you changed version afterwards? :eyes:
![C5270F62-A2D8-4CC2-9CE5-51672D4C3D2A](https://user-images.githubusercontent.com/40482367/209162858-76f078b9-c0bd-434d-83ea-6cbb5df952a2.jpeg)
At the moment, PojavLauncher doesn’t automatically change as we have yet added profile-based management layer as Android (at the moment it’s managed through manually-created instances)

Also, with local account, you won’t get any far. Downloading files is not available for it.
