### ISSUE TITLE
[Bug] Unjailbroken status while Sideloaded on Mac using PlayCover

### ISSUE THREAD

**Issue by amirsaam** [PojavLauncherTeam/PojavLauncher_iOS#467]
### Describe the bug

While testing Pojav in PlayCover we encountered that Pojav thinks it's an Unjailbroken device (while we had trouble to other apps not noticed it's jailbroken) and wants to check out on AltJit that should not be required at all on Mac.

Plus, Pojav window size couldn't be handled with PlayCover's PlayTools and mouse clicks are not recognised. I suspect that there are some tweaks that have been done on Pojav side, (it would be lovely to guide us through) and we needed to remove PlayTools to make Pojav window correct and make mouse work.

### The log file and images/videos

<img width="1315" alt="Screenshot 1401-10-07 at 09 17 37" src="https://user-images.githubusercontent.com/1331289/209765101-e9a01ac8-d689-4090-8c7f-43fe51428237.png">

### Steps To Reproduce

```markdown
1. Install PojavLauncher on Mac using [PlayCover](https://github.com/PlayCover/PlayCover)
2. Open PojavLauncher
3. If you installed PlayTools through install you see window is not adjusted and mouse clicks are not recognised
5. You'll see PojavLauncher is trying to connect to JIT and detects device as Unjailbroken

For making window adjusted and make mouse work you need to Right Click on Pojav in App Library of PlayCover > Settings > Miscs > Remove PlayTools and reopen PojavLauncher
```

### Expected Behavior

1. Pojav should detect Mac as Jailbroken
2. Pojav window should be adjustable via PlayTools in PlayCover

### Platform

```markdown
- Device model: M1 MBP 2020
- iOS version: PlayCover iOS: 16.2 - Device macOS: 13.1
- PojavLauncher version: 2.1.1
```

### Anything else?

We know that Minecraft Java Edition is available on macOS, but it would be nice to have PojavLauncher work as good as iOS on macOS.

**Comment by crystall1nedev** [comment]
While I understand the want to have PojavLauncher on macOS, there are more important things for us to focus on at this point, namely a tvOS port given that there is no existing Java Edition launcher for the Apple TV. 

If you want to find the code changes required to make PojavLauncher work correctly on macOS, feel free to and submit a PR. However beyond this there will likely not be activity for a while. Nothing personal, just limited time and deteriorating health make me want to focus on bigger issues.

Also, unless you guys do some magic with debugging behind the scenes, flipping to Jailbroken won’t do much as JIT hasn’t been enabled. Unsure if PlayCover does anything in that degree as I don’t use it or an Apple Silicon machine, just take that into account.

**Comment by amirsaam** [comment]
Understandable,
Can you give us hints about where should we look into?
Like where do you handle these things.

**Comment by crystall1nedev** [comment]
@amirsaam Did a little bit of work in this regard since getting a 2021 16" MacBook Pro, found a few things out.

A few code changes made to support palera1n and fix jailbroken status on Taurine and other jailbreaks that don't set CS_DEBUGGED also happened to fix PlayCover installations. I was able to play without needing to debug manually this way.

The window resizing issue is not an issue with PojavLauncher, it's an issue with PlayTools. I tested a bunch of apps with PlayCover and PlayTools just because I could, and a bunch of them had the same issues with window resizing as PojavLauncher with PlayTools installed. Removing it solved the issue and window resizing worked as normal in all of the apps. I tested Adobe Illustrator, Adobe Photoshop, AmeriCU Credit Union, and GitHub.

**Comment by amirsaam** [comment]
@crystall1nedev may i ask how were you able to run pojav in playcover? in my test no matter what i couldn't run it

**Comment by crystall1nedev** [comment]
> @crystall1nedev may i ask how were you able to run pojav in playcover? in my test no matter what i couldn't run it

Turns out that the app was getting debugged automatically. I've found that to use JIT in iOS apps, you have the same restrictions as iOS. Disabling SIP and running a ptrace() on the executable seemed to work.

**Comment by crystall1nedev** [comment]
JIT restriction would still exist.
