### ISSUE TITLE
[Bug] Zink does not work properly on iOS 16

### ISSUE THREAD

**Issue by Bitboss2** [PojavLauncherTeam/PojavLauncher_iOS#469]
### Describe the bug

My iPad air 4 has a black screen when I press play we have the controllers but no mojang logo just black with any Minecraft version please do something.

### The log file and images/videos

Uploading IMG_0853.MOV…

### Steps To Reproduce

```markdown
1 start pojave 
2. Go to setting 
3 choose render 
4. Use zink meza 21
5. Tap on play button
```

### Expected Behavior

Xxx

### Platform

```markdown
- Device model: iPad Air 4
- iOS version: 16.2
- PojavLauncher version: 2.1 (AltStore latest)
```

**Comment by Bitboss2** [comment]
[](url) https://drive.google.com/file/d/1OV5NgqR5_CYzxhqVBBht6dIbbxEV9JCQ/view?usp=drivesdk

here is the media link to see the bug

**Comment by khanhduytran0** [comment]
Send latestlog.txt

Open Log Output and see what’s happening there.

**Comment by Bitboss2** [comment]
![4263CB5F-ADDB-431B-BBD3-4FD80B88F8FA](https://user-images.githubusercontent.com/121692780/210130634-abe08ccb-857c-4686-8804-ffc8789f74d9.png)
![4D62E345-90DB-4575-B7D9-58E174C6AE9C](https://user-images.githubusercontent.com/121692780/210130638-9dde6fd3-ff73-4e71-a9f3-5d1a1055322e.png)
![8C16148B-60A5-4709-9778-06C590672ACF](https://user-images.githubusercontent.com/121692780/210130642-1f0d06cf-30b3-4fd5-9a64-3c7321120260.png)
![CABBD0DC-B4F2-4CD9-AE2F-40F86D18D512](https://user-images.githubusercontent.com/121692780/210130643-aac8a0a3-544f-4b58-b8db-9da1bd466cc3.png)
![3CA39663-7F65-43CD-92D9-11024C1AB353](https://user-images.githubusercontent.com/121692780/210130645-c2ffa570-f8ac-4bb9-b8f3-d2af4208155c.png)
Here’s the log it was blocked on optimisations during 30 min

**Comment by Bitboss2** [comment]
I tested with all Minecraft version but it’s the same optimisation message

**Comment by Bitboss2** [comment]
![8B8A16C2-55A5-43AA-A9A9-D7B412739C27](https://user-images.githubusercontent.com/121692780/210153991-539c4736-a013-4389-a8fd-0d2f8f541606.png)

**Comment by Bitboss2** [comment]
Afer 2 days trying to solve this problem realized the sound is working. When I on the screen randomly I hear the Minecraft button song.

**Comment by MythicGithub** [comment]
Same error with me

**Comment by MythicGithub** [comment]
[latestlog.old.txt](https://github.com/PojavLauncherTeam/PojavLauncher_iOS/files/10329314/latestlog.old.txt)

**Comment by IrvinK02** [comment]
Same issue,
Device: iPhone 14 Pro Max, iOS 16.2 (20C65)
PojavLauncher Version: 2.1.1

Something I want to note, I saw on a YouTube video (https://www.youtube.com/watch?v=dWAi3XOshpg) where it was run successfully with shaders, the Mesa version was 22.1.2 on pojavlauncher version 2.1, I tried both version 2.1, and 2.1.1, but it shows as Mesa version 21.0 for me in both.

[latestlog.old.txt](https://github.com/PojavLauncherTeam/PojavLauncher_iOS/files/10329665/latestlog.old.txt)

**Comment by kwankiu** [comment]
Same issue with both iPhone 14 Pro and iPad Air M1

**Comment by Tatouu14** [comment]
The black screen is because zink in ios 16 is not compatible, I don't know why, but in ios 15 it is compatible.

**Comment by abhishekgi** [comment]
I am also facing same issue

**Comment by abhishekgi** [comment]
When I launch game with Zink renderer the screen remain black for all time however I noticed sound of game come and when I randomly tap on button the button tapping sound also come but screen remain totaly black my ios version is ipados 16.2.

**Comment by crystall1nedev** [comment]
This is a known issue with Zink on iOS 16. Comments saying "It also happens to me" or reiterating the issue are not needed, thank you!

**Comment by Monke132** [comment]
Can this help?

[UTM Mesa Black Screen](https://github.com/utmapp/UTM/issues/4983)

**Comment by crystall1nedev** [comment]
> Can this help?
> 
> [UTM Mesa Black Screen](https://github.com/utmapp/UTM/issues/4983)

While your comment is appreciated it doesn't. That bug also affects macOS Big Sur and Monterey (equivalent to iOS 14 and iOS 15 in this case.)

It's also caused by the *guest* operating system's Mesa version... too many variables here.

**Comment by Monke132** [comment]
> > Can this help?
> > [UTM Mesa Black Screen](https://github.com/utmapp/UTM/issues/4983)
> 
> While your comment is appreciated it doesn't. That bug also affects macOS Big Sur and Monterey (equivalent to iOS 14 and iOS 15 in this case.)
> 
> It's also caused by the _guest_ operating system's Mesa version... too many variables here.

Ok Thanks

**Comment by SueYanr** [comment]
When can fix it?

**Comment by NuraadGit** [comment]
LETS GOOOOOOOOOOOOOOOO

**Comment by frankpadada** [comment]
Hope the fix can be released soon 😉
