### ISSUE TITLE
warning: could not load inserted library '/usr/lib/TweakInject.dylib' into hardened process because image not found

### ISSUE THREAD

**Issue by Axgk23** [PojavLauncherTeam/PojavLauncher_iOS#47]
![D1EA9023-862C-4E8B-BD11-5EC211A54AE3](https://user-images.githubusercontent.com/35518105/107862966-8f77cf00-6e1e-11eb-8ece-71a7cb14b0be.png)

im probably being stupid but i just wanna play on my friends java server ;-;

**Comment by Axgk23** [comment]
Ok i somehow fixed that, but now theres this 
![64ED6056-3B10-4DE8-BA76-AD11E593DF39](https://user-images.githubusercontent.com/35518105/107863403-285c1980-6e22-11eb-8881-f749a2ac84d4.png)


and nothing is in any of the folders to edit versions

**Comment by khanhduytran0** [comment]
Edit version is here
![Uploading EEDF2CCC-5953-4D5E-8310-E7AE7126F543.png…]()

**Comment by khanhduytran0** [comment]
![AD9488FA-25CD-44D4-9D14-0C967387A6D3](https://user-images.githubusercontent.com/40482367/107864194-6ee65e00-6e8c-11eb-8494-58d457eef98b.png)
