### ISSUE TITLE
[Bug] No mods in the mods menu in Minecraft 1.12.2 forge local account 

### ISSUE THREAD

**Issue by Jadon67** [PojavLauncherTeam/PojavLauncher_iOS#473]
### Describe the bug

I added one mod that I need, but the mod can’t be seen.
I NEED THAT MOD. I REALLY NEED IT!

### The log file and images/videos

![9BCEDB31-FB7A-445C-ADF2-FB3E8C4E4222](https://user-images.githubusercontent.com/102257451/210448049-6e44fa22-6cf1-4098-8f6f-35502335b5ea.png)

### Steps To Reproduce

```markdown
1. Start PojavLauncher.
2. Start Minecraft 1.12.2 forge. 
3. Go to mods menu. 
4. Try to find the mod.
```

### Expected Behavior

I expect the mod to be there.

### Platform

```markdown
- Device model: iPad Pro (11-inch) (3rd generation)
- iOS version: 15.3.1
- PojavLauncher version: 2.1.1 —-latest
```

**Comment by Jadon67** [comment]
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher_iOS/files/10340079/latestlog.txt)

**Comment by GaucovyAero** [comment]
```[21:56:04] [Client thread/WARN]: Zip file retro64-1.0.9.jar failed to read properly, it will be ignored```
retro64 ships with libraries for Windows only, you can't run it on Android

**Comment by khanhduytran0** [comment]
> you can't run it on Android
iOS isn’t Android bruh

**Comment by GaucovyAero** [comment]
> > you can't run it on Android
> 
> iOS isn’t Android bruh

he still cant play it

**Comment by crystall1nedev** [comment]
No support for local accounts. You are on your own.
