### ISSUE TITLE
My game crash with code 1

### ISSUE THREAD

**Issue by PsanesX** [PojavLauncherTeam/PojavLauncher_iOS#474]
### Describe the bug

![03F66D45-1478-4B3A-9045-13779F9E8D7D](https://user-images.githubusercontent.com/120598400/210512032-2e32e1af-50b5-4b39-9ed4-f22ed37b8c7e.png)

### Steps To Reproduce

```markdown
O
```

### Expected Behavior

No

### Platform

```markdown
- Device model: 
- iOS version: 
- PojavLauncher version:
```

**Comment by crystall1nedev** [comment]
You have repeatedly opened issues with little information that we can go on, and have ignored our requests for more information. I’m blocking you from creating issues and pull requests due to this.
