### ISSUE TITLE
Forge 1.12.2 downloading Error

### ISSUE THREAD

**Issue by l9njiezxc** [PojavLauncherTeam/PojavLauncher_iOS#478]
### Describe the bug

I downloaded forge 1.12.2.jar and PojavLauncher give error to me, after Appeared black screen.
![65313516-8F38-4F51-8440-99411E359C85](https://user-images.githubusercontent.com/122044955/211218356-fe2decea-9162-47fd-86f2-cd2afaeb9b80.png)

### The log file and images/videos

java.lang.ClassNotFoundException: net.minecraft.client.Main
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:419)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:352)
	at net.kdt.pojavlaunch.uikit.UIKit.callback_JavaGUIViewController_launchJarFile(UIKit.java:87)
	at net.kdt.pojavlaunch.PojavLauncher.main(PojavLauncher.java:53)

### Steps To Reproduce

```markdown
1. Start PojavLauncher 
2. Downloaded forge 1.12.2.jar
3. Bruh error, black screen
```

### Expected Behavior

X

### Platform

```markdown
- Device model: iPhone XR
- iOS version: 16.2
- PojavLauncher version: 2.1
```

**Comment by khanhduytran0** [comment]
It looks like you tried to launch the client file instead of Forge installer.

**Comment by l9njiezxc** [comment]
> It looks like you tried to launch the client file instead of Forge installer.

how to install Forge?

**Comment by Valdex** [comment]
Same problem, iPad Air 4, iOS 16.2
