### ISSUE TITLE
Can’t download with scarlet

### ISSUE THREAD

**Issue by Thebelg** [PojavLauncherTeam/PojavLauncher_iOS#479]
### Describe the bug

When the installation ends, the launcher does not start and has such an icon next to the name 
![0A0E3F36-9BA0-4BC3-8477-11C8D4B602B2](https://user-images.githubusercontent.com/122259937/211264184-a7a2cd21-dba7-4021-9a35-088889a57ad8.jpeg)

### Steps To Reproduce

```markdown
1. Start scarlet
2. Select .ipa file of pojav launcher
3.wait for installing
```

### Expected Behavior

I can’t open launcher

### Platform

```markdown
- Device model: IPad pro 3 generation
- iOS version: 16 
- PojavLauncher version: 2.1.2
```

**Comment by abhishekgi** [comment]
First intall esign ipa using scarlet

**Comment by abhishekgi** [comment]
Then import pojav launcher ipa in esign and click on unzip then click on payload then click on pojav launcher ipa and click on sign 
After signing complete click on install button that appears

**Comment by abhishekgi** [comment]
After that launcher will open but

**Comment by abhishekgi** [comment]
You have to find a way to enable jit

**Comment by abhishekgi** [comment]
But make sure that before installing the pojav launcher with esign delete the existing pojav launcher

**Comment by crystall1nedev** [comment]
See #477
