### ISSUE TITLE
[Bug] Crash with Exit code 6 when entering skyblock

### ISSUE THREAD

**Issue by billyau615** [PojavLauncherTeam/PojavLauncher_iOS#480]
### Describe the bug

Entering Hypixel SkyBlock results in a crash. Thank you.

### The log file and images/videos

[
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher_iOS/files/10387896/latestlog.txt)
](url)

### Steps To Reproduce

```markdown
1. Start PojavLauncher with 1.8.9 or 1.12.2 Vanilla (only tested with these 2 versions)
2. Join Hypixel, then enter SkyBlock
3. Wait for a minute 
4. Crashed with Exit code 6
```

### Expected Behavior

I expect it can run correctly without crashing.

### Platform

```markdown
- Device model: iPad 9 (2021)
- iOS version: 16.2
- PojavLauncher version: 2.1.2-release
```

**Comment by khanhduytran0** [comment]
This appears to be another memory issue in gl4es/ANGLE. will probably look into it then

**Comment by billygor123** [comment]
Thank you for your reply, may I ask are there any alternative method to solve it temporarily?

**Comment by billygor123** [comment]
Some extra information: only gl4es works and angle (exit code 6) and zink (blackened screen, can hear sound) doesn't. It that possible to make angle or zink work so I can get rid of this issue? Thank you.

**Comment by khanhduytran0** [comment]
ANGLE only supports 1.17+. Zink is currently broken on iOS 16. We might probably trying with latest Zink, if performance is acceptable.
Could you try tinkering with game settings, such as disabling VBO?

**Comment by billygor123** [comment]
Got it. I will try to make some adjustments. Thank you very much.
