### ISSUE TITLE
[错误] <简短描述>

### ISSUE THREAD

**Issue by CSLjiaowo** [PojavLauncherTeam/PojavLauncher_iOS#483]
### Describe the bug

不能在聊天栏打出中文字符

### Steps To Reproduce

```markdown
在键盘上拼写出了中文，但是聊天栏却没有显示
```

### Expected Behavior

我希望可以修复这个问题

### Platform

```markdown
- Device model: 
- iOS version: 
- PojavLauncher version:
```

**Comment by Zhou-Shilin** [comment]
i met the same problem, but this issue does not conform to the regulations, many spaces are not filled in. i opened a new [issue](https://github.com/PojavLauncherTeam/PojavLauncher_iOS/issues/487) and plz close yours
