### ISSUE TITLE
[Bug] <Short description>

### ISSUE THREAD

**Issue by JuiceQPS** [PojavLauncherTeam/PojavLauncher_iOS#484]
### Describe the bug

When i try to enter in a multiplayer server with a resourcepack, the game crash with code 6

### The log file and images/videos

[latest.log](https://github.com/PojavLauncherTeam/PojavLauncher_iOS/files/10420503/latest.log)

### Steps To Reproduce

```markdown
1. Start PojavLauncher

2. Start 1.17.1

3. Try to enter in the server
```

### Expected Behavior

I expect the game to enter in the server without crash

### Platform

```markdown
- Device model: IPhone 13
- iOS version: 16.1.2
- PojavLauncher version: 1.17.1
```

**Comment by khanhduytran0** [comment]
latest.log doesn’t contain error info. Send latestlog.txt

**Comment by GaucovyAero** [comment]
gl4es cannot convert shaders on ios
