### ISSUE TITLE
[Reappeared] [Bug] Cannot type Chinese in chat

### ISSUE THREAD

**Issue by Zhou-Shilin** [PojavLauncherTeam/PojavLauncher_iOS#487]
### Describe the bug

_This issue happened again in the latest version [2.1.3](https://github.com/PojavLauncherTeam/PojavLauncher_iOS/releases/tag/v2.1.3)._  

**I can't type Chinese in the chat.**

We use Pinyin to type Chinese, like this:
![IMG_6500](https://user-images.githubusercontent.com/86581525/212906450-5e4410ab-5a25-4f07-93d2-38554b5a9ec4.jpeg)
When i point the button “你好”, the Pinyin which i just type "ni hao" change to 你好 in normal. But it doesn't work on Pojavlauncher.

_My english is not very well, so these words may be strange_

### The log file and images/videos

https://user-images.githubusercontent.com/86581525/212908209-6327cf68-b6fe-430c-b12f-54a2312af0cc.MOV

### Steps To Reproduce

```markdown
1. Start Pojavlauncher 
2. Try to type chinese
```

### Expected Behavior

Chinese appears in the chat

### Platform

```markdown
- Device model: iPad Air 5
- iOS version: iOS16.2 Beta2
- PojavLauncher version: [Latest Release]
```

### Anything else?

no

**Comment by khanhduytran0** [comment]
Could you try the latest build? it should work now but I'm unsure about stability.

**Comment by Zhou-Shilin** [comment]
> Could you try the latest build? it should work now but I'm unsure about stability.

i'll try it later, thanks :)

**Comment by Zhou-Shilin** [comment]
it works well now, thx!

**Comment by Zhou-Shilin** [comment]
This issue reappeared in the latest version [2.1.3](https://github.com/PojavLauncherTeam/PojavLauncher_iOS/releases/tag/v2.1.3).

**Comment by khanhduytran0** [comment]
v2.1.3 is out of date (Jan 17) compared to when the fix commit was introduced (Jan 19).

**Comment by Zhou-Shilin** [comment]
> v2.1.3 is out of date (Jan 17) compared to when the fix commit was introduced (Jan 19).

Shall I try the dev build in actions?

**Comment by khanhduytran0** [comment]
You did it before, but now you returned to the older build so of course the issue came back. Use v2.2.

**Comment by Zhou-Shilin** [comment]
> You did it before, but now you returned to the older build so of course the issue came back. Use v2.2.

OK, i see. I am using sidestore source so it returned to the old build... Thanks!
