### ISSUE TITLE
[Bug] Pojav crashes when I press anything while running Minecraft

### ISSUE THREAD

**Issue by C0LoRzz** [PojavLauncherTeam/PojavLauncher_iOS#489]
### Describe the bug

Pojav crashes when I touch the screen during minecraft running

### The log file and images/videos

[latestlog.old.txt](https://github.com/PojavLauncherTeam/PojavLauncher_iOS/files/10448557/latestlog.old.txt)

https://user-images.githubusercontent.com/90789453/213239147-78fc54d8-3611-44d2-8d1e-73e09674233e.MP4

### Steps To Reproduce

```markdown
1. Start PojavLauncher
2. Launch 1.8.9 Minecraft
3. Wait till minecraft shows up
4. Touch the screen
```

### Expected Behavior

I expect it to not crash.

### Platform

```markdown
Device: IPad Air 2
IOS version: 15.0
PojavLauncher version: 2.1.3-release (2.1.3-legacy/cc887c3)
Ram Allocated: 1096 MB
Minecraft Version: 1.8.9 vanilla
Jailed: Yes
Installed through: TrollStore, Sileo (repo: palera1n strap)
Jailed by: palera1n
```

**Comment by khanhduytran0** [comment]
Did you get any Cr4shed report?

**Comment by C0LoRzz** [comment]
with debug enabled:
[latestlog.old 3.txt](https://github.com/PojavLauncherTeam/PojavLauncher_iOS/files/10453620/latestlog.old.3.txt)

**Comment by khanhduytran0** [comment]
Still, there isn't any trace of crash in the log.
Install Cr4shed from Sileo and then reproduce the issue to generate a report file.

**Comment by C0LoRzz** [comment]
> Did you get any Cr4shed report?

There’s no crash report even after I installed Cr4shed

**Comment by C0LoRzz** [comment]
[text.txt](https://github.com/PojavLauncherTeam/PojavLauncher_iOS/files/10465424/text.txt)
I have it now

**Comment by khanhduytran0** [comment]
> Process: cryptexd

this is wrong process

**Comment by saodMinecarft01** [comment]
Please help I also have this issue 
Platform
iOS 15.7.1 
Jailed: Yes
Installed through: TrollStore, Sileo (repo: palera1n strap)
Jailed by: palera1n
maybe because of palera1n

**Comment by Yan-Jobs** [comment]
I fixed it by using the mouse. Then it worked !

**Comment by saodMinecarft01** [comment]
Good news I fixed the problem using 3.0 dev version in the actions tap and then set the render to zink

**Comment by Piipperi** [comment]
I have a similar issue, with 1.8.9 if I move my mouse it crashes instantly. With 1.19.4 I can’t do much neither, it crashes only a few seconds into the game. Also using iPad Air 2 with Palera1n

**Comment by Squidtito** [comment]
I fixed it by using Java 17 in the settings.
