### ISSUE TITLE
iPhone 5s, IOS 12.4.9 crashing after clicking "play"

### ISSUE THREAD

**Issue by Skierman** [PojavLauncherTeam/PojavLauncher_iOS#49]
Hi, 
When using this on IOS 12.4.9 on an iPhone 5s, the app crashes shortly after clicking the play button. It has downloaded already but I am not able to play.

**Comment by khanhduytran0** [comment]
Could you send latestlog.txt?

**Comment by Skierman** [comment]
Where can I find that?

**Comment by khanhduytran0** [comment]
It’s on /var/mobile/Documents/minecraft/latestlog.txt

also try https://github.com/PojavLauncherTeam/PojavLauncher_iOS/actions/runs/567549911

**Comment by Skierman** [comment]
Yep that fixes it. Thanks!
