### ISSUE TITLE
[Bug] error when download

### ISSUE THREAD

**Issue by quocn9043** [PojavLauncherTeam/PojavLauncher_iOS#492]
### Describe the bug

![F8EEBC7F-70C2-4B8C-AC06-080D8A24602E](https://user-images.githubusercontent.com/94427163/213861534-146d69be-1d9a-4001-9c71-0a74dee23373.jpeg)

### Steps To Reproduce

```markdown
Install and get this error
```

### Expected Behavior

Idk

### Platform

```markdown
- Device model: iphone xs
- iOS version: 16.1 
- PojavLauncher version: New
```

### Anything else?

This error also occurs on my iphone 7, ver 15.7 ios

**Comment by l9njiezxc** [comment]
You can try download PojavLauncher.ipa

**Comment by thedirptastic** [comment]
Try running altserver as an administrator.

**Comment by crystall1nedev** [comment]
Not an issue with PojavLauncher itself but the installation. Follow what thedirptastic said above to see if it helps, nothing we can do otherwise.
