### ISSUE TITLE
[F-Req] Add MCPE buttons. 

### ISSUE THREAD

**Issue by thedirptastic** [PojavLauncherTeam/PojavLauncher_iOS#495]
### Is this request related to a bug?

You should add the in-game GUI from MCPE.

### Describe the request.

My one dislike about pojavlauncher is how the in-game button looks nothing like the game. It would be a very nice change for the buttons to match the pixel art style of the game (like MCPE).

**Comment by GaucovyAero** [comment]
this would mean super low framerate in the case of pojav, so no

**Comment by thedirptastic** [comment]
> this would mean super low framerate in the case of pojav, so no

How would this affect the framerate?

**Comment by crystall1nedev** [comment]
I might look into this, but don't get your hopes up too much. We would need to create the buttons ourselves to not infringe on Microsoft's copyrights, and I have no idea what this would mean for memory usage because we would need to load images in place of simple text.

**Comment by crystall1nedev** [comment]
Clsoing as not planned, for the reasons I listed above.
