### ISSUE TITLE
[Error] <Short description> Mouse pulley has no effect in the game

### ISSUE THREAD

**Issue by John021001** [PojavLauncherTeam/PojavLauncher_iOS#497]
### Describe the bug

Mouse pulley is not available in the game.

### Steps To Reproduce

```markdown
1 Open the launcher

2 Open the map

3 Use mouse pulleys
```

### Expected Behavior

I hope the mouse pulley works.

### Platform

```markdown
- Device model: iPad pro2021
- iOS version: iPadOS16.2
- PojavLauncher version: 2.1.3
```

### Anything else?

iPadPro 2021, equipped with Forge and 45 other MODs, the mouse and keyboard use external OTG, the game version is 1.12.2, the launcher version is 2.1.3, and the touch is turned off in the game.

In addition, the launcher developed by the author is really easy to use. I am very grateful to the author.

**Comment by Zhou-Shilin** [comment]
建议将标题修改为 _[Bug] The mouse pulley is not working_
最好用英文提交issue，这会让开发者更好的理解你的问题并尽快修复 XD
