### ISSUE TITLE
Fabric crashes on 1.16.5

### ISSUE THREAD

**Issue by IvanKulagin** [PojavLauncherTeam/PojavLauncher_iOS#50]
I've installed Fabric on 1.16.5 according to this [instruction](https://github.com/PojavLauncherTeam/PojavLauncher_iOS/wiki/Installing-Fabric), but it keeps crashing
Here is the [latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher_iOS/files/5977535/latestlog.txt)

**Comment by khanhduytran0** [comment]
You've missed a step: create `launcher_profiles.json` before installing Fabric.

**Comment by IvanKulagin** [comment]
> You've missed a step: create `launcher_profiles.json` before installing Fabric.

Nope, here it is (had to rename to .txt since github doesn't want to upload .json)
[launcher_profiles.txt](https://github.com/PojavLauncherTeam/PojavLauncher_iOS/files/5977680/launcher_profiles.txt)

**Comment by khanhduytran0** [comment]
Try to re-install Fabric.

**Comment by IvanKulagin** [comment]
Apparently, the issue was that I've installed everything from root over SSH and because of that there was something wrong with file permissions. Thanks for help anyway!
