### ISSUE TITLE
[Bug] <Don’t See Login Button>

### ISSUE THREAD

**Issue by FouZzKiNg** [PojavLauncherTeam/PojavLauncher_iOS#504]
### Describe the bug

![4EDDA772-F729-47B5-9A3A-EB41E36F95AF](https://user-images.githubusercontent.com/109780240/216997410-2257147e-9973-4f25-9a3f-efe3d2dda3e2.png)

[Bug] <After Install The Open The App I See Version And Play Button Don’t See Place To Login Account>
Device IPhone X
Version 15.4.1
Install By TrollStore

### The log file and images/videos

![E96FB8A0-E52E-478C-8517-468A9324C0D2](https://user-images.githubusercontent.com/109780240/216997808-3fc0414a-7625-4a7f-ac66-e05419a898e3.png)

### Steps To Reproduce

```markdown
Can’t find login button
```

### Expected Behavior

Can’t Find Login Account Button

### Platform

```markdown
- Device model: IPhone X
- iOS version: 15.4.1
- PojavLauncher version: 2.1
```

### Anything else?

Nothing

**Comment by khanhduytran0** [comment]
Known issue. Swipe from the left edge to reveal missing UI. Enable `unlock iPadOS UI` under UI Debugging settings to workaround it.
