### ISSUE TITLE
[Question] "Payload" doesn't exist

### ISSUE THREAD

**Issue by RealJitR** [PojavLauncherTeam/PojavLauncher_iOS#505]
### Ask the question here.

How to fix "Payload" doesn't exist?  ![5B08ACC4-14AF-4075-99CE-D08609A1E8AF](https://user-images.githubusercontent.com/124596322/217010378-c3269d76-9fe1-4f67-b156-cd4d560e756b.jpeg)

**Comment by khanhduytran0** [comment]
You tried to install something not an IPA, or modified.
