### ISSUE TITLE
Add the ability to exit the game without quitting PovajLaucher

### ISSUE THREAD

**Issue by TheOneAndOnly-Loup** [PojavLauncherTeam/PojavLauncher_iOS#506]
### Describe the request.

Add the ability to exit the game without quitting PovajLaucher and without having to re-enable JIT.

**Comment by khanhduytran0** [comment]
Not possible because of how memory is managed. A complete exit is required to clean up allocated memory regions, else there will be memory leaks due to statically allocated memory regions.

**Comment by TheOneAndOnly-Loup** [comment]
> Not possible because of how memory is managed. A complete exit is required to clean up allocated memory regions, else there will be memory leaks due to statically allocated memory regions.

Oh ok! Would this be possible for jailbroken phones tho?

**Comment by khanhduytran0** [comment]
Jailbreak allows JIT already so there is no need to keep app opened.

**Comment by TheOneAndOnly-Loup** [comment]
> Jailbreak allows JIT already so there is no need to keep app opened.

Ok thx!
