### ISSUE TITLE
Switch slot while aiming

### ISSUE THREAD

**Issue by PadaiOS** [PojavLauncherTeam/PojavLauncher_iOS#507]
### Is this request related to a bug?

On PojavLauncher when you have a finger on your screen used to aim around, you can't switch slots at the same time (you need to release the other finger to switch slot). This was the case on older versions of mcpe too but now they changed it.

### Describe the request.

Add a toggle that allows you to aim and switch slot at the same time.

**Comment by khanhduytran0** [comment]
It was supposed to work before but seems to be broken recently. It should now work again. Use the [latest dev build](https://github.com/PojavLauncherTeam/PojavLauncher_iOS/actions/runs/4199071484)
