### ISSUE TITLE
Help pls

### ISSUE THREAD

**Issue by efsane14010** [PojavLauncherTeam/PojavLauncher_iOS#508]
### Describe the bug

![Ekran Resmi 2023-02-18 - 22 28 07](https://user-images.githubusercontent.com/97107742/219884523-478bb558-49a1-4f3c-a79f-17dae708ec6e.png)
App cant be installed because its not verified

### Steps To Reproduce

```markdown
İ open the app and it showed this error
```

### Expected Behavior

İt dont let me open the app

### Platform

```markdown
- Device model: iphone 12
- iOS version: 16.1.1
- PojavLauncher version: latest
```

**Comment by Tatouu14** [comment]
Judging that you installed it from scarlet, that way simply fails when installing pojavlauncher correctly, use another method such as sideoadly or altstore, if you don't know how to do it there are videos on youtube of how to do it, this is one of them I hope it will help you. https://youtu.be/jd3JgMG3RVI

**Comment by efsane14010** [comment]
K thanks : D
