### ISSUE TITLE
Can not play via Lan

### ISSUE THREAD

**Issue by aliszr263** [PojavLauncherTeam/PojavLauncher_iOS#509]
### Describe the bug

I am trying to play modded with my brother. Everything is done correctly.When I am trying to join his world these errors pops up.
![E0090D7B-C4D0-4DEA-BDF4-89DF8EE801D9](https://user-images.githubusercontent.com/125740749/219957740-2efcb499-18b0-4d75-ac4d-31f966b3a34a.png)
![348C5564-F399-4267-9021-83378753BA09](https://user-images.githubusercontent.com/125740749/219957747-71d7eba8-4b2b-463e-ac73-fc0767e6cb71.png)

### The log file and images/videos

There isnt any log

### Steps To Reproduce

```markdown
Because of his world isnt showing on LAN we downloaded Essential mod on 1.16.5 forge.
Added him as friend in game. Hosted my world. Invited him. He tried to join.
```

### Expected Behavior

Expecting two error which I attached
![10CCB3D7-BB3B-44DF-9B48-3760DEF152C6](https://user-images.githubusercontent.com/125740749/219957902-475bf27c-9cec-488e-bb50-d884c06a7eef.png)
![1BBBCEED-3C7A-4E94-A59B-D9F3F0DA2181](https://user-images.githubusercontent.com/125740749/219957909-e7200989-6f62-4401-9042-781ebd18a834.png)

### Platform

```markdown
- Device model: IPad Air 5th gen (We both use)
- iOS version: 16.3.1
- PojavLauncher version: latest release
```

**Comment by khanhduytran0** [comment]
Make sure you’ve granted PojavLauncher for `Local Network` permission.

**Comment by aliszr263** [comment]
Of course i did. I guess Pojav Launcher isnt responsible for javas LAN permission

**Comment by khanhduytran0** [comment]
Send latestlog.txt

**Comment by UchihaSac12** [comment]
> 



> Make sure you’ve granted PojavLauncher for `Local Network` permission.

I also have the same problem as above, specifically when I open the lan network, my computer will see my iphone world, but when my computer opens the lan network, my iphone will not see the computer world and I don't know how to grant Local Network permission so how do I grant Local Network permission?

**Comment by aliszr263** [comment]
Nope this is not a transient problem. It still exists

**Comment by crystall1nedev** [comment]
You still haven't provided any logs to help use diagnose the issue, nor tried the development builds to see if the issue has been fixed.

**Comment by aliszr263** [comment]
If the game produced any logs for this I would send it

**Comment by crystall1nedev** [comment]
PojavLauncher always produces `latestlog.txt`.

**Comment by aliszr263** [comment]
Okay I will send my latest log

**Comment by Nathan12e4** [comment]
Did you fix it guys?

**Comment by CHORAPROiTzTh** [comment]
I can't play via LAN with my brother, we are on the same network and we can't, we use mods and we are on 1.19.2
