### ISSUE TITLE
[Bug] Spiral Knights: unable to login

### ISSUE THREAD

**Issue by SirDank** [PojavLauncherTeam/PojavLauncher_iOS#513]
### Describe the bug

[Steps]
- Successful Install
- Successful Launch

[Bugs]
- Audio gets cut off 8 seconds after launch
- Game continues to run
- Clicking on "Logon" gives the error: "Your client needs to be updated. It will automatically update in just a moment."
- Clicking on "Quit" does nothing

[Preview]
![tmp](https://user-images.githubusercontent.com/52797753/221099831-f62cc9ce-373d-4812-b61b-e3c9e711bc85.jpg)

### The log file and images/videos

[Pre-Init] PojavLauncher version: 2.2-debug, branch: main, commit: c431f9e
[Pre-Init] iPhone 8 with iOS 15.4.1 (TrollStore)
[Pre-init] Entitlements availability:
* com.apple.developer.kernel.extended-virtual-addressing: YES
* com.apple.developer.kernel.increased-memory-limit: YES
* com.apple.private.security.no-sandbox: YES
* dynamic-codesigning: NO
Debug log enabled: YES
[Pre-init] Restored preference: MULTI_DIR is set to spiral
[Pre-init] no-sandbox: YES, trying to enable JIT
calling ptrace(PT_TRACE_ME)
[Pre-init] JIT has been enabled with PT_TRACE_ME
[MCDL] Warning: couldn't find SHA for /var/mobile/Containers/Data/Application/F3C55E1E-E382-472F-9163-BE956AAF1422/Documents/Library/Application Support/minecraft/versions/SpiralKnights/SpiralKnights.json, have to assume it's good.
[MCDL] Unknown artifact object for spiral:config:0.0, attempting to generate one
[MCDL] Warning: couldn't find SHA for /var/mobile/Containers/Data/Application/F3C55E1E-E382-472F-9163-BE956AAF1422/Documents/Library/Application Support/minecraft/libraries/spiral/config/0.0/config-0.0.jar, have to assume it's good.
[MCDL] Unknown artifact object for spiral:projectx-config:0.0, attempting to generate one
[MCDL] Warning: couldn't find SHA for /var/mobile/Containers/Data/Application/F3C55E1E-E382-472F-9163-BE956AAF1422/Documents/Library/Application Support/minecraft/libraries/spiral/projectx-config/0.0/projectx-config-0.0.jar, have to assume it's good.
[MCDL] Unknown artifact object for spiral:projectx-pcode:0.0, attempting to generate one
[MCDL] Warning: couldn't find SHA for /var/mobile/Containers/Data/Application/F3C55E1E-E382-472F-9163-BE956AAF1422/Documents/Library/Application Support/minecraft/libraries/spiral/projectx-pcode/0.0/projectx-pcode-0.0.jar, have to assume it's good.
[MCDL] Unknown artifact object for spiral:jutils:0.0, attempting to generate one
[MCDL] Warning: couldn't find SHA for /var/mobile/Containers/Data/Application/F3C55E1E-E382-472F-9163-BE956AAF1422/Documents/Library/Application Support/minecraft/libraries/spiral/jutils/0.0/jutils-0.0.jar, have to assume it's good.
[MCDL] Unknown artifact object for spiral:jshortcut:0.0, attempting to generate one
[MCDL] Warning: couldn't find SHA for /var/mobile/Containers/Data/Application/F3C55E1E-E382-472F-9163-BE956AAF1422/Documents/Library/Application Support/minecraft/libraries/spiral/jshortcut/0.0/jshortcut-0.0.jar, have to assume it's good.
[MCDL] Unknown artifact object for spiral:commons-beanutils:0.0, attempting to generate one
[MCDL] Begin: download libraries
[MCDL] Warning: couldn't find SHA for /var/mobile/Containers/Data/Application/F3C55E1E-E382-472F-9163-BE956AAF1422/Documents/Library/Application Support/minecraft/libraries/spiral/commons-beanutils/0.0/commons-beanutils-0.0.jar, have to assume it's good.
[MCDL] Unknown artifact object for spiral:commons-digester:0.0, attempting to generate one
[MCDL] Warning: couldn't find SHA for /var/mobile/Containers/Data/Application/F3C55E1E-E382-472F-9163-BE956AAF1422/Documents/Library/Application Support/minecraft/libraries/spiral/commons-digester/0.0/commons-digester-0.0.jar, have to assume it's good.
[MCDL] Unknown artifact object for spiral:commons-logging:0.0, attempting to generate one
[MCDL] Warning: couldn't find SHA for /var/mobile/Containers/Data/Application/F3C55E1E-E382-472F-9163-BE956AAF1422/Documents/Library/Application Support/minecraft/libraries/spiral/commons-logging/0.0/commons-logging-0.0.jar, have to assume it's good.
[MCDL] Skipped library SpiralKnights.jar
[MCDL] Finished: download libraries
[MCDL] Begin: download assets
[MCDL] Finished: download assets
Successfully set Jetsam task limit
[MCDL] Warning: couldn't find SHA for /var/mobile/Containers/Data/Application/F3C55E1E-E382-472F-9163-BE956AAF1422/Documents/Library/Application Support/minecraft/versions/SpiralKnights/SpiralKnights.json, have to assume it's good.
[JavaLauncher] Beginning JVM launch
[JavaLauncher] Restored preference: JAVA_HOME is set to /var/containers/Bundle/Application/44D5E9AD-CFCD-48B4-8E6F-E2C5A381F8C4/PojavLauncher.app/jvm/java-8-openjdk
[JavaLauncher] Restored preference: RENDERER is set to auto
[JavaLauncher] Max RAM allocation is set to 493 MB
[Init] Can't load /var/containers/Bundle/Application/44D5E9AD-CFCD-48B4-8E6F-E2C5A381F8C4/PojavLauncher.app/jvm/java-8-openjdk/lib/libjli.dylib (dlopen(/var/containers/Bundle/Application/44D5E9AD-CFCD-48B4-8E6F-E2C5A381F8C4/PojavLauncher.app/jvm/java-8-openjdk/lib/libjli.dylib, 0x0008): tried: '/var/containers/Bundle/Application/44D5E9AD-CFCD-48B4-8E6F-E2C5A381F8C4/PojavLauncher.app/jvm/java-8-openjdk/lib/libjli.dylib' (no such file), '/private/var/containers/Bundle/Application/44D5E9AD-CFCD-48B4-8E6F-E2C5A381F8C4/PojavLauncher.app/jvm/java-8-openjdk/lib/libjli.dylib' (no such file)), trying /var/containers/Bundle/Application/44D5E9AD-CFCD-48B4-8E6F-E2C5A381F8C4/PojavLauncher.app/jvm/java-8-openjdk/lib/jli/libjli.dylib
[Init] Found JLI lib
[Init] Calling JLI_Launch
Arc Capes DNS Injector
Parts of Alibaba's DCM library were used, please read https://github.com/alibaba/java-dns-cache-manipulator/blob/main/README.md for more info
Added DNS cache entry: s.optifine.net/23.95.137.176
Launching Minecraft SpiralKnights
Args init finished. Now starting game
LIBGL: Initialising gl4es
LIBGL: v1.1.4 built on Sep 16 2022 03:53:40
LIBGL: Using GLES 2.0 backend
LIBGL: Using GLES 2.0 backend
LIBGL: Hardware Full NPOT detected and used
LIBGL: Extension GL_EXT_blend_minmax  detected and used
LIBGL: Extension GL_EXT_draw_buffers  detected and used
LIBGL: FBO are in core, and so used
LIBGL: PointSprite are in core, and so used
LIBGL: CubeMap are in core, and so used
LIBGL: BlendColor is in core, and so used
LIBGL: Blend Substract is in core, and so used
LIBGL: Blend Function and Equation Separation is in core, and so used
LIBGL: Texture Mirrored Repeat is in core, and so used
LIBGL: Extension GL_OES_mapbuffer  detected
LIBGL: Extension GL_OES_element_index_uint  detected and used
LIBGL: Extension GL_OES_packed_depth_stencil  detected and used
LIBGL: Extension GL_OES_depth24  detected and used
LIBGL: Extension GL_OES_rgb8_rgba8  detected and used
LIBGL: Extension GL_EXT_texture_format_BGRA8888  detected and used
LIBGL: Extension GL_OES_depth_texture  detected and used
LIBGL: Extension GL_EXT_texture_rg  detected and used
LIBGL: Extension GL_OES_texture_float  detected and used
LIBGL: Extension GL_OES_texture_half_float  detected and used
LIBGL: Extension GL_EXT_color_buffer_half_float  detected and used
LIBGL: high precision float in fragment shader available and used
LIBGL: Extension GL_EXT_frag_depth  detected and used
LIBGL: Max vertex attrib: 16
LIBGL: Extension GL_OES_standard_derivatives  detected and used
LIBGL: Max texture size: 16384
LIBGL: Max Varying Vector: 31
LIBGL: Texture Units: 16/16 (hardware: 16), Max lights: 8, Max planes: 6
LIBGL: Extension GL_EXT_texture_filter_anisotropic  detected and used
LIBGL: Max Anisotropic filtering: 16
LIBGL: Hardware vendor is Google Inc.
LIBGL: Max Color Attachments: 4 / Draw buffers: 4
LIBGL: sRGB surface supported
LIBGL: Targeting OpenGL 2.1
LIBGL: No hack in shader converter to define overloaded function with int
LIBGL: NPOT texture handled in hardware
LIBGL: Not trying to batch small subsequent glDrawXXXX
LIBGL: try to use VBO
LIBGL: glX Will try to recycle EGL Surface
LIBGL: Current folder is:/private/var/mobile/Containers/Data/Application/F3C55E1E-E382-472F-9163-BE956AAF1422/Documents/instances/spiral
libgl4es_114.dylib=0x2021a8be0, error=(null)
EGLBridge: Initializing
EGLBridge: Initialized!
EGLBridge: ThreadID=60695
EGLBridge: EGLDisplay=0x157d11b30, EGLSurface=0x151bb0570
EGLBridge: Created CTX pointer = 0x153258200 (source = 0x0)
EGLBridge: Comparing: thr=60695, this=0x153258200, curr=0x0
EGLBridge: Making current on window 0x153258200 on thread 60695
EGLBridge: eglMakeCurrent() succeed!
OpenJDK 64-Bit Server VM warning: Attempt to protect stack guard pages failed.
OpenJDK 64-Bit Server VM warning: Attempt to deallocate stack guard pages failed.

### Steps To Reproduce

```markdown
[Steps]
- Successful Install
- Successful Launch
```

### Expected Behavior

- Audio not getting cut off after 8 seconds
- Successful Login
- Working quit button

### Platform

```markdown
- Device model: iPhone 8
- iOS version: 15.4.1
- PojavLauncher version: latest dev build
```

**Comment by artdeell** [comment]
You need to rerun the installer after the first launch so that it can update the game

**Comment by SirDank** [comment]
Solved be re-running the installer
