### ISSUE TITLE
[Bug] <Short description> can not pickblock nbt data 

### ISSUE THREAD

**Issue by dragonplus8** [PojavLauncherTeam/PojavLauncher_iOS#517]
### Describe the bug

If you set up a new control it only does Regular pick block 

### Steps To Reproduce

```markdown
1. Set up control
2. Load minecraft 
3. Try
```

### Expected Behavior

 Pick block nbt data 

### Platform

```markdown
- Device model: iPad Pro (11-inch) (3rd generation)
- iOS version: 16.3
- PojavLauncher version: 2.1.3
```

**Comment by VenomousSteam81** [comment]
literally use the `sprint` keybind. you have to press ctrl+<pick block button> to get nbt data

**Comment by dragonplus8** [comment]
OK thanks

**Comment by dragonplus8** [comment]
Does not work would not have labelled as bug otherwise

**Comment by GaucovyAero** [comment]
needs reproducing again i think
