### ISSUE TITLE
[Bug] Games crashes using impact client on 1.12.2

### ISSUE THREAD

**Issue by potjtmtp** [PojavLauncherTeam/PojavLauncher_iOS#518]
### Describe the bug

Crash after showing Mojang when trying to open game with impact hack client installed.

### The log file and images/videos

no log file

### Steps To Reproduce

```markdown
1. install impact client(1.12.2)
2.Start pojavlauncher with online account.
3. Start a game with the impact client installed
4.crash
```

### Expected Behavior

I expected to be able to play without crashing

### Platform

```markdown
- Device model: iPhone12
- iOS version: 16.3
- PojavLauncher version: 2.1.3
```

**Comment by GaucovyAero** [comment]
probably due to discordrpc, cant be fixed
