### ISSUE TITLE
[Bug] Entity and Item triangular rendering bug in old betas

### ISSUE THREAD

**Issue by JulianBvW** [PojavLauncherTeam/PojavLauncher_iOS#521]
### Describe the bug

This has already been posted about [2 years ago](https://github.com/PojavLauncherTeam/PojavLauncher/issues/1169) and marked as closed, but it (at least for me) is not fixed: 

When playing on old beta versions, entities and items have black, triangular overlays that look like weird shadows.

![IMG_1809](https://user-images.githubusercontent.com/45465429/224277497-90b289f8-a94b-414b-9ac3-0cefb6148f82.PNG)

### The log file and images/videos

[latestlog.old.txt](https://github.com/PojavLauncherTeam/PojavLauncher_iOS/files/10940542/latestlog.old.txt)

### Steps To Reproduce

```markdown
1. Start PojavLauncher and load an old beta (like b1.7.3)
2. Start a world and look at entities/ items
```

### Expected Behavior

The shadows should not be there...

### Platform

```markdown
- Device model: iPad Pro 12.9" (2nd Gen)
- iOS version: 16.3.1
- PojavLauncher version: Latest from AltStore (2.1.3)
```

**Comment by GaucovyAero** [comment]
install optifine and its gonna fix itself

**Comment by JulianBvW** [comment]
I already did that but it does not help. The graphical bug is still there.

(Installed Optifine b1.7.3 HD G by moving the .zip contents into the .jar and deleting META-INF)

**Comment by GaucovyAero** [comment]
> I already did that but it does not help. The graphical bug is still there.
> 
> (Installed Optifine b1.7.3 HD G by moving the .zip contents into the .jar and deleting META-INF)

imma try for myself, gimme a few minutes

**Comment by GaucovyAero** [comment]
![Screenshot_2023-03-10-13-21-19-625_net kdt pojavlaunch debug](https://user-images.githubusercontent.com/85581164/224314811-ff1fe18c-edd9-44a8-8619-4b1145ad182a.jpg)
works just fine for me

**Comment by GaucovyAero** [comment]
[b1.2_02OM.zip](https://github.com/PojavLauncherTeam/PojavLauncher_iOS/files/10941979/b1.2_02OM.zip)
here's my versions file (folder)

**Comment by khanhduytran0** [comment]
@JulianBvW for the time being, put `LIBGL_ES=1` in `PojavLauncher/custom_env.txt` (create the file first)
automated switch will come later once I finish stuff

**Comment by GaucovyAero** [comment]
> @GaucovyAero Your version works correctly if I run it. But my beta 1.7.3 still won't work. I have no tried Optifine G, Optifine S G and Optimine. You just paste the files from the zip into the jar and remove METAINF folder, right?

I suggest reading [this](https://pojavlauncherteam.github.io/MODDED-MC.html), you gotta create a custom version. Just disregard the MiX and MiX Archive thing, that's just for Android.

**Comment by JulianBvW** [comment]
@khanhduytran0 If I do that the game won't show up at all. Just a black screen. But sometimes it does click-sounds when tapping on the screen.

**Comment by GaucovyAero** [comment]
yeah, i've heard this too, LIBGL_ES=1 breaks on ios

**Comment by GaucovyAero** [comment]
> > I suggest reading [this](https://pojavlauncherteam.github.io/MODDED-MC.html), you gotta create a custom version. Just disregard the MiX and MiX Archive thing, that's just for Android.
> 
> facepalm Yes, that worked, thank you. I completely forgot about the json...

okay, so everything is working now, no issues?

**Comment by JulianBvW** [comment]
>
> okay, so everything is working now, no issues?

Doing so for a 'vanilla' jar works perfectly, yes!
But I also tried to add it to a modified jar ([BTA jar from reddit](https://www.reddit.com/r/PojavLauncher/comments/1081gy5/is_it_possible_to_run_the_beta_173_better_than/)) but that does not fix the issue. :/

**Comment by GaucovyAero** [comment]
> > okay, so everything is working now, no issues?
> 
> Doing so for a 'vanilla' jar works perfectly, yes! But I also tried to add it to a modified jar ([BTA jar from reddit](https://www.reddit.com/r/PojavLauncher/comments/1081gy5/is_it_possible_to_run_the_beta_173_better_than/)) but that does not fix the issue. :/

uhm cause obviously BTA doesn't work with OptiFine, even on PC. The fix is to implement the b1.8 light engine. ReIndev wants to do that for release 2.9, so let's hope at least that'll work. BTA - no fix for now.

**Comment by crystall1nedev** [comment]
Closing issue as solutions have been provided.

**Comment by Nikitosina** [comment]
@JulianBvW Hello! Could you please tell, what exactly did you do to fix the issue? The [link](https://pojavlauncherteam.github.io/MODDED-MC.html) seems to return 404 now :(

**Comment by GaucovyAero** [comment]
> [@JulianBvW](https://github.com/JulianBvW) Hello! Could you please tell, what exactly did you do to fix the issue? The [link](https://pojavlauncherteam.github.io/MODDED-MC.html) seems to return 404 now :(

here's a video fix, probably not very easy to understand

also to unpack the jar like that on ios you have to rename to zip, extract, modify and replace the files, and then archive (re-zip) again, then rename back to jar

i think you also have to do a similar thing for the json, like rename to txt, edit and back to json

https://github.com/user-attachments/assets/724f6201-f5b6-4b94-888e-e7bc5535b9fd
