### ISSUE TITLE
[Bug] Game crashing when entering Video Settings in old beta versions

### ISSUE THREAD

**Issue by JulianBvW** [PojavLauncherTeam/PojavLauncher_iOS#522]
### Describe the bug

When opening options from either the main menu or within a world and clicking on Video Settings... the game just displays the background dirt image and seemingly does nothing else.

When accessing the Video Settings from a world it also says "Saving chunks":

![IMG_1810](https://user-images.githubusercontent.com/45465429/224279214-c1dc2083-ef41-4488-b9b4-9ced590a7fe6.PNG)

### The log file and images/videos

From within a world:

[latestlog.old.txt](https://github.com/PojavLauncherTeam/PojavLauncher_iOS/files/10940593/latestlog.old.txt)

From the main menu:

[latestlog.old.txt](https://github.com/PojavLauncherTeam/PojavLauncher_iOS/files/10940601/latestlog.old.txt)

### Steps To Reproduce

```markdown
1. Start PojavLauncher and load an old beta (like b1.7.3)
2. (optional) Join a world
3. Esc > Options > Video Settings
```

### Expected Behavior

It should direct me to the Video Settings

### Platform

```markdown
- Device model: iPad Pro 12.9" (2nd Gen)
- iOS version: 16.3.1
- PojavLauncher version: Latest from AltStore (2.1.3)
```

**Comment by khanhduytran0** [comment]
Please make separate instance for old beta, as classic versions do not parse options.txt properly if you have previously launched release versions.

**Comment by JulianBvW** [comment]
Thanks, that worked.
