### ISSUE TITLE
[Question] Pojavlauncher doesn't seem to work on my iphone and how to install java jdk on iphone by terminal

### ISSUE THREAD

**Issue by EnderGameMing** [PojavLauncherTeam/PojavLauncher_iOS#523]
### Describe the bug

when I enter the game I can't seem to interact with anything in Pojavlauncher.

https://user-images.githubusercontent.com/92959766/224304427-f2f4e5ae-ceef-4933-bf72-fa82956026ed.mp4

If it is bug then help me or if it no longer support for iPhone 6 then help me because Pojavlauncher version 2.1 and above is not working so I am using Pojavlauncher version 2.0.1 and it works great on my iphone. But i want to install forge version 1.12.2 it requires java 8 but i don't know how to install java 8 so show me how to install java 8 or give me a file similar to this:
https://github.com/PojavLauncherTeam/PojavLauncher_iOS/releases/tag/v16-openjdk

### Steps To Reproduce

```markdown
1. Start PojavLauncher 
2. Can't interact with the app
```

### Expected Behavior

I want to play Pojavlauncher with forge installed

### Platform

```markdown
- Device model: iPhone 7 and 6
- iOS version: 12.5.5
- PojavLauncher version: from version 2.1 and above
```

### Anything else?

please help me and thanks for taking your time to help.

**Comment by khanhduytran0** [comment]
Do actions builds work?

**Comment by EnderGameMing** [comment]
do you mean the actions section here: https://github.com/PojavLauncherTeam/PojavLauncher_iOS/actions ?

**Comment by khanhduytran0** [comment]
Try the latest build

**Comment by EnderGameMing** [comment]
:V Pojavlauncher 2.2 does not support iOS 12

**Comment by EnderGameMing** [comment]
Currently Pojavlauncher versions 2.1 and above the play button and version selection button do not work for my machine, it must be because my machine is no longer supported, you can integrate java 8 in Pojavlauncher version 2.0.1 , Can you help me do it?
https://github.com/PojavLauncherTeam/PojavLauncher_iOS/releases/tag/v2.0.1

**Comment by JackyNatcumi** [comment]
my iphone is also IOS 12 when downloading the latest version, it looks like this:
![image](https://user-images.githubusercontent.com/128700865/227189974-26a20adf-df54-401e-ac09-841a9b26b588.png)

**Comment by EnderGameMing** [comment]
You can integrate java 8 in Pojavlauncher version 2.0.1 , Can you help me do it?
https://github.com/PojavLauncherTeam/PojavLauncher_iOS/releases/tag/v2.0.1
please help me, i really want to play Pojavlauncher on my iphone.

**Comment by khanhduytran0** [comment]
@JackyNatcumi @EnderGameMing set `force_unsupported_launch` in launcher_preferences.plist ~~(also consider upgrading)~~

**Comment by EnderGameMing** [comment]
wow it worked thank you so much

**Comment by EnderGameMing** [comment]
sorry I suddenly realized that there is still 1 problem to solve that is downloading forge is this a game error or my network error?
![image](https://user-images.githubusercontent.com/92959766/227567191-d6f83a8e-73ce-4cbe-8914-7ae7ff1c214d.png)
