### ISSUE TITLE
Game exited with code -1

### ISSUE THREAD

**Issue by abhishekgi** [PojavLauncherTeam/PojavLauncher_iOS#526]
### Describe the bug

When I try to launch Minecraft 1.19.3 with PojavLauncher on my iPad 9th generation on iPadOS  
16.3.1 , it shows 
![4420FB0E-142B-4EB1-9A91-364B58DB801A](https://user-images.githubusercontent.com/84626229/226188319-18acfd23-1b5f-4e89-bbda-dd2be2152439.png)

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher_iOS/files/11011573/latestlog.txt)

### Steps To Reproduce

```markdown
1. Start PojavLauncher on iPad 9th gen (unjailbroken) on iPadOS 16.3.1

2.launch Minecraft 1.19.3

3.it shows at top that game exited with code 1
```

### Expected Behavior

3 days  before the Minecraft 1.19.3 was opening
After I reinstall PojavLauncher after restoring my iPad backup Minecraft 1.19.3 is not opening I have tried changing settings lowering down memory allocation and tweaks other settings 
And reinstalled whole PojavLauncher again but nothing works but I can play Minecraft 1.8.9,Minecraft 1.16.5,Minecraft,1.17.
But Minecraft 1.19.3 always show game exited with code 1. I don’t know why it is showing this,Minecraft 1.19.3 was launching on my iPad before 3 days 

### Platform

```markdown
- Device model: iPad (9th generation)
- iOS version: 16.3.1
- PojavLauncher version: PojavLauncher 2.1.3-release (2.1.3-legacy/cc887c3)
```

**Comment by khanhduytran0** [comment]
Delete the `assets` folder in your instance then try again

**Comment by abhishekgi** [comment]
Okay

**Comment by totoprotto** [comment]
It didn’t help

**Comment by Cube5x59999** [comment]
_java 17_ is enabled?

**Comment by khanhduytran0** [comment]
@abhishekgi try with the latest actions build. Also, switch renderer to Auto (ANGLE), because gl4es does not render 1.17+ properly (gives a red screen only, then crash)

**Comment by VenomousSteam81** [comment]
> @abhishekgi try with the latest actions build. Also, switch renderer to Auto (ANGLE), because gl4es does not render 1.17+ properly (gives a red screen only, then crash)

Big rip. Sucks how android and iOS are not the same when coding this stuff

**Comment by abhishekgi** [comment]
Downloading the whole game again 
Mean a fresh installation worked for me now I can launch all versions

**Comment by abhishekgi** [comment]
> It didn’t help

See

**Comment by khanhduytran0** [comment]
> > It didn’t help
> 
> See

I see just one line of message. No log, no further info. Please send it.

**Comment by abhishekgi** [comment]
> It didn’t help

Bro send the latestlog.txt

**Comment by abhishekgi** [comment]
> It didn’t help

Bro please send latestlog.txt so that developer could fix the issue you are facing

**Comment by abhishekgi** [comment]
> It didn’t help

Bro please re-download the game to fix it 
And now I am closing this issue 
It if re-downloading not work open an issue and fill all details their and add the latestlog.txt file there
