### ISSUE TITLE
[Question] How do I play minecraft on Pojavlauncher with an offline account but not in DEMO mode?

### ISSUE THREAD

**Issue by UchihaSac12** [PojavLauncherTeam/PojavLauncher_iOS#527]
### Ask the question here.

I simply haven't bought Minecraft so is there a way to play with an offline account?

**Comment by phyr1sc** [comment]
....no.
You gotta sit out on Demo Mode until you got the money to buy Minecraft

**Comment by UchihaSac12** [comment]
Is there a way to circumvent the rules to play the game for free?
Can you guys add this functionality back?

https://user-images.githubusercontent.com/128875877/227697950-f08655fb-56c2-4e3f-b2d8-022a3f13dc7c.mp4

**Comment by phyr1sc** [comment]
So you're technically speaking that you want to get our asses getting kicked off again? We removed Offline Mode because Microsoft.

We aren't adding it back.

**Comment by UchihaSac12** [comment]
okay I understand
