### ISSUE TITLE
[Bug] PojavLauncher Crashing as soon as joining server

### ISSUE THREAD

**Issue by NijremNL** [PojavLauncherTeam/PojavLauncher_iOS#528]
### Describe the bug

When I try to join a server it crashes

### The log file and images/videos

[crash-2023-03-28_21.37.20-client.txt](https://github.com/PojavLauncherTeam/PojavLauncher_iOS/files/11093533/crash-2023-03-28_21.37.20-client.txt)
![C19D03C3-04C1-42E5-9393-5B83E2C9DB20](https://user-images.githubusercontent.com/105514811/228348657-dbd9c971-6145-4e5c-a5a4-a8b0be0083a7.png)

### Steps To Reproduce

```markdown
1. Start PojavLauncher
2. Click Play
3. Click multiplayer
4. Join the server
```

### Expected Behavior

I expect the game to let me Play on the server

### Platform

```markdown
- Device model: iPad Air (5e generatie)
- iOS version: 16.3.1
- PojavLauncher version: version 2.1.3
```

**Comment by NijremNL** [comment]
Does Anyone know how to fix this

**Comment by khanhduytran0** [comment]
As Xaero said in your CurseForge issue report, please use v23.3.2.

**Comment by NijremNL** [comment]
I tried but it didnt work

Here's the new log:

g-1.2.jar 2023-03-29 08:58:08.470 PojavLauncher[4272:612493] [MCDL] SHA1 passed for netty-buffer-4.1.82.Final.jar 2023-03-29 08:58:08.471 PojavLauncher[4272:612493] [MCDL] SHA1 passed for netty-codec-4.1.82.Final.jar 2023-03-29 08:58:08.473 PojavLauncher[4272:612493] [MCDL] SHA1 passed for netty-common-4.1.82.Final.jar 2023-03-29 08:58:08.474 PojavLauncher[4272:612493] [MCDL] SHA1 passed for netty-handler-4.1.82.Final.jar 2023-03-29 08:58:08.475 PojavLauncher[4272:612493] [MCDL] SHA1 passed for netty-resolver-4.1.82.Final.jar 2023-03-29 08:58:08.475 PojavLauncher[4272:612493] [MCDL] SHA1 passed for netty-transport-classes-epoll-4.1.82.Final.jar 2023-03-29 08:58:08.476 PojavLauncher[4272:612493] [MCDL] SHA1 passed for netty-transport-native-epoll-4.1.82.Final-linux-aarch_64.jar 2023-03-29 08:58:08.476 PojavLauncher[4272:612493] [MCDL] SHA1 passed for netty-transport-native-epoll-4.1.82.Final-linux-x86_64.jar 2023-03-29 08:58:08.478 PojavLauncher[4272:612493] [MCDL] SHA1 passed for netty-transport-native-unix-common-4.1.82.Final.jar 2023-03-29 08:58:08.479 PojavLauncher[4272:612493] [MCDL] SHA1 passed for netty-transport-4.1.82.Final.jar 2023-03-29 08:58:08.541 PojavLauncher[4272:612493] [MCDL] SHA1 passed for fastutil-8.5.9.jar 2023-03-29 08:58:08.545 PojavLauncher[4272:612493] [MCDL] SHA1 passed for jna-platform-5.12.1.jar 2023-03-29 08:58:08.550 PojavLauncher[4272:612493] [MCDL] SHA1 passed for jna-5.12.1.jar 2023-03-29 08:58:08.550 PojavLauncher[4272:612493] [MCDL] SHA1 passed for jopt-simple-5.0.4.jar 2023-03-29 08:58:08.553 PojavLauncher[4272:612493] [MCDL] SHA1 passed for commons-compress-1.21.jar 2023-03-29 08:58:08.555 PojavLauncher[4272:612493] [MCDL] SHA1 passed for commons-lang3-3.12.0.jar 2023-03-29 08:58:08.557 PojavLauncher[4272:612493] [MCDL] SHA1 passed for httpclient-4.5.13.jar 2023-03-29 08:58:08.558 PojavLauncher[4272:612493] [MCDL] SHA1 passed for httpcore-4.4.15.jar 2023-03-29 08:58:08.559 PojavLauncher[4272:612493] [MCDL] SHA1 passed for log4j-a

**Comment by khanhduytran0** [comment]
Please send the full log file.

**Comment by NijremNL** [comment]
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher_iOS/files/11109141/latestlog.txt)
Here is the full log file

**Comment by GaucovyAero** [comment]
> [latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher_iOS/files/11109141/latestlog.txt) Here is the full log file

don't use xaeros minimap

**Comment by NijremNL** [comment]
Why not?

**Comment by crystall1nedev** [comment]
> Why not?

Because either you did not update to 23.3.2, or it is still not updated.
