### ISSUE TITLE
[Bug] Install Error on iPad 9th Gen

### ISSUE THREAD

**Issue by CandiedCat** [PojavLauncherTeam/PojavLauncher_iOS#529]
### Describe the bug

Hello, I’m using Scarlet to sideload. It’s been working fine for other apps but it’s giving me an error with Pojav stating “This app cannot be installed because its integrity could not be verified”. Please help!
![1999A643-A756-4F7D-A39D-E96A1C80BB29](https://user-images.githubusercontent.com/108160815/228468013-9e0e24fa-e371-44f3-80b5-59ffd6989d9f.jpeg)

### Steps To Reproduce

```markdown
…
```

### Expected Behavior

The app should be installing without any issues

### Platform

```markdown
- Device model: iPad 9th Gen
- iOS version: iPadOS 19.3
- PojavLauncher version: Latest
```

**Comment by khanhduytran0** [comment]
Sideloading via Scarlet does not allow JIT, so it is unplayable.
Please use other apps like SideStore. Do note that you need PC at least once.
