### ISSUE TITLE
How do you open the fabric version in the launcher? Also what is version editor?

### ISSUE THREAD

**Issue by JforJason101** [PojavLauncherTeam/PojavLauncher_iOS#53]
Note: I also got a message saying it couldn't fine the launcher profile file even though it was in the same folder. Maybe that's why I can't see it but how do you fix that?

**Comment by khanhduytran0** [comment]
You need cd to minecraft folder before run fabric installer.

**Comment by khanhduytran0** [comment]
(old command that contains `-dir .`

**Comment by khanhduytran0** [comment]
And this is **version editor** why you don't know it?
![CA2DC003-5013-45A8-AD68-70D624A400FF](https://user-images.githubusercontent.com/40482367/108021202-a30a7c00-7050-11eb-99ff-c0f557a5f7e5.jpeg)

**Comment by EzzPrograms** [comment]
I think that it isn’t obvious, I also had troubles finding the version editor before deciding just to edit the `config_ver.txt` file just to change the versions without the app. Then when you showed this picture I realized that it was a text box, not a log output area as I had assumed earlier.

UI-wise, it’s still not that user friendly when compared to the Android version, which mimics the actual Minecraft launcher. I do understand that most of this is still in early development, but I would highly recommend that by at least some parts of the launcher be more obvious as some users like myself would have little to no knowledge as to how to use this launcher.

**Comment by khanhduytran0** [comment]
> UI-wise, it’s still not that user friendly when compared to the Android version, which mimics the actual Minecraft launcher. I do understand that most of this is still in early development, but I would highly recommend that by at least some parts of the launcher be more obvious as some users like myself would have little to no knowledge as to how to use this launcher.

Maybe..
