### ISSUE TITLE
[Keyboard]

### ISSUE THREAD

**Issue by syntex12** [PojavLauncherTeam/PojavLauncher_iOS#531]
### Describe the bug

Why there's no keyboard in the jar suction? + how to install the beta build * test * dev idk what is the name

### The log file and images/videos

.

### Steps To Reproduce

```markdown
.
```

### Expected Behavior

.

### Platform

```markdown
- Device model:iPad 9
- iOS version:16.3.1
- PojavLauncher version: latest
```

### Anything else?

no

**Comment by khanhduytran0** [comment]
@syntex12 keyboard is only available in v2.2 dev build (Actions)
