### ISSUE TITLE
[BUG] iOS Sideload bug

### ISSUE THREAD

**Issue by jack11e** [PojavLauncherTeam/PojavLauncher_iOS#533]

**Comment by crystall1nedev** [comment]
Wrong repository for the issue, transferred to PojavLauncherTeam/PojavLauncher_iOS.

This error occurs when the profile used to sign the certificate is rejected by your device. If you're using a website to sideload (such as Scarlett), that's not going to work. Follow the instructions on the README.md of this repo to learn what you should use instead.
