### ISSUE TITLE
[错误] <简短描述>Ctrl button is not responding.

### ISSUE THREAD

**Issue by John021001** [PojavLauncherTeam/PojavLauncher_iOS#536]
### Describe the bug

 in Pojavlauncher，Added a Ctrl button, there is no response in the game.

### Steps To Reproduce

```markdown
Step 1: Add left_control and right_control to the custom control button respectively.
Step 2: Open the game. In create mod, you need to press Ctrl to complete some operations.
Step 3: Press the added Ctrl button and there is no response. life and right have both tried.
Another note: the key binding in mod does not provide the change of Ctrl key.
```

### Expected Behavior

I hope the Ctrl button will work as well as in windows in the Pojavlauncher
I know this is not your problem, Apple's system doesn't have the Ctrl button, only the command button.

### Platform

```markdown
- Device model: ipad pro 3
- iOS version: 16.3.1
- PojavLauncher version: 2.2
```

**Comment by UchihaSac12** [comment]
I have the same error, is there any way to fix it?

**Comment by crystall1nedev** [comment]
Apple does have a control button, the issue is that sometimes when paired with other keys it does something other than intended.

**Comment by Zhou-Shilin** [comment]
You can check the "toggleable" option in the edit button screen. When you need to use a key combination (or ctrl in some cases of mechanical power modules as you said), the standalone button can toggle whether it is pressed or not (equivalent to an automatic long press). For example, to move the blueprint structure is to click ctrl, then move the mouse wheel, then click again to switch back to not long pressed state. This method also allows you to achieve functions such as locking sprint.

> 你可以在编辑按钮的界面里选中“可切换”选项。需要使用组合键时（或者在你所说的在机械动力模组的某些情况下需要使用ctrl的时候），单机按钮即可切换是否按下（相当于自动长按）。比如移动蓝图结构，就是单击一下Ctrl，再移动鼠标滚轮，再单击一下切换回不长按状态。通过这个方法还可以实现锁定疾跑之类的功能。
> 还有哥们，「in Pojavlauncher，Added a Ctrl button, there is no response in the game.」逐句翻译是罢

**Comment by khanhduytran0** [comment]
> Apple does have a control button, the issue is that sometimes when paired with other keys it does something other than intended.

Minecraft does actually expect for Command key instead of Control key, given MacBook keyboard does not have Control key.

```
/**
 * Returns true if either windows ctrl key is down or if either mac meta key is down
 */
public static boolean isCtrlKeyDown() {
    return Minecraft.isRunningOnMac ?
        Keyboard.isKeyDown(Keyboard.KEY_LMETA) || Keyboard.isKeyDown(Keyboard.KEY_RMETA):
        Keyboard.isKeyDown(Keyboard.KEY_LCONTROL) || Keyboard.isKeyDown(Keyboard.KEY_RCONTROL);
}
```
