### ISSUE TITLE
[BUG] I don't see the world my PC plays over LAN

### ISSUE THREAD

**Issue by UchihaSac12** [PojavLauncherTeam/PojavLauncher_iOS#537]
### Ask the question here.

The thing is that I want to play with my brother so we connect to the same wifi network when I open the map, my brother comes in normally, but when my brother opens the map, I can't see my brother's world. I don't know is it because of my wifi network or the computer or Pojavlauncher IOS so I ask if this is the fault of Pojavlauncher or my brother's computer?

**Comment by abhishekgi** [comment]
I think it’s a glitch bro
You should delete Minecraft Java completely from your device and from your brother’s device 
Then redownload Minecraft Java on both after that it must fix

**Comment by khanhduytran0** [comment]
@UchihaSac12 make sure that you have allowed the prompt `PojavLauncher would like to find and connect to devices on your local network`
This prompt can be triggered by waiting until AltKit JIT lookup or attempting to direct connect to the local IP.
See https://support.apple.com/HT211870
