### ISSUE TITLE
[问题] <简短描述>Why does PojavLauncher need Jit?

### ISSUE THREAD

**Issue by Gzline4-24hc** [PojavLauncherTeam/PojavLauncher_iOS#541]
### Ask the question here.

If I have a computer do  I still need PojavLauncher？

**Comment by khanhduytran0** [comment]
Without JIT, it would look like emulating Windows 11 on your phone (no virtualization present!) that would run at 1fps.

**Comment by Gzline4-24hc** [comment]
But only JitterbugPiar and Bullfrog can open Jit.
JitterbugpPiar and Bullfrog need a computer.
If I have a computer. I don't need to use PojavLauncher.

**Comment by khanhduytran0** [comment]
> If I have a computer. I don't need to use PojavLauncher.

iOS restriction only, does not apply to TrollStore-capable versions (iOS 14.0-15.4.1) and Android. Use Android instead if you don't have access to a computer by any chance, or use SideStore which requires PC just once, or wait for iOS 17.
Also, mini PCs like Raspberry PI also counts as computer. It can barely be used for running Minecraft, but can be used for sideloading and enabling JIT.

**Comment by Gzline4-24hc** [comment]
iOS17 can open Jit？

**Comment by Gzline4-24hc** [comment]
I have already said that I don't have a computer.

**Comment by khanhduytran0** [comment]
Borrow someone else’s, go to Internet cafe, etc, or just play on an Android device.
PC/laptop is required because Apple forbids JIT by default.
Because EU is forcing Apple to allow third party browser engines, JIT may be a thing, but not anytime soon.

**Comment by Gzline4-24hc** [comment]
When Apple can open Jit, I'll open this issue again.
