### ISSUE TITLE
[Bug] Specify version doesn't respond

### ISSUE THREAD

**Issue by User8395** [PojavLauncherTeam/PojavLauncher_iOS#543]
### Describe the bug

Literally the only thing I can do is read the pojavlauncher news page.

### The log file and images/videos

N/A

### Steps To Reproduce

```markdown
1. Start PojavLauncher

I'm repeatedly pressing the "specify version" button but it doesn't work

Also I can't leave the news menu
```

### Expected Behavior

I expect to see a dropdown

### Platform

```markdown
- Device model: iPhone 6
- iOS version: 12.5.5
- PojavLauncher version: 2.1.3
```

**Comment by crystall1nedev** [comment]
Use one of the latest builds of 2.2

**Comment by User8395** [comment]
So I have to compile it myself?

**Comment by khanhduytran0** [comment]
Dev builds are in the Actions tab

**Comment by GaucovyAero** [comment]
fixed
