### ISSUE TITLE
[Bug] PojavLauncher crashes with XinaA15 installed

### ISSUE THREAD

**Issue by 22localport** [PojavLauncherTeam/PojavLauncher_iOS#544]
### Describe the bug

With XinaA15 installed, after Minecraft starts up into main menu, touching the screen (or pressing any mouse button) anywhere results in a crash.

### The log file and images/videos

[log.txt](https://github.com/PojavLauncherTeam/PojavLauncher_iOS/files/11234467/log.txt)

### Steps To Reproduce

```markdown
1. Jailbreak with XinaA15
2. Start PojavLauncher
3. Wait for Minecraft to launch into main menu
4. Touch the screen (or press a mouse button)
```

### Expected Behavior

The game continues to run normally.

### Platform

```markdown
- Device model: iPad Mini 6
- iOS version: 15.0 (19A342)
- PojavLauncher version: 2.1.2 (TrollStore)
- XinaA15 version: 1.1.8
```

### Anything else?

This bug persists no matter Minecraft version / Xina version / Pojav version / memory allocated / tweaks installed / ...

Entering 临退 (TempDisable / LinTui) in XinaA15 fixes the problem but also disables whole tweak injection. Tried launching Minecraft with a fresh jb install (no user tweaks installed) but still crashed.

**Comment by crystall1nedev** [comment]
This is going to be a pain to debug since none of the team members have a device compatible with XinaA15.

**Comment by 22localport** [comment]
> 

I suspect it’s because of malfunctioning tweak injection libraries. Xina depends on a somewhat broken bootstrap and some hacky workarounds to support rootful tweaks. Anyway I’m switching to Fugu15/Ellekit and I hope this can fix the crash.

**Comment by 22localport** [comment]
Btw thanks for this brilliant work!

**Comment by khanhduytran0** [comment]
> Anyway I’m switching to Fugu15/Ellekit and I hope this can fix the crash.

Yeah you should do so. XinaA15 is deprecated so this issue will likely be marked as wontfix.

**Comment by crystall1nedev** [comment]
> > Anyway I’m switching to Fugu15/Ellekit and I hope this can fix the crash.
> 
> Yeah you should do so. XinaA15 is deprecated so this issue will likely be marked as wontfix.

Was actually going to say this same thing when I had learned about it. I'll close as not planned because of XinaA15's deprecation.

Try Fugu15 Max. Not sure if it works, would be interesting to see.

**Comment by crystall1nedev** [comment]
> Btw thanks for this brilliant work!

On behalf of @khanhduytran0 and I, thanks for the feedback!

**Comment by 22localport** [comment]
> Try Fugu15 Max. Not sure if it works, would be interesting to see.

It worked flawlessly with tweaks so yeah Xina’s tweak injection seems to be problematic
