### ISSUE TITLE
[Question] looking for a file 

### ISSUE THREAD

**Issue by dragonplus8** [PojavLauncherTeam/PojavLauncher_iOS#545]
### Ask the question here.

I’m looking for the (or files) that controls what button do what when playing with a bluetooth controller 
so i can change it to my preference (hopefully).

thanks in advance for and help I might get :)

**Comment by crystall1nedev** [comment]
We added a configurator in the 2.2 development builds. 2.1.3 and older don't have the capability to change controller button mappings.
