### ISSUE TITLE
[Bug] The game crashed in the latest build on iOS 12.5.5

### ISSUE THREAD

**Issue by EnderGameMing** [PojavLauncherTeam/PojavLauncher_iOS#546]
### Describe the bug

update to the current build and then go into the game to crash on iOS 12.5.5

### Steps To Reproduce

```markdown
1.Start PojavLauncher
2.Crash Game
```

### Expected Behavior

want to enter the PojavLauncher app

### Platform

```markdown
- Device model: Iphone 7,2
- iOS version: 12.5.5
- PojavLauncher version: latest edition
```

**Comment by crystall1nedev** [comment]
In order to help, we are going to need log files, and need to know what Minecraft version you are attempting to use.

**Comment by EnderGameMing** [comment]
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher_iOS/files/11286621/latestlog.txt)

**Comment by crystall1nedev** [comment]
I see the issue. OpenJDK 8 is currently broken on iOS 12, and I don't think you can use Java 17 with 1.7.10. This is an issue but we already have it noted, going to close this one but know that we are working on it!
