### ISSUE TITLE
[F-Req] should add the feature that once logged in to the account that owns minecraft, it will let you play minecraft right away without receiving a continuous access key

### ISSUE THREAD

**Issue by UchihaSac12** [PojavLauncherTeam/PojavLauncher_iOS#554]
### Is this request related to a bug?

If the account is locked, it cannot receive the access key, it gives the error "Request failed: bad request (400)"

### Describe the request.

i have an account i own minecraft and logged in to pojavlauncher but my account got hacked and i cant recover my account and i cant play pojavlauncher so i think should add a feature that even if the account is locked i can still play, like the local account before.

**Comment by UchihaSac12** [comment]
Or at least for those accounts that are locked, they can play lan local network

**Comment by crystall1nedev** [comment]
The current implementation is needed in order for users with multiple devices to be able to play online with PojavLauncher (as signing in on another device invalidates your token on all others.) While this could be changed, it would pose as a major inconvenience to most users who are used to it automatically working.

Additionally, there's no way we can verify that an account wasn't just stolen in the first place. Ignoring the errors means we would be ignoring authentication entirely.

Your only option is to find a way to get your account unlocked.
