### ISSUE TITLE
Question: Does the Forge supported now?

### ISSUE THREAD

**Issue by ENDERMANYK** [PojavLauncherTeam/PojavLauncher_iOS#56]
Just a confuse, because i see in the actions tabs there is a fix forge crash release when in the Markdown it says doesn't support forge

**Comment by khanhduytran0** [comment]
Forge is supported on action builds, but mouse input broken on it, so I leave Forge not yet supported 👀

**Comment by ENDERMANYK** [comment]
so it means you can launch Forge on it, but can't 
such as presss button?

**Comment by khanhduytran0** [comment]
Yes.. but you stills can use tab and space to navigate to button.

**Comment by khanhduytran0** [comment]
So, input issue on Forge is fixed.

**Comment by ENDERMANYK** [comment]
ok but seem my device can't launch forge it stuck at loading screen

**Comment by khanhduytran0** [comment]
Is it empty or on Mojang splash screen?

**Comment by ENDERMANYK** [comment]
![IMG_0106](https://user-images.githubusercontent.com/64646658/108620682-b6f71900-7468-11eb-9b5a-5e9536afe623.PNG)
it stuck at this step for about 10 minutes , should i send you latestlog

**Comment by khanhduytran0** [comment]
Yeah send latestlog.txt

**Comment by ENDERMANYK** [comment]
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher_iOS/files/6017464/latestlog.txt)

**Comment by khanhduytran0** [comment]
You broke the ability to access game dir, open Filza, change owner and group to mobile.

**Comment by ENDERMANYK** [comment]
![IMG_0107](https://user-images.githubusercontent.com/64646658/108621213-494cec00-746c-11eb-8592-14b4540f47d1.PNG)
like this?

**Comment by khanhduytran0** [comment]
Yes

**Comment by ENDERMANYK** [comment]
This sounds a bit strange, but it works after i deleted the config folder

**Comment by khanhduytran0** [comment]
Yeah, what I see in the log was permission denied at that directory.
