### ISSUE TITLE
[Bug] <Crash when launching the game in the new update>

### ISSUE THREAD

**Issue by EpicGamer243** [PojavLauncherTeam/PojavLauncher_iOS#563]
### Describe the bug

Launching the came gives a crash

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher_iOS/files/11422895/latestlog.txt)

### Steps To Reproduce

```markdown
1,Launch Minecraft
```

### Expected Behavior

Main menu

### Platform

```markdown
- Device model: IPad Pro 10.5
- iOS version: 16.4
- PojavLauncher version:2.2
```

**Comment by Monke132** [comment]
For the version it says 2.2-Development

**Comment by GaucovyAero** [comment]
fixed in the latest actions build
