### ISSUE TITLE
[Bug] Shaders not working

### ISSUE THREAD

**Issue by stossy11** [PojavLauncherTeam/PojavLauncher_iOS#565]
### Describe the bug

If you try to install any shaders it will be black screen or crash minecraft

### The log file and images/videos

https://imgur.com/a/Aku9n4Y

### Steps To Reproduce

```markdown
1. Install Optifine or iris 
2. Run any shaders
3. Black screen or crash
```

### Expected Behavior

I expect the game to show

### Platform

```markdown
- Device model: iPad Air 5
- iOS version: 16.5
- PojavLauncher version: PojavLauncher 2.2-development
```

**Comment by GaucovyAero** [comment]
use open4es
