### ISSUE TITLE
App crashes when customizing controller settings

### ISSUE THREAD

**Issue by incyada** [PojavLauncherTeam/PojavLauncher_iOS#566]
### Describe the bug

I was customizing my controls to test if it works with midnight controls. Every time I set one of the dpad buttons to none, I crashes the app.

### Steps To Reproduce

```markdown
1. Go to controller configuration
2.set one of the dpad directions to NONE
3.scroll up
4.crash
```

### Expected Behavior

I expected for nothing to go wrong

### Platform

```markdown
- Device model: iPhone 12
- iOS version: 16.5
- PojavLauncher version: 2.2
```

**Comment by GaucovyAero** [comment]
third party controller mods are not made for inputs on smartphones and are also not made for our modified version of lwjgl3, use the integrated pojav controller remapper instead

**Comment by crystall1nedev** [comment]
PojavLauncher won't work with MidnightControls as they use the desktop APIs, unsupported by iOS. However I can reproduce the issue and think I know what the cause is so it should be fixed soon.

**Comment by incyada** [comment]
> third party controller mods are not made for inputs on smartphones and are also not made for our modified version of lwjgl3, use the integrated pojav controller remapper instead

I know, but curiosity got onto my mind.
