### ISSUE TITLE
[Bug] I get stuck at waiting for JIT 

### ISSUE THREAD

**Issue by blazebrown87221** [PojavLauncherTeam/PojavLauncher_iOS#567]
### Describe the bug

Every time I try to run Minecraft it just gets stuck at waiting for JIT and I want to know if I can turn it off or at least fix it

### The log file and images/videos

Log

[Pre-Init] PojavLauncher INIT!
[Pre-Init] Version: 2.2-development
[Pre-Init] Commit: d9877bc (main)
[Pre-Init] Device: iPhone SE (2nd generation)
[Pre-Init] iOS 16.4.1 (Unjailbroken)
[Pre-init] Entitlements availability:
* com.apple.developer.kernel.extended-virtual-addressing: NO
* com.apple.developer.kernel.increased-memory-limit: NO
* com.apple.private.security.no-sandbox: NO
* dynamic-codesigning: NO
[Debugging] Debug log enabled: YES
[Pre-init] Restored game directory preference (default)
[JitStreamer] Server is 69.69.0.0, attempting to connect...
Path is file:///var/mobile/Containers/Data/Application/DB91C052-5183-4356-8593-359F9AACB088/Documents/latestlog.old.txt
[JitStreamer] Server not found or VPN not connected.
Discovering servers...
Stopped discovering servers.
Discovering servers...
Path is file:///var/mobile/Containers/Data/Application/DB91C052-5183-4356-8593-359F9AACB088/Documents/latestlog.old.txt
Path is file:///var/mobile/Containers/Data/Application/DB91C052-5183-4356-8593-359F9AACB088/Documents/latestlog.old.txt
Stopped discovering servers.
Discovering servers...
Path is file:///var/mobile/Containers/Data/Application/DB91C052-5183-4356-8593-359F9AACB088/Documents/latestlog.old.txt
Stopped discovering servers.
Discovering servers...
Stopped discovering servers.
Discovering servers...
Stopped discovering servers.
Discovering servers...
Path is file:///var/mobile/Containers/Data/Application/DB91C052-5183-4356-8593-359F9AACB088/Documents/latestlog.old.txt
Stopped discovering servers.

### Steps To Reproduce

```markdown
Use iPhone SE second gen and download scarlet to side load PojavLauncher
```

### Expected Behavior

JIT is not working 

### Platform

```markdown
- Device model: iPhone SE (second gen)
- iOS version: iOS 16.4.1 (20E252)
- PojavLauncher version: 2.2
```

### Anything else?

I left it for a night and still it was on that screen and that was while I was sleeping but this one it not the one I can’t find it at all

**Comment by blazebrown87221** [comment]
Update: I found a switch to turn it off but now it just does not load the game or errors out with the exit code 6

**Comment by khanhduytran0** [comment]
> errors out with the exit code 6

Because you *must* enable JIT. Forcing it to work would not do the trick, otherwise we would not put that waiting for JIT. Attempt to play without JIT = exit that looks like a crash.
