### ISSUE TITLE
[BUG] Microsoft login does not work with GitHub login

### ISSUE THREAD

**Issue by j-f1** [PojavLauncherTeam/PojavLauncher_iOS#568]
### Describe the bug

Logging into a Microsoft account that is linked to a GitHub account fails

### The log file and images/videos

[latestlog.old.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/11607469/latestlog.old.txt)

### Steps To Reproduce

1. Link your GitHub account to a Microsoft account that has legally purchased Minecraft
2. In PojavLauncher (iOS), tap the account picker, then the + button, then “Microsoft Account.”
3. Enter your Microsoft account email
4. Tap “Log in with GitHub”
5. Log in with GitHub
6. Enter your Microsoft 2FA code (if necessary)

### Expected Behavior

The app logs in successfully

### Platform

- Device model: iPhone 13 Pro (A2483)
- iOS version: iOS 16.5 (20F65)
- PojavLauncher version: 2.2-development (main/d9877bc)

### Anything else?

I recorded a trace with SSL proxying enabled to capture the exact content of the 400 error. Here is the response body:

```json
{
  "error": "invalid_grant",
  "error_description": "The provided value for the 'code' parameter is not valid. The code has expired.",
  "correlation_id": "7027cd57-1c7c-46a9-be60-33704bb3ebe6"
}
```

I was able to successfully log in by tapping “log in with password instead” and skipping the GitHub portion of the flow entirely.

**Comment by crystall1nedev** [comment]
Seems that the GitHub signin flow doesn't follow back to MSA. This will take a while to fix, and likely won't be until PojavLauncher 3.0 is out.

**Comment by khanhduytran0** [comment]
It would have been quicker to fix if you had also checked the provided `code` parameter 😅
Turns out it included unexpected parameter `state` in `M.C103_BAY.2.XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX&state=XXXXXXXXX`
