### ISSUE TITLE
[Bug] Snapshots above 23w14a crash

### ISSUE THREAD

**Issue by Cheeseff** [PojavLauncherTeam/PojavLauncher_iOS#571]
### Describe the bug

I’m using an iPhone 12 with iOS 15.1.1. I can’t load snapshots 23w16a or above. I also can’t run 1.20 pre releases or release candidates. I tried all renderers and none work. I tried giving it more memory and it still didn’t work. 

### The log file and images/videos

[crash-2023-06-01_15.38.05-client.txt](https://github.com/PojavLauncherTeam/PojavLauncher_iOS/files/11629928/crash-2023-06-01_15.38.05-client.txt)
https://drive.google.com/file/d/1OmNwi647cEEbLKzc5uvk0ooa_ttHQnOs/view?usp=drivesdk

### Steps To Reproduce

```markdown
1. Use an iPhone 12 with iOS 15.1.1 that is not jailbroken and installed with TrollStore.
2. Select any snapshot above 23w14a.
3. Launch the game.
```

### Expected Behavior

The game should load without crashing.

### Platform

```markdown
- Device model: iPhone 12
- iOS version: 15.1.1
- PojavLauncher version: 2.2
```

**Comment by khanhduytran0** [comment]
This issue was fixed in recent dev builds.
