### ISSUE TITLE
Add some features.

### ISSUE THREAD

**Issue by NoviceXiaoren** [PojavLauncherTeam/PojavLauncher_iOS#573]
### Describe the request.

I hope to increase the upper limit of gyroscope sensitivity to obtain better PVP.
If possible, it's best to add a floating joystick or fix the problem of button jamming.

**Comment by iFlxy** [comment]
Yes, that would be really useful. I tried increasing it manually from the settings file, but it didn’t work.

**Comment by GaucovyAero** [comment]
should be resolved except for the button jams

**Comment by GaucovyAero** [comment]
its in another issue and is more complicated to reproduce
