### ISSUE TITLE
[Bug] Crashes after a few minutes of playing

### ISSUE THREAD

**Issue by iced-capp** [PojavLauncherTeam/PojavLauncher_iOS#574]
### Describe the bug

After about 5 minutes of playing the game crashes. The game runs perfectly fine otherwise. This has happened every time I've tried to play.

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher_iOS/files/11646126/latestlog.txt)

https://github.com/PojavLauncherTeam/PojavLauncher_iOS/assets/117924373/b7715476-534a-4902-a749-3721ddd1af61

### Steps To Reproduce

```markdown
1. Start PojavLauncher
2. Play for a few minutes
3. Your game crashes.
```

### Expected Behavior

I expect that the game does not crash while playing. 

### Platform

```markdown
- Device model: iPhone 11 Pro
- iOS version: iOS 16.5
- PojavLauncher version: Latest Release - v2.2
```

### Anything else?

I've even tried re-installing PojavLauncher, but I still have the same issue.

**Comment by khanhduytran0** [comment]
> Changing view distance to 12, from 10

Drop your render distance settings to the point that it should fit your RAM allocated. the log above is broken into pieces so I couldn’t find the allocated RAM

**Comment by iced-capp** [comment]
Thanks, this seemed to work.
