### ISSUE TITLE
[Bug] "Failed to download (null), unsupported url" when the first time launch the game

### ISSUE THREAD

**Issue by Zhou-Shilin** [PojavLauncherTeam/PojavLauncher_iOS#575]
### Describe the bug

Error when first time start the game (Forge 1.18.2 40.1.93)
Message:
`Failed to download (null), unsupported url`
(Translated, original text: `Error: 下载 (null) 失败：不支持的URL`)

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher_iOS/files/11651992/latestlog.txt)
```
[MCDL] Error: 下载 (null) 失败：不支持的URL (
	0   PojavLauncher                       0x00000001024934ec __71+[MinecraftResourceUtils downloadClientJson:progress:callback:success:]_block_invoke.88 + 284
	1   libAFNetworking.dylib               0x000000010261907c __72-[AFURLSessionManagerTaskDelegate URLSession:task:didCompleteWithError:]_block_invoke + 168
	2   libdispatch.dylib                   0x00000001a748f4b4 24DB930D-870B-31CE-AC69-534D7896B4A8 + 9396
	3   libdispatch.dylib                   0x00000001a7490fdc 24DB930D-870B-31CE-AC69-534D7896B4A8 + 16348
	4   libdispatch.dylib                   0x00000001a749f850 24DB930D-870B-31CE-AC69-534D7896B4A8 + 75856
	5   libdispatch.dylib                   0x00000001a749f444 _dispatch_main_queue_callback_4CF + 44
	6   CoreFoundation                      0x000000019ff126d8 725E49F4-653B-39BF-9A7A-8A3250911ECB + 632536
	7   CoreFoundation                      0x000000019fef403c 725E49F4-653B-39BF-9A7A-8A3250911ECB + 507964
	8   CoreFoundation           2023-06-05 19:20:20.692 PojavLauncher[30798:36027055] Successfully load keyboard extensions
```

### Steps To Reproduce

```markdown
1. Start Pojavlauncher (with JIT)
2. Download 1.18.2 vanilla
3. Click "Install jar" in the left bar
4. Choose `1.18.2-forge-40.1.93.jar`
5. Restart Pojavlauncher
6. Launch the game
7. Get the error message
```

### Expected Behavior

The game starts.

### Platform

- Device model: iPad Air 5
- iOS version: 16.2 Beta 2
- PojavLauncher version: 3.0-development [5665f4c](https://github.com/PojavLauncherTeam/PojavLauncher_iOS/commit/5665fc4ea8f9f529d98b9ce7259477a2275ec7d1)

### Anything else?

I can launch a game which i have been launched before (same version 1.18.2 forge 40.1.93) successfully.

**Comment by Zhou-Shilin** [comment]
@khanhduytran0 @crystall1nedev

**Comment by khanhduytran0** [comment]
latestlog.txt is pretty much incomplete, there was nothing other than the error, please send the full log.
Before doing so, make sure to try with the [latest build](https://github.com/PojavLauncherTeam/PojavLauncher_iOS/actions/runs/5362158289) and latest Forge build.

**Comment by Zhou-Shilin** [comment]
> latestlog.txt is pretty much incomplete, there was nothing other than the error, please send the full log.
> Before doing so, make sure to try with the [latest build](https://github.com/PojavLauncherTeam/PojavLauncher_iOS/actions/runs/5362158289) and latest Forge build.

[latest.log](https://github.com/PojavLauncherTeam/PojavLauncher_iOS/files/11856339/latest.log)

(I tried the latest build 1db83c6, it didn't work either.)
![65867D44-0C96-4404-B6DA-40B3B59DA422](https://github.com/PojavLauncherTeam/PojavLauncher_iOS/assets/86581525/2de2dfa6-40c0-481a-ae4a-650ec9046fc0)

**Comment by khanhduytran0** [comment]
latest.log contains only game log, not launcher log.
Send the version’s json file I guess

**Comment by Zhou-Shilin** [comment]
[1.18.2-forge-40.1.93.json and 1.18.2.json](https://gist.github.com/Zhou-Shilin/f67f0285750723ec79f18c88ff924347)

/instances/singleplayer/versions/single-1.18.2-forge-40.1.93/single-1.18.2-forge-40.1.93.json
/instances/singleplayer/versions/1.18.2/1.18.2.json

**Comment by khanhduytran0** [comment]
The file you uploaded doesn’t have `single-` name prefix. It is required to change `id` variable to match the json filename.

**Comment by Zhou-Shilin** [comment]
Where can I change it?

**Comment by khanhduytran0** [comment]
```json

{
    "_comment_": [
        "Please do not automate the download and installation of Forge.",
        "Our efforts are supported by ads from the download page.",
        "If you MUST automate this, please consider supporting the project through https://www.patreon.com/LexManos/"
    ],
    "id": "single-1.18.2-forge-40.1.93", <- here
    "time": "2022-12-30T19:03:42+00:00",
```

**Comment by Zhou-Shilin** [comment]
I successfully launched the game, but and then it crashed.
[crash-2023-06-24_19.22.39-client.txt](https://github.com/PojavLauncherTeam/PojavLauncher_iOS/files/11856658/crash-2023-06-24_19.22.39-client.txt)

**Comment by khanhduytran0** [comment]
Send full log in `PojavLauncher/latestlog(.old).txt`, choose the larger one.

**Comment by Zhou-Shilin** [comment]
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher_iOS/files/11868489/latestlog.txt)

**Comment by khanhduytran0** [comment]
I'm not sure what's wrong but you should try adjusting memory allocation.

**Comment by khanhduytran0** [comment]
I discovered an issue that could be related, please try [this build](https://github.com/PojavLauncherTeam/PojavLauncher_iOS/actions/runs/5384333936).

**Comment by Zhou-Shilin** [comment]
> I discovered an issue that could be related, please try [this build](https://github.com/PojavLauncherTeam/PojavLauncher_iOS/actions/runs/5384333936).

Ok.

**Comment by Zhou-Shilin** [comment]
It's not working either.
[latest.log](https://github.com/PojavLauncherTeam/PojavLauncher_iOS/files/11876341/latest.log)
[crash-2023-06-27_08.22.47-client.txt](https://github.com/PojavLauncherTeam/PojavLauncher_iOS/files/11876339/crash-2023-06-27_08.22.47-client.txt)
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher_iOS/files/11876337/latestlog.txt)

**Comment by khanhduytran0** [comment]
> I'm not sure what's wrong but you should try adjusting memory allocation.

The RAM amount is unchanged compared to the previous log.

**Comment by Zhou-Shilin** [comment]
[crash-2023-06-27_09.31.55-client.txt](https://github.com/PojavLauncherTeam/PojavLauncher_iOS/files/11876759/crash-2023-06-27_09.31.55-client.txt)
[latest.log](https://github.com/PojavLauncherTeam/PojavLauncher_iOS/files/11876761/latest.log)
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher_iOS/files/11876763/latestlog.txt)
![16AF3147-71D8-459A-8EC2-2AF0C1EDB7B4](https://github.com/PojavLauncherTeam/PojavLauncher_iOS/assets/86581525/7d0f1170-bf59-4bbb-9eba-f03c7df5f7d1)

**Comment by khanhduytran0** [comment]
That’s you’re overallocating it. Try lowering to just 1GB

**Comment by Zhou-Shilin** [comment]
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher_iOS/files/11876938/latestlog.txt)
[crash-2023-06-27_10.07.14-client.txt](https://github.com/PojavLauncherTeam/PojavLauncher_iOS/files/11876939/crash-2023-06-27_10.07.14-client.txt)
[latest.log](https://github.com/PojavLauncherTeam/PojavLauncher_iOS/files/11876941/latest.log)
![4AED077C-874C-418F-94CD-C31255AD7C7F](https://github.com/PojavLauncherTeam/PojavLauncher_iOS/assets/86581525/8cb14561-3cd0-42d8-992a-1bcf2cfccb12)

**Comment by khanhduytran0** [comment]
Library has been updated, please try [this build](https://github.com/PojavLauncherTeam/PojavLauncher_iOS/actions/runs/5389964521)

**Comment by Zhou-Shilin** [comment]
It can launch the game, but cannot install forge.
![43B1F04F-46C8-4AC9-88E2-3F73D6F8D2B8](https://github.com/PojavLauncherTeam/PojavLauncher_iOS/assets/86581525/cbf0c1c2-8848-4632-806a-004b0bd158d8)
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher_iOS/files/11882586/latestlog.txt)

**Comment by khanhduytran0** [comment]
what.. latestlog.txt has almost nothing in it, where did the rest of log go

Which way you used to enable JIT?

**Comment by khanhduytran0** [comment]
Oh look there’s VPN so I’d guess it’s SideStore.
Can you check the file size when JIT is not enabled? (and also its content, should start with `PojavLauncher INIT!)

**Comment by Zhou-Shilin** [comment]
SideStore
![3ED4D881-0FF6-4452-99BD-84670462707E](https://github.com/PojavLauncherTeam/PojavLauncher_iOS/assets/86581525/bb7c4a9c-ca1f-49fe-87f2-3908f3a21eca)

**Comment by Zhou-Shilin** [comment]
> Oh look there’s VPN so I’d guess it’s SideStore.
> Can you check the file size when JIT is not enabled? (and also its content, should start with `PojavLauncher INIT!)

When JIT is not enabled, the file size is 2KB and it starts with `Pojavlauncher INIT!`

**Comment by khanhduytran0** [comment]
Alright, after opening PojavLauncher without JIT, you can go back to SideStore enable JIT and redo the issue, then send log.

**Comment by khanhduytran0** [comment]
Try [this build](https://github.com/PojavLauncherTeam/PojavLauncher_iOS/actions/runs/5396738906) and let me know if logger works.
Regarding the installer issue, your file might have corrupted. Try redownloading it.

**Comment by Zhou-Shilin** [comment]
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher_iOS/files/11889320/latestlog.txt)
The logger works well now.
I am pretty sure that my forge installer is not corrupted. I compared the MD5 value of my file with the official forge website file. I can use this installer normally on my computer. Once I also installed forge successfully using the same installer on Pojavlauncher.
![01581141-88AF-470E-897C-7D8968710657](https://github.com/PojavLauncherTeam/PojavLauncher_iOS/assets/86581525/737416f6-5ab0-4bb9-b6fa-614f5aa0d719)
![1FA1E8B9-56B0-488A-8C72-FE67F75F667B](https://github.com/PojavLauncherTeam/PojavLauncher_iOS/assets/86581525/7b925aec-ba08-4b04-8f77-5aa94c09efc3)

**Comment by khanhduytran0** [comment]
The actual issue has been found, try [this](https://github.com/PojavLauncherTeam/PojavLauncher_iOS/actions/runs/5397190912) should work now.

**Comment by Zhou-Shilin** [comment]
> The actual issue has been found, try [this](https://github.com/PojavLauncherTeam/PojavLauncher_iOS/actions/runs/5397190912) should work now.

Thanks! It works now.
