### ISSUE TITLE
[Bug] Black screen when trying to play

### ISSUE THREAD

**Issue by iced-capp** [PojavLauncherTeam/PojavLauncher_iOS#576]
### Describe the bug

As soon as I hit play the screen turns black.

### The log file and images/videos

Log:

2023-06-05 16:35:14.099 PojavLauncher[4282:851830] invalid mode 'kCFRunLoopCommonModes' provided to CFRunLoopRunSpecific - break on _CFRunLoopError_RunCalledWithInvalidMode to debug. This message will only appear once per execution.
[Init] Can't load /var/containers/Bundle/Application/C04C3F95-BF2B-4698-9D68-3AFD8824F49F/App.app/java_runtimes/java-17-openjdk/lib/libjli.dylib (dlopen(/var/containers/Bundle/Application/C04C3F95-BF2B-4698-9D68-3AFD8824F49F/App.app/java_runtimes/java-17-openjdk/lib/libjli.dylib, 0x0008): tried: '/var/containers/Bundle/Application/C04C3F95-BF2B-4698-9D68-3AFD8824F49F/App.app/java_runtimes/java-17-openjdk/lib/libjli.dylib' (code signature invalid in <FAC98080-7EEF-3D20-A192-7FFC1EDBC744> '/private/var/containers/Bundle/Application/C04C3F95-BF2B-4698-9D68-3AFD8824F49F/App.app/java_runtimes/java-17-openjdk/lib/libjli.dylib' (errno=1) sliceOffset=0x00000000, codeBlobOffset=0x00016E40, codeBlobSize=0x00003660), '/private/preboot/Cryptexes/OS/var/containers/Bundle/Application/C04C3F95-BF2B-4698-9D68-3AFD8824F49F/App.app/java_runtimes/java-17-openjdk/lib/libjli.dylib' (no such file), '/var/containers/Bundle/Application/C04C3F95-BF2B-4698-9D68-3AFD8824F49F/App.app/java_runtimes/java-17-openjdk/lib/libjli.dylib' (code signature invalid in <FAC98080-7EEF-3D20-A192-7FFC1EDBC744> '/private/var/containers/Bundle/Application/C04C3F95-BF2B-4698-9D68-3AFD8824F49F/App.app/java_runtimes/java-17-openjdk/lib/libjli.dylib' (errno=1) sliceOffset=0x00000000, codeBlobOffset=0x00016E40, codeBlobSize=0x00003660), '/private/var/containers/Bundle/Application/C04C3F95-BF2B-4698-9D68-3AFD8824F49F/App.app/java_runtimes/java-17-openjdk/lib/libjli.dylib' (code signature invalid in <FAC98080-7EEF-3D20-A192-7FFC1EDBC744> '/private/var/containers/Bundle/Application/C04C3F95-BF2B-4698-9D68-3AFD8824F49F/App.app/java_runtimes/java-17-openjdk/lib/libjli.dylib' (errno=1) sliceOffset=0x00000000, codeBlobOffset=0x00016E40, codeBlobSize=0x00003660), '/private/preboot/Cryptexes/OS/private/var/containers/Bundle/Application/C04C3F95-BF2B-4698-9D68-3AFD8824F49F/App.app/java_runtimes/java-17-openjdk/lib/libjli.dylib' (no such file), '/private/var/containers/Bundle/Application/C04C3F95-BF2B-4698-9D68-3AFD8824F49F/App.app/java_runtimes/java-17-openjdk/lib/libjli.

### Steps To Reproduce

```markdown
1. Start PojavLauncher
2. Click play
3. Black screen
```

### Expected Behavior

I expect that the game will work.

### Platform

```markdown
- Device model: iPhone 11 Pro
- iOS version: 16.5
- PojavLauncher version: Latest Release - v2.2 Deepslate
```

### Anything else?

This worked perfectly fine a few hours ago

**Comment by crystall1nedev** [comment]
The error seems to say that your copy of the Java runtime is not properly codesigned. Try resigning the app from whatever you sideloaded from.
