### ISSUE TITLE
[Question]<how to fix is>

### ISSUE THREAD

**Issue by GameCapp** [PojavLauncherTeam/PojavLauncher_iOS#578]
![DFF5C1F9-B0CE-4D71-99BF-40640F438451](https://github.com/PojavLauncherTeam/PojavLauncher_iOS/assets/120325088/03fec248-ec7b-4211-9d2b-edd70b163ea3)
minecraft can't be legally installed when logged in with in with a local account.

**Comment by crystall1nedev** [comment]
Use a Microsoft account that owns the game to install Minecraft. Alternatively, you can try out demo mode with one that doesn't.
