### ISSUE TITLE
Can not input Chinese through the input method

### ISSUE THREAD

**Issue by Officeyutong** [PojavLauncherTeam/PojavLauncher_iOS#58]
When I touched a key on the virtual keyboard, the corresponding english letter was directly sent to the game but not the input method.

https://user-images.githubusercontent.com/9004058/108598570-4cdb6700-73c9-11eb-8ce0-f652bf135e73.MP4

**Comment by xiaohei24679** [comment]
你下一个搜狗输入法试试，我用那个可以输入中文

**Comment by lanspring** [comment]
ios怎么装模组？

**Comment by Officeyutong** [comment]
> ios怎么装模组？

https://github.com/PojavLauncherTeam/PojavLauncher_iOS/wiki
