### ISSUE TITLE
Pojavlauncher Crasges randomly anywhere 

### ISSUE THREAD

**Issue by abhishekgi** [PojavLauncherTeam/PojavLauncher_iOS#580]
### Describe the bug

Pojavlauncher crashes anywhere randomly within minutes of playtime. It crashes very frequently.It will crash anywhere while playing, ,while changing settings,while you are in area where many entities are there.
-The world never reopens if Pojavlauncher was crashed in that world.
And also I tested auto ram, and custom ram 512mb 600mb 700mb , Pojavlauncher crashes in all these ram settings

### The log file and images/videos

I will upload

### Steps To Reproduce

```markdown
Start Pojavlauncher
Play it on iPad 9 iPados 16
With 5 render distance 

```

### Expected Behavior

It should run without crashing, because performance doesn't matter if the Pojavlauncher crashes frequently how could we play Minecraft,
I have a Android phone and the Pojavlauncher never crashes on my Android phone in hours of play time .
And in iOS it it everytime crashes within 1 to 5 minutes. Because Pojavlauncher crashes everytime I play Minecraft on my PC and phone which are slower than iPad 

### Platform

```markdown
- Device model:iPad 9 wifi 64
- iOS version:ipados 16.5
- PojavLauncher version:depslate 2.2
```

### Anything else?

Do anything ruduce performance, tell us best settings or anything else but please fix crash so that I can play Minecraft Java my on iPad .

**Comment by incyada** [comment]
From what I know, it's seems to be a issue with auto save. It also happens to me but I have a short fix:

If your device is overheating (which is VERY common) if you pause the game on single player, the auto save counter (4 min) will reset since you manually saved rather than auto save.

Make sure to do it often though.

**Comment by abhishekgi** [comment]
> From what I know, it's seems to be a issue with auto save. It also happens to me but I have a short fix:
> 
> If your device is overheating (which is VERY common) if you pause the game on single player, the auto save counter (4 min) will reset since you manually saved rather than auto save.
> 
> Make sure to do it often though.
Hmm

**Comment by abhishekgi** [comment]
Hmm

**Comment by incyada** [comment]
So I tried cooling my phone with a awkward setup (which help with preformance) but the crashes still occur. Seems like the PojavLauncher IOS team might need to fix that in 2.3 or 2.3.1.

**Comment by abhishekgi** [comment]
Yes

**Comment by khanhduytran0** [comment]
You’ll need to understand that those random crashes are caused by Jetsam, it will just kill a process using too much resources. This is not something PojavLauncher, a regular sandboxed app, can bypass without jailbreak or granted special entitlements through TrollStore.

**Comment by incyada** [comment]
> You’ll need to understand that those random crashes are caused by Jetsam, it will just kill a process using too much resources. This is not something PojavLauncher, a regular sandboxed app, can bypass without jailbreak or granted special entitlements through TrollStore.

But what if we were to remove it, will PojavLauncher give up without it or it isn't major for the app?

**Comment by incyada** [comment]
> > You’ll need to understand that those random crashes are caused by Jetsam, it will just kill a process using too much resources. This is not something PojavLauncher, a regular sandboxed app, can bypass without jailbreak or granted special entitlements through TrollStore.
> 
> But what if we were to remove it, will PojavLauncher give up without it or it isn't major for the app?

Forget what I said, this google result shows how important it is to PojavLauncher.

"It triggers an event when the device encounters low memory, and will reclaim memory from other apps to improve performance of whatever is running in the foreground."

**Comment by khanhduytran0** [comment]
Jetsam is built into the operating system so it’s completely impossible to remove it.
Best you could do to mitigate this kind of crash is to install optimization modpacks.

On the other hand, there is a way to use swap, not sure if it works and how much impact to performance. JVM arg: `-XX:AllocateHeapAt=.`

**Comment by incyada** [comment]
> Jetsam is built into the operating system so it’s completely impossible to remove it.
> 
> Best you could do to mitigate this kind of crash is to install optimization modpacks.
> 
> 
> 
> On the other hand, there is a way to use swap, not sure if it works and how much impact to performance. JVM arg: `-XX:AllocateHeapAt=.`

Well 1st, I friend optimization modpack but that delayed the crashes, not stop them.

2nd, how am I supposed to use swap (im not that technology advance so sorry in advance If I don't know much.)?

**Comment by abhishekgi** [comment]
Could pojavlauncher be launched on appstore .

**Comment by abhishekgi** [comment]
If it is possible then we will never see crash again. am i Right bro ?

**Comment by khanhduytran0** [comment]
> Could pojavlauncher be launched on appstore ?

![image](https://github.com/PojavLauncherTeam/PojavLauncher_iOS/assets/40482367/ab7bef25-bf1c-4d27-bd88-6776e62e8063)
Apple does not allow any kind of emulator/virtual machines on iOS unless for education purposes, so JIT isn't allowed either, also with $99/year cost.
Your only hope if in EU is third party app store, but what matters is will Apple allow JIT there.

**Comment by khanhduytran0** [comment]
> 2nd, how am I supposed to use swap (im not that technology advance so sorry in advance If I don't know much.)?

Put it in `JVM Launch arguments`

**Comment by incyada** [comment]
From my testing, using swap seems to delay the crashes a lot so sadly, there is no way to get rid of the crashes, only delay them.

**Comment by abhishekgi** [comment]
> 

I think by using the jvm lauch and argument you provided and reducing some settings may fix this problem 
Once i had played pojavlaucher on 67 % that is 1080p out 1620p out of ipad screen and there were no crashes

**Comment by abhishekgi** [comment]
> Jetsam is built into the operating system so it’s completely impossible to remove it. Best you could do to mitigate this kind of crash is to install optimization modpacks.
> 
> On the other hand, there is a way to use swap, not sure if it works and how much impact to performance. JVM arg: `-XX:AllocateHeapAt=.`

It this does work you tell everyone about it in news and code section

**Comment by abhishekgi** [comment]
> Jetsam is built into the operating system so it’s completely impossible to remove it. Best you could do to mitigate this kind of crash is to install optimization modpacks.
> 
> On the other hand, there is a way to use swap, not sure if it works and how much impact to performance. JVM arg: `-XX:AllocateHeapAt=.`

Btw thanks

**Comment by abhishekgi** [comment]
> > Could pojavlauncher be launched on appstore ?
> 
> ![image](https://user-images.githubusercontent.com/40482367/248535599-ab7bef25-bf1c-4d27-bd88-6776e62e8063.png) Apple does not allow any kind of emulator/virtual machines on iOS unless for education purposes, so JIT isn't allowed either, also with $99/year cost. Your only hope if in EU is third party app store, but what matters is will Apple allow JIT there.

This is very bad that there are so many restrictions in ios/ipados that don’t allow us to take take full advantage of our device
