### ISSUE TITLE
Game crashes with sodium extra

### ISSUE THREAD

**Issue by incyada** [PojavLauncherTeam/PojavLauncher_iOS#584]
### Describe the bug

Been a while since a bug report was posted! I’ll keep this short, Sodium + sodium extra + reese’s sodium options = crash.

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher_iOS/files/11900691/latestlog.txt)

### Steps To Reproduce

```markdown
1. Add sodium, Reese’s sodium options and sodium extra in the mods folder
2. Start PojavLauncher
3. If unlucky enough, crash
```

### Expected Behavior

Game should work fine with the mod.

### Platform

```markdown
- Device model: IPhone 12
- iOS version: 16.5.1
- PojavLauncher version: 2.2
```

**Comment by khanhduytran0** [comment]
Update to [latest build](https://github.com/PojavLauncherTeam/PojavLauncher_iOS/actions/runs/5402546221) and try again.

**Comment by incyada** [comment]
New issue.

Loading the game with the mod is so broken, the mojang logo isn't in the center and crashes afterwards.

Here are the logs.
[latestlog.old.txt](https://github.com/PojavLauncherTeam/PojavLauncher_iOS/files/11906804/latestlog.old.txt)
As you can see, there are A TON of errors.

**Comment by incyada** [comment]
> New issue.
> 
> 
> 
> Loading the game with the mod is so broken, the mojang logo isn't in the center and crashes afterwards.
> 
> 
> 
> Here are the logs.
> 
> [latestlog.old.txt](https://github.com/PojavLauncherTeam/PojavLauncher_iOS/files/11906804/latestlog.old.txt)
> 
> As you can see, there are A TON of errors.

Since it's broken, guess I'll play without sodium extra until it's get fixed.

**Comment by khanhduytran0** [comment]
Sodium uses OpenGL 4 config by default (and Pojav rendereds except Zink do not offer OpenGL 4; plus Zink is unavailable on iOS 16), so it must be patched before it would work.

> the mojang logo isn't in the center

That’s just you initially started game in portrait then rotated to landscape. Do it back forth to fix.

**Comment by khanhduytran0** [comment]
If this is not the case, disable `Reduce Resolution on macOS`
Sodium patcher: [sodiumpatcher-1.0.1-SNAPSHOT.jar](https://www.mediafire.com/file/g09xmfa1yfrp1km/sodiumpatcher-1.0.1-SNAPSHOT.jar/file)

**Comment by cyriotic3** [comment]
have you tried ANGLE renderer?

**Comment by incyada** [comment]
> have you tried ANGLE renderer?

Yes, but sodium requires Open GL 4 to work soooooooooo....
