### ISSUE TITLE
[Bug] Pojvlauncher flashes back

### ISSUE THREAD

**Issue by Zhou-Shilin** [PojavLauncherTeam/PojavLauncher_iOS#585]
### Describe the bug

Pojavlauncher flashes back.

### The log file and images/videos

[lastest.log](http://files.baimoqilin.top:8088/files.baimoqilin.top:8088/d/files/github-issues/Pojavlauncher/flashes-back/latestlog.txt)
![screenshots.MOV](https://files.baimoqilin.top:8088/files.baimoqilin.top:8088/d/files/github-issues/Pojavlauncher/flashes-back/screenshot.MOV)

### Steps To Reproduce

```markdown
1. Start Pojavlauncher with JIT
2. **Do not do anything**, just wait for a few seconds
3. Flashes back
```

### Expected Behavior

I expect nothing happens (because I do nothing)

### Platform

```markdown
- Device model: iPad Air 5
- iOS version: 16.2 Beta 2
- PojavLauncher version: 3.0 development 3c61b5b
```

**Comment by khanhduytran0** [comment]
Send latest PojavLauncher analytics data, can be found in Settings > Privacy > Analytics > Analysis Data.

**Comment by Zhou-Shilin** [comment]
[PojavLauncher-2023-06-29-110755.ips.txt](https://github.com/PojavLauncherTeam/PojavLauncher_iOS/files/11906671/PojavLauncher-2023-06-29-110755.ips.txt)

**Comment by khanhduytran0** [comment]
Try deleting the account folder and login again
