### ISSUE TITLE
[Bug] Shaders not working

### ISSUE THREAD

**Issue by Zhou-Shilin** [PojavLauncherTeam/PojavLauncher_iOS#587]
### Describe the bug

See the picture below.
The game interface goes black after any shader is added. You can see the sun in some shaders.
_I'm using a translator, so some words may be strange._

### The log file and images/videos

![AEE1BD52-2532-4B29-AD93-D3C771148861](https://github.com/PojavLauncherTeam/PojavLauncher_iOS/assets/86581525/f5048779-7182-409f-9100-d7b2cde9adea)
![video](https://github.com/PojavLauncherTeam/PojavLauncher_iOS/assets/86581525/89305508-1664-4ce6-be15-d85a9e1fc596)

### Steps To Reproduce

```markdown
1. Launch Minecraft
2. Add any shader (BSL, 超低配光影水反, etc.)
3. You can only see the sun or nothing.
```

### Expected Behavior

I expect load the shader.

### Platform

```markdown
- Device model: iPad Air 5 (Apple M1 GPU)
- iOS version: 16.2
- PojavLauncher version: 3.0 developement
```
3c61b5b

**Comment by khanhduytran0** [comment]
Expected behavior, because Apple has never brought OpenGL 4 to Mx iPads

**Comment by GaucovyAero** [comment]
> > Expected behavior, because Apple has never brought OpenGL 4 to Mx iPads
> 
> So does Minecraft (or optifine?) support loading shaders by OpenGL 3?

well, 3.0 isnt enough, they also need everything 2.x and 1.x, but ANGLE does not have that, it only has 3.0/3.2
