### ISSUE TITLE
Add to TestFlight

### ISSUE THREAD

**Issue by Quocnam201010** [PojavLauncherTeam/PojavLauncher_iOS#589]
### Is this request related to a bug?

I tried to download Trollstore, Altstore,… but everytime I try to install the app, the screen said:” unable to install app because its integrity cannot be verified”. I tried all ways but I can’t install them. 

### Describe the request.

Add PojavLauncher on to TestFlight.

### Anything else?
If can’t. Please help me installing them.
_No response_

**Comment by khanhduytran0** [comment]
Submitting to TestFlight is not possible because PojavLauncher requires JIT which is not allowed.
Use SideStore to install.

**Comment by Mickeljay** [comment]
blank
