### ISSUE TITLE
Info Lobymod4

### ISSUE THREAD

**Issue by xuechenyi1** [PojavLauncherTeam/PojavLauncher_iOS#590]
### Describe the bug

When using Lobymod4, it can't start. Sometimes there is no "LobyMod" option at all when downloaded or the next startup disappears.

### The log file and images/videos

(Picture and Log Update Failed)

### Steps To Reproduce

```markdown
1.Start PojavLauncher
2.Select Version
3.Start Game
4.Abnormal exit of the game, error code-1337
```

### Expected Behavior

Play normally.

### Platform

```markdown
- Device model: iPhone7
- iOS version: 15.4.1
- PojavLauncher version: 2.2 Deepslate
```

**Comment by herbrine8403** [comment]
I've tried that before, and it went wrong. The first error is the missing jar file. LabyMod4 does not run with jar files, so I did not bring the jar file when I installed LabyMod4. The Pojavlauncher iOS does not support it, just like BakaXL does, so it does. The second error is that the OpenGL version of Pojavlauncher iOS is too low. The highest OpenGL version of PojavLauncher is 4.1, while LabyMod4 only supports version 4.6 and later, so an error occurs.

中文/Chinese：
我之前也尝试过，但也出错了。第一个错误是缺少jar文件，因为LabyMod4是不用jar文件运行的，所以在所以在安装LabyMod4的时候就没有带jar文件，而Pojavlauncher iOS跟BakaXL一样不支持，所以会出错。第二个错误是OpenGL版本过低，Pojavlauncher iOS的OpenGL版本最高是4.1，而LabyMod4仅支持4.6及以上的版本，所以会出错。
