### ISSUE TITLE
Request failed: bad request (400)

### ISSUE THREAD

**Issue by the-duck2010** [PojavLauncherTeam/PojavLauncher_iOS#591]
### Describe the bug

When I open the app, it just displays a pop up saying “ Request failed: bad request (400) “. 
The “play” button is then disabled. 

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher_iOS/files/12137331/latestlog.txt)

### Steps To Reproduce

```markdown
Start pojavlauncher on a unjailbroken iPhone 13 pro sideloaded with Altstore
```

### Expected Behavior

I expect to be able to start the game

### Platform

```markdown
- Device model: iPhone 13 pro
- iOS version: 15.5
- PojavLauncher version: 2.2-development
```

**Comment by the-duck2010** [comment]
Quick thing I just realized: the button is greyed out but not actually disabled. ![image](https://github.com/PojavLauncherTeam/PojavLauncher_iOS/assets/75392757/d05b71f2-8db2-4408-9c0c-1b6d36e1b821)
![image](https://github.com/PojavLauncherTeam/PojavLauncher_iOS/assets/75392757/fe1e4b95-b3e7-497e-8d8b-88f01251ed66)

**Comment by khanhduytran0** [comment]
Outdated version. Please use v3.0 in Actions.
~~also what made you update to 15.5 rather than staying in 15.4.1?~~

**Comment by JulianBvW** [comment]
> Outdated version. Please use v3.0 in Actions. ~also what made you update to 15.5 rather than staying in 15.4.1?~

But 2.2 is the latest version I can find. Where can I download v3.0?

**Comment by LeBobrze** [comment]
Any luck?

**Comment by GaucovyAero** [comment]
> > Outdated version. Please use v3.0 in Actions. ~also what made you update to 15.5 rather than staying in 15.4.1?~
> 
> But 2.2 is the latest version I can find. Where can I download v3.0?

click on github actions here on this repository

**Comment by GaucovyAero** [comment]
> Any luck?

read above comment 👍

**Comment by AndreCodin24** [comment]
You need, or buy Xbox Game Pass.
