### ISSUE TITLE
Error code 1 on IOS

### ISSUE THREAD

**Issue by Nonowarwood** [PojavLauncherTeam/PojavLauncher_iOS#592]
### Describe the bug

When i start the game with any version of forge selected the game crash

### The log file and images/videos

[latestlog-1.txt](https://github.com/PojavLauncherTeam/PojavLauncher_iOS/files/12147843/latestlog-1.txt)

### Steps To Reproduce

```markdown
1. Start PojavLauncher 
2. Select any version of forge
3. Start the game
.
```

### Expected Behavior

I don’t realy Know because I start using PojavLauncher on iOS this week

### Platform

```markdown
- Device model: iPhone 12 Pro Max
- iOS version: 16.5.1
- PojavLauncher version: 2.2
```

### Anything else?

So I can’t play the game and it produce with no mod 

PS: I am ont English si excuse if I don’t speak or well

**Comment by khanhduytran0** [comment]
Outdated version. Use v3 to play

**Comment by Nonowarwood** [comment]
Did thé version of PojavLauncher us like v2.2 Deepslate etc ?

**Comment by khanhduytran0** [comment]
V3 is currently in [Actions](https://github.com/PojavLauncherTeam/PojavLauncher_iOS/actions)

**Comment by Nonowarwood** [comment]
Thanks ,
Do you know how can I easily enable JIT on IOS

**Comment by khanhduytran0** [comment]
In SideStore, hold and enable JIT there.

**Comment by mkbsprod** [comment]
doesn't work, any version is crashing
iphone 12
