### ISSUE TITLE
Developer builds crashes every time the game opens

### ISSUE THREAD

**Issue by incyada** [PojavLauncherTeam/PojavLauncher_iOS#593]
### Describe the bug

Hi, every time I try opening the game in a developer build, it crashes every time. It seems to mostly affect me since I heard that others didn’t experience that issue.

### The log file and images/videos

Logs: 
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher_iOS/files/12161819/latestlog.txt)

### Steps To Reproduce

```markdown
It may not affect everyone but here are the step to reproduce it:
1.Open PojavLauncher
2.Enable Jit
3.open Minecraft
4.within seconds, the game doesn’t go through the mojang logo since it crashes.
```

### Expected Behavior

It should be fine and I’m able to test the developer builds without the game crashing a soon as I open it.

### Platform

```markdown
- Device model: iPhone 12
- iOS version: 16.5
- PojavLauncher version: dev build 1102
```

### Anything else?

My theory is that, sodium doesn’t support OpenGL 4 due to rendering issues, that’s confirmed BUT, the reason I’m still posting this is due to the sodium patcher also not working. I could remove sodium from my mods folder, but then the game will run worse.

**Comment by incyada** [comment]
Because of the crashes, the ONLY way I could play with these builds is without sodium, and any mod that needs it i.e: Reese's sodium options, indium, continuity.

**Comment by khanhduytran0** [comment]
Sodium default config requires OpenGL 4 thus you need to patch it.
