### ISSUE TITLE
When i try load modpack, it close

### ISSUE THREAD

**Issue by Proteamkoxx** [PojavLauncherTeam/PojavLauncher_iOS#595]
### Describe the bug

When I try load modpack, it closes itself without any message. 

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher_iOS/files/12270116/latestlog.txt)

### Steps To Reproduce

```markdown
1.Enable Jit
2.Start PojavLauncher
3.Wait 1-2 minute 
4.Game closes itself
```

### Expected Behavior

I expected it gonna load

### Platform

```markdown
- Device model:iPhone 13
- iOS version:16.6
- PojavLauncher version:Latest Release
```

**Comment by khanhduytran0** [comment]
please try again in the latest build or remove Xmx arguments

**Comment by Proteamkoxx** [comment]
> please try again in the latest build or remove Xmx arguments

I alerady updated to new bulid but it still crashes at end of load

**Comment by Proteamkoxx** [comment]
Here is a log 
[latest.log](https://github.com/PojavLauncherTeam/PojavLauncher_iOS/files/12501340/latest.log)
#

**Comment by GaucovyAero** [comment]
most probably out of menory
