### ISSUE TITLE
[Bug] Version problem/Mod problem

### ISSUE THREAD

**Issue by danzheng666** [PojavLauncherTeam/PojavLauncher_iOS#596]
### Describe the bug

1. I try to download version 1.12.2forge-14.23.4.2758 and enter this version of the game but it shows error code 1 exit
2. I try to install 1.20.1forge and Optfine at the same time, but when I enter the game, an error code -1 is displayed on the installation interface to exit
3. Whenever I want to port a modpack, I get stuck on the red screen download interface every time

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher_iOS/files/12272693/latestlog.txt)
[latestlog2.txt](https://github.com/PojavLauncherTeam/PojavLauncher_iOS/files/12272696/latestlog2.txt)
[latestlog3.txt](https://github.com/PojavLauncherTeam/PojavLauncher_iOS/files/12272702/latestlog3.txt)
![3B85E361-B9A8-45BB-9B4C-47199143E791](https://github.com/PojavLauncherTeam/PojavLauncher_iOS/assets/121393862/e13a36fb-12cd-4825-b7b8-90b590b56e62)

The log files correspond to the above three bugs
This picture is about the third bug

### Steps To Reproduce

```markdown
1.Open PojavLauncher, enter forge1.12.2 forge-14.23.4.2758, then exit with error code 1
2.Open PojavLauncher, enter forge1.20.1, and exit with error code -1
3.Open PojavLauncher, enter forge1.16.5, and after a second, the download mod list will be paused
```

### Expected Behavior

I hope you fix these bugs and do better

### Platform

```markdown
- Device model: iPad Pro 2020
- iOS version: 15.2
- PojavLauncher version: 3.0
```

**Comment by GaucovyAero** [comment]
1: turn off arc capes dns
2: disable the forge loading screen
3: you are missing modernlife configs, but maybe its some shaders failing to convert, who knows
