### ISSUE TITLE
[虫子] shadow packages are not supported under the iOS16 system

### ISSUE THREAD

**Issue by 1006034287** [PojavLauncherTeam/PojavLauncher_iOS#599]
### Describe the bug

IOS16 system pojavlauncher cannot enable shaderpacks files such as BSL or Chocapic, and an error will be reported every time the light and shadow are loaded and started
![Uploading IMG_3956.PNG…]()
![Uploading IMG_3954.PNG…]()
![Uploading IMG_3955.PNG…]()

### Steps To Reproduce

```markdown
1. Start pojavlauncher
2. At the bottom, select "1.18.2 Optimize HD u h7"
3. Enter the game
4. Options - Video Settings - Light and Shadow - Select Light and Shadow Package - Complete
5. Start the game
6. Error reporting and flashing
```

### Expected Behavior

I hope to be able to successfully run various shaderpacks on iOS 16 devices like computers

### Platform

```markdown
- Device model: iPhone 13
- iOS version: 16.6
- PojavLauncher version: 2.1.2
```

**Comment by GaucovyAero** [comment]
https://github.com/Open4Es/Open4Es-Shader-IOS
other shaders dont work, i think this one only works on mc 1.8 to 1.16.5
