### ISSUE TITLE
Forge Installer Error

### ISSUE THREAD

**Issue by admin-elvistrujanovic** [PojavLauncherTeam/PojavLauncher_iOS#60]
![image](https://user-images.githubusercontent.com/45666011/108621784-06bbed00-7435-11eb-9ad3-3242495c438c.png)

Can you fix this error?

**Comment by khanhduytran0** [comment]
Did you download forge-installer-headless.jar?

**Comment by admin-elvistrujanovic** [comment]
> Did you download forge-installer-headless.jar?

Yes (v1.0.1 and v1.0.0)

**Comment by khanhduytran0** [comment]
Where it was placed?

**Comment by lanspring** [comment]
Me too. Which path do I need to put the files in

**Comment by khanhduytran0** [comment]
You need move these to a path that Terminal can access.

**Comment by lanspring** [comment]
> You need move these to a path that Terminal can access.

Thank you, it can work normally

**Comment by hahawang-boom** [comment]
兄弟可以教下我吗？跟你一样的问题

**Comment by lanspring** [comment]
> 兄弟可以教下我吗？跟你一样的问题

把两个文件复制到/var/mobile目录下，打开终端输入命令试试

**Comment by hahawang-boom** [comment]
谢谢老哥！成功啦

**Comment by lanspring** [comment]
> 谢谢老哥！成功啦

我也是成功了，就是进不了游戏界面，显示黑屏，键位可以看到- -

**Comment by hahawang-boom** [comment]
我可以进游戏，但是在游戏主页面不能触屏了，只能点tab一个一个的选。进入世界后正常

**Comment by lanspring** [comment]
> 我可以进游戏，但是在游戏主页面不能触屏了，只能点tab一个一个的选。进入世界后正常

你的启动器是最新版本吗？加我qq我们深入的聊聊/滑稽

**Comment by hahawang-boom** [comment]
我加你，你留QQ

**Comment by lanspring** [comment]
> 我加你，你留QQ

495522415

**Comment by hahawang-boom** [comment]
搜不到，只能找到一个群。你加我吧3233451509
