### ISSUE TITLE
[Bug] <iOS14.4Using the joystick version will flash.>

### ISSUE THREAD

**Issue by XEYt44** [PojavLauncherTeam/PojavLauncher_iOS#602]
### Describe the bug

pojavlauncher3.0Rocker versionDon't seem to support it.
iOS14.4 iPhone11He will flicker.

### The log file and images/videos

Uploading IMG_2229.MP4…

### Steps To Reproduce

```markdown
Flicker
```

### Expected Behavior

I hope I can fix this.我希望我能修好它。我希望

### Platform

```markdown
- Device model: iPhone11
- iOS version: 14.3
- PojavLauncher version: 3.0
```

**Comment by Kinda-Stormy** [comment]
I'm just wondering, why are you still on iOS 14?

**Comment by khanhduytran0** [comment]
@Kinda-Stormy Pretty sure for a jailbreak/TrollStore
@XEYt44 please send latestlog.txt; video didn’t even have enough time to upload

**Comment by XEYt44** [comment]
UploaAfter uploading the log, I started the game and flashed directly without any hint to go back to the main interface of the phone.

**Comment by khanhduytran0** [comment]
> UploaAfter
@XEYt44 looks like you didn’t wait long enough for the log to upload

**Comment by XEYt44** [comment]
> > UploaAfter
> 
> @XEYt44看起来你没等足够长的时间让日志上传

I can't upload my log, because he didn't show it and returned it to the desktop.

**Comment by GaucovyAero** [comment]
i guess its fixed? lmk if you want to reopen?
