### ISSUE TITLE
[F-Req] <Removing the three dots on top while in-game>

### ISSUE THREAD

**Issue by Kinda-Stormy** [PojavLauncherTeam/PojavLauncher_iOS#604]
### Is this request related to a bug?

not related to a bug

### Describe the request.

I would like to see those three dots at the top be removed while in-game, in the menu it's fine. For me they get in the way of my custom controls
![IMG_0740](https://github.com/PojavLauncherTeam/PojavLauncher_iOS/assets/80485413/d62cc3e4-d3a5-4f9e-b913-45adf0304f58)

**Comment by khanhduytran0** [comment]
It’s a part of iPadOS multitasking mode and cannot be hidden without hiding the home indicator altogether (enable “Hide Home Indicator” in debug settings), which conflicts with slidable hotbar; or enable Guided Access to solve both issues.

**Comment by Kinda-Stormy** [comment]
okay, thanks for the help!

**Comment by Kinda-Stormy** [comment]
closed
