### ISSUE TITLE
Game crashes when try to run shaders using zink rederer after joining a world 

### ISSUE THREAD

**Issue by abhishekgi** [PojavLauncherTeam/PojavLauncher_iOS#605]
### Describe the bug

When i apply shaders and load a world it crashes 

### The log file and images/videos

I will upload 🙃

### Steps To Reproduce

```markdown
Start pojav 
Select zink renderer 
Apply shaders in menu or in a world 
It will crash after joining a world or if you already in world it will crash instantly
```

### Expected Behavior

It should run shaders 

### Platform

```markdown
- Device model: ipad 9 wifi 
- iOS version: ipad os 16.6
- PojavLauncher version: #1114
```

**Comment by Mario191209** [comment]
I'm afraid that zink doesn't work on ios when you're using shader

**Comment by Mario191209** [comment]
It's working, but shader doesn't work.

**Comment by abhishekgi** [comment]
Thank you for telling this 🤣

**Comment by Kinda-Stormy** [comment]
Zink is still brand new on iOS 16 right now, so maybe give the devs some time, also are you using Optifine or Sodium/Iris?

**Comment by abhishekgi** [comment]
I am using optifine

**Comment by Kinda-Stormy** [comment]
nvm, this isn't a minecraft issue, this a zink issue, zink is still new on iOS 16 so you should probably just wait for now.

**Comment by GaucovyAero** [comment]
closing this as a duplicate because another issue has logs of this
