### ISSUE TITLE
[Bug] I have bought Minecraft, but only the demo is alvaiable

### ISSUE THREAD

**Issue by Pemptous** [PojavLauncherTeam/PojavLauncher_iOS#607]
### Describe the bug

As I say on the title, I bought Minecraft (about 10 hours ago) on minecraft.net at my Microsoft account. However when I login with my Microsoft account (the same acc) it downloads the demo assets and I’m able to play only the demo

### Steps To Reproduce

```markdown
Start Pojav
Login
Select Profil
Tap “play”
```

### Expected Behavior

I expect the game to download the files of the version and play he default version 

### Platform

```markdown
- Device model: iPad 9
- iOS version: latest
- PojavLauncher version: latest
```

### Anything else?

Is there any way to copy the files of the version (I have them) on the .Minecraft folder. However it’s hidden, sooooooo…I need help

**Comment by GaucovyAero** [comment]
be sure to set up your minecraft account at minecraft.net

**Comment by Pemptous** [comment]
As I said I have already bought it from there

**Comment by Pemptous** [comment]
I’m not sure what you exactly mean. However, I have checked it on Xbox app and on Microsoft store, I’m not sure what is wrong

**Comment by khanhduytran0** [comment]
Go to https://www.minecraft.net/msaprofile/mygames/editprofile and check if you have username set up.

**Comment by Pemptous** [comment]
Thank you so, so much! It’s working now and I can even play online. There’s re no words to thank you!
