### ISSUE TITLE
[Bug] Game crashes when open iOS Control Center

### ISSUE THREAD

**Issue by Zhou-Shilin** [PojavLauncherTeam/PojavLauncher_iOS#608]
### Describe the bug

Game crashes when open iOS Control Center.
Edit: **I've since tried 1.20.1 vanilla and 1.18.2 forge (manually installed forge) and neither had this problem. It might because the auto-installer.**

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher_iOS/files/12640128/latestlog.txt)
And this one maybe useful:
[hs_err_pid51028.log](https://github.com/PojavLauncherTeam/PojavLauncher_iOS/files/12640127/hs_err_pid51028.log)

I tried to open control center but then the app crashed, the control center didn't open either.
When the game goes to the start screen, or after entering a world or server, the problem also exists.
https://github.com/PojavLauncherTeam/PojavLauncher_iOS/assets/86581525/7b4e6ba1-213f-427e-8621-304b6318a550

### Steps To Reproduce

```markdown
1. Start Pojavlauncher
2. Launch 1.20.1 with latest forge (forge is installed with the built-in forge installer)
3. Open iOS Control Center
4. Game crashes
```

### Expected Behavior

Nothing happens

### Platform

```markdown
- Device model: iPad Air 5
- iOS version: iPadOS 16.2 Developer Beta 2
- PojavLauncher version: 3.0-dev-pid51051 (https://github.com/PojavLauncherTeam/PojavLauncher_iOS/actions/runs/6126881722)
```

**Comment by khanhduytran0** [comment]
Auto installer uses the same installer as you download in Forge site, but it just clicks install automatically. Try adjusting something else

**Comment by ItAnthon** [comment]
This is fixed btw latest build, close issue
