### ISSUE TITLE
[F-Req] Run PojavLauncher without JIT

### ISSUE THREAD

**Issue by eTNTdiscord** [PojavLauncherTeam/PojavLauncher_iOS#609]
### Is this request related to a bug?

No.

### Describe the request.

Run PojavLauncher without JIT

### Anything else?

If no, maybe u can try cranking down the graphics?

**Comment by khanhduytran0** [comment]
Without JIT it’d be slow as hell and quickly drain your battery.
Instead, either just
- Borrow someone’s pc/laptop then install SideStore and enable JIT from there. **Do not update to iOS 17 until SideStore JIT enabler supports it.**
- Wait for Apple to support native sideloading (EU), though JIT works or not depending on whether EU will require to allow third party browser engines.
- Get an Android device.

**Comment by eTNTdiscord** [comment]
does the laptop have to be on for the game to work, because i use altstore and my pc has to be on for pojav to work

**Comment by khanhduytran0** [comment]
Nope, just use SideStore with the VPN tunnel, works anywhere as long as you have wifi or hotspot.

**Comment by eTNTdiscord** [comment]
oh ok.

**Comment by eTNTdiscord** [comment]
it has expiration?

**Comment by eTNTdiscord** [comment]
ok, does the apps like expire?

**Comment by eTNTdiscord** [comment]
@khanhduytran0

**Comment by khanhduytran0** [comment]
Nope, if you refresh it before it expires, or leave it in background for auto refresh. No need PC anymore.

**Comment by eTNTdiscord** [comment]
i updated mine to ios 17 i forgot that pojav requires JIT. what should i do @khanhduytran0

**Comment by DucNghia25** [comment]
Sao e tải về qua trollstore vào toàn bị văng v
