### ISSUE TITLE
[Bug] The game is minimized

### ISSUE THREAD

**Issue by Zhou-Shilin** [PojavLauncherTeam/PojavLauncher_iOS#611]
### Describe the bug

Just watch the video below

### The log file and images/videos

<This video is too big (10mb+) and cannot upload to github so it's on google drive>
https://drive.google.com/file/d/1MM5W5ihTpMws1gh-xqWCcr3FME73FXlg/view?usp=drive_link

### Steps To Reproduce

```markdown
1. Start Pojavlauncher
2. Launch Minecraft 1.8.9 (without forge and optifine)
3. Join a world or server (in the video i join hypixel bedwars 4v4)
```

### Expected Behavior

I expect nothing happens.

### Platform

```markdown
- Device model: iPad Air 5 (M1)
- iOS version: 16.2 Developer Beta 2
- PojavLauncher version: 3.0-dev 980ddd3
```

**Comment by GaucovyAero** [comment]
bind fullscreen to f12 in minecraft controls settings

**Comment by Zhou-Shilin** [comment]
it works thx @GaucovyAero XD
