### ISSUE TITLE
[F-Req] 1.20.2 Support (Bug?)

### ISSUE THREAD

**Issue by ItAnthon** [PojavLauncherTeam/PojavLauncher_iOS#614]
### Is this request related to a bug?

1.20.2 immediately crashes and doesn’t work, doesn’t even make an effort to post 
(at least the option is there)

This includes: Vanilla, Forge, and Fabric. [1.20.2]

### Describe the request.

Please add 1.20.2 support!

(Including mod loaders!)

### Anything else?

I’ve got no clue on how to add logs, but….

To reproduce the issue: grab any iOS device and try to play on 1.20.2

**Comment by khanhduytran0** [comment]
Should be fixed in be86b5f
