### ISSUE TITLE
[Bug] Consistent Crash under iOS 17

### ISSUE THREAD

**Issue by hydrationMan** [PojavLauncherTeam/PojavLauncher_iOS#617]
### Describe the bug

Attempting to start any version of Minecraft (in this case, 1.20.2) under iOS 17 and running on an iPhone 15 Pro Max results in a crash with error code -1, I am unsure if this happens on other devices. 

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher_iOS/files/12861413/latestlog.txt)

### Steps To Reproduce

```markdown
1. Start PojavLauncher
2. Attempt to run Minecraft 
3. Witness Crash with error code -1
```

### Expected Behavior

I expected the game to begin running, of which it unfortunately does not.

### Platform

```markdown
- Device model: iPhone 15 Pro Max
- iOS version: 17.0 (21A327)
- PojavLauncher version: 2.2-development (main/d9877bc)
```

### Anything else?

This appears to be the result of a Sandbox violation stopping sysctl-read, process fork and so on.

**Comment by GaucovyAero** [comment]
outdated build, use the latest one on github actions

**Comment by hydrationMan** [comment]
wow I mixed up the ipa's, one sec

**Comment by hydrationMan** [comment]
Yep, latest build resolves this. Sorry for the trouble.
