### ISSUE TITLE
Keeps telling me I’m unable to access the OptiInst file

### ISSUE THREAD

**Issue by JakobNorman** [PojavLauncherTeam/PojavLauncher_iOS#62]
![image](https://user-images.githubusercontent.com/79488116/108867128-b7e39400-75a9-11eb-9a3f-a116fed9d6d0.png)

**Comment by khanhduytran0** [comment]
Haven't you downloaded OptiInst.jar?

**Comment by JakobNorman** [comment]
Yes I did and optifine and OptiInst are in the same directory

**Comment by khanhduytran0** [comment]
What about `ls` command? **haven't you put them to current directory?**

**Comment by JakobNorman** [comment]
What's is that?

**Comment by khanhduytran0** [comment]
The list directory command

**Comment by JakobNorman** [comment]
Can you send it so I can see what you're talking about?

**Comment by khanhduytran0** [comment]
I mean execute ls command and give the output.
![image](https://user-images.githubusercontent.com/40482367/108923145-e2495600-766a-11eb-9ed6-42306c4b16d3.jpeg)

**Comment by JakobNorman** [comment]
![image](https://user-images.githubusercontent.com/79488116/108923270-5fce8100-75ed-11eb-8d50-c83158089d30.png)

**Comment by khanhduytran0** [comment]
So what you see? There isn't OptiInst.jar and OptiFine_1.16.5_HD_U_G7.jar in the **current directory**.

**Comment by JakobNorman** [comment]
![image](https://user-images.githubusercontent.com/79488116/108923741-37935200-75ee-11eb-9012-878810f38fb6.png)

This is all I needed to do

**Comment by khanhduytran0** [comment]
Yes

**Comment by JakobNorman** [comment]
Thanks a lot I'll let you know if it works

**Comment by JakobNorman** [comment]
![image](https://user-images.githubusercontent.com/79488116/108924485-90afb580-75ef-11eb-9794-d6ffeb4d10fe.jpeg)

I don't know what's todo

**Comment by khanhduytran0** [comment]
Where did you download optifine?

**Comment by JakobNorman** [comment]
Optifine.net

**Comment by JakobNorman** [comment]
I installed a different version and it worked I guess it was a false file

**Comment by JakobNorman** [comment]
How do I launch it

**Comment by JakobNorman** [comment]
![image](https://user-images.githubusercontent.com/79488116/108927243-c60ad200-75f4-11eb-80a0-3a3d4554e557.png)

I tried installing different version of 1.16 but they won't isntall

**Comment by JakobNorman** [comment]
Now for some reason none of the optifine are installing

**Comment by lanspring** [comment]
![15CA0DCA-2448-490E-9234-CA60555DAAFE](https://user-images.githubusercontent.com/79379583/108945504-ad9fc380-7697-11eb-9957-230bfb75f4f6.jpeg)
You must delete >,Write the pathIt,can work properly.

**Comment by lanspring** [comment]
> ![15CA0DCA-2448-490E-9234-CA60555DAAFE](https://user-images.githubusercontent.com/79379583/108945504-ad9fc380-7697-11eb-9957-230bfb75f4f6.jpeg)
> You must delete >,Write the pathIt,can work properly.

![394C2F23-C91C-4DEF-8B6B-458CFBD9A455](https://user-images.githubusercontent.com/79379583/108945942-931a1a00-7698-11eb-873d-65775f595765.jpeg)
Do as I say and get what you want :)

**Comment by lanspring** [comment]
![Uploading 76156A8B-B5AA-4949-A786-1BD1B5D1D4D7.png…]()

**Comment by JakobNorman** [comment]
It ended up fixing itself
