### ISSUE TITLE
[F-Req] Hey i would like to know if there’s a way to play Java without JIT.

### ISSUE THREAD

**Issue by PythonTilk** [PojavLauncherTeam/PojavLauncher_iOS#625]
### Is this request related to a bug?

I just wanna run my farms afk and not play.

**Comment by Zhou-Shilin** [comment]
no

**Comment by ItAnthon** [comment]
There isn’t a way to play PojavLauncher without JIT Compilation. 

Even then, it would take 18-20
minutes to load up your world (i tested this on the A12X) and this was a brand new world, so it could end up taking much longer for you. 

PojavLauncher without JIT Compilation would just not work out, and will never be added to PojavLauncher.

**Comment by abhishekgi** [comment]
> > There isn’t a way to play PojavLauncher without JIT Compilation.
> > Even then, it would take 18-20 minutes to load up your world (i tested this on the A12X) and this was a brand new world, so it could end up taking much longer for you.
> > PojavLauncher without JIT Compilation would just not work out, and will never be added to PojavLauncher.
> 
> wait wat, it only takes me few seconds to join a forge server with 20 mods and 1min to load my world (i use m1)

He is saying that without jit it would take that much time .
Like the utm SE version run without JIT but it is a lot slower than JIT version

**Comment by abhishekgi** [comment]
> ### Is this request related to a bug?
> I just wanna run my farms afk and not play.
> 
> ### Describe the request.
> _No response_
> 
> ### Anything else?
> _No response_

Issue section is not for questions bro , ask questions in the discussions section
