### ISSUE TITLE
[Bug] ios17 zink Renderer Not available

### ISSUE THREAD

**Issue by 0402Siesta0402** [PojavLauncherTeam/PojavLauncher_iOS#626]
### Describe the bug

There is no problem when set to auto, but light and shadow cannot be used.
But set it to zink black screen

### The log file and images/videos

https://github.com/PojavLauncherTeam/PojavLauncher_iOS/assets/126928193/eaef3dd7-94e5-4ab8-b4f8-5e75333be0f4

### Steps To Reproduce

```markdown
1.Start ProjavLauncher
2.Renderer-->Zink(Mesa21,0)
```

### Expected Behavior

fix problem

### Platform

```markdown
- Device model: iPhone 15
- iOS version: 17.0.2
- PojavLauncher version:2.2
```

**Comment by Kinda-Stormy** [comment]
I had the same issue on Ios 17.2

**Comment by GaucovyAero** [comment]
not supported yet
