### ISSUE TITLE
iOS16.1 + PL + TS2 + MC1.20.2= crash

### ISSUE THREAD

**Issue by aspauldingcode** [PojavLauncherTeam/PojavLauncher_iOS#628]
### Describe the bug

Using iOS 16.1, iPhone 12 Pro Max. 
Running Pojauv Launcher with TrollStore 2. 
Minecraft 1.19.4 works fine. 
Minecraft 1.20.2 crashes on launch. Doesn’t crash Pojav. 
using Pojav v. 2.2
Logs:

### The log file and images/videos

[latestlog.old.txt](https://github.com/PojavLauncherTeam/PojavLauncher_iOS/files/13531627/latestlog.old.txt)
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher_iOS/files/13531628/latestlog.txt)

### Steps To Reproduce

```markdown
1. Install Pojav with Trollstore 2 (might not even matter)

2. Launch it

3. Install mc 1.20.2
3.5 git rekt with hash mismatch error

4. Launch it after download completes

5. Git rekt as game crashes.
```

### Expected Behavior

Shouldn’t crash but..

### Platform

```markdown
- Device model: iPhone 12 Pro Max
- iOS version: 16.1
- PojavLauncher version: 2.2
```

### Anything else?

Not sure if My logs included the issue but I include just in case…

**Comment by ItAnthon** [comment]
You are using an old version of PojavLauncher. Download the ipa from GitHub Actions

https://github.com/PojavLauncherTeam/PojavLauncher_iOS/actions

**Comment by aspauldingcode** [comment]
> You are using an old version of PojavLauncher. Download the ipa from GitHub Actions
> 
> 
> 
> https://github.com/PojavLauncherTeam/PojavLauncher_iOS/actions

You mean, release or development builds?

**Comment by Achiyun** [comment]
me too, but i useing the version in Actions, unable to download My World, URL is null

**Comment by ItAnthon** [comment]
> > You are using an old version of PojavLauncher. Download the ipa from GitHub Actions
> > https://github.com/PojavLauncherTeam/PojavLauncher_iOS/actions
> 
> You mean, release or development builds?

no i mean you have to get the ipa from github actions. the releases don’t work with anything past 1.20.1
