### ISSUE TITLE
[Bug] can’t install by Scarlet

### ISSUE THREAD

**Issue by LUke8544** [PojavLauncherTeam/PojavLauncher_iOS#631]
### Describe the bug

When I install this app by Scarlet, it says I use a  wrong way to install so the JIT is not enabled on my device.

### Steps To Reproduce

```markdown
Start the app
Press the button on the left and above
```

### Expected Behavior

The app flashbacked

### Platform

```markdown
- Device model: iPhone 13mini
- iOS version: 17.1.2
- PojavLauncher version: latest release
```

**Comment by GaucovyAero** [comment]
jit wont work with scarlet, you have to have a pc to use sidestore
