### ISSUE TITLE
[Bug] 1.20 minecraft not launching with trollstore

### ISSUE THREAD

**Issue by Geskawary234** [PojavLauncherTeam/PojavLauncher_iOS#632]
### Describe the bug

When i try to launch 1.20.2 it gives me error. Idk what could cause it. Old versions(i tried beta1.7.3) launch fine i assume

### The log file and images/videos

[Pre-Init] PojavLauncher INIT!
[Pre-Init] Version: 2.2-development
[Pre-Init] Commit: d9877bc (main)
[Pre-Init] Device: iPhone 11
[Pre-Init] iOS 15.7.1 (TrollStore)
[Pre-init] Entitlements availability:
* com.apple.developer.kernel.extended-virtual-addressing: YES
* com.apple.developer.kernel.increased-memory-limit: YES
* com.apple.private.security.no-sandbox: YES
* dynamic-codesigning: NO
[Debugging] Debug log enabled: YES
[Pre-init] Restored game directory preference (default)
[Pre-init] no-sandbox: YES, trying to enable JIT
calling ptrace(PT_TRACE_ME)
[Pre-init] JIT has been enabled with PT_TRACE_ME
[MCDL] Загрузка 1.20.2
[MCDL] SHA1 checker: file doesn't exist: 1.20.2.json
[MCDL] SHA1 passed for 1.20.2.json
[MCDL] Загрузка 8
[MCDL] SHA1 checker: file doesn't exist: 8.json
[MCDL] SHA1 passed for 8.json
[MCDL] Begin: download libraries
[MCDL] SHA1 passed for java-objc-bridge-1.1.jar
[MCDL] SHA1 passed for oshi-core-6.4.5.jar
[MCDL] SHA1 passed for gson-2.10.1.jar
[MCDL] SHA1 passed for failureaccess-1.0.1.jar
[MCDL] SHA1 passed for guava-32.1.2-jre.jar
[MCDL] SHA1 passed for icu4j-73.2.jar
[MCDL] SHA1 checker: file doesn't exist: authlib-5.0.47.jar
[MCDL] SHA1 passed for authlib-5.0.47.jar
[MCDL] SHA1 passed for blocklist-1.0.10.jar
[MCDL] SHA1 checker: file doesn't exist: brigadier-1.1.8.jar
[MCDL] SHA1 passed for brigadier-1.1.8.jar
[MCDL] SHA1 passed for datafixerupper-6.0.8.jar
[MCDL] SHA1 passed for logging-1.1.1.jar
[MCDL] SHA1 passed for patchy-2.2.10.jar
[MCDL] SHA1 passed for text2speech-1.17.9.jar
[MCDL] SHA1 passed for commons-codec-1.16.0.jar
[MCDL] SHA1 passed for commons-io-2.13.0.jar
[MCDL] SHA1 passed for commons-logging-1.2.jar
[MCDL] SHA1 passed for netty-buffer-4.1.97.Final.jar
[MCDL] SHA1 passed for netty-codec-4.1.97.Final.jar
[MCDL] SHA1 passed for netty-common-4.1.97.Final.jar
[MCDL] SHA1 passed for netty-handler-4.1.97.Final.jar
[MCDL] SHA1 passed for netty-resolver-4.1.97.Final.jar
[MCDL] SHA1 passed for netty-transport-classes-epoll-4.1.97.Final.jar
[MCDL] SHA1 passed for netty-transport-native-epoll-4.1.97.Final-linux-aarch_64.jar
[MCDL] SHA1 passed for netty-transport-native-epoll-4.1.97.Final-linux-x86_64.jar
[MCDL] SHA1 passed for netty-transport-native-unix-common-4.1.97.Final.jar
[MCDL] SHA1 passed for netty-transport-4.1.97.Final.jar
[MCDL] SHA1 passed for fastutil-8.5.12.jar
[MCDL] SHA1 passed for jna-platform-5.13.0.jar
[MCDL] SHA1 passed for jna-5.13.0.jar
[MCDL] SHA1 passed for jopt-simple-5.0.4.jar
[MCDL] SHA1 passed for commons-compress-1.22.jar
[MCDL] SHA1 passed for commons-lang3-3.13.0.jar
[MCDL] SHA1 passed for httpclient-4.5.13.jar
[MCDL] SHA1 passed for httpcore-4.4.16.jar
[MCDL] SHA1 passed for log4j-api-2.19.0.jar
[MCDL] SHA1 passed for log4j-core-2.19.0.jar
[MCDL] SHA1 passed for log4j-slf4j2-impl-2.19.0.jar
[MCDL] SHA1 passed for joml-1.10.5.jar
[MCDL] Skipped library org.lwjgl:lwjgl-glfw:3.3.2
[MCDL] Skipped library org.lwjgl:lwjgl-glfw:3.3.2:natives-linux
[MCDL] Skipped library org.lwjgl:lwjgl-glfw:3.3.2:natives-macos
[MCDL] Skipped library org.lwjgl:lwjgl-glfw:3.3.2:natives-macos-arm64
[MCDL] Skipped library org.lwjgl:lwjgl-glfw:3.3.2:natives-windows
[MCDL] Skipped library org.lwjgl:lwjgl-glfw:3.3.2:natives-windows-arm64
[MCDL] Skipped library org.lwjgl:lwjgl-glfw:3.3.2:natives-windows-x86
[MCDL] SHA1 passed for slf4j-api-2.0.7.jar
[MCDL] SHA1 checker: file doesn't exist: 1.20.2.jar
[MCDL] Skipped library org.lwjgl:lwjgl-jemalloc:3.3.2
[MCDL] Skipped library org.lwjgl:lwjgl-jemalloc:3.3.2:natives-linux
[MCDL] Skipped library org.lwjgl:lwjgl-jemalloc:3.3.2:natives-macos
[MCDL] Skipped library org.lwjgl:lwjgl-jemalloc:3.3.2:natives-macos-arm64
[MCDL] Skipped library org.lwjgl:lwjgl-jemalloc:3.3.2:natives-windows
[MCDL] Skipped library org.lwjgl:lwjgl-jemalloc:3.3.2:natives-windows-arm64
[MCDL] Skipped library org.lwjgl:lwjgl-jemalloc:3.3.2:natives-windows-x86
[MCDL] Skipped library org.lwjgl:lwjgl-openal:3.3.2
[MCDL] Skipped library org.lwjgl:lwjgl-openal:3.3.2:natives-linux
[MCDL] Skipped library org.lwjgl:lwjgl-openal:3.3.2:natives-macos
[MCDL] Skipped library org.lwjgl:lwjgl-openal:3.3.2:natives-macos-arm64
[MCDL] Skipped library org.lwjgl:lwjgl-openal:3.3.2:natives-windows
[MCDL] Skipped library org.lwjgl:lwjgl-openal:3.3.2:natives-windows-arm64
[MCDL] Skipped library org.lwjgl:lwjgl-openal:3.3.2:natives-windows-x86
[MCDL] Skipped library org.lwjgl:lwjgl-opengl:3.3.2
[MCDL] Skipped library org.lwjgl:lwjgl-opengl:3.3.2:natives-linux
[MCDL] Skipped library org.lwjgl:lwjgl-opengl:3.3.2:natives-macos
[MCDL] Skipped library org.lwjgl:lwjgl-opengl:3.3.2:natives-macos-arm64
[MCDL] Skipped library org.lwjgl:lwjgl-opengl:3.3.2:natives-windows
[MCDL] Skipped library org.lwjgl:lwjgl-opengl:3.3.2:natives-windows-arm64
[MCDL] Skipped library org.lwjgl:lwjgl-opengl:3.3.2:natives-windows-x86
[MCDL] Skipped library org.lwjgl:lwjgl-stb:3.3.2
[MCDL] Skipped library org.lwjgl:lwjgl-stb:3.3.2:natives-linux
[MCDL] Skipped library org.lwjgl:lwjgl-stb:3.3.2:natives-macos
[MCDL] Skipped library org.lwjgl:lwjgl-stb:3.3.2:natives-macos-arm64
[MCDL] Skipped library org.lwjgl:lwjgl-stb:3.3.2:natives-windows
[MCDL] Skipped library org.lwjgl:lwjgl-stb:3.3.2:natives-windows-arm64
[MCDL] Skipped library org.lwjgl:lwjgl-stb:3.3.2:natives-windows-x86
[MCDL] Skipped library org.lwjgl:lwjgl-tinyfd:3.3.2
[MCDL] Skipped library org.lwjgl:lwjgl-tinyfd:3.3.2:natives-linux
[MCDL] Skipped library org.lwjgl:lwjgl-tinyfd:3.3.2:natives-macos
[MCDL] Skipped library org.lwjgl:lwjgl-tinyfd:3.3.2:natives-macos-arm64
[MCDL] Skipped library org.lwjgl:lwjgl-tinyfd:3.3.2:natives-windows
[MCDL] Skipped library org.lwjgl:lwjgl-tinyfd:3.3.2:natives-windows-arm64
[MCDL] Skipped library org.lwjgl:lwjgl-tinyfd:3.3.2:natives-windows-x86
[MCDL] Skipped library org.lwjgl:lwjgl:3.3.2
[MCDL] Skipped library org.lwjgl:lwjgl:3.3.2:natives-linux
[MCDL] Skipped library org.lwjgl:lwjgl:3.3.2:natives-macos
[MCDL] Skipped library org.lwjgl:lwjgl:3.3.2:natives-macos-arm64
[MCDL] Skipped library org.lwjgl:lwjgl:3.3.2:natives-windows
[MCDL] Skipped library org.lwjgl:lwjgl:3.3.2:natives-windows-arm64
[MCDL] Skipped library org.lwjgl:lwjgl:3.3.2:natives-windows-x86
[MCDL] SHA1 passed for 1.20.2.jar
[MCDL] Finished: download libraries
[MCDL] Begin: download assets
[MCDL] SHA1 checker: file doesn't exist: c2511ffc48374a7b05f83e0718bba9875a1ecfa7
[MCDL] SHA1 checker: file doesn't exist: a661b5622172ea1ce1fa9ec78fad484d118e5689
[MCDL] SHA1 checker: file doesn't exist: af6b7387f6d3140d630060c8efe5d25493d9e69c
[MCDL] SHA1 checker: file doesn't exist: 6994b2d54e4ce1e6b65efefac0200faffa7386d0
[MCDL] SHA1 checker: file doesn't exist: 1e37a7e44e34d5a0e338c2d57424eaab4ba8eb46
[MCDL] SHA1 checker: file doesn't exist: 7cd3d8225fa509ad313cbf622341b90d0b641e7b
[MCDL] SHA1 checker: file doesn't exist: 98fe2b2b0c6bcc3f921c1ae8ec0686b719569e70
[MCDL] SHA1 checker: file doesn't exist: 5716954e6041e0ec81b8d13b18b31b576d0067ee
[MCDL] SHA1 checker: file doesn't exist: 5c84f54276722bea66088e2774e0fcd00929ae58
[MCDL] SHA1 checker: file doesn't exist: 141458e36420686689a4a804fc66b2cd131cd6a1
[MCDL] SHA1 checker: file doesn't exist: 9be5bd79cec57751d647b70d2502ef7ea23a4791
[MCDL] SHA1 checker: file doesn't exist: a9b1ed0987ebce1032d83588fece1ef12642b602
[MCDL] SHA1 checker: file doesn't exist: 21d4ebdf82249ccdcda3f01b23bb783490fe57d7
[MCDL] SHA1 checker: file doesn't exist: 3074b4ae157b43321c2310de6e930b6584e1caac
[MCDL] SHA1 checker: file doesn't exist: 162e1406a22bda7483ad1b643a4277bec636c26f
[MCDL] SHA1 checker: file doesn't exist: ed1727e71588360e17a9ec891e448e2dc7cfe4ea
[MCDL] SHA1 checker: file doesn't exist: 1b3b43234e41b3de5da436ea098ebb84f8363540
[MCDL] SHA1 checker: file doesn't exist: 5985e73faa571a80ce67ea3ced8f90483bf942d6
[MCDL] SHA1 checker: file doesn't exist: aab5cf806b0948e7cf0b858fa36385913a2e486f
[MCDL] SHA1 passed for 3615/3616 asset files
Note: some files of 1.19+ are skipped to workaround an issue
[MCDL] Finished: download assets
Successfully set Jetsam task limit
[MCDL] Warning: couldn't find SHA for /var/mobile/Containers/Data/Application/3C37410D-3F90-43DF-A8A5-57BE08C633A7/Documents/Library/Application Support/minecraft/versions/1.20.2/1.20.2.json, have to assume it's good.
[MCDL] SHA1 passed for 8.json
[JavaLauncher] Beginning JVM launch
[JavaLauncher] Attempting to change to Java 17 (actual might be higher)
[JavaLauncher] JAVA_HOME is now set to /var/containers/Bundle/Application/8A3C4C6D-9E5F-48F3-853A-45F3D4FA3CCF/PojavLauncher.app/java_runtimes/java-17-openjdk
[JavaLauncher] Restored preference: RENDERER is set to auto
[JavaLauncher] Max RAM allocation is set to 962 MB
[Init] Found JLI lib
[Init] Calling JLI_Launch
WARNING: Unknown module: cpw.mods.bootstraplauncher specified to --add-exports
Arc Capes DNS Injector
Parts of Alibaba's DCM library were used, please read https://github.com/alibaba/java-dns-cache-manipulator/blob/main/README.md for more info
Added DNS cache entry: s.optifine.net/23.95.137.176
Launching Minecraft 1.20.2
Ignored non-exists file: /var/mobile/Containers/Data/Application/3C37410D-3F90-43DF-A8A5-57BE08C633A7/Documents/Library/Application Support/minecraft/libraries/io/netty/netty-transport-native-epoll/4.1.97.Final/netty-transport-native-epoll-4.1.97.Final.jar
Ignored non-exists file: /var/mobile/Containers/Data/Application/3C37410D-3F90-43DF-A8A5-57BE08C633A7/Documents/Library/Application Support/minecraft/libraries/org/lwjgl/lwjgl-glfw/3.3.2/lwjgl-glfw-3.3.2.jar
Ignored non-exists file: /var/mobile/Containers/Data/Application/3C37410D-3F90-43DF-A8A5-57BE08C633A7/Documents/Library/Application Support/minecraft/libraries/org/lwjgl/lwjgl-jemalloc/3.3.2/lwjgl-jemalloc-3.3.2.jar
Ignored non-exists file: /var/mobile/Containers/Data/Application/3C37410D-3F90-43DF-A8A5-57BE08C633A7/Documents/Library/Application Support/minecraft/libraries/org/lwjgl/lwjgl-openal/3.3.2/lwjgl-openal-3.3.2.jar
Ignored non-exists file: /var/mobile/Containers/Data/Application/3C37410D-3F90-43DF-A8A5-57BE08C633A7/Documents/Library/Application Support/minecraft/libraries/org/lwjgl/lwjgl-opengl/3.3.2/lwjgl-opengl-3.3.2.jar
Ignored non-exists file: /var/mobile/Containers/Data/Application/3C37410D-3F90-43DF-A8A5-57BE08C633A7/Documents/Library/Application Support/minecraft/libraries/org/lwjgl/lwjgl-stb/3.3.2/lwjgl-stb-3.3.2.jar
Ignored non-exists file: /var/mobile/Containers/Data/Application/3C37410D-3F90-43DF-A8A5-57BE08C633A7/Documents/Library/Application Support/minecraft/libraries/org/lwjgl/lwjgl-tinyfd/3.3.2/lwjgl-tinyfd-3.3.2.jar
Ignored non-exists file: /var/mobile/Containers/Data/Application/3C37410D-3F90-43DF-A8A5-57BE08C633A7/Documents/Library/Application Support/minecraft/libraries/org/lwjgl/lwjgl/3.3.2/lwjgl-3.3.2.jar
Args init finished. Now starting game
2023-12-13 19:14:10,325 main ERROR appender Console has no parameter that matches element Policies
[19:14:10] [main/WARN]: Failed sysctl call: hw.cpufrequency, Error code: 2
[19:14:13] [Datafixer Bootstrap/INFO]: 192 Datafixer optimizations took 172 milliseconds
[19:14:14] [Render thread/INFO]: Environment: Environment[accountsHost=https://api.mojang.com, sessionHost=https://sessionserver.mojang.com, servicesHost=https://api.minecraftservices.com, name=PROD]
[19:14:15] [Render thread/INFO]: Setting user: Geskawary234
[19:14:15] [Render thread/INFO]: Backend library: LWJGL version 3.2.3 SNAPSHOT
[19:14:15] [Render thread/WARN]: Failed sysctl call: hw.cpufrequency, Error code: 2
---- Minecraft Crash Report ----
// There are four lights!

Time: 2023-12-13 19:14:15
Description: Initializing game

java.lang.ExceptionInInitializerError
	at com.mojang.blaze3d.platform.GLX._initGlfw(SourceFile:64)
	at com.mojang.blaze3d.systems.RenderSystem.initBackendSystem(SourceFile:847)
	at eqv.<init>(SourceFile:491)
	at net.minecraft.client.main.Main.main(SourceFile:214)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at net.kdt.pojavlaunch.Tools.launchMinecraft(Tools.java:141)
	at net.kdt.pojavlaunch.PojavLauncher.launchMinecraft(PojavLauncher.java:106)
	at net.kdt.pojavlaunch.PojavLauncher.main(PojavLauncher.java:55)
Caused by: java.lang.NullPointerException: Cannot invoke "String.contains(java.lang.CharSequence)" because the return value of "java.lang.System.getProperty(String)" is null
	at org.lwjgl.opengl.GL.<clinit>(GL.java:81)
	... 11 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at com.mojang.blaze3d.platform.GLX._initGlfw(SourceFile:64)
	at com.mojang.blaze3d.systems.RenderSystem.initBackendSystem(SourceFile:847)
	at eqv.<init>(SourceFile:491)

-- Initialization --
Details:
	Modules: 
Stacktrace:
	at net.minecraft.client.main.Main.main(SourceFile:214)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at net.kdt.pojavlaunch.Tools.launchMinecraft(Tools.java:141)
	at net.kdt.pojavlaunch.PojavLauncher.launchMinecraft(PojavLauncher.java:106)
	at net.kdt.pojavlaunch.PojavLauncher.main(PojavLauncher.java:55)

-- System Details --
Details:
	Minecraft Version: 1.20.2
	Minecraft Version ID: 1.20.2
	Operating System: Mac OS X (aarch64) version 15.7.1
	Java Version: 17.0.8-internal, N/A
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 136423936 bytes (130 MiB) / 304087040 bytes (290 MiB) up to 1015021568 bytes (968 MiB)
	CPUs: 6
	Processor Vendor: Apple Inc.
	Processor Name: Apple processor
	Identifier: Apple Inc. Family 0x462504d2 Model 0 Stepping 0
	Microarchitecture: unknown
	Frequency (GHz): -0.00
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 6
	Graphics card #0 name: unknown
	Graphics card #0 vendor: unknown
	Graphics card #0 VRAM (MB): 0.00
	Graphics card #0 deviceId: unknown
	Graphics card #0 versionInfo: unknown
	Memory slot #0 capacity (MB): 0.00
	Memory slot #0 clockSpeed (GHz): 0.00
	Memory slot #0 type: unknown
	Virtual memory max (MB): 3977.78
	Virtual memory used (MB): 2335.06
	Swap memory total (MB): 128.00
	Swap memory used (MB): 18.25
	JVM Flags: 3 total; -Xms128M -Xmx962M -Xbootclasspath/a:/var/containers/Bundle/Application/8A3C4C6D-9E5F-48F3-853A-45F3D4FA3CCF/PojavLauncher.app/libs_caciocavallo17/cacio-shared-1.18-SNAPSHOT.jar:/var/containers/Bundle/Application/8A3C4C6D-9E5F-48F3-853A-45F3D4FA3CCF/PojavLauncher.app/libs_caciocavallo17/cacio-tta-1.18-SNAPSHOT.jar
	JVM uptime in seconds: 6.595
	Launched Version: 1.20.2
	Backend library: LWJGL version 3.2.3 SNAPSHOT
	Backend API: Unknown
	Window size: <not initialized>
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: <disabled>
	Using VBOs: Yes
	Is Modded: Probably not. Client jar signature and brand is untouched
	Type: Client (map_client.txt)
	Locale: ru_RU
	CPU: <unknown>
#@!@# Game crashed! Crash report saved to: #@!@# /var/mobile/Containers/Data/Application/3C37410D-3F90-43DF-A8A5-57BE08C633A7/Documents/Library/Application Support/minecraft/crash-reports/crash-2023-12-13_19.14.15-client.txt
exit(-1) called
2023-12-13 19:15:28.401 PojavLauncher[587:18388] <CATransformLayer: 0x2826240e0> - changing property backgroundColor in transform-only layer, will have no effect

### Steps To Reproduce

```markdown
1. Start pojav launcher?
Idk, trollstore works fine, launcher says JIT is enabled
```

### Expected Behavior

Well i want to play minecraft

### Platform

```markdown
- Device model: iphone 11
- iOS version: 15.7.1
- PojavLauncher version: 2.2
```

**Comment by Geskawary234** [comment]
1.19.4 launched sucessfully. I have no clue guys, please help. Like i love to see at least 1.19 but i really want 1.20

**Comment by GaucovyAero** [comment]
you are on an old version, please use the latest build thats located in the actions tab here on github
