### ISSUE TITLE
[Bug] <Account corruption in one email>

### ISSUE THREAD

**Issue by speedyfriend67** [PojavLauncherTeam/PojavLauncher_iOS#635]
### Describe the bug

When I authorize to microsoft through xbox, my one gmail account connects to same other account. Like i use my gmail and it automatically connects to demo account i. Pojavlauncher. I have purchased java account few days ago and it seems my original account didn’t connected with my original account 

### Steps To Reproduce

```markdown
Start pojavlauncher 
Login with microsoft
Connect to my main account email
And it automatically connects to my demo account not a real java account. (Even i bought java account with the email
```

### Expected Behavior

Log in to my demo account

### Platform

```markdown
- Device model: iphone 11 prk
- iOS version: 16.6
- PojavLauncher version: 3.0 from action tab
```

**Comment by NAVECCIER** [comment]
same issue, reinstalling fixed it

**Comment by speedyfriend67** [comment]
alternative method : try login on pc mc launcher or web microsoft web workaround fixes that
