### ISSUE TITLE
[F-Req] Support Rubiduim

### ISSUE THREAD

**Issue by Zhou-Shilin** [PojavLauncherTeam/PojavLauncher_iOS#637]
### Ask the question here.

(using deepl translate, some words may be strange)
Hi!
I tried installing Rubidium+Oculus and Pojavlauncher tells me it's not supported. It's also true that the mod doesn't render properly. However I can't use Optifine either because it's not compatible with Steam 'n Rails. ~~So now there is a Shader loader mod that is compatible with Pojavlauncher, but not Optifine?~~ So please support rubidium!
(neo)forge 1.20.1

**Comment by GaucovyAero** [comment]
the message is from rubidium and not pojav, we gotta figure out a way to patch sodium for it to work

**Comment by Zhou-Shilin** [comment]
> the message is from rubidium and not pojav, we gotta figure out a way to patch sodium for it to work

so shall we change the label to a bug 🤔️

**Comment by GaucovyAero** [comment]
> > the message is from rubidium and not pojav, we gotta figure out a way to patch sodium for it to work
> 
> so shall we change the label to a bug or feature-req 🤔️

its not a bug, its a lack of features in gl4es that we have to work around
