### ISSUE TITLE
How to change mine craft version

### ISSUE THREAD

**Issue by djzdaman1** [PojavLauncherTeam/PojavLauncher_iOS#64]

**Comment by djzdaman1** [comment]
My screen is black when pressing offline play and there is no button other than play. There is no change version button so I’m not sure how to change to optifine.

**Comment by djzdaman1** [comment]
https://ibb.co/QnKr5bH

**Comment by massuus** [comment]
Go to Minecraft folder then config_ver.txt then type the version you wanne play in and then press save! Then restart the app.

**Comment by khanhduytran0** [comment]
Also the builtin editor, (I stills thinking nobody know it’s existence) 
![](https://user-images.githubusercontent.com/40482367/108021202-a30a7c00-7050-11eb-99ff-c0f557a5f7e5.jpeg)

**Comment by khanhduytran0** [comment]
You need update to latest build in order to showing correctly.
