### ISSUE TITLE
[Bug] <Short description>

### ISSUE THREAD

**Issue by colejrlol** [PojavLauncherTeam/PojavLauncher_iOS#640]
### Describe the bug

Demo mode enabled even though I have Minecraft purchased 

and yes I set my username already 

### The log file and images/videos

No logs

### Steps To Reproduce

```markdown
Idk
```

### Expected Behavior

I should have online enabled 

### Platform

```markdown
- Device model: iPhone 12 mini 
- iOS version: 16.2 TrollStore enabled 
- PojavLauncher version: 2.2
```

**Comment by colejrlol** [comment]
If confused with iOS version iOS 16.2 with TrollStore installed

**Comment by GaucovyAero** [comment]
try setting up your skin and relogging

**Comment by ItAnthon** [comment]
I want you to try something. Try to go to the files app, and open PojavLauncher’s file. Open the folder labeled “accounts” Delete the .json and try to login again.
