### ISSUE TITLE
[Bug] 1-3 fPS

### ISSUE THREAD

**Issue by MogwartUser** [PojavLauncherTeam/PojavLauncher_iOS#642]
### Describe the bug

I decided to play with the visualizer gl4es 1.1.4 - OpenGL 2.1 to support some mods on Forge/Optifine 1.16.5 when entering the game there were no problems until I entered the single player game, it was very laggy and the fps reached up to 3, in auto: were stable 60 fps

### The log file and images/videos

-

### Steps To Reproduce

```markdown
1. Start PojavLauncher 
2. Entered a single player game
3. 1-3 fps
```

### Expected Behavior

-

### Platform

```markdown
- Device model: iPad 2020
- iOS version: 14.7
- PojavLauncher version: PojavLauncher 3.0
```

**Comment by GaucovyAero** [comment]
probably an issue with gl4es not supporting gl features the mods require, cant really do anything about that, remove the mods that dont work correctly

**Comment by MogwartUser** [comment]
thanks
