### ISSUE TITLE
[Bug] 1.20.X Support

### ISSUE THREAD

**Issue by fritzlb** [PojavLauncherTeam/PojavLauncher_iOS#644]
### Describe the bug

1.20.X Crash
Trying to start MC 1.20 in Pojavlauncher results in a crash. The latest 1.19 does start without issues. 

### Steps To Reproduce

```markdown
Start Minecraft 1.20.4 (also tested 1.20.2) in Pojavlauncher
```

### Expected Behavior

Expected to see a Mojang Loading screen. Instead got a direct crash to latest.log

### Platform

```markdown
- Device model: iPad14,3 (iPad Pro 11, 4th)
- iOS version: 17.2
- PojavLauncher version: Latest release (2.2 Deepslate)
```

### Anything else?

I am aware that iOS 17 isn’t officially supported. If this bug is iOS 17 specific then I am sorry, please close this report. Due to a lack of devices I am unable to test 1.20 on any other version of iOS.  Because 1.19 starts without issues, I assume that it’s got something to do with 1.20.
The android version recently got an update to support 1.20+ afaik, maybe a similar patch has to be made for iOS?

**Comment by GaucovyAero** [comment]
send log

**Comment by fritzlb** [comment]
![IMG_0574](https://github.com/PojavLauncherTeam/PojavLauncher_iOS/assets/106099434/4dc964c1-36ac-4f39-946f-5f8328310aa1)
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher_iOS/files/13829155/latestlog.txt)
here you go :)

**Comment by ItAnthon** [comment]
> ![IMG_0574](https://private-user-images.githubusercontent.com/106099434/294162176-4dc964c1-36ac-4f39-946f-5f8328310aa1.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQzNjc4MjYsIm5iZiI6MTcwNDM2NzUyNiwicGF0aCI6Ii8xMDYwOTk0MzQvMjk0MTYyMTc2LTRkYzk2NGMxLTM2YWMtNGYzOS05NDZmLTVmODMyODMxMGFhMS5QTkc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwNFQxMTI1MjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xZWE1ZThlZjk5ZTRjMmI5Zjk2MTNiYmUyOWE1NTM0ZTVkODNmYWY4NjNlMTQ3NDUwYmI5YjgyMmRjYTljY2ExJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.YIWNn8p5siCy4G8seKfPTkcOedkDa19LtzDx8P6I958)
> [latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher_iOS/files/13829155/latestlog.txt)
> here you go :)

You’re using an outdated version of PojavLauncher.

Try This! —>  https://github.com/PojavLauncherTeam/PojavLauncher_iOS/actions/runs/7174067551

**Comment by fritzlb** [comment]
That’s the official release I was using, maybe then a 2.2.1 release or sth is needed? Or at least a reference somewhere that 1.20 is only supported using a development version?
The dev version works beautifully tho :)

**Comment by ItAnthon** [comment]
I know that it is the official release that you were using. It is outdated though.

**Comment by benn511** [comment]
How do I get the dev build for ios? Tried checking out that link but wasn't sure how to get the ipa.
