### ISSUE TITLE
[Bug] Pojavlauncher ios keeps crashing when resource pack is almost loaded

### ISSUE THREAD

**Issue by 3remy** [PojavLauncherTeam/PojavLauncher_iOS#645]
### Describe the bug

When I enter the server that the resource pack is forced to apply and resource pack loading is almost done, it keeps crashing. I'm in ios 17

### Steps To Reproduce

```markdown
1. Start pojavlauncher
2. Enter the server
3. ResourcePack progress bar is almost end
4. And then crash
```

### Expected Behavior

I expect to successfully download the resource pack that I need to download to log in the server

### Platform

```markdown
- Device model: iPhone 15
- iOS version: 17.0.3
- PojavLauncher version: latest release
```

**Comment by GaucovyAero** [comment]
try using a different renderer, custom shaders are unsupported on gl4es
