### ISSUE TITLE
[Bug] Apple Pencil Issue

### ISSUE THREAD

**Issue by yaj321** [PojavLauncherTeam/PojavLauncher_iOS#646]
### Describe the bug

Moving the screen in game with a Apple Pencil (Gen 2 in my case) will break the input of touching if you touch your screen with a finger afterwards, if you continue to tap with the Apple Pencil, you would be fine. The keyboard, controller, and the buttons that pojav added would still work perfectly. I do not know if this is an issue with Apple Pencil gen 1

### Steps To Reproduce

```markdown
1. Go into PojavLauncher
2. Launch a profile
3. Click anything or move anything with a apple pencil
4. Touch the screen with your finger, you will see that you cant change where you are looking at anymore
5. Yep
```

### Expected Behavior

I can still move where my character is aiming at if I touched the screen with a Apple Pencil

### Platform

```markdown
- Device model: iPad 11 inch (4th Gen) 
- iOS version: 16.3.1
- PojavLauncher version: https://github.com/PojavLauncherTeam/PojavLauncher_iOS/actions/runs/7498475877 this action
- TrollStore
```

**Comment by ItAnthon** [comment]
Thats really weird but really funny, can you confirm if this is still an issue on the latest development build? @jayshen8

**Comment by jayshen8** [comment]
i will test it when i get off my flight, gimme 5 hours

**Comment by jayshen8** [comment]
> Thats really weird but really funny, can you confirm if this is still an issue on the latest development build? @jayshen8

yep, still seems to be an issue on the latest dev build, however, it seems, this time the game just freezes entirely, no crash log

**Comment by ItAnthon** [comment]
Interesting.. I’ll see what I can document about this issue. Thanks! @jayshen8

**Comment by ItAnthon** [comment]
I finally got ahold of the Apple Pencil. I couldn’t reproduce this issue on the latest developer build, latest snapshot. what version on Minecraft was this?

**Comment by yaj321** [comment]
is it a apple pencil 2? also what device are you on

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by ItAnthon** [comment]
Apple Pencil Gen 2, iPad Pro 12.9” (3rd generation)

**Comment by yaj321** [comment]
can you tap on your screen with your fingers after? does it work? for me, input doesnt work

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by ItAnthon** [comment]
Yeah it works, latest developer build, latest snapshot. It all works.

**Comment by jumJup-jirma7-jypgaq** [comment]
Vào Th 6, 1 thg 3, 2024 lúc 23:56 ItAnthon ***@***.***> đã
viết:

**Comment by ItAnthon** [comment]
…?

**Comment by yaj321** [comment]
close it i guess, and mark it as solved, cause it works for me too now.
