### ISSUE TITLE
[Bug] java.lang.system.getproperty returns null and crashes the game on launch (init)

### ISSUE THREAD

**Issue by ImNotDario** [PojavLauncherTeam/PojavLauncher_iOS#647]
### Describe the bug

The game refuses to launch and crashes. The logs say that java.lang.system.getproperty is causing this. Please fix it!!! I cant play minecraft!!!

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher_iOS/files/14112052/latestlog.txt)

### Steps To Reproduce

```markdown
1. Start pojavlauncher on trollstore
2. Start minecraft 1.20.2
3. Crash
```

### Expected Behavior

I expect it to start

### Platform

```markdown
- Device model: iphone X
- iOS version: 16.7.4 but happened on older versions 
- PojavLauncher version: 
2.2 Deepslate latest
```

**Comment by GaucovyAero** [comment]
old pojav, update to 3.0 github actions builds, guide is on the wiki
