### ISSUE TITLE
[Bug] keyboard bug

### ISSUE THREAD

**Issue by 1epicfb** [PojavLauncherTeam/PojavLauncher_iOS#648]
### Describe the bug

When i am using ipad magic keyboard i presseed shift + w and the screen started flashing and not letting me play this which means i cant walk while shifting help 

### Steps To Reproduce

```markdown
1.start pojav launcher
2.go in minecraft vanilla
3.press shift + w
4.screen flashing
5.game crashed
6.report the problem
```

### Expected Behavior

fix it

### Platform

```markdown
- Device model: iPad Air 5
- iOS version: 16.7.2
- PojavLauncher version: newest
```

**Comment by jayshen8** [comment]
i dont have any issues with pojavlauncher, I am on 16.3.1 and trollstore

**Comment by ItAnthon** [comment]
@1epicfb it would really help if you were to send us a log, so that we could see more of what was going on.

**Comment by GaucovyAero** [comment]
stale

**Comment by ItAnthon** [comment]
@GaucovyAero i honestly think its that stupid 1.8.9 issue lol the one where u have to change fullscreen bind
