### ISSUE TITLE
[Bug] mod support problem

### ISSUE THREAD

**Issue by 1epicfb** [PojavLauncherTeam/PojavLauncher_iOS#649]
### Describe the bug

the launcher does support essential but does not support essential mods (e.g.https://sk1er.club/mods/)
and the game crashes when the mod is loaded(using fabric + essential + essential mods)

### Steps To Reproduce

```markdown
1.start
2.install fabric & api
3.import essential
4.import essential mods
5.game crashed
```

### Expected Behavior

fix

### Platform

```markdown
- Device model: ipad air 5
- iOS version: 16.7.2
- PojavLauncher version: newest
```

**Comment by ItAnthon** [comment]
@1epicfb Do you have a log of sorts??

**Comment by GaucovyAero** [comment]
stale
