### ISSUE TITLE
I can't install pojavlaucher 

### ISSUE THREAD

**Issue by ShopRobloxsieuuytin** [PojavLauncherTeam/PojavLauncher_iOS#652]
### Describe the bug

I can't install PojavLauncher on eSign.

### The log file and images/videos

.

### Steps To Reproduce

```markdown
.
```

### Expected Behavior

.

### Platform

```markdown
- Device model: 
- iOS version: 
- PojavLauncher version:
```

### Anything else?

.

**Comment by fritzlb** [comment]
Build 1142 does work for my AltStore configuration, newer builds don‘t. Does 1142 work for you?

**Comment by ItAnthon** [comment]
@ShopRobloxsieuuytin You can’t install PojavLauncher on eSign. It is not a supported installation method for iOS/iPadOS.

use the supported methods that being: TrollStore, SideStore, or AltStore.

**Comment by Zhou-Shilin** [comment]
> @ShopRobloxsieuuytin You can’t install PojavLauncher on eSign. It is not a supported installation method for iOS/iPadOS.
> 
> use the supported methods that being: TrollStore, SideStore, or AltStore.

esign is a fork of trollstore

**Comment by ItAnthon** [comment]
@Zhou-Shilin not that I’ve heard of. 

Please use one of the installation methods that we have documented to work.

Those being: TrollStore, SideStore, and AltStore. Thank you! :)
