### ISSUE TITLE
[F-Req] <Add the function of importing local modpack. >

### ISSUE THREAD

**Issue by qnqnpll** [PojavLauncherTeam/PojavLauncher_iOS#658]
### Is this request related to a bug?

As the title suggests, modpacks made by some authors are not only published on platforms such as curseforge. They are more published on cloud disks with .zip files, which leads to the need for special porting to use them.

### Describe the request.

I think we can add a function to import local modpack.

**Comment by GaucovyAero** [comment]
those local modpacks can have different structures, therefore no
