### ISSUE TITLE
Forge version control error

### ISSUE THREAD

**Issue by Lilblack24679** [PojavLauncherTeam/PojavLauncher_iOS#66]
When I use forge version, there will be an error. When I click the button, I need to press the top left.

**Comment by khanhduytran0** [comment]
Can you describe more? Log?

**Comment by Lilblack24679** [comment]
After entering the 1.16.5 forge version of the game, I can't directly click the start game button to open it. I need to click a blank position in the upper left corner of the button

**Comment by khanhduytran0** [comment]
Maybe update to latest build?

**Comment by Lilblack24679** [comment]
Yes, I just updated it, but there is still this problem

**Comment by khanhduytran0** [comment]
What about current fullscreen mode? :eyes:

**Comment by Lilblack24679** [comment]
https://github.com/PojavLauncherTeam/PojavLauncher_iOS/actions/runs/600924702 I updated this version, or is it like this

**Comment by khanhduytran0** [comment]
> What about current fullscreen mode? :eyes:

I mean this 
![image](https://user-images.githubusercontent.com/40482367/109237573-6420b700-7804-11eb-99cf-f71afe1ebb47.jpeg)
Change to ON and restart game.

**Comment by Lilblack24679** [comment]
OK, I'll try again

**Comment by Lilblack24679** [comment]
The problem has been solved, thank you

**Comment by khanhduytran0** [comment]
You're welcome!
