### ISSUE TITLE
Signing error for ver.3.0

### ISSUE THREAD

**Issue by hackcr1258** [PojavLauncherTeam/PojavLauncher_iOS#661]
### Describe the bug

Issue:
Using Altstore to install the nightly build will crash Altstore, failing the install.
Using Sidestore to install the nightly build will give a signing error, failing the install.

### The log file and images/videos

![IMG_5492](https://github.com/PojavLauncherTeam/PojavLauncher_iOS/assets/96476115/9ed85fcc-3725-4418-9e4f-be19b28d50d9)
*Sidestore error log

### Steps To Reproduce

```markdown
Altserver method
1. Use Altserver to install the nightly app
2. Alt server will crash

Sidestore method
1. Use Sidestore to install the nightly app
2. Sidestore will give the above error
```

### Expected Behavior

The app will not install properly

### Platform

```markdown
- Device model: iPhone 14 Pro
- iOS version: 17.4
- PojavLauncher version: 3.0
```

**Comment by hackcr1258** [comment]
Solved today using the latest developer build

**Comment by speedyfriend67** [comment]
cool
