### ISSUE TITLE
[Bug] Launcher won't sign me in

### ISSUE THREAD

**Issue by emeraldongithub** [PojavLauncherTeam/PojavLauncher_iOS#664]
### Describe the bug

Trying to sign-in via Microsoft just.. times out.

### The log file and images/videos

I don't know how to get the log, here's a video of the issue.
https://cdn.discordapp.com/attachments/1067378217842905091/1223135697301667850/copy_16D15CF1-F8DC-463D-9FC9-4880114DE2B9.mov?ex=6618c0e2&is=66064be2&hm=697806255958c1614e93a34b28d642b72ee9343870138ebe8c9613069381bfe5&

### Steps To Reproduce

```markdown
1. Click green play button
2. Use Microsoft authentication
3. Sign in as usual
```

### Expected Behavior

I expect the launcher to successfully log me in.

### Platform

```markdown
- Device model: iPhone 11 Pro Max
- iOS version: 17.4.1
- PojavLauncher version: 2.2 Deepslate
```

**Comment by 0hStormy** [comment]
Don't use that version of Pojav as it's very old.
Instead you should be using the latest Github Actions build here https://github.com/PojavLauncherTeam/PojavLauncher_iOS/actions/runs/8357450615
