### ISSUE TITLE
[Question] I need an old launcher version

### ISSUE THREAD

**Issue by Happyplanetxh** [PojavLauncherTeam/PojavLauncher_iOS#668]
### Ask the question here.

can someone provide the pojavlauncher 3.0(commit:74de96b)?I really need this versions! 
If you have please put it into the mediafire!!!

**Comment by Kiokingz** [comment]
why

**Comment by Happyplanetxh** [comment]
> 为什么
I thought the versions after it got a render bug,they always crashed in a short time,(I can’t describe it very clear)
But the versions before it can prefectly run I have no idea to slove this problem,so i really need this version!

**Comment by Happyplanetxh** [comment]
> why

as you see this version was expired,so I try to have a request

**Comment by GaucovyAero** [comment]
nobody has it i think
