### ISSUE TITLE
[F-Req] <Request to add MoltenVK rendering.>

### ISSUE THREAD

**Issue by XEYt44** [PojavLauncherTeam/PojavLauncher_iOS#669]
### Is this request related to a bug?
yes

### Describe the request.

About
MoltenVK is a Vulkan Portability
implementation. It layers a subset of
the high-performance, industry-
standard Vulkan graphics and
compute APl over Apple's Metal
graphics framework, enabling Vulkan
applications to run on macOS,iOS and
tvOS.

"Can Vulkan → Metal renderer add this renderer? I feel like zink and angle have too much performance loss.

**Comment by XEYt44** [comment]
Link is here：
https://github.com/KhronosGroup/MoltenVK

**Comment by alexytomi** [comment]
Minecraft uses OpenGL, you can't use this alone for Minecraft. This is also already used for Zink.

ANGLE translates OpenGL directly to Metal so it would be useless there.
