### ISSUE TITLE
Problems with the game registering L2 and R2 triggers

### ISSUE THREAD

**Issue by KatazGuy** [PojavLauncherTeam/PojavLauncher_iOS#673]
### Describe the bug

When i play with my PS4 controller the game oftenly has problems with the L2 and R2 problems 

Example: when i press L2 to open a door sometimes the game registers it as if i pressed L2 two times wich makes my character instantly open and close doors and vice versa. Or when i press R2 to destroy blocks on creative my character breaks 2 blocks instantly instead of just 1.

https://github.com/PojavLauncherTeam/PojavLauncher_iOS/assets/83526218/f4070110-1c37-405d-9b16-e40ae1aea4fb

### Steps To Reproduce

```markdown
1- Connect PS4 controller
2- Launch the game
3- Open world
4- Place door and press L2
5- The error happens (sometimes)
```

### Expected Behavior

I expect the game to register the triggers correctly

### Platform

```markdown
- Device model: Samsung Galaxy A31 5G
- iOS version: Android 12
- PojavLauncher version: Lastest google play release
```

**Comment by Kiokingz** [comment]
@KatazGuy wrong repo, post the issue at https://github.com/PojavLauncherTeam/PojavLauncher/issues
