### ISSUE TITLE
[Bug] <Crash on start version 1.20.4>

### ISSUE THREAD

**Issue by Makedodo** [PojavLauncherTeam/PojavLauncher_iOS#674]
### Describe the bug

When I started Minecraft 1.20.4, it has been crashed.

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher_iOS/files/14896008/latestlog.txt)
![E72D6B38-C546-45B5-AF22-F0EA617F4AD6](https://github.com/PojavLauncherTeam/PojavLauncher_iOS/assets/112254698/cc4a308b-7aae-4ab2-9d5e-d84cdbc6d9ce)

### Steps To Reproduce

```markdown
1. Start PojavLauncher 2.2
2. Install Minecraft 1.20.4
3. Start Minecraft 1.20.4
```

### Expected Behavior

When I started Minecraft 1.20.4, it has been crashed

### Platform

```markdown
- Device model: IPhone 7
- iOS version: 14.7.8
- PojavLauncher version: 2.2
```

**Comment by 0hStormy** [comment]
Your version of Pojav os really old, use the latest nightly version here https://github.com/PojavLauncherTeam/PojavLauncher_iOS/actions/runs/8562076077/artifacts/1386574079

**Comment by chair-man-f** [comment]
> Your version of Pojav os really old, use the latest nightly version here https://github.com/PojavLauncherTeam/PojavLauncher_iOS/actions/runs/8562076077/artifacts/1386574079

How do I do that? I don't see any download button in the artifacts place
