### ISSUE TITLE
[Bug] <Crashed when launching the gamen>

### ISSUE THREAD

**Issue by XEYt44** [PojavLauncherTeam/PojavLauncher_iOS#675]
### Describe the bug

"When I tried to launch the game, it crashed without any other actions. The latestlog file doesn't seem to mention this crash behavior. I noticed that the previous 3.0 version also had the same issue. I tried replacing the old version of Java, and it was able to start normally, but only with the old version of 3.0. The version I'm having trouble with is from April 7, 2024. This issue has been bothering me for a long time, and I hope it can be fixed."

### The log file and images/videos

https://github.com/PojavLauncherTeam/PojavLauncher_iOS/assets/121798130/9d971d44-fd04-400c-a388-b7cae08992be

### Steps To Reproduce

```markdown
repeated crashes
```

### Expected Behavior

This issue has been bothering me for a long time. Can it be fixed

### Platform

```markdown
- Device model: iphone11
- iOS version: 14.3
- PojavLauncher version: 3.0-2024-4-7
```

### Anything else?

unc0ver jailbre
[latestlog(6).txt](https://github.com/PojavLauncherTeam/PojavLauncher_iOS/files/14898122/latestlog.6.txt)
ak

**Comment by GaucovyAero** [comment]
pretty sure unc0ver is not one of the recommended jailbreaks

you can use chimera, taurine, odyssey or odysseyra1n depeding on which one supports your device
