### ISSUE TITLE
Better way to use JIT

### ISSUE THREAD

**Issue by Elbozo123** [PojavLauncherTeam/PojavLauncher_iOS#676]
### Is this request related to a bug?

Not really

### Describe the request.

JIT is getting very hard to enable. Is there any chance u can add a program of your own to enble jit? That would be very convenient.

### Anything else?

Oh, and make sure it works on common OSes

**Comment by Kiokingz2** [comment]
thats now how it works sadly.

**Comment by Kiokingz** [comment]
thats not how it works sadly.

**Comment by GaucovyAero** [comment]
ask apple lol

**Comment by Elbozo123** [comment]
Bruh
