### ISSUE TITLE
[Bug] crash right now when I start my game

### ISSUE THREAD

**Issue by Anasui404** [PojavLauncherTeam/PojavLauncher_iOS#679]
### 描述错误

当我开始我的游戏时，它通常会崩溃

### 日志文件和图像/视频

[latestlog.txt]（https://github.com/PojavLauncherTeam/PojavLauncher_iOS/files/15040239/latestlog.txt）

### 复制步骤

```降价
1.启动Pojav Launcher
2.reinstallation MC lib
3.change ic2 classic for ic2 exp
```

### 预期行为

正常工作

###平台

```降价
-设备型号：Ipad Pro 2021
- iOS版本：iOS16
- PojavLauncher版本：版本2.2
```

### 还有别的吗？

_无响应_

**Comment by GaucovyAero** [comment]
dead log link

**Comment by GaucovyAero** [comment]
stale
