### ISSUE TITLE
java.reflect.InvocationTargetException crash when running any version of Forge

### ISSUE THREAD

**Issue by Ryorama** [PojavLauncherTeam/PojavLauncher_iOS#68]
When ever I try to launch forge, it freezes and in the log the error "java.reflect.InvocationTargetException" gets thrown. I have also already tried the fix for this error already with the fix in #56 with no success. 

The log: https://pastebin.com/Mn6bbg5G

Version: Latest dev build from GitHub actions.

If anything else is needed just let me know and I will send it.

**Comment by khanhduytran0** [comment]
The error looks similar to #67. Due to java 16, it removed a bunch of deprecated stuff, so the only way to fix is downgrade to java8 but I haven’t seen any jdk 8 iOS port.

**Comment by Ryorama** [comment]
Quick update, managed to get forge 1.16.5 running, but while the game loads, the background appears with a null background and eventually crashes. 
![8A92855C-AB15-4288-B484-BE9370DE3DCA](https://user-images.githubusercontent.com/35707939/109367259-9c0b1700-7863-11eb-99f5-74473cc2b752.png)
[latest.log](https://github.com/PojavLauncherTeam/PojavLauncher_iOS/files/6053255/latest.log)

**Comment by khanhduytran0** [comment]
It's likely a mod attempt to load shader. But shader support is very limited.

**Comment by Ryorama** [comment]
Weird, let me try something

**Comment by Ryorama** [comment]
Ok, if it’s a shader issue, it must be from one of the mods I have installed. Because I removed all the shaders I was testing with OptiFine and still has the same issue.

**Comment by khanhduytran0** [comment]
Check out the information of “botania” mod

**Comment by Ryorama** [comment]
Ok, it doesn't look like it would affect the game, but I removed it just to be sure and to my surprise the game looks normal now which I find interesting.

**Comment by Ryorama** [comment]
Never mind, it's back to the bull background

**Comment by Ryorama** [comment]
Managed to get it working. As for older versions, I came across this and maybe this can be implemented in some way to allow older versions to run, but I’m not completely sure if it would work https://openjdk.java.net/projects/mobile/ios.html.

**Comment by Doregon** [comment]
Issue given an answer, closing.
