### ISSUE TITLE
App Store 

### ISSUE THREAD

**Issue by Fgksjaaagkjsf** [PojavLauncherTeam/PojavLauncher_iOS#680]
### Is this request related to a bug?

No

### Describe the request.

Since Apple has to allow emulators on the App Store because of the EU you could put it on the App Store as a Java emulator. For example, a popular emulator on AltStore, called Delta is now on the App Store and is no. 1 in its category.
![IMG_4381](https://github.com/PojavLauncherTeam/PojavLauncher_iOS/assets/119998034/c183fbbd-7695-48ea-a348-0c27af37134f)

### Anything else?

No

**Comment by GaucovyAero** [comment]
Pojav is not an emulator, it runs natively and needs JIT
