### ISSUE TITLE
[Bug] I can’t play the full version of java edition even though I own it

### ISSUE THREAD

**Issue by InconsistentMinecraftServer** [PojavLauncherTeam/PojavLauncher_iOS#681]
### Describe the bug

So I own Java edition on my Microsoft account but when I try to log in to it, it says my account doesn’t own Java and I have to play the demo. Is this a bug or is it intended and if it’s a bug how do I fix it?

### The log file and images/videos

![IMG_2351](https://github.com/PojavLauncherTeam/PojavLauncher_iOS/assets/167709961/b1ff6d59-8a7d-496c-b74b-c4cc1ab955ed)

### Steps To Reproduce

```markdown
1. Start Pojav launcher
2. Try to sign in to your Microsoft account
3. The message should pop up
```

### Expected Behavior

I have no idea what the expected behavior is

### Platform

```markdown
- Device model: 
- iOS version: 
- PojavLauncher version:
```

**Comment by GaucovyAero** [comment]
try logging into minecraft.net first

**Comment by InconsistentMinecraftServer** [comment]
> try logging into minecraft.net first

THANK YOU SO MUCH
