### ISSUE TITLE
[Question] Hotbar not working

### ISSUE THREAD

**Issue by CitrusIntellect** [PojavLauncherTeam/PojavLauncher_iOS#683]
### Ask the question here.

When using touchscreen, the Hotbar does not work by taping, also the launcher started to bug out my keyboard

**Comment by CitrusLinux** [comment]
So i just saw in settings that there is hotbar gestures, what are these gestures?

**Comment by 0hStormy** [comment]
hotbar gestures are when you swipe at the bottom of the screen, it will over your position in the hotbar iirc
