### ISSUE TITLE
Error code 1[Bug] <Short description>

### ISSUE THREAD

**Issue by Montivillon** [PojavLauncherTeam/PojavLauncher_iOS#684]
### Describe the bug

I was enabling JIT on iOS 17 and started running PojavLauncher and it gave me error code 1

### The log file and images/videos

![IMG_0200](https://github.com/PojavLauncherTeam/PojavLauncher_iOS/assets/156731526/5220473c-3604-4f89-bd24-53ffbd3a0eb4)

### Steps To Reproduce

```markdown
1.Start PojavLauncher 
2. Enable JIT
3. Set up profile
4. Launch Minecraft with the error code 1
```

### Expected Behavior

Launch the version

### Platform

```markdown
- Device model: iPad 9th generation
- iOS version: 17.3.1
- PojavLauncher version: 3.0/2.2 deepslate
```

**Comment by GaucovyAero** [comment]
stale
