### ISSUE TITLE
[Bug] Crash on 1.20.4 using Dopamine jailbreak

### ISSUE THREAD

**Issue by GavinGoGaming** [PojavLauncherTeam/PojavLauncher_iOS#685]
### Describe the bug

Opened 1.204, app crashed like 3 times while downloading, but once downloaded game crashed on opening

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher_iOS/files/15131825/latestlog.txt)

### Steps To Reproduce

```markdown
1. Open PojavLauncher installed using TrollStore on Dopamine
2. Install 1.20.4
3. Open 1.20.4
```

### Expected Behavior

Game opens and you get to see the main menu

### Platform

```markdown
- Device model: iPhone 7
- iOS version: 15.7.8
- PojavLauncher version: 2.2
```

**Comment by GavinGoGaming** [comment]
UPD: I’ve updated to PojavLauncher 3.0 and it works now, however I’m stuck on waiting for JIT

**Comment by GaucovyAero** [comment]
check if your jb supports jit

**Comment by ItAnthon** [comment]
Aero, thats not how that works.

**Comment by ItAnthon** [comment]
@GavinGoGaming how was PojavLauncher even installed on your device? Be sure to send another log.

**Comment by GavinGoGaming** [comment]
I installed TrollStore using TrollInstallerX, and installed the Dopamine jb via ipa and then jailbroke, then installed 3.0.0 pojav and launched default profile

**Comment by Kiokingz** [comment]
do you have URL Scheme enabled in trollstore settings?

**Comment by GavinGoGaming** [comment]
Nevermind - I was using an old nightly build with broken JIT
