### ISSUE TITLE
[Question] <Android 6 farbic support>

### ISSUE THREAD

**Issue by TylerHaoNhot** [PojavLauncherTeam/PojavLauncher_iOS#687]
### Ask the question here.

In my lastest bug report, I know that farbic doesn't work below android 9. But i wonder there's any by-pass like magisk modules, root, or modify version of pojav?

**Comment by GaucovyAero** [comment]
the solution is most probably like fork pojav and move its minecraft directory into root

**Comment by GaucovyAero** [comment]
oops, wrong repository, this is iOS, closing
