### ISSUE TITLE
Joining LAN

### ISSUE THREAD

**Issue by recklessking** [PojavLauncherTeam/PojavLauncher_iOS#69]
I play on pc with my MC Leaks acc since I’m broke, and I can’t play with my sibling since they play on the PE. I found out this way to play java on iOS recently and it’s been a really dope experience. One thing, it just won’t let them join into my pc world, but it’ll let me join theirs. Can you please fix this, I know how hard it is but it’d mean a lot.

Sincerely,
JR.

**Comment by khanhduytran0** [comment]
You need to be signed in a paid account (non-offline) to be able to join LAN.

**Comment by recklessking** [comment]
Ohhh okay word. Thanks man
