### ISSUE TITLE
[Question] cant ues launcher

### ISSUE THREAD

**Issue by SivanRen** [PojavLauncherTeam/PojavLauncher_iOS#690]
### Ask the question here.

I am trying to use the 3.0 version of the launcher to play fabirc's mods
![2DA7A9E4-417A-4555-BA03-943A1CF51005](https://github.com/PojavLauncherTeam/PojavLauncher_iOS/assets/169580737/1950554d-44f4-4ad2-b6bd-78e5a9a3331b)
[,](
[latestlog-1.txt](https://github.com/PojavLauncherTeam/PojavLauncher_iOS/files/15285436/latestlog-1.txt)
) but I encountered an error and cannot try to solve it. Is there any way that I can use the launcher smoothly without deleting most of the mods？

**Comment by SivanRen** [comment]
[latestlog-1.txt](https://github.com/PojavLauncherTeam/PojavLauncher_iOS/files/15285440/latestlog-1.txt)
this is logtxt

**Comment by Kiokingz** [comment]
you're currently using an outdated PojavLauncher build (v2.2), as minecraft 1.20+ above crashes on those versions, download the launcher via this link: https://nightly.link/PojavLauncherTeam/PojavLauncher_iOS/workflows/development/main/net.kdt.pojavlauncher-ios.ipa.zip

once, you've finished downloading, sideload it via your sideloading service. (AltStore, SideStore, TrollStore, etc.)
i also saw your iOS version is still at 16.5.1, i recommend getting TrollStore, as enabling JIT will be way easier. so don't update your device :D

**Comment by Kiokingz** [comment]
i noticed the screenshot that is attached is v3.0, so the log you attached could be incorrect.

**Comment by SivanRen** [comment]
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher_iOS/files/15285645/latestlog.txt)
I can guarantee that this must be the latest error file, but the launcher still cannot be run.

**Comment by Kiokingz** [comment]
hey @SivanRen , sorry for the late response, but it seems that pojav couldn't access option.txt
can you try reinstalling pojav? (yes, including the data) and see if the issue still persists
