### ISSUE TITLE
App Store ios

### ISSUE THREAD

**Issue by malachirichardson** [PojavLauncherTeam/PojavLauncher_iOS#692]
### Ask the question here.

Are you all going to put PojavLauncher on the App Store any time soon?

**Comment by ItAnthon** [comment]
no

PojavLauncher uses JIT, and unless apple changes their rules with JIT, we are going to put PojavLauncher on the appstore anytime soon.

**Comment by Kiokingz** [comment]
only possible if apple allows JIT on the app store, and no, ios 17 "sideloading" isn't real sideloading
