### ISSUE TITLE
java executables [F-Req] <Short description>

### ISSUE THREAD

**Issue by Biggestmogger** [PojavLauncherTeam/PojavLauncher_iOS#693]
### Describe the request.

add java executables because it and can be used with some clients and its needed for them to work properly

**Comment by Kiokingz** [comment]
clients are unlikely supported, however executing .jars already exists

**Comment by Biggestmogger** [comment]
> clients are unlikely supported, however executing .jars already exists
well then can you use jdk 8 on pojav?

**Comment by Kiokingz** [comment]
> > clients are unlikely supported, however executing .jars already exists
> > well then can you use jdk 8 on pojav?

minecraft >1.16.5 version works, i don't see why wouldn't it
