### ISSUE TITLE
[Bug] <Short description> game exited with error code -1

### ISSUE THREAD

**Issue by endcharlotte** [PojavLauncherTeam/PojavLauncher_iOS#699]
### Describe the bug

install PojavLauncher by altstore
Start PojavLauncher by SideJITServer
Launch Minecraft with the error code 1

### The log file and images/videos

[latestlog.txt](https://github.com/user-attachments/files/15751266/latestlog.txt)

### Steps To Reproduce

```markdown
1.install PojavLauncher by altstore
2.Start PojavLauncher by SideJITServer
3. Set up profile
4. Launch Minecraft with the error code 1
```

### Expected Behavior

except game to log me in

### Platform

```markdown
- Device model: ipad pro(4th)
- iOS version: 17.5.1
- PojavLauncher version: v2.2
```

**Comment by GaucovyAero** [comment]
you are running a really old version of pojav, please update to 3.0 actions builds, click here on the actions tab, click on the latest one, download the build, extract the zip and install the ipa
