### ISSUE TITLE
[Bug] Jit

### ISSUE THREAD

**Issue by mattiatek** [PojavLauncherTeam/PojavLauncher_iOS#700]
### Describe the bug

Hi i'm trying to enable JIT for pojavLauncher but altstore tells me this: "The URL to download the Developer disk image could not be determined.
How do i solve it?

### Steps To Reproduce

```markdown
1 start alt server
2 install k jit
3 error:"The URL to download the Developer disk image could not be determined.
```

### Expected Behavior

I expected that JIT activeted

### Platform

```markdown
- Device model: iPad (8th generation)
- iOS version: 17.4
- PojavLauncher version: 2.2-development
```

**Comment by ItAnthon** [comment]
you aren’t doing it correctly. for iOS 17.4 you need to do extra steps to enable JIT. you need to either use AltJITServer or use wired JIT for the Mac only. furthermore, your version of PojavLauncher is outdated. 

get this one instead: https://github.com/PojavLauncherTeam/PojavLauncher_iOS/actions/runs/9437436535/artifacts/1583170918

**Comment by ItAnthon** [comment]
please do keep in mind that JIT isn’t permanent and that every time you open the launcher you will have to re-enable it. for the best and smoothest experience for projects like these on iOS, please stop updating your iDevice

**Comment by mattiatek** [comment]
Ok but I saw going on the Altjitserver site it shows me the procedure on Mac os not on windows
