### ISSUE TITLE
[Question] Are we able to use PojavLauncher on ios17 if i had a developer account?

### ISSUE THREAD

**Issue by fengyuan213** [PojavLauncherTeam/PojavLauncher_iOS#702]
### Ask the question here.

Hi just to confirm that are we able to use it on ios 17 if I had a developer account(mean no problems on installing ipa)? does the hardware allows you to do with it? can we install mods with them?

**Comment by Kiokingz** [comment]
yes, you can sideload it with a developer account, though i assume you don't have any problems in enabling JIT? sorry for the late response.
