### ISSUE TITLE
Forge 1.20.1 error 1 dist cleaner is missing

### ISSUE THREAD

**Issue by Huynhagiau1** [PojavLauncherTeam/PojavLauncher_iOS#703]
### Describe the bug

I got error code 1 when click play and when i read the log it said dist cleaner is missing

### The log file and images/videos

[latestlog.txt](https://github.com/user-attachments/files/15856159/latestlog.txt)

### Steps To Reproduce

```markdown
1.Installing Forge 1.20.1-47.3.0
2.Start The Game
3.Crash With Error Code 1
```

### Expected Behavior

I expect it to log me in

### Platform

```markdown
- Device model: Iphone 6s 
- iOS version: 15.7.3
- PojavLauncher version: 2.2
```

### Anything else?

I tried reinstall PojavLauncher but it didn’t work i try forge 1.20.1-47.3.1 too but still not working

**Comment by Kiokingz** [comment]
outdated pojavlauncher version, please get the [github actions](https://github.com/PojavLauncherTeam/PojavLauncher_iOS/actions/runs/9437436535) version.

**Comment by Huynhagiau1** [comment]
> outdated pojavlauncher version, please get the [github actions](https://github.com/PojavLauncherTeam/PojavLauncher_iOS/actions/runs/9437436535) version.
Which One? Btw I download pojavlauncher from the release page and 2.2 is the lasted wdym outdate?

**Comment by LanRhyme** [comment]
> > outdated pojavlauncher version, please get the [github actions](https://github.com/PojavLauncherTeam/PojavLauncher_iOS/actions/runs/9437436535) version.
> Which One? Btw I download pojavlauncher from the release page and 2.2 is the lasted wdym outdate?
> 
The version in the release is not the latest. Please download the latest build from actions.

Take a look at this.

PojavLauncher的更新与下载：
为了保证游玩时不会出各种问题，请保持更新
最新版下载链接：
1.Github下载:https://github.com/PojavLauncherTeam/PojavLauncher_iOS/actions
2.[推荐]nightly直接自动获取最新开发版（不用挂梯子和登录）（你每次进入此链接时获取到的永远是最新的主线开发版）：https://nightly.link/PojavLauncherTeam/PojavLauncher_iOS/workflows/development/main/net.kdt.pojavlauncher-ios.ipa.zip
tipa版本nightly链接:https://nightly.link/PojavLauncherTeam/PojavLauncher_iOS/workflows/development/main/net.kdt.pojavlauncher.slimmed-ios-trollstore.tipa.zip

**Comment by Huynhagiau1** [comment]
> > > outdated pojavlauncher version, please get the [github actions](https://github.com/PojavLauncherTeam/PojavLauncher_iOS/actions/runs/9437436535) version.
> > > Which One? Btw I download pojavlauncher from the release page and 2.2 is the lasted wdym outdate?
> 
> The version in the release is not the latest. Please download the latest build from actions.
> 
> Take a look at this.
> 
> PojavLauncher的更新与下载： 为了保证游玩时不会出各种问题，请保持更新 最新版下载链接： 1.Github下载:https://github.com/PojavLauncherTeam/PojavLauncher_iOS/actions 2.[推荐]nightly直接自动获取最新开发版（不用挂梯子和登录）（你每次进入此链接时获取到的永远是最新的主线开发版）：https://nightly.link/PojavLauncherTeam/PojavLauncher_iOS/workflows/development/main/net.kdt.pojavlauncher-ios.ipa.zip tipa版本nightly链接:https://nightly.link/PojavLauncherTeam/PojavLauncher_iOS/workflows/development/main/net.kdt.pojavlauncher.slimmed-ios-trollstore.tipa.zip

Can you suggest me another version cuz the newest version is like 400mb when install and like 1.3gb when download 1.20.1 my storage is only 16gb and i already used 14,4/16gb
