### ISSUE TITLE
NO JAVARUNTIME SECTION

### ISSUE THREAD

**Issue by soapheadd** [PojavLauncherTeam/PojavLauncher_iOS#704]
### Describe the bug

Im on ipad sideloaded from trollstore, and the install javaruntime button is missing, please help me!!!!

### Steps To Reproduce

```markdown
Im on ipad installed using Altstore
```

### Expected Behavior

I expect to see button

### Platform

```markdown
- Device model: Ipad Air 2 
- iOS version: 15.4.1
- PojavLauncher version: 2.2
```

**Comment by FullOfSpaghetti** [comment]
Same, no option to run 1.21 or Java 21 on iOS

**Comment by LanRhyme** [comment]
Please use the version built in actions instead of the release version.

https://github.com/PojavLauncherTeam/PojavLauncher_iOS/actions/runs/9657916516/artifacts/1634782646

**Comment by soapheadd** [comment]
> Please use the version built in actions instead of the release version.
> 
> https://github.com/PojavLauncherTeam/PojavLauncher_iOS/actions/runs/9657916516/artifacts/1634782646

i dont have trollstore, and i dont really know how to  use github to find it, can you send me one as a normal ipa file please

**Comment by soapheadd** [comment]
> https://github.com/PojavLauncherTeam/PojavLauncher_iOS/actions/runs/9657916516/artifacts/1634782646

I used that link but now i have no releases, how do i install them

**Comment by GaucovyAero** [comment]
try pulling the sidebar from the left side

**Comment by Jerry12798** [comment]
> Please use the version built in actions instead of the release version.
> 
> https://github.com/PojavLauncherTeam/PojavLauncher_iOS/actions/runs/9657916516/artifacts/1634782646

Are you able to select version of MC still with this one? I tried using 3.0 an I don't see the option to select my version anymore.

**Comment by Kiokingz** [comment]
> > Please use the version built in actions instead of the release version.
> > https://github.com/PojavLauncherTeam/PojavLauncher_iOS/actions/runs/9657916516/artifacts/1634782646
> 
> Are you able to select version of MC still with this one? I tried using 3.0 an I don't see the option to select my version anymore.

![IMG_3126](https://github.com/user-attachments/assets/1a2824a0-1246-4146-a002-93ff02307251)
uh what
