### ISSUE TITLE
No Java 21 for IOS

### ISSUE THREAD

**Issue by Skeletthuhn** [PojavLauncherTeam/PojavLauncher_iOS#705]
### Describe the bug

I tried launchung the game and I got an error message. It said, that Java 21 is requierd, to launch the Version 1.21 of Minecraft. Is there a way to Install Java 21, to run Minecraft 1.21 with mods? (fabric)

### Steps To Reproduce

```markdown
1. Install Pajov Launcher via AltStore
2. Enable JIT via PC
3. Install Version 1.21 of Minecraft
4. Try to start the Game
```

### Expected Behavior

I expected, that the Game would start normal.

### Platform

```markdown
- Device model: iPad 10. gen
- iOS version: 17.5.1
- PojavLauncher version: 2.2 „Deepslate“
```

**Comment by YafiHassan** [comment]
Hi how the help did you fix ot

**Comment by Skeletthuhn** [comment]
> Hi how the help did you fix ot

The problem was, that I used an older version. The newer versions of PojavLauncher are in the "Actions" tab

**Comment by squairYT** [comment]
> > Hi how the help did you fix ot
> 
> The problem was, that I used an older version. The newer versions of PojavLauncher are in the "Actions" tab

Hey, so where/how do you fix it? Is there a IPA download or something?

**Comment by Kiokingz** [comment]
> > > Hi how the help did you fix ot
> > 
> > 
> > The problem was, that I used an older version. The newer versions of PojavLauncher are in the "Actions" tab
> 
> Hey, so where/how do you fix it? Is there a IPA download or something?

yes, there is one.
can be found [here](https://github.com/PojavLauncherTeam/PojavLauncher_iOS/actions/runs/10634529587).

make sure to pick this one:
![image](https://github.com/user-attachments/assets/21fb2124-63c2-4a6e-8a0f-90cd4244224e)

**Comment by Chicowee429** [comment]
This is bullshit its expired

**Comment by Kiokingz** [comment]
> This is bullshit its expired

this thread is like a few months old, of course the build is expired

get a new one [here](https://github.com/PojavLauncherTeam/PojavLauncher_iOS/actions/runs/12291672801) then

**Comment by bruh830** [comment]
I had gotten my version of PojavLauncher from SideStore, shouldn’t they have the latest?

**Comment by kiokori-git** [comment]
> I had gotten my version of PojavLauncher from SideStore, shouldn’t they have the latest?

well yes; it is the latest, latest release.
the latest release was released 2 years ago, where Java 21 wasn't included yet.

the next release is guaranteed that the Java 21 JRE bundle will be included, as seen in the developer builds, so use the developer builds for now

**Comment by rgoob** [comment]
How do you download files from dev build??

**Comment by foss-lover34** [comment]
hey, i too had this issue and after downloading hte latest real latest relaease from github action, it works, would be nice to have this written somewhere in the official website tho lol

**Comment by Pohesa** [comment]
Yea i am also having this same issue after installing pojav launcher and enabling jit it says u need java 21 to play on 1.21 i am on ipad ios 17.4 still cant find a way to make it work can someone provide the latest release from github action as he said i am not able to find that actually

**Comment by Jamrge** [comment]
There is no download button??

**Comment by Takacdeu** [comment]
> There is no download button??
You need to sign in to github in order to download from "Actions" tab
