### ISSUE TITLE
[BUG] Failed to verify file (null): SHA1 mismatch in Dev version of PojavLauncher

### ISSUE THREAD

**Issue by Rayray1099** [PojavLauncherTeam/PojavLauncher_iOS#706]
### Describe the bug

When I start a custom client named Batmod it shows this error, but on release version there is no problem like this…

### The log file and images/videos

![IMG_0432](https://github.com/PojavLauncherTeam/PojavLauncher/assets/95627112/8e815b9c-ac34-4712-a1ca-e2a10032516d)

### Steps To Reproduce

```markdown
1. Start PojavLauncher
2. Choose Badmod client
3. Click on start game
4. Shows the error Failed to verify file (null): SHA1 mismatch
*Note: It didn’t happen on release version on PojavLauncher, it can start with no problems before.
```

### Expected Behavior

Start the game without any error.

### Platform

```markdown
- Device model: iPad Pro 2022 (4th Gen)
- iOS version: iPadOS 18.0
- PojavLauncher version: 3.0 Development
```

### Anything else?

Old version of PojavLauncher works

**Comment by Kiokingz** [comment]
batmod isn't supported afaik.
