### ISSUE TITLE
Changing selected hotbar item

### ISSUE THREAD

**Issue by djzdaman1** [PojavLauncherTeam/PojavLauncher_iOS#71]
How do I change what I'm holding in my hotbar I can't figure out how to change between slot 1-9

**Comment by khanhduytran0** [comment]
You can directly press a hotbar slot.

**Comment by djzdaman1** [comment]
It doesn't work I've tried.

**Comment by InfernoNova9999** [comment]
> It doesn't work I've tried.

Go to video settings and set gui scale to auto

**Comment by recklessking** [comment]
Yo might help but you can go to Minecraft settings>controls>mouse settings and make sure touchscreen is off. Or if you mean like while your not in a chest or invintory you just double tap item you want to hold and use in game. Hope this helped man

**Comment by asdfugil** [comment]
@djzdaman1 can you change to issue title to `Changing selected hotbar item doesn't work when GUI scale is not auto`?

**Comment by Doregon** [comment]
Closingg due to inactivity, and because a recent commit fixed a possible issue where the home bar gets in the way (possibly related as the home bar covers the hotbar).
