### ISSUE TITLE
[Question] No Java runtime option on iOS (Java 21)

### ISSUE THREAD

**Issue by FullOfSpaghetti** [PojavLauncherTeam/PojavLauncher_iOS#710]
### Ask the question here.

![IMG_0245](https://github.com/PojavLauncherTeam/PojavLauncher_iOS/assets/42872640/6784a083-beb9-4564-ac1b-7d46cd0d4327)
![IMG_0246](https://github.com/PojavLauncherTeam/PojavLauncher_iOS/assets/42872640/606edb74-9c72-4a3e-ad12-d7546bbae42e)

I see on android pojav there is an option to update the Java runtime but iOS has no such option, any idea how to fix? Thanks in advance

**Comment by Waterstorma** [comment]
you should use developer release channel.
public channel is not support java21 (java17 is higher)
[https://github.com/PojavLauncherTeam/PojavLauncher_iOS/actions/runs/9720445756]
go to this url and download ipa file (artifacts)

**Comment by FullOfSpaghetti** [comment]
> https://github.com/PojavLauncherTeam/PojavLauncher_iOS/actions/runs/9720445756

What should I do with the ipa file? Sorry I just started using pojav

**Comment by Waterstorma** [comment]
How did you install pojav before? (trollstore? sideload?)

**Comment by Kiokingz** [comment]
sideload the ipa with your sideloading service

**Comment by Kiokingz** [comment]
also, since you're on a demo account, probably no more support will be given later. (demo account = you don't own java)

**Comment by FullOfSpaghetti** [comment]
> How did you install pojav before? (trollstore? sideload?)

With AltStore and SideJITServer. @Kiokingz I do own Java don’t know why it’s stuck in demo

**Comment by Kiokingz** [comment]
> > How did you install pojav before? (trollstore? sideload?)
> 
> With AltStore and SideJITServer. @Kiokingz I do own Java don’t know why it’s stuck in demo

yeah, thats why its on demo.

**Comment by Kiokingz** [comment]
this post will closed soon

**Comment by FullOfSpaghetti** [comment]
> > > How did you install pojav before? (trollstore? sideload?)
> > 
> > 
> > With AltStore and SideJITServer. @Kiokingz I do own Java don’t know why it’s stuck in demo
> 
> yeah, thats why its on demo.

I don’t understand, do you mean using AltStore?

**Comment by GaucovyAero** [comment]
> > > > How did you install pojav before? (trollstore? sideload?)
> > > 
> > > 
> > > With AltStore and SideJITServer. @Kiokingz I do own Java don’t know why it’s stuck in demo
> > 
> > 
> > yeah, thats why its on demo.
> 
> I don’t understand, do you mean using AltStore?

you have to buy minecraft java edition

**Comment by FullOfSpaghetti** [comment]
> > > > > How did you install pojav before? (trollstore? sideload?)
> > > > 
> > > > 
> > > > With AltStore and SideJITServer. @Kiokingz I do own Java don’t know why it’s stuck in demo
> > > 
> > > 
> > > yeah, thats why its on demo.
> > 
> > 
> > I don’t understand, do you mean using AltStore?
> 
> you have to buy minecraft java edition

As stated above I do own Java.
![IMG_0247](https://github.com/PojavLauncherTeam/PojavLauncher_iOS/assets/42872640/34a4d898-f079-4f3e-abcf-a9453e46cc7a)

**Comment by Kiokingz** [comment]
> > > > > > How did you install pojav before? (trollstore? sideload?)
> > > > > 
> > > > > 
> > > > > With AltStore and SideJITServer. @Kiokingz I do own Java don’t know why it’s stuck in demo
> > > > 
> > > > 
> > > > yeah, thats why its on demo.
> > > 
> > > 
> > > I don’t understand, do you mean using AltStore?
> > 
> > 
> > you have to buy minecraft java edition
> 
> As stated above I do own Java. ![IMG_0247](https://private-user-images.githubusercontent.com/42872640/344800475-34a4d898-f079-4f3e-abcf-a9453e46cc7a.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk4NzYwMTUsIm5iZiI6MTcxOTg3NTcxNSwicGF0aCI6Ii80Mjg3MjY0MC8zNDQ4MDA0NzUtMzRhNGQ4OTgtZjA3OS00ZjNlLWFiY2YtYTk0NTNlNDZjYzdhLmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwMVQyMzE1MTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wZjMzNmJjZDBjN2FlZmY3NTY5YzA2MWRkZDA3MzM5N2MzY2EwN2JmYmVhMWM1YjY2MjY4ZWQ5YmYyYzU0MTM3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.oADTIX2TYYsFxDkkPcah7Ghjwbd2JzvA7mqyvV9ja7I)

might have misread your text, but we should this in the discord support server instead.

**Comment by Muhammet218** [comment]
All ipa files are expired. If anyone has them, can they share them?

**Comment by realdoomsboygaming** [comment]
https://nightly.link/PojavLauncherTeam/PojavLauncher_iOS/actions/runs/13833653522

Next time before messaging in a really old thread, perhaps take a look within the discord for a up to date link. This link should allow you to download the latest working build.
