### ISSUE TITLE
[Question] <App crashed when open for the second time>

### ISSUE THREAD

**Issue by lava114514** [PojavLauncherTeam/PojavLauncher_iOS#715]
### Ask the question here.

[latestlog.txt](https://github.com/user-attachments/files/16093343/latestlog.txt)

**Comment by Bonzai-Dev** [comment]
try this build: [https://github.com/PojavLauncherTeam/PojavLauncher_iOS/actions/runs/9800764087](url)

**Comment by lava114514** [comment]
It fixed. Thx
