### ISSUE TITLE
[Bug] Pojav faild to identify that my device is jail brocken

### ISSUE THREAD

**Issue by HelloWorldCoder-China** [PojavLauncherTeam/PojavLauncher_iOS#717]
### Describe the bug

pojav can not found out that my iphone is jail Brocken and install JIT

### Steps To Reproduce

```markdown
nop
```

### Expected Behavior

pojav install JIT

### Platform

```markdown
- Device model: iPhone
- iOS version: 17
- PojavLauncher version: newest
```

**Comment by ItAnthon** [comment]
send a log. also you cannot get jailbreak iphones on iOS 17.
