### ISSUE TITLE
[Bug] No runtime manager.

### ISSUE THREAD

**Issue by frdude** [PojavLauncherTeam/PojavLauncher_iOS#718]
### Describe the bug

Trying to add java 21, but I can't see runtime manager anywhere.
![IMG_1032](https://github.com/PojavLauncherTeam/PojavLauncher_iOS/assets/98312887/05bb2482-fd81-48d3-ad43-05e7de3c7130)

### The log file and images/videos

none

### Steps To Reproduce

```markdown
1. start pojav
2. settings -> java tweaks
```

### Expected Behavior

I expected runtime manager to be there.

### Platform

```markdown
- Device model: iphone 12 pro max
- iOS version: 16.3.1
- PojavLauncher version: 2.2 "deepslate"
```

**Comment by GaucovyAero** [comment]
update to the latest pojavlauncher ios github actions build
