### ISSUE TITLE
[Bug] Cannot Start Minecraft 1.21 with Sodium 0.5.11: LWJGL 3.3.3 required.

### ISSUE THREAD

**Issue by Shiroiame-Kusu** [PojavLauncherTeam/PojavLauncher_iOS#721]
### Describe the bug

Same as the title said.

### Steps To Reproduce

```markdown
1. Install Minecraft 1.21 , Fabric (latest), Sodium (latest).
2. Start the game.
3. Game crashed.
```

### Expected Behavior

The game starts normally.

### Platform

```markdown
- Device model: iPhone 15 Pro
- iOS version: 18.0
- PojavLauncher version: 3.0-development (main/073389e)
```

### Anything else?

[https://github.com/CaffeineMC/sodium-fabric/wiki/LWJGL-Compatibility](https://github.com/CaffeineMC/sodium-fabric/wiki/LWJGL-Compatibility)

**Comment by Shiroiame-Kusu** [comment]
Also I've noticed that PojavLauncherTeam has created a [fork](https://github.com/PojavLauncherTeam/lwjgl3/tree/wip/rebase_3.3.3) from LWJGL repo, is there any way to replace the LWJGL 3.3.1 in PojavLauncher_iOS with a higher version 3.3.3?

**Comment by ABBISOOO** [comment]
Same im trying to get sodium on fabric but required LWJGL 3.3.3

**Comment by Shiroiame-Kusu** [comment]
I tried the [latest build](https://github.com/PojavLauncherTeam/PojavLauncher_iOS/actions/runs/9918242601) from Github Action, and now it stuck at "Downloading Files......" when I try to start the game......
![352705bad215e138847a38839ac25f51](https://github.com/user-attachments/assets/92b8e968-bff0-475d-93f9-6e6a2dfcf86e)
sad:(

**Comment by ABBISOOO** [comment]
I think you just moved the files because i did and it gave me the same error but im currently downloading fabric perfectly

**Comment by Shiroiame-Kusu** [comment]
> I think you just moved the files because i did and it gave me the same error but im currently downloading fabric perfectly

Not sure about this, I can start the game(without Sodium) after I rollback PojavLauncher to a previous build
But the latest build can’t do anything.

**Comment by ABBISOOO** [comment]
Idk maybe a bug on the latest build.

**Comment by ABBISOOO** [comment]
![IMG_5624](https://github.com/user-attachments/assets/38089053-3035-42e3-999b-f96c657152d9)
So i got sodium 1.21 but…

**Comment by Shiroiame-Kusu** [comment]
> ![IMG_5624](https://private-user-images.githubusercontent.com/175425436/348460532-38089053-3035-42e3-999b-f96c657152d9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA4NjA0NjMsIm5iZiI6MTcyMDg2MDE2MywicGF0aCI6Ii8xNzU0MjU0MzYvMzQ4NDYwNTMyLTM4MDg5MDUzLTMwMzUtNDJlMy05OTliLWY5NmM2NTcxNTJkOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxM1QwODQyNDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kMWVlMjk5ZTgxYjE5ZGJmMzJiYjQ0YWZlNDg1MmQ5OTQxODhiNTIwMWNmYmYzOWI3OWFiNGM4NGRlN2EyNDMzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.VMI3ZU56qV1SjNJqKCn8lb6w0kLhkdj1Pv-LkmV0v-M) So i got sodium 1.21 but…

um……same as mine if I disable the LWJGL check from Sodium before starting the game

**Comment by Kiokingz** [comment]
> > ![IMG_5624](https://private-user-images.githubusercontent.com/175425436/348460532-38089053-3035-42e3-999b-f96c657152d9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA4NjA0NjMsIm5iZiI6MTcyMDg2MDE2MywicGF0aCI6Ii8xNzU0MjU0MzYvMzQ4NDYwNTMyLTM4MDg5MDUzLTMwMzUtNDJlMy05OTliLWY5NmM2NTcxNTJkOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxM1QwODQyNDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kMWVlMjk5ZTgxYjE5ZGJmMzJiYjQ0YWZlNDg1MmQ5OTQxODhiNTIwMWNmYmYzOWI3OWFiNGM4NGRlN2EyNDMzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.VMI3ZU56qV1SjNJqKCn8lb6w0kLhkdj1Pv-LkmV0v-M) So i got sodium 1.21 but…
> 
> um……same as mine if I disable the LWJGL check from Sodium before starting the game

its because sodium isn't supported.
sodium uses OpenGL extensions that PojavLauncher iOS doesn't have. (ANGLE/gl4es)
Zink renderer solves this, but the performance will be heck bad, even worse than without sodium installed.

**Comment by Kiokingz** [comment]
LWJGL has been updated to 3.3.3 also, take a look [here](https://github.com/PojavLauncherTeam/PojavLauncher_iOS/actions/runs/9918242601).

**Comment by ABBISOOO** [comment]
Any fix?

**Comment by Kiokingz** [comment]
> Any fix?

no

**Comment by khanhduytran0** [comment]
> its because sodium isn't supported. sodium uses OpenGL extensions that PojavLauncher iOS doesn't have. (ANGLE/gl4es) Zink renderer solves this, but the performance will be heck bad, even worse than without sodium installed.

This is why you see a big red warning that reads “PojavLauncher is unsupported” and you still ignored it.

**Comment by Kiokingz** [comment]
> > its because sodium isn't supported. sodium uses OpenGL extensions that PojavLauncher iOS doesn't have. (ANGLE/gl4es) Zink renderer solves this, but the performance will be heck bad, even worse than without sodium installed.
> 
> This is why you see a big red warning that reads “PojavLauncher is unsupported” and you still ignored it.

i even don't get how they did not see it

**Comment by ABBISOOO** [comment]
I mean yea ik but sometimes they say its not supported but it end up working but with some bugs
