### ISSUE TITLE
TLauncher.org Account Support

### ISSUE THREAD

**Issue by admin-elvistrujanovic** [PojavLauncherTeam/PojavLauncher_iOS#73]
Can you add the TLauncher.org login option so we can change Minecraft skins and play servers without buying a real mc account

**Comment by khanhduytran0** [comment]
They didn’t export any API related to account authentication, so we can’t do that. Also, their modded libraries (custom skins/cape, etc...) seems only works with their launcher.

**Comment by elvistrujanovic51** [comment]
> They didn’t export any API related to account authentication, so we can’t do that. Also, their modded libraries (custom skins/cape, etc...) seems only works with their launcher.

And what if you work with tlauncher.org, you can ask them to give you all the information and support needed to implement that option and support your project to make their account work properly. If you have any problems with them, I am here to help you (elvistrujanovic51@gmail.com)

**Comment by khanhduytran0** [comment]
But their service has some paid stuff, so I don't think if I can contact them for free :eyes:
Also, their paid stuff violates Minecraft EULA, so I'm a bit confused.

**Comment by admin-elvistrujanovic** [comment]
> But their service has some paid stuff, so I don't think if I can contact them for free :eyes:
> 
> Also, their paid stuff violates Minecraft EULA, so I'm a bit confused.

Their paid stuff do not violate the Minecraft EULA for only one reason - they work with Mojang to provide free bills, but they have to pay them all instead of us

As for free contact, I think you should start and inquire about their phone number, then call them and only then see how things are with the collaboration

**Comment by timof121** [comment]
> > But their service has some paid stuff, so I don't think if I can contact them for free 👀
> > Also, their paid stuff violates Minecraft EULA, so I'm a bit confused.
> 
> Their paid stuff do not violate the Minecraft EULA for only one reason - they work with Mojang to provide free bills, but they have to pay them all instead of us
> 
> As for free contact, I think you should start and inquire about their phone number, then call them and only then see how things are with the collaboration 

(No, they dont work for mojang because they let you play mojang’s **paid** game for free)

**Comment by khanhduytran0** [comment]
Their paid stuff:
![image](https://user-images.githubusercontent.com/40482367/109403305-fbb21100-798e-11eb-9f20-0e2424e486a3.jpeg)

**Comment by admin-elvistrujanovic** [comment]
> Their paid stuff:
> ![image](https://user-images.githubusercontent.com/40482367/109403305-fbb21100-798e-11eb-9f20-0e2424e486a3.jpeg)

And how you stand with your account - just imagine a “PojavLauncher Account” that can provide their free users with full game features including Skins and Multiplayer

**Comment by khanhduytran0** [comment]
- We don't have any servers to host it.
- Multiplayer/premium server can't be cracked with 3rd party account.

**Comment by admin-elvistrujanovic** [comment]
> - We don't have any servers to host it.
> - Multiplayer/premium server can't be cracked with 3rd party account.

Can a hosting server be purchased and Multiplayer/Servers hacked?

(But so that Mojang doesn't find out about this)

**Comment by khanhduytran0** [comment]
Do you have money? Do you own account database manager source code?

**Comment by khanhduytran0** [comment]
Do you own the server that want to hack?

**Comment by khanhduytran0** [comment]
Do F🅱️1 meet us if we begin hack?

**Comment by khanhduytran0** [comment]
Do we know how to hack?

**Comment by admin-elvistrujanovic** [comment]
> Do you know how to hack?

Yes but I didn't do that for a long time because of the risk of not being caught (it's hard to sleep with the fear of the police entering and being arrested immediately) - If you know how to hack, you could do it if you didn't have the same fear as me
