### ISSUE TITLE
[Bug] Need to install Java 21

### ISSUE THREAD

**Issue by Legend7832** [PojavLauncherTeam/PojavLauncher_iOS#730]
### Describe the bug

When trying to run Minecraft Java 1.21, shows error and says I need to install Java 21

### The log file and images/videos

[Pre-Init] PojavLauncher INIT!
[Pre-Init] Version: 2.2-development
[Pre-Init] Commit: d9877bc (main)
[Pre-Init] Device: iPad (9th generation)
[Pre-Init] iOS 16.1.1 (TrollStore)
[Pre-init] Entitlements availability:
* com.apple.developer.kernel.extended-virtual-addressing: YES
* com.apple.developer.kernel.increased-memory-limit: YES
* com.apple.private.security.no-sandbox: YES
* dynamic-codesigning: NO
[Debugging] Debug log enabled: YES
[Pre-init] Restored game directory preference (default)
[Pre-init] no-sandbox: YES, trying to enable JIT
calling ptrace(PT_TRACE_ME)
[Pre-init] JIT has been enabled with PT_TRACE_ME
2024-07-19 19:36:39.746 PojavLauncher[1032:80412] -[UIPickerView setFrame:]: invalid size {320, 216} pinned to {320, 216} 
Path is file:///var/mobile/Containers/Data/Application/A91BC5AB-B907-44CC-A76E-6820FA02B057/Documents/latestlog.old.txt
[MCDL] Downloading 1.21
[MCDL] Warning: couldn't find SHA for /var/mobile/Containers/Data/Application/A91BC5AB-B907-44CC-A76E-6820FA02B057/Documents/Library/Application Support/minecraft/versions/1.21/1.21.json, have to assume it's good.
[MCDL] Downloading 17
[MCDL] SHA1 passed for 17.json
[MCDL] Begin: download libraries
[MCDL] SHA1 passed for java-objc-bridge-1.1.jar
[MCDL] SHA1 passed for oshi-core-6.4.10.jar
[MCDL] SHA1 passed for gson-2.10.1.jar
[MCDL] SHA1 passed for failureaccess-1.0.1.jar
[MCDL] SHA1 passed for guava-32.1.2-jre.jar
[MCDL] SHA1 passed for icu4j-73.2.jar
[MCDL] SHA1 passed for authlib-6.0.54.jar
[MCDL] SHA1 passed for blocklist-1.0.10.jar
[MCDL] SHA1 passed for brigadier-1.2.9.jar
[MCDL] SHA1 passed for datafixerupper-8.0.16.jar
[MCDL] SHA1 passed for logging-1.2.7.jar
[MCDL] SHA1 passed for patchy-2.2.10.jar
[MCDL] SHA1 passed for text2speech-1.17.9.jar
[MCDL] SHA1 passed for commons-codec-1.16.0.jar
[MCDL] SHA1 passed for commons-io-2.15.1.jar
[MCDL] SHA1 passed for commons-logging-1.2.jar
[MCDL] SHA1 passed for netty-buffer-4.1.97.Final.jar
[MCDL] SHA1 passed for netty-codec-4.1.97.Final.jar
[MCDL] SHA1 passed for netty-common-4.1.97.Final.jar
[MCDL] SHA1 passed for netty-handler-4.1.97.Final.jar
[MCDL] SHA1 passed for netty-resolver-4.1.97.Final.jar
[MCDL] SHA1 passed for netty-transport-classes-epoll-4.1.97.Final.jar
[MCDL] SHA1 passed for netty-transport-native-epoll-4.1.97.Final-linux-aarch_64.jar
[MCDL] SHA1 passed for netty-transport-native-epoll-4.1.97.Final-linux-x86_64.jar
[MCDL] SHA1 passed for netty-transport-native-unix-common-4.1.97.Final.jar
[MCDL] SHA1 passed for netty-transport-4.1.97.Final.jar
[MCDL] SHA1 passed for fastutil-8.5.12.jar
[MCDL] SHA1 passed for jna-platform-5.14.0.jar
[MCDL] SHA1 passed for jna-5.13.0.jar
[MCDL] SHA1 passed for jopt-simple-5.0.4.jar
[MCDL] SHA1 passed for commons-compress-1.26.0.jar
[MCDL] SHA1 passed for commons-lang3-3.14.0.jar
[MCDL] SHA1 passed for httpclient-4.5.13.jar
[MCDL] SHA1 passed for httpcore-4.4.16.jar
[MCDL] SHA1 passed for log4j-api-2.22.1.jar
[MCDL] SHA1 passed for log4j-core-2.22.1.jar
[MCDL] SHA1 passed for log4j-slf4j2-impl-2.22.1.jar
[MCDL] SHA1 passed for jorbis-0.0.17.jar
[MCDL] SHA1 passed for joml-1.10.5.jar
[MCDL] Skipped library org.lwjgl:lwjgl-freetype:3.3.3
[MCDL] Skipped library org.lwjgl:lwjgl-freetype:3.3.3:natives-linux
[MCDL] Skipped library org.lwjgl:lwjgl-freetype:3.3.3:natives-macos-arm64
[MCDL] Skipped library org.lwjgl:lwjgl-freetype:3.3.3:natives-macos-patch
[MCDL] Skipped library org.lwjgl:lwjgl-freetype:3.3.3:natives-windows
[MCDL] Skipped library org.lwjgl:lwjgl-freetype:3.3.3:natives-windows-arm64
[MCDL] Skipped library org.lwjgl:lwjgl-freetype:3.3.3:natives-windows-x86
[MCDL] Skipped library org.lwjgl:lwjgl-glfw:3.3.3
[MCDL] Skipped library org.lwjgl:lwjgl-glfw:3.3.3:natives-linux
[MCDL] Skipped library org.lwjgl:lwjgl-glfw:3.3.3:natives-macos
[MCDL] Skipped library org.lwjgl:lwjgl-glfw:3.3.3:natives-macos-arm64
[MCDL] Skipped library org.lwjgl:lwjgl-glfw:3.3.3:natives-windows
[MCDL] Skipped library org.lwjgl:lwjgl-glfw:3.3.3:natives-windows-arm64
[MCDL] Skipped library org.lwjgl:lwjgl-glfw:3.3.3:natives-windows-x86
[MCDL] Skipped library org.lwjgl:lwjgl-jemalloc:3.3.3
[MCDL] Skipped library org.lwjgl:lwjgl-jemalloc:3.3.3:natives-linux
[MCDL] Skipped library org.lwjgl:lwjgl-jemalloc:3.3.3:natives-macos
[MCDL] Skipped library org.lwjgl:lwjgl-jemalloc:3.3.3:natives-macos-arm64
[MCDL] Skipped library org.lwjgl:lwjgl-jemalloc:3.3.3:natives-windows
[MCDL] Skipped library org.lwjgl:lwjgl-jemalloc:3.3.3:natives-windows-arm64
[MCDL] Skipped library org.lwjgl:lwjgl-jemalloc:3.3.3:natives-windows-x86
[MCDL] Skipped library org.lwjgl:lwjgl-openal:3.3.3
[MCDL] Skipped library org.lwjgl:lwjgl-openal:3.3.3:natives-linux
[MCDL] Skipped library org.lwjgl:lwjgl-openal:3.3.3:natives-macos
[MCDL] Skipped library org.lwjgl:lwjgl-openal:3.3.3:natives-macos-arm64
[MCDL] Skipped library org.lwjgl:lwjgl-openal:3.3.3:natives-windows
[MCDL] Skipped library org.lwjgl:lwjgl-openal:3.3.3:natives-windows-arm64
[MCDL] Skipped library org.lwjgl:lwjgl-openal:3.3.3:natives-windows-x86
[MCDL] Skipped library org.lwjgl:lwjgl-opengl:3.3.3
[MCDL] Skipped library org.lwjgl:lwjgl-opengl:3.3.3:natives-linux
[MCDL] Skipped library org.lwjgl:lwjgl-opengl:3.3.3:natives-macos
[MCDL] Skipped library org.lwjgl:lwjgl-opengl:3.3.3:natives-macos-arm64
[MCDL] Skipped library org.lwjgl:lwjgl-opengl:3.3.3:natives-windows
[MCDL] Skipped library org.lwjgl:lwjgl-opengl:3.3.3:natives-windows-arm64
[MCDL] Skipped library org.lwjgl:lwjgl-opengl:3.3.3:natives-windows-x86
[MCDL] Skipped library org.lwjgl:lwjgl-stb:3.3.3
[MCDL] Skipped library org.lwjgl:lwjgl-stb:3.3.3:natives-linux
[MCDL] Skipped library org.lwjgl:lwjgl-stb:3.3.3:natives-macos
[MCDL] Skipped library org.lwjgl:lwjgl-stb:3.3.3:natives-macos-arm64
[MCDL] Skipped library org.lwjgl:lwjgl-stb:3.3.3:natives-windows
[MCDL] Skipped library org.lwjgl:lwjgl-stb:3.3.3:natives-windows-arm64
[MCDL] Skipped library org.lwjgl:lwjgl-stb:3.3.3:natives-windows-x86
[MCDL] Skipped library org.lwjgl:lwjgl-tinyfd:3.3.3
[MCDL] Skipped library org.lwjgl:lwjgl-tinyfd:3.3.3:natives-linux
[MCDL] Skipped library org.lwjgl:lwjgl-tinyfd:3.3.3:natives-macos
[MCDL] Skipped library org.lwjgl:lwjgl-tinyfd:3.3.3:natives-macos-arm64
[MCDL] Skipped library org.lwjgl:lwjgl-tinyfd:3.3.3:natives-windows
[MCDL] Skipped library org.lwjgl:lwjgl-tinyfd:3.3.3:natives-windows-arm64
[MCDL] Skipped library org.lwjgl:lwjgl-tinyfd:3.3.3:natives-windows-x86
[MCDL] Skipped library org.lwjgl:lwjgl:3.3.3
[MCDL] Skipped library org.lwjgl:lwjgl:3.3.3:natives-linux
[MCDL] Skipped library org.lwjgl:lwjgl:3.3.3:natives-macos
[MCDL] Skipped library org.lwjgl:lwjgl:3.3.3:natives-macos-arm64
[MCDL] Skipped library org.lwjgl:lwjgl:3.3.3:natives-windows
[MCDL] Skipped library org.lwjgl:lwjgl:3.3.3:natives-windows-arm64
[MCDL] Skipped library org.lwjgl:lwjgl:3.3.3:natives-windows-x86
[MCDL] SHA1 passed for lz4-java-1.8.0.jar
[MCDL] SHA1 passed for slf4j-api-2.0.9.jar
[MCDL] SHA1 passed for 1.21.jar
[MCDL] Finished: download libraries
[MCDL] Begin: download assets
[MCDL] SHA1 passed for 3886/3887 asset files
[MCDL] Finished: download assets
Note: some files of 1.19+ are skipped to workaround an issue
Successfully set Jetsam task limit
[MCDL] Warning: couldn't find SHA for /var/mobile/Containers/Data/Application/A91BC5AB-B907-44CC-A76E-6820FA02B057/Documents/Library/Application Support/minecraft/versions/1.21/1.21.json, have to assume it's good.
[MCDL] SHA1 passed for 17.json
[JavaLauncher] Beginning JVM launch
[JavaLauncher] Attempting to change to Java 21 (actual might be higher)
[JavaLauncher] JAVA_HOME is now set to (null)
[UI] Dialog shown: Error: Minecraft 1.21 requires Java 21 in order to run. Please install it first.

### Steps To Reproduce

```markdown
1. Start PojavLauncher
2. Selected Version 1.21
3. Selected Play
```

### Expected Behavior

Expected game to load

### Platform

```markdown
- Device model: IPad (9th Generation)
- iOS version: 16.1.1
- PojavLauncher version: PojavLauncher 2.2-development
```

**Comment by Kiokingz** [comment]
update to the latest [github actions build](https://github.com/PojavLauncherTeam/PojavLauncher_iOS/actions/runs/9988360435).

**Comment by Jerry12798** [comment]
> update to the latest [github actions build](https://github.com/PojavLauncherTeam/PojavLauncher_iOS/actions/runs/9988360435).

Do you know why we aren't we able to select Minecraft version when we use the latest actions build?

**Comment by Legend7832** [comment]
> update to the latest [github actions build](https://github.com/PojavLauncherTeam/PojavLauncher_iOS/actions/runs/9988360435).

How would I update to the latest [GitHub Actions Build](https://github.com/PojavLauncherTeam/PojavLauncher_iOS/actions/runs/9988360435)

**Comment by Legend7832** [comment]
Closing Issue
