### ISSUE TITLE
[Bug] Black screen while playing

### ISSUE THREAD

**Issue by Zhang00007** [PojavLauncherTeam/PojavLauncher_iOS#734]
### Describe the bug

Black screen while playing

### The log file and images/videos

[latestlog.old-1.txt](https://github.com/user-attachments/files/16323508/latestlog.old-1.txt)

https://github.com/user-attachments/assets/c5164d59-c002-4060-9ed0-5f703ad1caac

### Steps To Reproduce

```markdown
video
```

### Expected Behavior

Solved my problem

### Platform

```markdown
- Device model: ipad9
- iOS version:16.1 
- PojavLauncher version: latest
```

**Comment by Mobimi** [comment]
how to enable performance monitor on ios 16?

**Comment by Zhang00007** [comment]
> how to enable performance monitor on ios 16?

in the settings of your pojavluncher
![Uploading BF83C04C-EE8E-40CE-8279-9703949D0B76.jpeg…]()

**Comment by Zhang00007** [comment]
> how to enable performance monitor on ios 16?

in the settings of your pojavluncher
