### ISSUE TITLE
How to install Java 21 on IOS for Minecraft 1.21?

### ISSUE THREAD

**Issue by SkyKingPX** [PojavLauncherTeam/PojavLauncher_iOS#735]
### Ask the question here.

I have no Idea how to do that…

**Comment by ItAnthon** [comment]
you need to use the latest github actions build. this will contain java 21 itself and improvements and updates to the launcher. it can be found from the following link: https://nightly.link/PojavLauncherTeam/PojavLauncher_iOS/workflows/development/main/net.kdt.pojavlauncher-ios.ipa.zip

**Comment by SkyKingPX** [comment]
Thank you

**Comment by SkyKingPX** [comment]
Now all Icons are bigger than usual and it crashes with this Message @ItAnthon : 
![image](https://github.com/user-attachments/assets/c40ab8c0-ffc6-490d-a601-e15c53b90779)

**Comment by SkyKingPX** [comment]
I have a iPhone 11 and IOS 18 installed.
![image](https://github.com/user-attachments/assets/fd8ed022-bb86-42d5-af3d-f569043393b8)

**Comment by ItAnthon** [comment]
what was the point of your second screenshot? your iPhone no longer supports TrollStore.

you also have an unsupported installation method for PojavLauncher. you need to either use SideStore or AltStore.

**Comment by SkyKingPX** [comment]
> what was the point of your second screenshot?

I don’t know if my iPhone is Arm64 or Arm64e


I will try installing it with those

**Comment by ItAnthon** [comment]
your iPhone is arm64e. either way, it’s unsupported for TrollStore. Stop updating your iDevice if you hope for the smoothest experience possible.

**Comment by SkyKingPX** [comment]
Well AltStore and SideStore don't work because my appleid is not available for "developement with XCode"

**Comment by ItAnthon** [comment]
you need to sign into apple’s developer portal (thing)? with your Apple ID at least once.

**Comment by SkyKingPX** [comment]
Well I'm not 16 yet![image](https://github.com/user-attachments/assets/7d445dfa-5f94-492a-9aa9-0576e1a2a98e)
