### ISSUE TITLE
Whats the problem?

### ISSUE THREAD

**Issue by SB3S** [PojavLauncherTeam/PojavLauncher_iOS#736]
### Describe the bug

When I launch the game, it crash and then when I saw the log file, I don't understand 

### The log file and images/videos

-
[latestlog.txt](https://github.com/user-attachments/files/16323871/latestlog.txt)

### Steps To Reproduce

```markdown
1 installed minecraft 1.21, Fabric latest, sodium latest
2. Start the game
3. Game crashed
```

### Expected Behavior

I expect the game would play smoothly and no bug and crashes 

### Platform

```markdown
- Device model:Honor x9a 5g
- PojavLauncher version: foxglove-20240709-045018f-v

3 openjdk
```

**Comment by TDosYos** [comment]
Here is the IOS issue, please submit this issue to the Android issue.
