### ISSUE TITLE
[iOS 18 Support?] <JIT issue>

### ISSUE THREAD

**Issue by Chxrgxr** [PojavLauncherTeam/PojavLauncher_iOS#738]
### Ask the question here.

okay, im kind of new to PojavLauncher, but, is it possible to use Pojav on iOS 18? im using AltStore to sideload it. When i enable JIT it keeps saying "The URL to download the Developer disk image could not be determined." i don't know if this is an AltStore issue, or an iOS issue. thanks.

**Comment by Mobimi** [comment]
maybe not:)

**Comment by Chxrgxr** [comment]
Fixed it

**Comment by jaktoes** [comment]
How do you fix it

**Comment by Chxrgxr** [comment]
> How do you fix it

I used SideStore, and used SideJITServer.

**Comment by BHATIAnub** [comment]
> > How do you fix it
> 
> 
> 
> I used SideStore, and used SideJITServer.

I tried it also. But didn't work. I enabled SideJITServer in SideStore but still am not able to enable side jit. Can you explain how you did that?
