### ISSUE TITLE
Maybe Controller Support?

### ISSUE THREAD

**Issue by poggies123** [PojavLauncherTeam/PojavLauncher_iOS#74]

**Comment by ThatsNiceGuy** [comment]
Pretty sure this isn’t possible, not even Minecraft Java Edition on PC has controller support, you have to use stuff like JoyToKey

**Comment by khanhduytran0** [comment]
Maybe, but then you need a mod such as Controllable to play with it.

**Comment by recklessking** [comment]
Or add like a joystick rather than the d pad we got now. With like traiangles cut in the circular shape around the joystick🤔actually now that I think about it that sounds quite tough

**Comment by Witherking25** [comment]
None of the joypads work because they rely on some classes from glfw that don’t exist in PojavLauncher

**Comment by Witherking25** [comment]
It would probably work if those classes were implemented

**Comment by Doregon** [comment]
Closing as this is mentioned in #184. This is still an issue.
