### ISSUE TITLE
[Bug] <Short description>

### ISSUE THREAD

**Issue by u-KpaTKoe** [PojavLauncherTeam/PojavLauncher_iOS#744]
### Describe the bug

when I login Microsoft account it sends Too many requests error. Even two days after this circumstance.
![Screenshot_20240812-210302](https://github.com/user-attachments/assets/27ffaacf-4319-4b9a-baec-eed1c359ff24)

### Steps To Reproduce

```markdown
1. Start PojavLauncher
2. Click the button 'add new account'
3. Enter my Microsoft account 
4. Too many requests
```

### Expected Behavior

I expect the game to log me in

### Platform

```markdown
- Device model: Tecno Spark 10 pro
- Android version: 13
- PojavLauncher version: Latest release
```

**Comment by fish12352** [comment]
use vpn

**Comment by u-KpaTKoe** [comment]
the problem was, that I used vpn
