### ISSUE TITLE
I can't use the local acc

### ISSUE THREAD

**Issue by F0rTrIp** [PojavLauncherTeam/PojavLauncher_iOS#752]
### Describe the bug

It said minecraft can't be legally installed

### Steps To Reproduce

```markdown
.
```

### Expected Behavior

I expect i can play

### Platform

```markdown
- Device model: ip x
- iOS version: 15+
- PojavLauncher version: 3.0
```

**Comment by khanhduytran0** [comment]
You need a valid Minecraft license or Xbox gamepass before proceeding. Otherwise you could play around the demo mode.
