### ISSUE TITLE
[F-Req] <Short description>i hope we can install java 22 because

### ISSUE THREAD

**Issue by qiewane** [PojavLauncherTeam/PojavLauncher_iOS#753]

**Comment by qiewane** [comment]
because we cannot play 1.21.1 ,it ’s bad

**Comment by Kiokingz** [comment]
you can run 1.21.1 with java 21, just make sure you're on the latest development build from the actions tab

**Comment by qiewane** [comment]
how can i install java21 on m iphone,my iphone is ios15.8.3

**Comment by qiewane** [comment]
what should i do,i don’t know how to install java21 on ios

> you can run 1.21.1 with java 21, just make sure you're on the latest development build from the actions tab

**Comment by GaucovyAero** [comment]
install the latest github actions build, guide is on the wiki

**Comment by littleboulderbro** [comment]
Perchance could I have the java21 file link right here maybe?

**Comment by Kiokingz** [comment]
> Perchance could I have the java21 file link right here maybe?
[here you go](https://nightly.link/PojavLauncherTeam/PojavLauncher_iOS/workflows/development/main/net.kdt.pojavlauncher-ios.ipa.zip)
