### ISSUE TITLE
[Bug] Forge 1.21.1 Crushing on start

### ISSUE THREAD

**Issue by jackson392** [PojavLauncherTeam/PojavLauncher_iOS#755]
### Describe the bug

Help

### The log file and images/videos

[latestlog.txt](https://github.com/user-attachments/files/16846838/latestlog.txt)

### Steps To Reproduce

```markdown
Help
```

### Expected Behavior

Help

### Platform

```markdown
- Device model: IPhone SE 2020
- iOS version:17.0
- PojavLauncher version:latest 3.0
```

### Anything else?

Help

**Comment by CowSheep72** [comment]
oh shit the "help" people have migrated to ios

**Comment by Kiokingz** [comment]
> oh shit the "help" people have migrated to ios

mostly iOS PojavLauncher users should have minercraft java

**Comment by Kiokingz** [comment]
yeah i have no idea what this is
