### ISSUE TITLE
[Bug] Performance Downgrade when using Zink backend.

### ISSUE THREAD

**Issue by Longtianmu** [PojavLauncherTeam/PojavLauncher_iOS#757]
### Describe the bug

In the latest dev version (main/ccde0ef),
choosing Zink instead of ANGLE or GL4ES may lower the fps by 80%.
Also, the Metal HUD is disappeared.

### Steps To Reproduce

```markdown
1. Install Pojav using TrollStore 2.1.
2. Start the latest Minecraft(1.21.1).
3. Create a superflat world and open Debug/F3.
```

### Expected Behavior

The FPS might be higher, and the Metal HUD should appear.

### Platform

```markdown
- Device model: iPad Pro (11-inch) (4th gen)
- iOS version: iOS 17.0 using TrollStore
- PojavLauncher version: 3.0 (main/ccde0ef)
```

### Anything else?

The view distance was set to 16 when simulate distance was 4.
3GB RAM was given for Java 21.
Other settings are all default.
The tipa format was used when downloading dev version.

**Comment by Kiokingz** [comment]
this is a known issue, but i also don't know when this will be "fixed", Zink is overall laggy which is normal, as if its a trade-off compatibility for performance, use Zink for debugging purposes only, not for regular use.

**Comment by GaucovyAero** [comment]
closing as this is normal, zink is more compatible but less performant
