### ISSUE TITLE
[Bug] ResolutionException Crash with Forge 1.21.1 on PojavLauncher (iOS - TrollStore)

### ISSUE THREAD

**Issue by jackson392** [PojavLauncherTeam/PojavLauncher_iOS#759]
### Describe the bug

I am experiencing a crash when trying to launch Minecraft 1.21.1 with Forge version 52.0.9 on PojavLauncher running on an iPhone with TrollStore. The crash seems to be related to a module resolution conflict involving com.sun.jna and brigadier, resulting in a ResolutionException. Despite allocating the maximum RAM available on my device and using TrollStore for extended memory capabilities, the game fails to launch.

### The log file and images/videos

[latestlog 3.txt](https://github.com/user-attachments/files/16920772/latestlog.3.txt)

### Steps To Reproduce

```markdown
Launch PojavLauncher with Forge 52.0.9 and Minecraft 1.21.1.
Allow maximum RAM allocation on the phone using TrollStore.
Attempt to start the game.
The game crashes before reaching the main menu, with the log showing a ResolutionException. This is not to do with trollstore just saying.
```

### Expected Behavior

The game should load without a crash, allowing me to play Minecraft with Forge mods.

### Platform

```markdown
device:iPhone Se(2ndgeneration)iOSVersion 17.0(TrollStoreinstalled)PojavLauncherVersion203.0-developmentMinecraftVersion1.21.1Forge Version2052.0.90MaxRAMAllocation 2515
```

**Comment by NPC885** [comment]
> ### Describe the bug
> 
> I am experiencing a crash when trying to launch Minecraft 1.21.1 with Forge version 52.0.9 on PojavLauncher running on an iPhone with TrollStore. The crash seems to be related to a module resolution conflict involving com.sun.jna and brigadier, resulting in a ResolutionException. Despite allocating the maximum RAM available on my device and using TrollStore for extended memory capabilities, the game fails to launch.
> 
> ### The log file and images/videos
> 
> [latestlog 3.txt](https://github.com/user-attachments/files/16920772/latestlog.3.txt)
> 
> 
> 
> ### Steps To Reproduce
> 
> ```markdown
> Launch PojavLauncher with Forge 52.0.9 and Minecraft 1.21.1.
> 
> Allow maximum RAM allocation on the phone using TrollStore.
> 
> Attempt to start the game.
> 
> The game crashes before reaching the main menu, with the log showing a ResolutionException. This is not to do with trollstore just saying.
> ```
> 
> 
> ### Expected Behavior
> 
> The game should load without a crash, allowing me to play Minecraft with Forge mods.
> 
> ### Platform
> 
> ```markdown
> device:iPhone Se(2ndgeneration)iOSVersion 17.0(TrollStoreinstalled)PojavLauncherVersion203.0-developmentMinecraftVersion1.21.1Forge Version2052.0.90MaxRAMAllocation 2515
> ```
> 
> 
> ### Anything else?
> 
> _No response_

**Comment by Kiokingz** [comment]
> ### Describe the bug
> I am experiencing a crash when trying to launch Minecraft 1.21.1 with Forge version 52.0.9 on PojavLauncher running on an iPhone with TrollStore. The crash seems to be related to a module resolution conflict involving com.sun.jna and brigadier, resulting in a ResolutionException. Despite allocating the maximum RAM available on my device and using TrollStore for extended memory capabilities, the game fails to launch.
> 
> ### The log file and images/videos
> [latestlog 3.txt](https://github.com/user-attachments/files/16920772/latestlog.3.txt)
> 
> ### Steps To Reproduce
> ```
> Launch PojavLauncher with Forge 52.0.9 and Minecraft 1.21.1.
> Allow maximum RAM allocation on the phone using TrollStore.
> Attempt to start the game.
> The game crashes before reaching the main menu, with the log showing a ResolutionException. This is not to do with trollstore just saying.
> ```
> 
> ### Expected Behavior
> The game should load without a crash, allowing me to play Minecraft with Forge mods.
> 
> ### Platform
> ```
> device:iPhone Se(2ndgeneration)iOSVersion 17.0(TrollStoreinstalled)PojavLauncherVersion203.0-developmentMinecraftVersion1.21.1Forge Version2052.0.90MaxRAMAllocation 2515
> ```
> 
> ### Anything else?
> _No response_

heya, sorry for the late response.
can you try downgrading back to this [build commit](https://github.com/PojavLauncherTeam/PojavLauncher_iOS/actions/runs/10413866591)? let me know if something happens.

**Comment by jackson392** [comment]
Thank you!

**Comment by jackson392** [comment]
Thank You!

**Comment by Kiokingz** [comment]
> Thank You!

is it fixed? if yes, thats good to great then.
