### ISSUE TITLE
[F-Req] i dont know how to get java 21 on pojav and need an ipa or something

### ISSUE THREAD

**Issue by Dual4578** [PojavLauncherTeam/PojavLauncher_iOS#762]
### Is this request related to a bug?

i have pojavlauncher through trollstore but when i try to open a new version aka 1.21.1 id says i need java 21 and i dont know how to get java 21.

### Describe the request.

if anyone has a version with java 21 aka ipa already installed that would be great

### Anything else?

tia

**Comment by Kiokingz** [comment]
https://nightly.link/PojavLauncherTeam/PojavLauncher_iOS/workflows/development/main/net.kdt.pojavlauncher-ios.ipa.zip
