### ISSUE TITLE
[F-Req] Please update ANGLE to a newer version for bug fixes and improvements

### ISSUE THREAD

**Issue by mrjasonn** [PojavLauncherTeam/PojavLauncher_iOS#767]
### Is this request related to a bug?

There may be many bugs with an older version, whilst a newer version may be more stable.

### Describe the request.

Please update ANGLE to a newer version for bug fixes and improvements. Potentially the Sodium mod might work properly if it is updated. I have created a pull request in the PojavLauncher custom ANGLE repository.

**Comment by Kiokingz** [comment]
fork the ANGLE repository and do it yourself
