### ISSUE TITLE
Can't Install Forge

### ISSUE THREAD

**Issue by waterdragon78** [PojavLauncherTeam/PojavLauncher_iOS#77]
When I try to use forge it crashes, I had to import the version from my computer as there is no working terminal for iPadOS 14. I'll include the log too 
[latest.log](https://github.com/PojavLauncherTeam/PojavLauncher_iOS/files/6063154/latest.log)

**Comment by lanspring** [comment]
forge Only version 1.16.5 is supported?

**Comment by waterdragon78** [comment]
oh im trying 1.7.10 and 1.12.2

**Comment by lanspring** [comment]
PojavLauncher Current support forge It is the latest version (1.16.5)

**Comment by waterdragon78** [comment]
it only supports 1.16.5?

**Comment by lanspring** [comment]
right

> it only supports 1.16.5?

yes, I try other versions, but it will stay in the interface

**Comment by waterdragon78** [comment]
k

**Comment by slavicweebofficial** [comment]
Did you type the commands or copy and paste?

**Comment by waterdragon78** [comment]
Does copy + pasting have to do with it? I cant run the terminal cuz iPad did something to the terminals so I copy and pasted.
