### ISSUE TITLE
[Bug] getting "Waiting for JIT" message while JIT is enabled

### ISSUE THREAD

**Issue by vsp-bo3** [PojavLauncherTeam/PojavLauncher_iOS#784]
### Describe the bug

was trying to use but everytime i tried to launch, it would say "Waiting for JIT" and would tell me to enable something on trollstore. i have a jailbroken device and made sure the correct setting was enabled, but nothing ended up working

### Steps To Reproduce

```markdown
1. launch PojavLauncher
2. try to play a version
```

### Expected Behavior

it gets past the "Waiting for JIT" message

### Platform

```markdown
- Device model: ipod (7th gen)
- iOS version: 15.8.3
- PojavLauncher version: nightly (latest as of 12-15-24)
```

### Anything else?

ik it might seem weird but that ipod actually worked for pojav before but it stopped working after i tried to play today after a few month

i could try the latest release instead of nightly but idk if its gonna fix the problem and im using nightly for java 21, which is needed for the later versions

**Comment by Kiokingz** [comment]
what did you use to install PojavLauncher?

**Comment by vsp-bo3** [comment]
> what did you use to install PojavLauncher? (SideStore/AltStore/Sideloadly/etc.)

i used trollstore

**Comment by vsp-bo3** [comment]
nvm, i fixed it by rejailbreaking
