### ISSUE TITLE
iOS version limitation?

### ISSUE THREAD

**Issue by thecoder08** [PojavLauncherTeam/PojavLauncher_iOS#8]

**Comment by khanhduytran0** [comment]
Since OpenJDK runs on iOS 12+ so minimum is iOS 12

**Comment by thecoder08** [comment]
oh ok. I thought it might be higher. I'm iOS 12.5 and iPhone 5s. When I open the app it immediately crashes, which usually involves the iOS version. I'll create a new issue for what I've experienced.
