### ISSUE TITLE
Cannot be compiled on macOS big sur

### ISSUE THREAD

**Issue by jumpers775** [PojavLauncherTeam/PojavLauncher_iOS#80]
MacOS big sur has some weird jdk file path wrong situation. this results in it not being compileable.

**Comment by khanhduytran0** [comment]
Maybe try set them? :eyes:

**Comment by khanhduytran0** [comment]
@jumpers775 ?

**Comment by Doregon** [comment]
This issue is going to be closed due to inactivity. I will explore it and report back on how to fix it soon.

**Comment by Doregon** [comment]
macOS Big Sur was able to successfully compile PojavLauncher with the following configurations:

- 2012 15" MacBook Pro (patched)
- 2018 Dell Inspiron 5570 (Hackintosh)
- 2018 "Mac Mini" (OSX-KVM server)

The jdk-wrong situation is unique to you, try installing Oracle's JDK package.
