### ISSUE TITLE
Mouse Positioning in-accurate while using forge.

### ISSUE THREAD

**Issue by BowlineNetwork** [PojavLauncherTeam/PojavLauncher_iOS#84]
When using Forge, tapping on the screen results in nothing being tapped. Holding down and dragging from the bottom right to the top left reveals the cursor is there, just positioned in the far bottom corner. 

No mods installed, tested 1.16.4-1.16.5

**Comment by khanhduytran0** [comment]
It’s likely fullscreen mode is not turned on. Try enable it and see.

**Comment by BowlineNetwork** [comment]
It was fullscreen not being enabled.
