### ISSUE TITLE
Fabric installer not working

### ISSUE THREAD

**Issue by rhizomacomp10** [PojavLauncherTeam/PojavLauncher_iOS#86]
When I try to install fabric it shows with this error

`
XII:/var/mobile/Documents root# /usr/lib/jvm/java-16-openjdk/bin/java -jar /var/mobile/Documents/fabric-installer-0.7.1.jar client -dir /var/mobile/Documents/minecraft -mcversion 1.16.5
Loading Fabric Installer: 0.7.1
Exception in thread "main" java.lang.RuntimeException: Failed to install Client
        at net.fabricmc.installer.Main.main(Main.java:79)
Caused by: java.io.FileNotFoundException: Launcher directory not found at /var/mobile/Documents/minecraft
        at net.fabricmc.installer.client.ClientHandler.installCli(ClientHandler.java:91)
        at net.fabricmc.installer.Main.main(Main.java:77)
`

**Comment by admin-elvistrujanovic** [comment]
Which version are you using?

**Comment by rhizomacomp10** [comment]
The latest version

**Comment by admin-elvistrujanovic** [comment]
Also, make sure you have a "launcher_profiles.json" file on location "/var/ mobile/Documents/ minecraft/" because if you don't, it could be a problem.

**Comment by rhizomacomp10** [comment]
I do it came with the Minecraft folder

**Comment by admin-elvistrujanovic** [comment]
launcher_profiles.json

{
  "profiles": {
    "(Default)": {
      "name": "(Default)",
      "lastVersionId": "Unknown"
    }
  },
  "selectedProfile": "(Default)"
}

**Comment by rhizomacomp10** [comment]
I replaced it still no work

**Comment by admin-elvistrujanovic** [comment]
I suggest that you create shortcuts to your commands from /usr/lib/jvm/ java-16-openjdk/bin/ to /bin and mount your /var/mobile/Documents directory with Filza. Then you need to rename the installer file to fabric.jar and use this command java -jar ./fabric.jar client -dir /var/mobile/Documents/minecraft -mcversion 1.16.5 - Also make sure you have downloaded the latest version of Fabric installer

**Comment by admin-elvistrujanovic** [comment]
If all this doesn't work, save your worlds and reinstall the entire minecraft folder together with the application by downloading the latest version and then when you open the application and log in, install version 1.16.5 immediately and then try this command. Good luck

**Comment by rhizomacomp10** [comment]
Did all of this no luck 

`

XII:~ root# /usr/lib/jvm/java-16-openjdk/bin/java -jar /var/mobile/Documents/fabric.jar client -dir /var/mobile/Documents/minecraft
Loading Fabric Installer: 0.7.1
Exception in thread "main" java.lang.RuntimeException: Failed to install Client
        at net.fabricmc.installer.Main.main(Main.java:79)
Caused by: java.io.FileNotFoundException: Launcher directory not found at /var/mobile/Documents/minecraft
        at net.fabricmc.installer.client.ClientHandler.installCli(ClientHandler.java:91)
        at net.fabricmc.installer.Main.main(Main.java:77)
XII:~ root#

`

**Comment by rhizomacomp10** [comment]
Downgrading to 0.6.1.51 of fabric fixed the issue

**Comment by admin-elvistrujanovic** [comment]
New versions of Fabric request this command to install "java -jar [fabric installer jar location] client -dir [minecraft directory] -mcversion [minecraft version]
