### ISSUE TITLE
All versions of Minecraft crash as soon as it opens

### ISSUE THREAD

**Issue by admin-elvistrujanovic** [PojavLauncherTeam/PojavLauncher_iOS#94]
I uninstalled the whole game, deleted Minecraft folders and .pojavlauncher folder, deleted java and after I deleted everything and restarted the phone, I installed everything again but it didn't work. Now I don't have any modloader and any mods but game is always crashing

**Comment by Zarbok786** [comment]
Same issue as stated above tried deleting and redos loading all game files but always crashes on game boot

**Comment by IvanKulagin** [comment]
Same. Everything works on latest release, but on the latest build every version just crashes.

**Comment by Doregon** [comment]
@admin-elvistrujanovic @Zarbok786 @IvanKulagin What are all of your devices? I’m having this issue as well and think I might have a workaround, depending on the actual problem.

**Comment by admin-elvistrujanovic** [comment]
> @admin-elvistrujanovic @Zarbok786 @IvanKulagin What are all of your devices? I’m having this issue as well and think I might have a workaround, depending on the actual problem.

iPhone 7 (iOS 14.4 Jailbroken) with Odysseyra1n

**Comment by Doregon** [comment]
Alright, I just found the problem. Do you know how iOS has memory limits and kills apps that go over the said limit? Simply put, the Jetsam memory management framework is interfering with how PojavLauncher works, shutting it down before it can work everything out properly. It’s more prominent on older devices, such as my iPhone 5s.

However, I’ve found a temporary workaround:

1. Install `jetsamctl` from its [GitHub](https://github.com/conradev/jetsamctl) page.
2. Once installed, open PojavLauncher but **stay on the sign in screen.**
3. Open a terminal or use SSH **as root or with `sudo`** and type the following command, with PojavLauncher still open:
`(sudo) jetsamctl -l 1024 PojavLauncher`

This tells the system to allow PojavLauncher to use *up to* 1024MB (but it will never use that unless specified). I’ll open a new issue with information on this and tell the devs what can be done to overcome it.

If 1024 doesn’t work for you, look up how much RAM your device has and use that.

**Comment by Doregon** [comment]
Forgot to make sure you guys got called out (so you can fix it fast <3) @IvanKulagin @admin-elvistrujanovic @Zarbok786

**Comment by IvanKulagin** [comment]
@Doregon That's a very useful tool not only for Minecraft, but for other things like emulators and virtual machines. Thanks!

**Comment by Doregon** [comment]
Yep! I use UTM all the time (mainly to stress my iPhone 5s and run small Linux distros) and thought this was a cool tool as well. If anyone wants more info, I just posted #97 with all the goodies attached.

**Comment by admin-elvistrujanovic** [comment]
> Alright, I just found the problem. Do you know how iOS has memory limits and kills apps that go over the said limit? Simply put, the Jetsam memory management framework is interfering with how PojavLauncher works, shutting it down before it can work everything out properly. It’s more prominent on older devices, such as my iPhone 5s.
> 
> 
> 
> However, I’ve found a temporary workaround:
> 
> 
> 
> 1. Install `jetsamctl` from its [GitHub](https://github.com/conradev/jetsamctl) page.
> 
> 2. Once installed, open PojavLauncher but **stay on the sign in screen.**
> 
> 3. Open a terminal or use SSH **as root or with `sudo`** and type the following command, with PojavLauncher still open:
> 
> `(sudo) jetsamctl -l 1024 PojavLauncher`
> 
> 
> 
> This tells the system to allow PojavLauncher to use *up to* 1024MB (but it will never use that unless specified). I’ll open a new issue with information on this and tell the devs what can be done to overcome it.
> 
> 
> 
> If 1024 doesn’t work for you, look up how much RAM your device has and use that.

Not worked for me :(

**Comment by khanhduytran0** [comment]
@admin-elvistrujanovic update to latest build

**Comment by Doregon** [comment]
> > Alright, I just found the problem. Do you know how iOS has memory limits and kills apps that go over the said limit? Simply put, the Jetsam memory management framework is interfering with how PojavLauncher works, shutting it down before it can work everything out properly. It’s more prominent on older devices, such as my iPhone 5s.
> > 
> > 
> > 
> > However, I’ve found a temporary workaround:
> > 
> > 
> > 
> > 1. Install `jetsamctl` from its [GitHub](https://github.com/conradev/jetsamctl) page.
> > 
> > 2. Once installed, open PojavLauncher but **stay on the sign in screen.**
> > 
> > 3. Open a terminal or use SSH **as root or with `sudo`** and type the following command, with PojavLauncher still open:
> > 
> > `(sudo) jetsamctl -l 1024 PojavLauncher`
> > 
> > 
> > 
> > This tells the system to allow PojavLauncher to use *up to* 1024MB (but it will never use that unless specified). I’ll open a new issue with information on this and tell the devs what can be done to overcome it.
> > 
> > 
> > 
> > If 1024 doesn’t work for you, look up how much RAM your device has and use that.
> 
> Not worked for me :( 

Yeah that’s why I originally asked for what type of device you had. The memory squeeze would only really affect models with less than 2GB RAM. The issue this fixes is **Killed: 9** if running Java in the terminal or **The process was terminated for exceeding jetsam limits.** which is a Cr4shed reason.

**Comment by admin-elvistrujanovic** [comment]
> @admin-elvistrujanovic update to latest build

I'm using latest build (From Procurs repo for Sileo)

**Comment by admin-elvistrujanovic** [comment]
I solved the problem - I restored the phone via iTunes and I re-jailbreaked via Odysseyra1n and now it works
