### ISSUE TITLE
I can’t download OptiFine 

### ISSUE THREAD

**Issue by nathan128** [PojavLauncherTeam/PojavLauncher_iOS#96]
When I enter the second command in terminal it said “unable to access optilnst.jar” even though I installed it and it’s in the document in filza. Please help thank you.

**Comment by Carter1190** [comment]
is it named correctly and you correctly set the path?

**Comment by pjcmplays** [comment]
Same mine says
error: unable to access jarfile /var/mobile/Documents/Optilnst.jar 

And there in exact same folder

**Comment by Carter1190** [comment]
is the jar file named OptiInst.jar ir the default name?

**Comment by pjcmplays** [comment]
Yes
![Uploading 0A5E3539-5A7F-4DEE-80AE-84D28943ED3B.png…]()

**Comment by Carter1190** [comment]
image doesnt load,whats the jar file called?

**Comment by Carter1190** [comment]
alright image loaded,your issue is that its looking for  OptiInst.jar not the jar you have so rename the jar you have to OptiInst.jar

**Comment by pjcmplays** [comment]
![117CCB99-64DD-4322-8424-DFC11BDFF9B3](https://user-images.githubusercontent.com/80432751/111238527-3c1dba00-8632-11eb-8ac6-9b503da2ee1d.png)
![9F1AD69B-EF53-42DC-986A-3D6CBCC3A8E3](https://user-images.githubusercontent.com/80432751/111238535-3de77d80-8632-11eb-915f-f16f9982549c.png)

**Comment by Carter1190** [comment]
@nathan128 and @pjcmplays ^^^ you just have to rename the jar file for optifine to OptiInst.jar

**Comment by Carter1190** [comment]
can you write out the command you used?

**Comment by pjcmplays** [comment]
Thank you so much it worked just now 
The rename thing you said worked
![8C3D8BAC-43B1-4D19-A879-76CB2C20FF51](https://user-images.githubusercontent.com/80432751/111239080-63c15200-8633-11eb-914f-5f977a3a43f7.png)

**Comment by ahmedisgamet** [comment]
How did you fix it me same unable to find jarfile what do I do to fix please help asap

**Comment by Doregon** [comment]
Closing as 2.0 includes a built-in mod installer.
