### ISSUE TITLE
[Information] iOS Memory Limits

### ISSUE THREAD

**Issue by Doregon** [PojavLauncherTeam/PojavLauncher_iOS#97]
# A backstory...
iOS and macOS use a common memory management framework called Jetsam. This framework lays down some harsh laws upon the computer land, setting a memory limit for all processes to obey:

- If a process is using less memory than the limit, Jetsam leaves it alone and the process continues as normal.

- If a process is using more memory than the limit, Jetsam quickly kills the app and frees all of the memory that it used.

This is helpful for keeping the system responsive (customer service is a goal of Apple’s), but can pose a problem when it comes to processes requiring heavier loads.

# So what’s this mean?
Since this app requires a heavier resource load (as you’re using JDK and need to allocate some memory), you may come across issues with actually doing anything. I’ve tested and seen these issues come up as one of the following:

- The process was terminated for exceeding jetsam memory limits (a Cr4shed log)
- The app unexpectedly quitting but the logs don’t show any errors relating to OpenGL or don’t show errors at all

This issue only really affects devices with less than 4GB of memory, and may not happen on those with 2GB.

# What to do if it all goes south
It’s actually really simple to fix this issue, using a simple tool I’ve found on GitHub. **I have seen Reddit posts about changing the jetsamproperties plist file,** but this doesn’t work (as it’s only fixing rebooting and unjailbreaking in the middle of the night.)

1. **Install jetsamctl** from the [new repository](https://doregon.github.io/cydia) repository. Even though it is not actively maintained anymore, it still does the job.

2. Open PojavLauncher, but **don’t start the game.** We just need PJ open for now.

3. Open your favorite terminal or use SSH and type the following command **as root or with sudo:**

```
jetsamctl -l 1024 PojavLauncher

# This command tells Jetsam that
# PJ can use *up to* 1024MB of
# memory. This won’t happen unless
# you start PJ with those options.
```

4. Profit! Switch back to PojavLauncher and start gaming!

Just take note: if you can’t play the game without entering this command, **you’ll have to follow these steps every time you open the app.** This is due to the lifecycle of the process and Jetsam’s memory.

# Can this be more streamlined?
At the moment, sort of. You can write this to a shell script so you don’t have to type it all, but other than that there’s not much you can do. The jetslammed library could present useful hints for the PJ devs to integrate this trickery directly into the app.

**Comment by ThatsNiceGuy** [comment]
> You can write this to a shell script so you don’t have to type it all, but other than that there’s not much you can do. 

**For the following, it is intended only for advanced users. If you decide to undertake the process, it is at your own risk and I cannot be held responsible for loss of jailbreak, etc**
There actually is, however it can be extremely dangerous and can softbrick your device, requiring a restore to fix.
Since we’re jailbroken, we can modify Jetsam memory limits as we please. I did this successfully on iOS 13.5 last year, and looking at the files, the Jetsam configuration files seem to be the same. I might try to increase the memory limit myself later.

**Comment by Doregon** [comment]
> There actually is, however it can be extremely dangerous and can softbrick your device, requiring a restore to fix.

**Comment by Zarbok786** [comment]
Well, assuming I did this correctly it doesn’t seem to have worked for me, PojavLauncher launcher goes to 0% before crashing

**Comment by Doregon** [comment]
@Zarbok786 I was able to get past the initial loading screen (albeit after ~25 mins) on my 5s and I was able to play. I don’t know what’s up, do you have Cr4shed and was it able to log? Also check latestlog.txt for Pojav.

**Comment by Zarbok786** [comment]
After reinstalling for the (I’ve lost count) time it’s finally started to work, I have an iPad Pro 10.5inch by the way. I am still unsure as to what the issue was the past times I’ve tried to use this.

**Comment by lanspring** [comment]
Tried it iOS 12?

**Comment by Doregon** [comment]
iOS 12 was the main OS that was affected, although I’m seeing it rarely on 13 and 14.

**Comment by ThatsNiceGuy** [comment]
Jetsamctl works fine, I had attempted to increase the jetsam memory limits entirely. It worked fine on iOS 13 but apparently not here on 14. Anyway yea just use jetsamctl

**Comment by Doregon** [comment]
I posted something on /r/jailbreak about how jetsamctl is now available on my repository and I'm picking up development to make it a little better.
