### ISSUE TITLE
I can't download forge

### ISSUE THREAD

**Issue by Vuqar05** [PojavLauncherTeam/PojavLauncher_iOS#99]
When i use 2nd command terminal says: 
me.xfl03.HeadlessInstaller

It could really help if someone sent link to the video guide of forge installation

**Comment by lanspring** [comment]
place the file in /var/mobile, and confirm whether the command corresponds to the file name

**Comment by Vuqar05** [comment]
@lanspring i did what you said but now there is another problem 
![8E82693B-079D-4112-BBE5-9CB4386C745D](https://user-images.githubusercontent.com/77661655/111107928-41670000-8571-11eb-97f5-327b5450a3f3.jpeg)

**Comment by Vuqar05** [comment]
Solved it! I needed to name forge installer to “forge-installer.jar” (my version had some numbers in its name)
